### ISSUE TITLE
Spaltenbreite bei Objekt auswahl

### ISSUE THREAD

**Issue by mctom** [ioBroker/ioBroker.vis#100]
Wenn man in VIS ein Objekt zu einem Widget auswählen will kommt ein eigener Dialog.
In diesem Dialog ist die Spaltenbreit für den Namen zu gering. Aus diesem Grund ist es teilweise schwierig das richtige Objekt zu identifizieren.

![2015-08-09 07_48_53-iobroker vis](https://cloud.githubusercontent.com/assets/12543796/9153737/931dead8-3e6b-11e5-9b75-8a75896475a4.png)

**Comment by GermanBluefox** [comment]
Kann nicht so einfach fixen. Bitte breiteren Bildschirm benutzen oder Zoomen.
