### ISSUE TITLE
Kopieren zerstört Widget

### ISSUE THREAD

**Issue by hometm** [ioBroker/ioBroker.vis#103]
Wird das Widget "hqwidgets On/Off" auf einen anderen View kopiert, ist die Kopie 'defekt' (Hintergrund sitzt neben image)

**Comment by GermanBluefox** [comment]
Sollte jetzt gehen (mit 0.1.6)

**Comment by hometm** [comment]
Beim Kopieren habe ich nach wie vor dieses Verhalten (mit aktuellem Softwarestand).

**Comment by GermanBluefox** [comment]
Fixed now?

**Comment by hometm** [comment]
soeben getestet, funktioniert. 
Danke
