### ISSUE TITLE
Metro: Navigation löst auch auf Folgeseite Tastendruck aus

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.vis#104]
http://forum.iobroker.org/viewtopic.php?f=30&t=1257

MoiN!

Ich hoffe ich bekomme mein Problem sauber beschrieben:
Plattform Android 5.x
Browser: Chrome

Ich verwende die Metro-Navigation-Widgets. Wenn jetzt auf der anzusteuernden Seite an der Stelle des Navigation-Widgets z.B. ein Toggle Widget ist wird dieses beim Seitenwechsel auch ausgelöst...anscheinend wird der "Fingerdruck nicht beim Seitenwechsel zurückgesetzt"....

... frei formuliert...

Kann man da etwas gegen tun?

bis denne
MrLEe

**Comment by MrLee99** [comment]
Moin!

Aktuell ist das Problem in der Ansroid-App (v1.1.1) mit Vis 1.0.4 und Metro-Widgets 1.1.0 massiv da.

Dadurch das die App und vis aktuell so schnell sind wird der Fingertipp durchgereicht und macht Projekte mit umfangreicher Navigation und vielen Unterseiten leider komplett unnutzbar.

Wäre nett wenn mal jemand reinscheun könnten.

bis denne & vielen Dank
Mr.Lee

siehe auch:
http://forum.iobroker.net/viewtopic.php?f=30&t=1257
