### ISSUE TITLE
Very little documentation

### ISSUE THREAD

**Issue by jonferreira** [ioBroker/ioBroker.vis#119]
Hi,
I have to say this is one of the coolest things I've found lately and I'm really liking it so far.
Unfortunately it's not that easy to move forward since there's little to no information available :-(

Is there any place one can check what's the correct payload to send for each different widget?

PS: I just realized I should probably have posted this on the node-red branch https://github.com/GermanBluefox/node-red-vis

**Comment by GermanBluefox** [comment]
Do you use ioBroker or just node-red?

**Comment by jonferreira** [comment]
just node-red-vis - https://github.com/GermanBluefox/node-red-vis
