### ISSUE TITLE
Installation not possible in Windows 10

### ISSUE THREAD

**Issue by StephanBeutel** [ioBroker/ioBroker.vis#126]
Hi,

I'm not able to install vis and create an instance.

F:\ioBroker>iobroker add vis

F:\ioBroker>node node_modules/iobroker.js-controller/iobroker.js add vis
host.Homeserver install adapter vis
npm install --production --prefix "F:/ioBroker/node_modules/iobroker.vis" (System call)
npm ERR! addLocal Could not install F:\ioBroker
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "F:\\nodejs\\node.exe" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--prefix" "F:/ioBroker/node_modules/iobroker.vis"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! No version provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\ioBroker\npm-debug.log
Cannot install iobroker.vis: 1

Any hints how to install vis?

**Comment by GermanBluefox** [comment]
What js-controller version do you have?

**Comment by GermanBluefox** [comment]
You can always install this adapter manually:
```
f:
cd F:\ioBroker
npm i iobroker.vis --production
iobroker add vis
```

**Comment by StephanBeutel** [comment]
Hi,

iobroker.js-controller@0.13.2

Trying it manually also does not work. 
npm install is successful but iobroker add fails.

Here's the console output:

F:\ioBroker>npm i iobroker.vis --production

> iobroker.vis@0.10.15 install F:\ioBroker\node_modules\iobroker.vis
> node main.js --install

iobroker.core@ F:\ioBroker
`-- iobroker.vis@0.10.15


F:\ioBroker>iobroker add vis

F:\ioBroker>node node_modules/iobroker.js-controller/iobroker.js add vis
host.Homeserver install adapter vis
npm install --production --prefix "F:/ioBroker/node_modules/iobroker.vis" (System call)
npm ERR! addLocal Could not install F:\ioBroker
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "F:\\nodejs\\node.exe" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--prefix" "F:/ioBroker/node_modules/iobroker.vis"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! No version provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\ioBroker\npm-debug.log
Cannot install iobroker.vis: 1

**Comment by GermanBluefox** [comment]
To fast fix the problem I suggest you to install npm 2
>npm i npm@latest-2 -g

And I must to find out, what to do with npm3

**Comment by StephanBeutel** [comment]
Thanks, it worked.
