### ISSUE TITLE
Initiales Setzen von Slider (horizontal) funktioniert nicht mehr, wenn der View nicht direkt aufgerufen wird.

### ISSUE THREAD

**Issue by nobodyMO** [ioBroker/ioBroker.vis#139]
Mit den aktuellen VIS-Version (0.15.0) wird der Slider nicht mehr gesetzt, wenn der View mit dem Slider nicht direkt mittels URL aufgerufen sondern erst von einem anderen View zu dem View mit dem Slider 
 über die Navigation gewechselt wird. Bei direktem Aufruf des Views über die URL wird der Wert des Sliders korrekt initialisiert.

**Comment by GermanBluefox** [comment]
Ich kann nicht reproduzieren. Gibt es das Problem noch?
