### ISSUE TITLE
javascript-dependend background with more than one condition does not work

### ISSUE THREAD

**Issue by jp112sdl** [ioBroker/ioBroker.vis#140]
I'm setting the background color of a widget with
```{h:hm-rpc.0.NEQ0529746.2.STATE;i:hm-rpc.0.NEQ0529746.1.STATE;h == "true" ? "#ff0000" : i == "true" ? "#ffa4280" : "#008000"}```

This worked with iobroker.vis 0.10.15

After upgrading to iobroker.vis 0.15.0, this code does not work anymore.
I tried it with a single condition, which is working - but not with two conditions...
It seems, that 0.14.7 also has this issue.

**Comment by jp112sdl** [comment]
P.S.: The code of the widget

```
[{"tpl":"tplStatefulImage8","data":{"oid":"hm-rpc.0.NEQ0529746.2.STATE","g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":true,"g_css_shadow_padding":true,"g_css_border":true,"g_gestures":false,"g_signals":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","refreshInterval":"0","count":"1","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"src_0":"/icons-mfd-png/fts_door.png","src_1":"/icons-mfd-png/fts_door_open.png"},"style":{"left":"98px","top":"460px","width":"52px","height":"52px","position":"","background":"","background-color":"{h:hm-rpc.0.NEQ0529746.2.STATE;i:hm-rpc.0.NEQ0529746.1.STATE;h == \"true\" ? \"#ff0000\" : i == \"true\" ? \"#ffa4280\" : \"#008000\"}","border-width":"1px","border-style":"hidden","border-radius":"5px","border-color":"#676767","box-shadow":"0px 0px 8px 2px #676767","z-index":"7"},"widgetSet":"basic"}]
```

**Comment by jp112sdl** [comment]
Ich habe mir zum Testen eine neue ioBroker Instanz aufgesetzt, die lediglich den hm-rpc Adapter und vis enthält.

Soweit ich es bisher testen konnte, scheint die 2. Variable ```i:...``` gar nicht gefüllt zu werden.

**Comment by jp112sdl** [comment]
<img width="1621" alt="bildschirmfoto 2017-06-15 um 20 33 26" src="https://user-images.githubusercontent.com/18190139/27196375-79821644-520a-11e7-8471-1a7650f48b28.png">

**Comment by jp112sdl** [comment]
Hier gehts noch (alte vis-Version)
<img width="1472" alt="bildschirmfoto 2017-06-15 um 20 49 12" src="https://user-images.githubusercontent.com/18190139/27196790-2a1c4f32-520c-11e7-942c-bb06fde790a1.png">

**Comment by jp112sdl** [comment]
Hier gehts nicht mehr (neue vis-Version)
<img width="1456" alt="bildschirmfoto 2017-06-15 um 20 49 20" src="https://user-images.githubusercontent.com/18190139/27196808-3c71b8b6-520c-11e7-998b-9f7353730083.png">

**Comment by jp112sdl** [comment]
Ich habe nun Folgendes noch probiert:
Lege ich 2 Logikvariablen ```admin.0.a``` und ```admin.0.b``` funktioniert die Formatierung.
```{h:admin.0.a;i:admin.0.b;h == "true" ? "#ff0000" : i == "true" ? "#ffa4280" : "#008000"}```
Lege ich 2 Logikvariablen ```hm-rpc.0.a```und ```hm-rpc.0.b``` an funktioniert die Formatierung
 **nicht** mehr.
```{h:hm-rpc.0.a;i:hm-rpc.0.b;h == "true" ? "#ff0000" : i == "true" ? "#ffa4280" : "#008000"}```

**Comment by GermanBluefox** [comment]
Thank you for your patience and very detailed error description. I could fix it.
Please test and close mit 0.15.2

**Comment by jp112sdl** [comment]
Yessss, works with 0.15.2 again. Thanks a lot
