### ISSUE TITLE
Button "tplBulbOnOffCtrl" verbleibt nicht im Zustand

### ISSUE THREAD

**Issue by jp112sdl** [ioBroker/ioBroker.vis#141]
**Ziel:**
Antippen eines Buttons schaltet einen Homematic Aktor ein und aus

**Problem:**
Wenn ich einen Button antippe, wird der Zustand des Aktors nur für eine halbe Sekunde getoggelt, danach fällt er wieder in seinen ursprünglichen Zustand. Der Aktor wird also nur für eine halbe Sekunde ein- und sofort wieder ausgeschaltet.

**Analyse:**
- Mausklicks im Browser werden korrekt verarbeitet (klick - ein, klick - aus)
- Das Problem tritt nur am Touchscreen (iPhone/iPad) auf **UND** wenn ich zusätzlich eine CSS background-color Formatierung verwende:
`{h:hm-rpc.0.NEQ0000000.1.STATE;h == "false" ? "#676767" : "#00aa00"}`

**Workaround:**
Ein längeres Antippen funktioniert, dann bleibt der Button in seinem Zustand, allerdings bekomme ich dann auch immer das Kontextmenü meines Browser angezeigt.

**Comment by LeRob** [comment]
Fehler besteht immernoch, auch ohne CSS Background. Einzelne Widgets sind so nicht zu gebrauchen... 

Gutes Beispiel aus Basic: Full Screen Button. Geht nur via Maus, nicht via Touch am Surface oder Tablet/Smartphone

EDIT:
Liegt an der Swipe Navigation. Ohne swipe funktioniert alles wie erwartet
