### ISSUE TITLE
Addition of "?_vis_refts=XXXXXX" URL parameter causes "Bad Request"

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.vis#142]
If in vis a basic-Image widget is added with an enabled refresh interval vis seem to add an own URL parameter `?_vis_refts=XXXXX` to the URL for the next and following refresh cycles (see https://github.com/ioBroker/ioBroker.vis/blob/master/www/widgets/basic.html#L345). For some strict web servers who are checking URL parameters quite strong this results in "Bad Request - 404" errors to be replied. One example URL where this happens is:

http://www.yr.no/place/Germany/Saxony/Loschwitz/avansert_meteogram.png

After the refresh interval VIS tries to reload the image but with the following self constructed example URL:

http://www.yr.no/place/Germany/Saxony/Loschwitz/avansert_meteogram.png?_vis_refts=1502181369835

As a result of having added this `_vis_refts=XXX` URL parameter the webserver of yr.no replies with a "Bad Request" (potentially to protect it from any scripting attack)

**Comment by jens-maus** [comment]
In addition, I wonder what this `_vis_refts` parameter is all about because I can't find any use of it in the VIS source code? It is just added but nowhere it seems to be actually used for something?!?

**Comment by GermanBluefox** [comment]
It is for cache. If you will ask "http://blabla.com/image.png" two times in
browser, so the second time you will get cached image.

2017-08-08 10:41 GMT+02:00 Jens Maus <notifications@github.com>:

**Comment by jens-maus** [comment]
@GermanBluefox I already guessed that. However, as you can see from the above example the approach of simply adding `_vis_refts` as an additional URL parameter could result in unwanted effects because not all webserver accept arbitrary URL parameters but might simply reject connections due to potentially fighting DoS attacks.

**Comment by GermanBluefox** [comment]
Just now yr is the one server who checked that and it has such a behavior
till a couple of months. I have a workaround for that:
http://forum.iobroker.net/viewtopic.php?f=22&t=7371&hilit=yr.no&start=20#p77127

2017-08-08 11:21 GMT+02:00 Jens Maus <notifications@github.com>:

**Comment by jens-maus** [comment]
Well, workarounds are nice, but solutions are better :)

Is there really no other way than always adding `_vis_refts=XXX`to solve the caching problem in browsers? IMHO it is anyway not a perfect approach to always add `_vis_refts=XXX` to all URLs because this might provide web servers with information they don't really need and might even provide them with information they *should* not get due to privacy concerns (web servers shouldn't know that it is VIS that is accessing them.)

**Comment by GermanBluefox** [comment]
I don't know the solution, but we can change attribute name to just "ts"

8 Авг 2017 г. 11:41 пользователь "Jens Maus" <notifications@github.com>
написал:

**Comment by jens-maus** [comment]
This will only solve the security concerns I raised, but will still cause trouble with servers returning "Bad Request". Are you sure that this parameter is still required? In one of the recent posts on the forum (http://forum.iobroker.net/viewtopic.php?f=22&t=7371&hilit=yr.no&start=20#p77677) pix is reporting that it doesn't seem to be required. Perhaps you can at least change it to be working only if a  global ioBroker.vis option is enabled in the configuration? This would allow users to check themselves if this parameter is really required or not with their browsers.

**Comment by GermanBluefox** [comment]
I removed the query from URL and the browser DOES NOT ask the image anew. Do you know the solution?

**Comment by Apollon77** [comment]
In general I also know this solutiuon with the extra parameter as "best practice".

Since HTTP 1.1 there is the option to work with ETags (https://de.wikipedia.org/wiki/HTTP_ETag). But this only works when the server send an ETag with the response ... and because VIS do not have control over the Servers in these "custom" cases this solution do not work too :-(

**Comment by jens-maus** [comment]
Why? AFAIK ioBroker comes with its own (or nodejs derived) webserver. Perhaps it already supports etags?

**Comment by Apollon77** [comment]
embedded images/iframes get the content directly from the other webserver and not from vis ...

example from above:
One example URL where this happens is:

http://www.yr.no/place/Germany/Saxony/Loschwitz/avansert_meteogram.png

so vis "webserver" is not used for this request and so this server would need to support that

**Comment by GermanBluefox** [comment]
I close this issue, because I build in this feature, but it does not work. 
![image](https://user-images.githubusercontent.com/4582016/31861636-315cdf66-b731-11e7-9a5b-ed7cfea1f50d.png)
Last line
