### ISSUE TITLE
wrong Blocky help link

### ISSUE THREAD

**Issue by mrMuppet** [ioBroker/ioBroker.vis#147]
in blocky the context-help of text trim blocks links to some ibm website not to [https://github.com/google/blockly/wiki/Text#trimming-removing-spaces](url)

**Comment by Homoran** [comment]
kann ich bestätigen.
Geht nach:
https://www.ibm.com/support/knowledgecenter

**Comment by Apollon77** [comment]
Ok, then please re-create in javascript adapter. Blockly != VIS!
