### ISSUE TITLE
some states not loading: Trying to get empty list, because the whole list could not be loaded

### ISSUE THREAD

**Issue by Locke** [ioBroker/ioBroker.vis#149]
Hi,

for a while now (several months? not quite sure..) I have an issue of some states to not load. I didn't investigate this further as I didn't had to remotely change the temperature at home, but now as it's getting colder I started looking into this issue ;)

I am running ioBroker on my webserver in a docker container behind a nginx reverse proxy handling http2 and https, not sure if it's related to my symptoms or not. I am using SliderTabs to separate the different rooms / floors.

I figured out that the section at https://github.com/ioBroker/ioBroker.vis/commit/3a71ab461ceddb2ee07fcecf67c4f3e44ab5af50#diff-cac666adcc96f99ac47921351950e570R605 seems to cause that some states are not loading, as I saw the entry `Trying to get empty list, because the whole list could not be loaded` in the console. When I comment out the `IDs = [];` assignment everything works fine for me.

I figured out that `getStates` is called multiple times, and mostly while an older request is still pending. So it seems reasonable in my case that `this.gettingStates` is indeed bigger than 1 and I don't think this should be limited to a single "getStates" call at a time in my case?

After some manual peeking with breakpoints I added console.log statements to get a timeline of the `getStates` calls (my line 698) and it's calls of the supplied callback (my line 718):

```
conn.js loaded at 1513350629.118

conn.js:698 getStates: Array(71) this.gettingStates=0 at 1513350629.602
conn.js:718 getStates completed call from 1513350629.602 at 1513350629.614
conn.js:698 getStates Array(8)  this.gettingStates=0 at 1513350629.844
conn.js:698 getStates Array(9)  this.gettingStates=1 at 1513350629.847
conn.js:698 getStates Array(9)  this.gettingStates=2 at 1513350629.849
conn.js:698 getStates Array(7)  this.gettingStates=3 at 1513350629.852
conn.js:698 getStates Array(38) this.gettingStates=4 at 1513350629.854
conn.js:718 getStates completed call from 1513350629.844 at 1513350629.868
conn.js:718 getStates completed call from 1513350629.847 at 1513350629.941
conn.js:718 getStates completed call from 1513350629.849 at 1513350630.006
conn.js:718 getStates completed call from 1513350629.852 at 1513350630.068
conn.js:718 getStates completed call from 1513350629.854 at 1513350630.116
```

btw, while manually debugging I noticed errors on `this._socket.emit` (socket closing / already closed). This only happened when I paused the execution via the debugger, therefore I suspect a timeout of the websocket. It might be worth catching the error caused by the `emit` function and incrementing `this.gettingStates` only afterwards when the request could be sent..

**Comment by Locke** [comment]
Any update on this? I really would like to use vis this winter without manually editing the file in iobroker-data..

Is the "fix for slow devices" still required or can it be removed? Should it be replaced by a more complicated approach that maybe buffers additional `getStates` calls?

**Comment by Locke** [comment]
Note: this issue might be the cause for #179

**Comment by oweitman** [comment]
Same here.
Maybe we can return in the error object meanwhile something to differentiate 
"not found" with "not requested"

what should the target solution be? What is the issue with slower device?
1) low processing speed for too many concurrent requests? 
solution can be queueing or request all states at once
2) low memory?
solution can be queueing

**Comment by Locke** [comment]
I'm tired of manually changing conn.js each time to get states loading on my side. So for me it is perfectly fine without the "fix for slow devices" and I don't see how loading an empty list would even work.

@Apollon77 @GermanBluefox Would you merge a PR that removes your "fix" and would you be able to test again with a slow device, like you did with the iPad1 mentioned in your commit message?

**Comment by oweitman** [comment]
@Locke 
bad boys do:

            vis.conn.gettingStates =0;
            vis.conn.getStates(key,function (err, obj) {
