### ISSUE TITLE
Change view by commando (object) only uses main project

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.vis#151]
When i want to change the current view on my PC and i enter in data field as example:
Temperature_Control/Verwarming_Woonkamer 

the browser goes to "main#Verwarming_Woonkamer" instead of the wanted "Temperature_Control#Verwarming_Woonkamer" in the other project
  
The field itself is also update with the value "main/Verwarming_Woonkamer"

**Comment by GermanBluefox** [comment]
Thanks. It will be fixed.
https://github.com/ioBroker/ioBroker.vis/commit/30c5ef31d8cea3474f71bf3359c00763750062a8

**Comment by DutchmanNL** [comment]
Nice thank you !
