### ISSUE TITLE
Seit update 1.1.0 hängt VIS

### ISSUE THREAD

**Issue by eXplOiD1** [ioBroker/ioBroker.vis#153]
Guten Tag,
seit dem update auf v1.1.0 bleibt der vis editor hängen.

Verbinde mit dem Server...
Lade Werte...

mehr kommt nicht mehr.
  
Die Konsole von firefox zeigt das hier an 
ReferenceError: getUsedObjectIDs is not defined
[Weitere Informationen]

**Comment by Apollon77** [comment]
Versuch bitte mal ein "iobroker upload vis" an der Kommandozeile

**Comment by jens-maus** [comment]
Ich hab hier seit update auf die 1.1.0 das selbe problem. Im Debugger von Safari wird der folgende Fehler angezeigt:

![screenshot_155](https://user-images.githubusercontent.com/5887769/34652928-2adf948a-f3e5-11e7-9ac7-bfb24e859b41.png)

Interessanterweise kann man allerdings problemlos in den Editor wechseln, der geht problemlos. Nur die direkte Ansicht eines Views geht nicht über "Loading Values..." hinaus.

**Comment by jens-maus** [comment]
Der folgende Patch löst hier das Problem für mich:

```diff
--- /opt/iobroker/node_modules/iobroker.vis/www/js/vis.js.orig	2018-01-07 20:08:01.912280400 +0100
+++ /opt/iobroker/node_modules/iobroker.vis/www/js/vis.js	2018-01-07 20:00:28.341471155 +0100
@@ -313,6 +313,7 @@
     },
     // Return as array used widgetSets or null if no information about it
     getUsedObjectIDs:   function () {
+        var getUsedObjectIDs = require(__dirname + '/../www/js/visUtils').getUsedObjectIDs;
         var result = getUsedObjectIDs(this.views, !this.editMode);
         if (!result) {
             return result;
```

Danach ein `iobroker upload vis` und wiederrum danach den browser cache gelöscht und schon geht es wieder.

**Comment by GermanBluefox** [comment]
Einfach Cache Löschen und geht es.
--

**Comment by GermanBluefox** [comment]
1.1.1 ausprobieren. Das problem war bei der Umstellung von grunt auf gulp diese Datei war falsch upgedatet:
https://github.com/ioBroker/ioBroker.vis/commit/bf02f981cbc3d6994ac42028f1f64e74c28ff69c#diff-4d1e301804bebb1aed036f8dfe7d3548L3

**Comment by Homoran** [comment]
Erledigt (??)

**Comment by Apollon77** [comment]
Please reopen if still a problem

**Comment by DavidTielke** [comment]
Habe leider das gleiche Problem, Cache wurde gelöscht und es hängt nur im Chrome, im Edge geht es.

![image](https://user-images.githubusercontent.com/1126737/48225816-377bd380-e39e-11e8-87ee-ae6c76587465.png)

Noch irgendwelche Ideen?

**Comment by GermanBluefox** [comment]
> Habe leider das gleiche Problem, Cache wurde gelöscht und es hängt nur im Chrome, im Edge geht es.
> 
> ![image](https://user-images.githubusercontent.com/1126737/48225816-377bd380-e39e-11e8-87ee-ae6c76587465.png)
> 
> Noch irgendwelche Ideen?

Version?
