### ISSUE TITLE
Widgets lassen sich nicht mehr löschen nach Javascript in color einstellungen.

### ISSUE THREAD

**Issue by eXplOiD1** [ioBroker/ioBroker.vis#154]
ich habe ein circleknob mit der eine javascript farbe belegt.
{n:paw.0.Smarthome Tablet Wohnzimmer.info.memory.ram_free;numberToColorHslmemory(n)}
seit dem lässt sich auf der seite weder was dauerhaft speichern, noch lassen sich diese objekte löschen.
wenn ich dannach speichern will passiert nix der speichern button bleibt dauerhaft aktiv.

auch lässt sich der gesamte view nicht löschen.

**Comment by GermanBluefox** [comment]
Da sollten die Fehlermeldungen in der Browserkonsole sein. Ohne Fehlermeldungen kann ich nicht helfen.

**Comment by eXplOiD1** [comment]
visEdit.js:174 Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.saveRemote (visEdit.js:174)
    at Object._saveToServer (visEdit.js:5487)
    at visEdit.js:5510
saveRemote @ visEdit.js:174
_saveToServer @ visEdit.js:5487
(anonymous) @ visEdit.js:5510
setTimeout (async)
save @ visEdit.js:5509
inspectWidgets @ visEditInspect.js:2234
delWidgets @ visEdit.js:3833
dialog_buttons.(anonymous function) @ visEdit.js:5775
s.click @ jquery-ui-1.11.4.full.min.js:11
dispatch @ jquery-1.11.2.min.js:3
r.handle @ jquery-1.11.2.min.js:3
21:54:53.156 visEdit.js:174 Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.saveRemote (visEdit.js:174)
    at Object._saveToServer (visEdit.js:5487)
    at HTMLButtonElement.<anonymous> (visEdit.js:2147)
    at HTMLButtonElement.dispatch (jquery-1.11.2.min.js:3)
    at HTMLButtonElement.r.handle (jquery-1.11.2.min.js:3)

**Comment by buanet** [comment]
Hallo, 
habe ein ganz ähnliches Problem. Bei mir ist es das Basic HTML Widget. Sobald ich im HTML einen Datenpunkt in geschweiften Klammern einfüge, etwa so:
`{hm-rpc.0.JEQXXXXXX.1.TEMPERATURE}`
lässt sich das Widget nicht mehr löschen oder ändern. Wenn der vis-editor nach dem Löschen versucht zu speichern bleibt oben rechts das Speichersymbol stehen. In der Browserkonsole gibt es folgenden Fehler:
`visEdit.js:174 Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.saveRemote (visEdit.js:174)
    at Object._saveToServer (visEdit.js:5487)
    at visEdit.js:5510
saveRemote @ visEdit.js:174
_saveToServer @ visEdit.js:5487
(anonymous) @ visEdit.js:5510
setTimeout (async)
save @ visEdit.js:5509
inspectWidgets @ visEditInspect.js:2234
delWidgets @ visEdit.js:3833
dialog_buttons.(anonymous function) @ visEdit.js:5775
s.click @ jquery-ui-1.11.4.full.min.js:11
dispatch @ jquery-1.11.2.min.js:3
r.handle @ jquery-1.11.2.min.js:3
`
Wenn ich in der "vis-views.json" das Widget leere (den html-Inhalt mit dem Datenpunkt entferne) lässt sich das Widget im Editor wieder löschen. 

MfG,
André

**Comment by eXplOiD1** [comment]
selbiges gilt auch für eine # im viewname ;)

**Comment by Arnulf22** [comment]
ich kann (so sieht es aus) zunächst  zwei problematische Widgets löschen.
Speicher ich, kommt folgende Meldung:

ypeError: viewsToSave[this.bindings[b][h].view].widgets[this.bindings[b][h].widget] is undefined
saveRemote
http://192.168.178.40:8082/vis/js/visEdit.js:174:21
_saveToServer
http://192.168.178.40:8082/vis/js/visEdit.js:5487:9
save/this._saveTimer<
http://192.168.178.40:8082/vis/js/visEdit.js:5510:13

Lege ich zwei neue Widgets an, bekommen sie die Namen der alten beiden Widgets.
Damit lässt sich der View speichern.

Verlasse ich die View ohne Neuanlage, sind die alten Widgets wieder da.

Dabei ist es egal, welche beiden neuen Widgets ich verwende. Sie lassen sich ebenfalls nicht löschen.,
Sie lassen sich nur durch Ersatzwidgets ersetzen.

**Comment by wendy2702** [comment]
Ich habe auch das Problem das ich ein "einfaches" Bar Widget nicht mehr löschen kann.

Console zeigt das:

`[Violation] 'setTimeout' handler took 51ms
visEdit.js:174 Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.saveRemote (visEdit.js:174)
    at Object._saveToServer (visEdit.js:5487)
    at visEdit.js:5510
saveRemote @ visEdit.js:174
_saveToServer @ visEdit.js:5487
(anonymous) @ visEdit.js:5510
visEdit.js:5509 [Violation] 'setTimeout' handler took 76ms`

Das ist das Widget als Export:

`[{"tpl":"tplValueFloatBar","data":{"oid":"","g_fixed":true,"g_visibility":true,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"visibility-cond":"==","visibility-val":"1","visibility-groups-action":"hide","min":"0","max":"{javascript.0.Spotify.PlaybackInfo.duration}","orientation":"horizontal","color":"","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"reverse":false,"class":"","border":"","lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"visibility-oid":""},"style":{"left":"19px","top":"222px","width":"100px","height":"16px","z-index":2},"widgetSet":"basic"}]`

**Comment by buanet** [comment]
Im letzten Update des Vis-Adapters (v 1.1.2) war offensichtlich ein Fix drin. Meine Widgets lassen sich jetzt zumindest wieder löschen. 

MfG,
André

**Comment by twonky4** [comment]
Also ich habe das Problem in der aktuellen Version v1.1.4 immer noch, allerdings bezieht es sich nicht nur aus's Löschen. Ich kann auch Wert in einem statischem HTML Element nicht ändern.

Export: `[{"tpl":"tplHtml","data":{"g_fixed":false,"g_visibility":true,"g_css_font_text":true,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"visibility-cond":"==","visibility-val":"false","visibility-groups-action":"hide","refreshInterval":"0","html":"{stand:hm-rpc.0.OEQ1223360.1.LEVEL;stand == 100 ? 'oben' : (stand == 0 ? 'unten' : stand+'%')}","html_prepend":"{w1:hm-rpc.0.NEQ1321372.1.WORKING;w1 == true ? 'läuft<div style=\"display: none\">' : ''}","visibility-oid":"hm-rpc.0.OEQ1223360.1.WORKING","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0},"style":{"left":"634px","top":"224px","font-family":"lcars_font","color":"#000000","text-align":"center","font-size":"xx-large","width":"76px","height":"35px","z-index":2},"widgetSet":"basic"}]`

Beim Löschen & Ändern bekomme ich folgende Fehlermeldung in der Console:

> visEdit.js:174 Uncaught TypeError: Cannot read property 'data' of undefined
>    at Object.saveRemote (visEdit.js:174)
>    at Object._saveToServer (visEdit.js:5487)
>    at visEdit.js:5510`

**Comment by buanet** [comment]
Bin gerade nach längere Zeit wieder beim "Bauen" in vis. Habe jetzt auch festgestellt, dass sich der Inhalt im statischen HTML Widget nicht ändern lässt. Löschen und css-Eigenschaften ändern geht bei mir. Nur der Inhalt wird nicht abgespeichert. Version 1.1.4.

Konkretes Beispiel: 
Das folgende Widget lässt sich z.B. problemlos verschieben und in der Größe anpassen. Will ich aber z.B. nach dem img-Tag ein Leerzeichen einfügen geht dies im Editor zwar (speichern wird auch angezeigt), wird aber nicht abgespeichert. Nach einem Reload ist der Inhalt wieder wir ursprünglich.

Export: `[{"tpl":"tplHtml","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":true,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","refreshInterval":"0","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"html":"<img id=\"picandtext\" src=\"/vis.0/main/img/icons/64px_white/raindrops.png\" width=\"30px\"><p id=\"picandtext\">{hm-rpc.0.KEQ0011578.1.TEMPERATURE;}&deg;C</p>"},"style":{"left":"39px","top":"91px","font-family":"RobotoCondensed-Regular","font-size":"25px","line-height":"35px","height":"35px","width":"100px"},"widgetSet":"basic"}]`

Workaround: Neues Widget anlegen und Eigenschaften und angepassten Inhalt übertragen. Danach das alte Widget löschen. :(

**Comment by twonky4** [comment]
Ich habe mir das mal näher angesehen. In vis v1.1.4 fliegt eine JS Exception in  visEdit.js in Zeile 174.
`viewsToSave[this.bindings[b][h].view].widgets[this.bindings[b][h].widget][this.bindings[b][h].type][this.bindings[b][h].attr] = this.bindings[b][h].format;`

Weil `viewsToSave[this.bindings[b][h].view].widgets[this.bindings[b][h].widget]` nicht existiert.

Packt man folgendes vor die Zeile 174
>if (viewsToSave[this.bindings[b][h].view].widgets[this.bindings[b][h].widget] === undefined) {
>   viewsToSave[this.bindings[b][h].view].widgets[this.bindings[b][h].widget] = {};
>}
>if (viewsToSave[this.bindings[b][h].view].widgets[this.bindings[b][h].widget][this.bindings[b][h].type] === undefined) {
>   viewsToSave[this.bindings[b][h].view].widgets[this.bindings[b][h].widget][this.bindings[b][h].type] = {};
>}

kommt zwar keine Fehlermeldung mehr und man kann Widgets wieder löschen, aber:
Sobald man ein neues Widget anlegt wird die ID des gelöschten wieder verwendet und im VIS wird das alte gelöschte Widget wieder dargestellt.
