### ISSUE TITLE
Can't enter license number.

### ISSUE THREAD

**Issue by ostgardh** [ioBroker/ioBroker.vis#160]
I have new install iobroker and vis
In old versoín is possible to click settings on vis.0 and enter license number.
But I get blank page..
![vis](https://user-images.githubusercontent.com/30891357/35735360-bcefb9a6-0824-11e8-8f36-c1bb9750176a.PNG)

**Comment by GermanBluefox** [comment]
Scroll down

2018-02-02 14:25 GMT+01:00 ostgardh <notifications@github.com>:

**Comment by ostgardh** [comment]
ha ha ..
I works!
Stupid page.. :)

Thanks GermanBluefox

**Comment by GermanBluefox** [comment]
Will be fixed asap.

2018-02-02 15:34 GMT+01:00 ostgardh <notifications@github.com>:
