### ISSUE TITLE
dimmer.png and humidity.png not found

### ISSUE THREAD

**Issue by AlGu1** [ioBroker/ioBroker.vis#163]
Hi,

the consol-window in Chrome shows the following error:

`jquery-1.11.2.min.js:3 GET http://192.168.178.160:8082/vis/icon/dimmer.png 404 (Not Found)`

if i look in github in file "/www/css/vis-editor.css" line 1071-1076 there are links to files where not exists in Folder "/www/Icon".

**Comment by pmaster555** [comment]
me too
