### ISSUE TITLE
Ladezeit der Android app

### ISSUE THREAD

**Issue by p33k** [ioBroker/ioBroker.vis#165]
Derzeit wird oft beim öffnen der App das komplette vis neu geladen (mit Background Bildern und so weiter) so kommt oft ein paar Sekunden die Ladeanimation.
Das ist natürlich sehr nervig wenn man **schnell** das Licht ausschalten will oder ähnliches.
Wenn die App offen ist geht es schnell auf wie es sein sollte.

Gibt es keine Möglichkeit eine Einstellung dazu zufügen bei der der Komplette resync nur manuell stattfindet und beim öffnen immer nur die Statusdaten abgefragt werden? Damit sich die Steuerung auch wirklich wie eine App anfühlt.

**Comment by smartboart** [comment]
Hallo das lässt sich doch in der App unter Einstellungen deaktivieren ...immer vom Server alles laden deaktivieren..

**Comment by p33k** [comment]
Die Einstellung gibt es bei mir in der Android App Version 1.1.1 nicht? Wo soll diese sein?

**Comment by smartboart** [comment]
![screenshot_2018-04-30-13-11-09](https://user-images.githubusercontent.com/38385805/39424720-3cc16bf6-4c78-11e8-9092-472f8d4a3ffb.png)

**Comment by p33k** [comment]
![vis android app](https://user-images.githubusercontent.com/6191925/39901090-97ffa9e6-54c6-11e8-8cfd-9c15cad6ed20.jpeg)

ist bei mir nicht da.. gibt es irgendwo eine aktuellere APK als aus dem Playstore?

**Comment by p33k** [comment]
Wenn man iobroker.pro in der App deaktiviert erscheint die Einstellungsmöglichkeit zu "immer vom server alles laden". Wenn man allerdings iobroker.pro verbunden hat verschwindet sie.
@GermanBluefox ist das richtig so?

**Comment by GermanBluefox** [comment]
Ja. Weil sonst pro überladen wird.
Ohne pro bezahlst du für Traffik.

вт, 12 июн. 2018 г., 1:29 p33k <notifications@github.com>:
