### ISSUE TITLE
Vis 1.1.2 - Es lässt sich kein Gradient Hintergrund einstellen

### ISSUE THREAD

**Issue by Harald-B-Rupp** [ioBroker/ioBroker.vis#166]
Im Vis 1.1.2 lassen sich im Edit Mode, keine vordefinierten Hintergründe (Gradienten) einstellen, lediglich feste Farben, welche man mittels der Farbauswahl erfassen kann, werden akzeptiert. Wird ein Gradient ausgwählt bleibt im Editor der Hintergrund schwarz. Wird die View dann geladen wird der eingestellte Hintergrund korrekt dargestellt.

**Comment by Lumumba76** [comment]
Ich habe das gleiche Problem in 1.1.7
