### ISSUE TITLE
komme nicht an "Wait Screen" vorbei

### ISSUE THREAD

**Issue by TonyBostonTB** [ioBroker/ioBroker.vis#168]
Bei uns in der Firma soll ich nun ioBroker fertig machen, allerdings mit Auth und HTTP via SSL.
Das Problem: ich komme beim verbinden mit der HTTPS Seite nicht weiter als bis zum "Wait Screen". Hat das mal jemand gehabt? Cache löschen habe ich schon versucht, hat nicht geholfen.

**Comment by GermanBluefox** [comment]
Ist socket io eingebaut order extra? Im Web instance?

ср, 28 мар. 2018 г., 14:23 TonyBoston <notifications@github.com>:

**Comment by TonyBostonTB** [comment]
`:8081/socket.io/?EIO=3&transport=polling&t=MALba50 Failed to load resource: the server responded with a status of 404 (Not Found)`

scheinbar sucht er socket.io?

**Comment by dilmash** [comment]
> Failed to load resource: the server responded with a status of 404 (Not Found)

Habe hier dasselbe Problem, allerdings nicht mit https sondern mit VPN. Ich habe die Bind Adresse der Admininstanz auf die VPN Adresse des Servers gesetzt und dann sehe ich nur noch das drehende Zahnrad.
Gibt es  Neuigkeiten hierzu?

**Comment by TonyBostonTB** [comment]
@dilmash 
bei mir hat es dann geholfen, das "Listen on LANIP" wieder auf "Listen on 0.0.0.0" umzustellen
