### ISSUE TITLE
Vis 1.1.3 - Bool SVG

### ISSUE THREAD

**Issue by DrBakterius** [ioBroker/ioBroker.vis#169]
Liegt es an mir bzw. meinem System oder funktioniert in Version 1.1.3 das Widget 'Bool SVG' nicht mehr?

**Comment by winterson0** [comment]
Versuch es mal mit einem anderen Browser 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DrBakterius** [comment]
Ich habe das Update noch einmal installiert und es mit Chrome, Firefox und Edge (jeweils aktuell) auf zwei Rechnern getestet. Mit allen drei Browsern das selbe Ergebnis. Weder im Vis-Editor werden 'Bool SVG' angezeigt, noch vor dem Update vorhandene Elemente in Vis.

Edit: nachdem ich wieder auf v1.1.2 zurückgegangen bin, wird auch wieder das Element in Vis angezeigt. Es liegt meines Erachtens nach also definitiv an Vis 1.1.3 ...
