### ISSUE TITLE
vis.0 aktualiesiert batterie status nicht regelmäßig

### ISSUE THREAD

**Issue by smartboart** [ioBroker/ioBroker.vis#170]
Bei aktiviertem batterie level in der vis app unter einstellungen werden die werte an die vis.0 unter objekte übermittelt, aber leider nicht wie beschrieben regelmäßig aktualisiert.

**Comment by smartboart** [comment]
habe jetzt festgestellt, dass nach einem Neustart des Tablet die Werte neu eingelesen werden. Vermutlich liegt das Problem nicht an der Kommunikation zwischen App und dem Objekt im iobroker / vis.0 , sondern eher zwischen der App und dem Tablet. Verwendet wird ein Google nexuss 7 gerootet und mit elementalx kernel..Hat jemand ähnliche Probleme? Update:  es sieht so aus als würde alles solange stabil laufen bis ein resync in der vis app durchgeführt wird...danach wird der Batteriestatus nicht mehr aktualisiert.. nach einem kompletten Neustart des Tablet und der vis App, scheint alles ok bis zum nächsten resync. Vlt. gibts Da noch ein Update

**Comment by fs-plugins** [comment]
kann ich hier nachvollziehen, nach resync keine Aktualisierung der Akku-Daten - erst nach Neustart von Table/Handy wieder aktuelle und aktualisierende Daten dazu

**Comment by smartboart** [comment]
Wegen dem Problem steuere ich die Akkuladung des Tablet jetzt mit dem paw adapter. Weil ich diese ohnehin brauche hab ich fuer mich eine Lösung gefunden..
