### ISSUE TITLE
[Improvement] VIS CSS-Property für Blinken hinzufügen, in welchem per Binding dann ein Wert für Intervall angegeben werden kann (oder so) 

### ISSUE THREAD

**Issue by manne01** [ioBroker/ioBroker.vis#176]
In der Visualisierung von Widgets ist deren Blinken als Eskalationsstufe ein beliebtes Mittel. Das Handling mit Signalbildern ist zu aufwändig. Aktuell setze ich per Property-Binding in bestimmten Situationen die Hintergrundfarbe z.B. auf rot. Es wäre super, wenn ein Blinken out of the box in einer zusätzlichen Eigenschaft im Reiter Sichtbarkeit oder CSS-Allgemein unterstützt werden würde, ein Widget komplett blinken zu lassen.

**Comment by Hypnos3** [comment]
Das Binding funktioniert auch im Reiter allgemein unter CSS:
![screenshot 2018-05-10 at 20 08 45](https://user-images.githubusercontent.com/12692680/39885876-189dcd82-548e-11e8-9f47-03c56e830d47.png)
Damit kann man einem Objekt eine andere CSS Klasse zuweisen und es beispielsweise auch "blinken" lassen.
