### ISSUE TITLE
Widget-Eigenschaft "Zeige letzte Änderung": Anzeige Zeitstempel an Stelle letzte Änderung

### ISSUE THREAD

**Issue by RK62** [ioBroker/ioBroker.vis#177]
Die Widget-Einstellung "Zeige letzte Änderung" zeigt unter bestimmtem Bedingungen nicht die letzte Änderung, sondern das letzte Update (Zeitstempel) an.

Eingestellt ist "Letzte Änderung". Verhalten in vis (getestet auf iPhone, Chrome, Edge):
- Bei Aufruf der WebSite wird "Zeistempel" an Stelle "Letzte Änderung" angezeigt
- Anzeige "Letzte Änderung" erfolgt erst wieder wenn ggf. ein anderes Element der vis-Seite einen Refresh ausgelöst hat 
- Bei F5/Aktualisieren wird wieder auf "Zeitstempel" gewechselt.

Workarround: Das Widget "Last change Timestamp" arbeitet richtig.
Siehe auch https://forum.iobroker.net/viewtopic.php?f=30&t=13246

Gruß, Ralf

**Comment by RK62** [comment]
Das Problem scheint gefixt zu sein:
Ich habe heute admin3 und mit "latest" alle Updates reingefahren.
VIS arbeitet bei mir in der V1.1.4 korrekt.

Gruß, Ralf

**Comment by RK62** [comment]
Irrtümlich geschlossen, Problem besteht immer noch.

**Comment by m0rph2k** [comment]
Hi

Kann ich bestätigen. Wäre schön wenn das gefixt wird

LG

**Comment by TjadenVdF** [comment]
Das Problem besteht leider nach wie vor. Bei Auswahl von "Letzte Änderung" wird nur der Zeitstempel angezeigt.

**Comment by thorsten26** [comment]
Ich habe da auch so ein Verständnisproblem:
Ich habe von einem Sensor ein Feld Namens Zeitpunkt, Rolle value.datetime, Der Wert ist 07.11.2019 17:48:28

Der Zeitstempel: 2019-11-07 17:55:02.335
Letzte Änderung: 2019-11-07 17:50:03.335
Wobei die Daten durch den MobileAlertsAdapter alle 5 min geholt werden.

In Vis sieht das dann so aus:

TimeStamp Value: 07 (wird nur der Tag angezeigt, die Formatierung greift nicht)
TimesValue: 07 (Wird nur Tag angezeigt, die Formatierung greift nicht)
StringValText: 07.11.2019 17:48:28 (Die Einzige Möglichkeit den tatsächlichen Wert zu bekommen, ohne Formatierung)
Timestamp: 07.11.2019 17:55:02
LastChTime: 07.11.2019 17:50:03

Dementsprechend scheint es derzeit keine Möglichkeit, außer einer Stringvariante, den Tatsächlichen Datums/Zeitwert auszulesen.

HabPanel hat das Problem nicht..

**Comment by jannnfe** [comment]
Das Problem scheint immer noch vorhanden zu sein.
Ist schon in Aussicht, ob das nochmal behoben wird?

**Comment by m0rph2k** [comment]
Push !!

**Comment by GermanBluefox** [comment]
Fixed in 1.3.3

**Comment by m0rph2k** [comment]
<3

**Comment by RK62** [comment]
In V1.3.4 erfolgreich getestet.
Danke für die Behebung!

Gruß, Ralf
