### ISSUE TITLE
vis menüleiste verschoben (1.1.4)

### ISSUE THREAD

**Issue by p33k** [ioBroker/ioBroker.vis#178]
![vis error](https://user-images.githubusercontent.com/6191925/41262329-73b734b8-6de0-11e8-8a8e-1e10603eadd7.PNG)

Die Menüleiste ist verschoben und kann nur als Workaround mit Stylish Browser Plugin gefixt werden.
`#menu_body {
    margin-top: -19px !important;
}`

Ist für den Fehler ein definitver Fix geplant? @GermanBluefox

**Comment by GermanBluefox** [comment]
Screenshot?

вт, 12 июн. 2018 г., 1:32 p33k <notifications@github.com>:

**Comment by p33k** [comment]
irgendwie ist der screenshot bei deiner antwort vertauscht und bei mir oben richtig, seltsam hier nochmal:
![41262329-73b734b8-6de0-11e8-8a8e-1e10603eadd7](https://user-images.githubusercontent.com/6191925/41284537-e13c6fc2-6e39-11e8-8e20-ab7960392ddf.png)
