### ISSUE TITLE
switches/radiobutton funktionieren nicht, wenn 'swipe' widget hinzugefügt ist

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.vis#180]
es scheint eine Regression im Zusammenspiel zwischen 'swipe' und 'radiobuttons' zu geben.
Repro in meinem Code Beispiel unter: https://forum.iobroker.net/viewtopic.php?f=30&t=7473&p=158799#p96215
Getestet auf meinem Produktiven System und einem minimal aufgesetztem System: 
- js-controller 1.4.2
- admin 2.0.9
- Discovery 1.1.0
- javascript 3.6.4
- simpleAPI 2.0.0
- socketio 2.1.1
- vis 1.1.4
- web 2.3.5

**Comment by Breisgauer** [comment]
Könnt ihr das Issue bestätigen?

**Comment by ghost** [comment]
Das Einfügen von "noSwipe" in die CSS Klasse des/der nicht funktionierenden Widgets hat bei mir zum Erfolg geführt. Trotz Swipe Widget funktioniert wieder alles.

**Comment by kahuwi14** [comment]
Hello!
Ich bin gerade auch über diesen Bug gestolpert, konnte das Verhalten aber ebenfalls dank des Hinweises von @arteck beheben.
