### ISSUE TITLE
Die Viewauswahl im VIS Editor ist zu unübersichtlich

### ISSUE THREAD

**Issue by mifricke** [ioBroker/ioBroker.vis#181]
Die Auswahl des aktuellen View in der Tableiste wird bei vielen Views sehr schnell unübersichtlich.
Hier wäre eine Art "Explorer" schön, in dem man die zu bearbeitende View auswählen kann. Damit es nicht zu viel Platz benötigt, reicht eventuell eine Dropdown Box irgendwo über dem Widget Explorer.
Alternativ die selbe Darstellung wie Widgets (eventuell Thumbnail Ansicht) in dem selben Bereich. Im Bereich darüber könnte es eine Auswahl zwischen Widgets und Views geben.

**Comment by arteck** [comment]
finde ich nicht.. wenn du zu viele Views hast dann teile diese auf mehrere Projekte. die ladezeit verkürtzt sich und die Übersicht bleibt z.b: Thematisch (Wohnzimmer, Küche) erhalten.

**Comment by mifricke** [comment]
Sorry, aber das ist für mich absolut keine Lösung des eigentlichen Problems. Ich möchte schon alles in einem Projekt verwalten können.

**Comment by Walkinlarge2010** [comment]
Es gibt doch ein Dropdown-Menü. Wenn du auf views gehst kannst du in dem Dropdown-Menü das View auswählen das du sehen willst. Oder ist etwas anderes gemeint?

**Comment by mifricke** [comment]
Ja, das ist schon nah dran. Leider muss ich halt immer wieder in das "Views" Menü um die Dropdownbox zu erreichen. Ich könnte die Box gut oberhalb der Widgetauswahl gebrauchen. Oder dauerhaft in jedem der Menüs oben. Also auch in Tools und Widgets.

**Comment by mifricke** [comment]
War das schon immer da, oder ist das in einer der letzten Versionen eingebaut worden? Das löst jedenfalls das "Problem". Oder habe ich das bisher nur immer übersehen?

![grafik](https://user-images.githubusercontent.com/5204755/61686275-6d3fcd00-ad1f-11e9-9110-669d1c583868.png)

**Comment by sigi2345** [comment]
> War das schon immer da, oder ist das in einer der letzten Versionen eingebaut worden? Das löst jedenfalls das "Problem". Oder habe ich das bisher nur immer übersehen?
> 

Schon immer............

**Comment by mifricke** [comment]
> Schon immer............

Kaum zu glauben, dass ich so blind war...  Ich schließe dann mal hier.. :-D
