### ISSUE TITLE
after update 1.1.6 wiew in widget8 is hidden

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.vis#182]
After update thge widget is not shown in editor, only in top of the page in the dropdown bit in editor is nothing

**Comment by buanet** [comment]
Same here. "View in widget 8" is no longer shown after update to 1.1.6.
The simple "View in widget" seems to be working.
Downgrading to 1.1.4 solves the problem (workaround).

**Comment by Scrounger** [comment]
have the same problem since v1.1.6

**Comment by GermanBluefox** [comment]
Fixed in 1.1.7. Thank you.

**Comment by buanet** [comment]
Fix is working. So I think this can be closed. Thx.
