### ISSUE TITLE
Widget "jqui - Input Datetime" hide Seconds working properly or not?

### ISSUE THREAD

**Issue by dkleber89** [ioBroker/ioBroker.vis#185]
I want to have a Input Field for Hours and Minutes so i found this Widget. I having here unwanted behavior for me:

Settings:
![image](https://user-images.githubusercontent.com/31743141/44626903-37367500-a925-11e8-8568-af1820516a90.png)

Then u can see i have only Hour and Minute Slider thats correct but there are Seconds in String and when i click on "Now" then you will see there also the Seconds from Now in the String
![image](https://user-images.githubusercontent.com/31743141/44626757-b4acb600-a922-11e8-9eda-bb5e7814ee99.png)![image](https://user-images.githubusercontent.com/31743141/44626897-1a9a3d00-a925-11e8-91c8-af5c4a9f7efc.png)![image](https://user-images.githubusercontent.com/31743141/44626793-40bedd80-a923-11e8-878d-09b1eb02a483.png)

Is that a bug or a wanted behavior? 
Do i make a mistake and everything working properly?

**Comment by GermanBluefox** [comment]
I think it is a bug.

**Comment by dkleber89** [comment]
Okay and in this Repo i take a look its only a implementation of the "jQuery-Timepicker-Addon" for JQUERY UI. And in my opinion the implementation is correct but its not the newest Version -> Unfortunately i found no Changelog for the Addon.

So for me it seems to be a Bug in this Addon ...
