### ISSUE TITLE
import export funktionieren nicht im Editor

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.vis#186]
Projekte können nicht importiert bzw. exportiert werden 

Chrome und FF

**Comment by ghost** [comment]
vis-Adapter 1.1.8.
Same here. See also in forum: https://forum.iobroker.net/viewtopic.php?f=30&t=16447
Does not work in Chrome, and neither with Edge under Windows 10. 

In Chrome, when navigating to "Setup > Projekte-Export/import > Exportieren (normal)", Download "Fehler – Netzwerkfehler" (Download - Network error) appears. I remember this worked several months ago well.

**Comment by BulldogISL** [comment]
Hallo..

.. habe gerade auf meiner Fehlersuche im Forum diesen nicht ganz aktuellen Beitrag gefunden..

Bei mir läuft ioBroker.admin 3.5.10 mit .vis 1.1.7

Leider bekomme auch ich beim Export meines Projektes immer diesen "Netzwerkfehler" :(
auch über mein Android Gerät habe ich es probiert..

über Firefox läßt sich der vis editor bei mir leider schon länger gar nicht mehr öffnen.
Ich habe es vollkommen stabil über Chrome laufen.
Merkwürdiger Weise funktioniert es ohne Probleme beim BeispielProjekt "main" ?!

Rein logisch betrachtet könnte es daher ja eigentlich ein bestimmter, eingebundener Adapter
verursachen..
Ideen oder bereits gefundene Lösungen bitte immer gern zu mir.. <gg>

Vielen Dank und liebe Grüße
Andre

**Comment by GermanBluefox** [comment]
Rs liegt an der Projektgröße.

Am Mi., 7. Nov. 2018, 00:01 hat BulldogISL <notifications@github.com>
geschrieben:

**Comment by BulldogISL** [comment]
> Rs liegt an der Projektgröße.

Hallo.. 
.. Wobei "Projektgröße" hier explizit heißen soll.. ?  :  

- Anzahl der eingefügten Objekte/Widgets im .Vis 
- Anzahl installierter Adapter
- Potentielle Export-Dateigröße beim Versuch desselben
-Anzahl Views

Anzahl Adapter  UND  Anzahl Views scheiden schonmal aus, da ich nach dem letzten Export beides bereits reduziert hatte und es ja JETZT leider nicht mehr funktioniert..
Was genau sollte also zu groß sein ?

LG
Andre

**Comment by BulldogISL** [comment]
So..
Nachdem ich mir beim Basteln das Filesystem auf der leider nicht gesicherten Speicherkarte des PI3
zerschossen habe und alles noch einmal neu aufgesetzt habe, habe ich den Aufwand direkt genutzt, die augenscheinlich defekte Export Funktion zu testen.
Das "Main" Projekt läßt sich ohne Probleme exportieren, auch vor der Crash bereits !
Kurzum.. Die Vermutung, das Projekt sei "zu groß" erschien mir unlogosch.

Nach der Neuinstallation importierte ich einen vorher bereits exportierten Projektstand.
Und siehe da.. Dieser ließ sich, im Gegensatz zum "Main"-Projekt, wieder nicht exportieren.

Dann hatte ich die Idee, einfach mal verschiedene, voneinander abhängige Elemente zu löschen, zu denen vielleicht andere Objekte (ganze Adapter zum Beispiel) fehlen..
Unter Anderem hatte ich ein View einer Heizungsthermostatsteuerung  vom User **Looxer01** im Projekt, an welchem ich bisher leider erfolglos herumgebastelt hatte ..  
Nachdem ich diesen View gelöscht habe, da schau her, springt der Download des Exports direkt an !! :)
Importiere ich den View erneut, gehts wieder nicht..

Ob es nun an bestimmten Abhängigkeiten des Codes dieses speziellen Views liegt, kann ich nicht sagen.
Vielleicht reagieren neuere ioBroker Versionen durch Änderungen im Code prinzipiell empfindlicher auf fehlende sich gegenseitig bedingende Objekte..?!

Einfach mal das eigene Projekt auf besagte Thermostatsteuerung checken.. Falls negativ, das Projekt auf andere fehlende Komponenten oder Bezüge prüfen..
Nur so eine Idee..

Ick freu mir so.. ! ;)

Viel Glück noch 
Andre

**Comment by Knallochse** [comment]
Ich habe ebenfalls das Problem, dass ich mein Projekt nicht exportieren kann.
Gibt es einen Lösungsansatz?

**Comment by BulldogISL** [comment]
Hallo..  Das ist jetzt schon etwas her..
Es hatte auf jeden Fall NICHT mit der Größe des Projektes zu tun !
Auf was auch immer die "Größe" bezogen gewesen sein sollte..
Wie ich mich erinnern kann, so hatte ich ja auch geschrieben, hatte ich den PI komplett neu mit dem ioBroker aufgesetzt und dann das vorherige Projekt wieder importiert..
Offensichtlich hatte ich aber Objekte bestimmter  Adapter im Projekt, dessen Adapter noch nicht wieder installiert waren..  Daher ließ sich das ohne Probleme importieren, ohne vorhandenen passenden Adapter jedoch nicht exportieren..!
Das also einmal genau prüfen, ob sich da irgendwo ein Widget eines deinstallierten Adapters versteckt hat..
Viele Grüße 
Andre
