### ISSUE TITLE
Xiaomi Philips Bulb E27

### ISSUE THREAD

**Issue by paskyecijano** [ioBroker/ioBroker.vis#188]
I am try to add xiaomi philips bulb but dont work

How i can use the script miio in iobroker???

thanks

**Comment by GermanBluefox** [comment]
Before you can control the bulb via vis, it must be connected to ioBroker
somehow.

Just now the easy way is not possible.
https://github.com/kirovilya/ioBroker.miio/issues/2
But you can ask in forum https://forum.iobroker.net which possibilities you
have.

вт, 4 сент. 2018 г. в 0:12, Pascual <notifications@github.com>:
