### ISSUE TITLE
Resync hängt beim laden der Bilddateien

### ISSUE THREAD

**Issue by smartboart** [ioBroker/ioBroker.vis#189]
Hallo zum oben gennaten Fehlerbild gibt es einen Beitrag im Forum. Siehe Link.
https://forum.iobroker.net/viewtopic.php?f=30&t=16661&p=176147&sid=2f27b48497172cef03bc7cb781dd015d#p176147
Beim resync hängt die vis app eine weile. 
Irgendwann fängt der Resync von selbst wieder bei null an und läd dann alles wie gewohnt..
Hängt immer an der gleichen  Stelle siehe Beispielfoto...
Andere User bestätigen das Fehlverhalten auch.
![01e3c953ea540017e461cceed780bb9f](https://user-images.githubusercontent.com/38385805/45267127-f717dc00-b466-11e8-8adc-28e1110db1fd.png)

**Comment by Harald-B-Rupp** [comment]
Gleiches Problem hier mit der VISAPP auf unterschiedlichster Android Hardware (Tablets, Settop Boxen und Handys).

Wir haben den WebAdapter auf Debug gestellt, leider keine siginifikaten Hinweise, wir sehen Logon und Logoff, aber keine Fehlermeldungen.

WLAN Verbindungsabbrüche können ausgeschlossen werden, da die Settop Box über das LAN Kabel angeschlossen wurde zum testen.

Keine Informationen im Android CAT Log.

1. Wir öffnen die VisApp und wechseln ins Konfigurations Menü.
2. Wir sehen Wlan Verbindung OK
3. Wir sehen das Projekt "main"
4. Wir klicken auf "Resync".
5. Bildschirm wird dunkel
6. Nach einer gewissen Zeit erscheint der oben angezeigte Fortschrittsbalken, dieser bleibt dann teilweise Stundenlang stehen, allerdings nicht immer am gleichen Objekt (Bilder usw.)

Alle Objekte liegen in /opt/iobroker

Auf dem PC mit unterschiedlichen Browsern gibt es keine Probleme mit IoB Backend.

Auf Android mit Fully Kiosk Browser gibt es keine Probleme mit IoB Backend.

**Comment by GermanBluefox** [comment]
Wie ist die Größe von der png-Datei?

**Comment by smartboart** [comment]
Vlt. 50kb aber das Thema ist eher das das  bild in keiner view mehr verwendet wird und nach meinem Verständnis garnicht geladen werden müsste / sollte...

**Comment by Hardwearhansi** [comment]
Anscheined wurde hier das problem nicht weiter behandelt aber bei mir ist der selbe fehler aufgetreten sobald ich meine vis auf mein tablet laden möchte versucht er ein widget zu laden dass aber gar nicht mehr exestiert und weiter lädt er dann auch nicht.

**Comment by smartboart** [comment]
Bin deswegen auf den fully Kiosk Browser umgestiegen. Resync dann nicht mehr nötig. Aber auch nicht ideal zwecks Aktualisierung.. Schade das das keiner anpackt...

**Comment by Apollon77** [comment]
Naja Issue ist nur bedingt Vis, sondern Android-App related, korrekt?

> Schade das das keiner anpackt...

Begrenzte Entwickler-Ressourcen bedeuten Priorisierung bedeutet ...

**Comment by smartboart** [comment]
Ja das thema ist der Android App geschuldet...
