### ISSUE TITLE
[CSS] <position: fixed> verschiebt Objekte im Editor

### ISSUE THREAD

**Issue by B748** [ioBroker/ioBroker.vis#192]
Wenn man einem View oder Objekt <position: fixed> im CSS zuweist, verschiebt sich das Objekt an die obere Bildschirmkante. In einigen Fällen springt es beim klick wieder auf die "normale" Position zurück.

(<fixed> für eine ordentliche Nutzung als web-application in iOS)

**Comment by GermanBluefox** [comment]
Ist leider so, und man muss mit css flags vorsichtig arbeiten.
