### ISSUE TITLE
setValue Debounce runtersetzen

### ISSUE THREAD

**Issue by Bjoern3003** [ioBroker/ioBroker.vis#193]
Spricht was dagegen, die Debounce Zeit auf 200ms runterzusetzen (alternativ evtl. einen Configpunkt bei dem Adapter hinzufügen)?

https://github.com/ioBroker/ioBroker.vis/blob/master/www/js/vis.js#L227

Bei mir gab es in den Tests keine Nachteile und ich konnten dieses Problem damit beheben: https://forum.iobroker.net/viewtopic.php?f=24&t=17954&p=187560

**Comment by Apollon77** [comment]
Naja das issue ist ja sign ich offen ;-)

**Comment by Bjoern3003** [comment]
Hätte ja sein können dass es "übersehen" oder aus einem anderen Grund nie übernommen wurde. Für mich wäre es halt interessant, ob der Vorschlag überhaupt einzug findet, oder ob ich für mich dann bei jedem Update einfach dieses für mich gravierende Problem immer nachziehen muss :-)

**Comment by GermanBluefox** [comment]
Implemented by Bjoern3003
