### ISSUE TITLE
View in Widget: no viewchange possible if history Widget in use / Viewwechsel mit History Widget fehlerhaft - geht nach paar Minuten nicht mehr

### ISSUE THREAD

**Issue by Walkinlarge2010** [ioBroker/ioBroker.vis#194]
Hello,

Iam using the “view in widget” widget to change my views in my main site. In one of the views I am using the history widget Sparkline. Since I using the history widget, after a few minutes I couldn’t change the view. To t
Change the views I have to refresh the page. Then it’s working, till I change to the view with the history. If I am using the flot, I don’t have this problem.

—-

German Version:

Hi zusammen,

Ich habe einen Effekt, der nur in Kombination mit dem History Widget Sparkline und dem View in Widget Widget Auftritt. Kann ihn auch reproduzieren bzw. Eliminieren indem ich das History Widget lösche. Daher würde ich einen Bug vermuten

Nun aber zum Problem.

Wie auf dem Bild zu sehen habe ich eine Hauptansicht. Auf dieser sind diverse Navigationselemente (links und unten) sowie ein View in Widget Widget (Hauptbereich Mitte). 

![6ce6b703-827d-43ce-bdda-2a92df279c65](https://user-images.githubusercontent.com/38894666/47720318-e5280d80-dc4d-11e8-95ff-b9a4a9006bca.jpeg)

Mittels der Navigationsknöpfe wird in einen Datenpunkt eine Zahl geschrieben und je nach wert wechselt das View in der Mitte auf den jeweiligen Raum bzw. die Funktion. Klappt auch alles wunderbar.

Nun wollte ich von den Flot Diagrammen weg zu dem History Sparkline Widget (hier die CO2 Anzeige). 

Das hat nun aber folgenden Effekt:
Sobald ich einmal auf der View mit einem History Widget war, schaltet das View nach ein paar Minuten nicht mehr um. Das drücken der Knöpfe verändert weiterhin den Datenpunkt zum umschalten aber es passiert nichts. Um alles wieder funktionsfähig zu bekommen muss ich die Seite neu laden, dann geht es bis ich wieder auf einem View mit dem History Widget war :(
Getestet habe ich es sowohl mit dem FullyKioskBrowser als auch mit dem iCab auf dem iPad.

Hat hier jemand eine Idee wie ich es lösen kann bzw. wer den Vermeintlichen Bug beheben kann? 

Gerne kann ich auch mein Projekt zum testen exportieren zur Verfügung stellen. Ggf kann jemand das Problem nachstellen :)

Hatte ioBroker auch mal neu installiert und danach den selben Effekt. Aktuell läuft bei mir alles unter Linux auf einem Rock64 mit NPM 6.2.0. das VIS ist die Version 1.1.7

Anbei noch die Konfig von dem History Widget
![85551be8-9946-4d0f-aeb9-b9fb51eb2920](https://user-images.githubusercontent.com/38894666/47720258-bc077d00-dc4d-11e8-9757-9dfeca1fda77.png)

Vielen Dank vorab
Walkinlarge

Gesendet von iPad mit Tapatalk

**Comment by dagrox** [comment]
Hallo, ich würde mich freuen wenn du die Visa hochladen könntest. Sieht super aus! :)
