### ISSUE TITLE
Widget html dialog Auto Zu funktioniert nicht

### ISSUE THREAD

**Issue by charakterkopf** [ioBroker/ioBroker.vis#195]
Hi, leider funktioniert bei mir beim Widget html dialog in der Visualisierung die Funktion auto-zu nicht. Bei den anderen Dialogen funktioniert es.

Hat jemand eine Tip oder ist es ein Bug?

Gruß & Danke Martin

**Comment by derRollo** [comment]
Das Gleiche hier. Bei eingestellten 5 (ms)? gehen die Dialoge nach ca. 14Min dann doch zu. Auf drei Endgeräten im Abstand von ca. 5Min. geöffnet schließen dann alle gleichzeitig. Bei den Container Widgets muss man Auto-Zu in Sekunden eingeben dann passt das, damit kann man leben.
