### ISSUE TITLE
keine Aktualisierung nach dem dritten mal (3min) 

### ISSUE THREAD

**Issue by fs-plugins** [ioBroker/ioBroker.vis#199]
getestet per Lan und W-Lan, Firefox und App gleichermaßen
das Project wird exakt drei mal aktualisiert, dann nicht mehr
dies gilt für widgets wie string, number, window usw., absolut alles wird nicht mehr aktualisiert

beim widget 'radial' (mit Luftdruck) geht zwar weiterhin regelmäßg der Zeiger animiert von 0 auf den Wert, jedoch bleibt dieser Wert (aus Javascript) ebenso wie alle anderen Zustände, egal aus welcher Art von Datenpunkt, auf dem alten Wert der letzten Aktualisierung
die Datenpunkte selbst sind während dessen ständig aktualisiert 

gibt es kritische widgets, welche die Aktualisierung verhindern könnten?

**Comment by fs-plugins** [comment]
Nachtrag:
ich habe zum Testen ein widget 'String' angelegt mit dem Datenpunkt einer Uhrzeit, welche ich jede Minute schreiben lasse
drei Minuten lang wird das widget ordentlich aktualisiert, danach bleibt die Anzeige stehen
zeige letzte Änderung (Typ letzte Änderung) aktualisiert sich jedoch weiter

**Comment by fs-plugins** [comment]
bitte als erledigt marken, war ein Fehler VOR dem screen ;-)
sorry für die Aufregung

**Comment by Apollon77** [comment]
Was war es denn?

**Comment by wendy2702** [comment]
Gibt es dazu einen thread im iobroker Forum?

**Comment by fs-plugins** [comment]
zB hier: https://forum.iobroker.net/topic/11903/kein-kamerabild-mit-vis-app-v1-1-1

**Comment by fs-plugins** [comment]
darf offenbar nicht editieren, sorry das vorige war ein anderes Thema - aber auch zu diesem Thema hier gab es Post's im Forum
