### ISSUE TITLE
It does not work correctly Show the last change

### ISSUE THREAD

**Issue by birdoplo** [ioBroker/ioBroker.vis#200]
If you click the button in the VIS. The interval display does not work. The interval is restored if you update the web page.
https://www.youtube.com/watch?v=JxuUmQIpPGw&feature=youtu.be

**Comment by cimba007** [comment]
This bug is still present. With this the last change is pretty unusable for my usecase.

vis 1.1.10
pi@ioBroker-RasPi:~ $ npm -v
6.4.1
pi@ioBroker-RasPi:~ $ node -v
v8.14.0

**Comment by Apollon77** [comment]
Please try most current version 1.2

**Comment by cimba007** [comment]
Still the same. Latest Chrome browser:

![image](https://user-images.githubusercontent.com/3453121/60384529-314a7c80-9a7f-11e9-85c8-06ced7eaf1ac.png)

No difference if using moment.js or not
When the value  is updated it switches to "non interval" mode and just displays the timestamp

Just after F5 refresh:

![image](https://user-images.githubusercontent.com/3453121/60384608-41af2700-9a80-11e9-8dfa-98bcda39013a.png)

A few moments later:

![image](https://user-images.githubusercontent.com/3453121/60384616-5c819b80-9a80-11e9-88d9-feaef330f764.png)


You can see that one value got updated

**Comment by Apollon77** [comment]
Which widgets are used? Any errors und Browser condole?

**Comment by cimba007** [comment]
Don't get fooled by the screenshot. I am using the basic HTML Widget. No errors on the console. TO be pricese no output in the event of updating the value.

![image](https://user-images.githubusercontent.com/3453121/60384724-ac149700-9a81-11e9-88e8-c4c4d35239c4.png)

The interval in the edit-window updates every minute and is working fine. But this is to be expected as the values in the edit window dont update at all:

EDIT window:

![image](https://user-images.githubusercontent.com/3453121/60384737-e9792480-9a81-11e9-981f-a886fe130ce1.png)

**Comment by cimba007** [comment]
Before update of event:

![image](https://user-images.githubusercontent.com/3453121/60384760-38bf5500-9a82-11e9-8882-8102c9c80369.png)

After:

![image](https://user-images.githubusercontent.com/3453121/60384766-4d035200-9a82-11e9-8530-e5c3244badaf.png)

**Comment by cimba007** [comment]
I am no pro but to be honest, i don't even see any code with the original time-interval here:

https://github.com/ioBroker/ioBroker.vis/blob/9cd3a469a990207af840cb25979bf1e02d180c70/www/js/vis.js

I can find it only here: https://github.com/ioBroker/ioBroker.vis/blob/01a5046d627d3f6a4fe92f8dee792f6094f2aca9/www/widgets/basic.html

Which is set on first load .. but assume the vis.js is doing the dynamic updates .. there is no code to set the original time-interval behavior
