### ISSUE TITLE
Slider touch support

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.vis#201]
Is there a way to either add Basic HTML slider (` <input type="range" min="1" max="100">`) widget that has a native support of touch screens, or add touch support for Jquery elements? 
E.g. current slider jquery widget can only be controlled on touch screens by clicking on desired position, but it is impossible to move slider by finger.

**Comment by Marsx79** [comment]
Is there any news in this regard? As before, I can only click the slider and not move slider by finger.
