### ISSUE TITLE
Delete/rename Projekt is not working

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.vis#208]
Can somebody please fix the delete and rename project function at VIS Editor.

https://forum.iobroker.net/viewtopic.php?f=30&t=2417&p=210857&hilit=Projekt+L%C3%B6schen#p210857

**Comment by wendy2702** [comment]
Problem existiert soweit mir bekannt immer noch.

Aber gut wenn automatisch geschlossen wird.

**Comment by Apollon77** [comment]
Alles ok, dann machen wir es wieder auf. Es gibt seeehr viele User die nicht tickets schliessen obwohl das Problem noch besteht

**Comment by wendy2702** [comment]
Hi,

Verstehe das nicht:

„ Es gibt seeehr viele User die nicht tickets schliessen obwohl das Problem noch besteht“

Ich habe das nicht geschlossen sondern der Stale bot.

Oder wie meinst du das?

**Comment by Apollon77** [comment]
Es gibt sehr viele User die ein gefixtes issue nicht schliessen ... dait weiss am Ende keiner welche Bugs noch "echt" sind und welche inzwischen gefixt wurden.

Deswegen habe wir den Stalebot der zuerst dazu auffordert es nochmal zu prüfen und feedback zu geben. Wenn das nicht kommt dann schliesst er das issue.

Der text sollte es an sich ausdrücken:

> Dieses Problem wurde automatisch als veraltet markiert, da es in letzter Zeit keine Aktivitäten gab. Es wird geschlossen, wenn nicht innerhalb der nächsten 7 Tage weitere Aktivitäten stattfinden. Bitte überprüft, ob das Problem auch in der aktuellsten Version des Adapters noch relevant ist, und teilt uns dies mit. Überprüft auch, ob alle relevanten Details, Logs und Reproduktionsschritte enthalten sind bzw. aktualisiert diese. Vielen Dank für Eure Unterstützung.

**Comment by wendy2702** [comment]
Hm,

Ich persönlich würde vor dem schließen eine Antwort vom Entwickler erwarten oder mir wünschen.

Zumindest kenne ich das so aus meinem professionellen Arbeitsumfeld.

Ich weiß.... hier alles freiwillig und Freizeit aber wenn User issues aufmachen und auch oft dazu aufgefordert werden sollte es doch zumindest ein kleines Feedback geben.

Ich teste das nochmal wenn ich wieder zu Hause bin. Kann mich aber nicht daran erinnern in einem changelog Eintrag gelesen zu haben das dieses Problem gelöst wurde, oder habe ich etwas überlesen bzw. Wurde es nicht dokumentiert?
