### ISSUE TITLE
timeandweather custom - no picture for day1...5

### ISSUE THREAD

**Issue by Herbert-Testmann** [ioBroker/ioBroker.vis#209]
In der Konfiguration des  Widget wird bei "Bild" der Datenpunkt "Icon" des Adapters angegeben.
ich habe den Adapter "yr.no"  und "openweathermap"  getestet.
yr.no  arbeitet mit lokalen Grafikdateien
openweathermap   mit http://...   Pfaden

Bei yr.no   werden die kleinen Bilder für die Tage day 1..3 nicht zuverlässig angezeigt.
Bei openweathermap   werden keine kleinen Bilder angezeigt.

Die Anzeige für current day funktioniert bei beiden Adaptern.

<img width="201" alt="screenshot 2019-01-06 15 16 13" src="https://user-images.githubusercontent.com/20645041/50737364-84c2c880-11c8-11e9-9c5a-0184d6543754.png">

**Comment by Drillo123** [comment]
The reported problem still exists. I have it in the current version too.
