### ISSUE TITLE
Widgets - MusicCast Adapter bitte mit einbinden

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.vis#217]
Bitte die Widgets o.g. Adapter mit einbinden in vis app und cloud.

**Comment by foxriver76** [comment]
Wenn der Adapter ein Widget bereitstellt und du diesen Adapter installiert hast, sollte es als Widget verfügbar sein. Hier muss in vis nichts zusätzlich implementiert werden.

**Comment by bahnuhr** [comment]
foxriver76
Deine Aussage dürfte nicht richtig sein.
Es geht mir nicht um vis!
Sondern um die vis.app für android handys.

Und hier muss dies sehr wohl integriert werden.

**Comment by foxriver76** [comment]
Wenn du tatsächlich die vis App für Android meinst (https://github.com/ioBroker/ioBroker.vis.cordova), stellt diese lediglich eine Alternative zum Browser dar und sollte 1:1 deinen View anzeigen. Und wenn dein View ein vom Yamaha Adapter zur Verfügung gestelltes Widget enthält, sollte auch dieses sichtbar sein. 

Allerdings wäre ich sehr interessiert daran, woher du diese Informationen beziehst?

**Comment by bahnuhr** [comment]
"Und wenn dein View ein vom Yamaha Adapter zur Verfügung gestelltes Widget enthält, sollte auch dieses sichtbar sein. Allerdings wäre ich sehr interessiert daran, woher du diese Informationen beziehst?"

Nach meiner Info ist das nicht so; und war m.E. auch noch nie so.
In der vis.app muss dies extra eingebunden werden.

siehe auch homoran:
https://forum.iobroker.net/topic/11758/musiccast-widget-unter-visapp-nicht-dargestellt/4

-> weil die app wohl eigene bibliotheken benutzt.

mfg

**Comment by foxriver76** [comment]
Ah, stimmt, die App zeigt anscheinend nur Widgets an die im Build in der package json enthalten waren. Dann brauchts wohl oder übel tatsächlich eine Änderung + neuen Build von https://github.com/ioBroker/ioBroker.vis.cordova 

Ich kümmere mich mal darum.

**Comment by bahnuhr** [comment]
Danke schön.

**Comment by Apollon77** [comment]
DIe Frage ist ob die VIS App noch gepflegt wird. Von wann ist denn der letzte Build?

**Comment by foxriver76** [comment]
Still relevant ;-)

**Comment by Apollon77** [comment]
ich habe mal "vis app und cloud" noch oben in den ersten post eingefügt :-)

**Comment by foxriver76** [comment]
War das falsche Issue, Musiccast sollte mittlerweile drin sein https://github.com/ioBroker/ioBroker.vis.cordova/blob/24cae4925756042443773b1345cd2a4d9f419f1e/package.json#L60 -> close, habe hier leider keine Rechte zum closen

**Comment by bahnuhr** [comment]
Bei Erstellung des issue war es nicht drin.
Mittlerweile wurde es eingefügt.
Somit erledigt.
