### ISSUE TITLE
Time and Weather Widgets: FlipClock

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.vis#219]
When putting the FlipClock on thescreen, the background is shifted down so that there is an around 10 pixels wide bar on top of the background. As soon as the clock ist removed, the background is back to normal covering the entire area.

![bildschirmfoto vom 2019-02-28 20-35-26](https://user-images.githubusercontent.com/11984960/53593232-783f6880-3b98-11e9-966c-8e86b4a606f6.png)

**Comment by Erzengel14** [comment]
i have the same problem, is there a solution?

**Comment by erkilic** [comment]
I have the same issue. Is there any solution in the meanwhile?
