### ISSUE TITLE
openweathermap.0.forecast.day1.date (today +1) does not display the correct date in vis

### ISSUE THREAD

**Issue by ioc73** [ioBroker/ioBroker.vis#221]
If you select the openweathermap.0.forecast.day1.date in a vis view, the value does not show the correct date (today +1). 
in the object it self the value shows the correct date for day1.

I this a knowen issue or am I doing anything wrong?

Bye

**Comment by Apollon77** [comment]
why you open two issues?

**Comment by ioc73** [comment]
sorry, for this, I was not shure where to place the issue... vis or openweathermap
