### ISSUE TITLE
View in Widget 8 not showed in special case

### ISSUE THREAD

**Issue by xolom** [ioBroker/ioBroker.vis#223]
**Following situation:**

I have a view **main**, where all other views are displayed. In the **main** view is a _view in widget 8_ which should display the content of a top navigation bar.
On my second tab i want to display all my history graphs. Therefore i have another navigation bar like a _sub menu_. So another  _view in widget 8_ is on displayed on the second tab, where i can choose the content with the buttons on the second navigation bar. (The Navigation bar contains buttons which set the appropriate number to the object linked to the view in widget 8 widget).

**Ok so here comes the issue:**

If the last selected main tab is the history tab (where i have another view in widget 8 inside), I can switch between those sub-tabs without any problems. But.... If i switch to another main tab and then back to the history tab, i can't switch between those sub-tabs anymore.

To make it more clear here is a demo:
https://schreda.com/nextcloud/index.php/s/356eDWffbK5ddcg

Please let me know if you need more information

**Comment by thenightfighter** [comment]
Same here. Still don't fixed :(
