### ISSUE TITLE
Keine gültige Lizenz gefunden V 1.1.12

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis#228]
Hallo,

Fehler , Keine gültige Lizenz gefunden. Lizenzprüfung aber Ok.
Dann wird der Bildschschirm schwarz.........Auf localhost.

![Screenshot (3112)](https://user-images.githubusercontent.com/41079106/57285304-3ad4eb00-70b3-11e9-8a05-f1f37ca96ce4.png)

**Comment by Apollon77** [comment]
fixed in 1.2.0 (in <5 mins in repo available)
