### ISSUE TITLE
Weisse Seite

### ISSUE THREAD

**Issue by carsten19** [ioBroker/ioBroker.vis#229]
Ich habe auf einem Android Tablet dauerhaft einen vis view laufen, Darstellung mittels fully.
Ich habe gerade von 1.1.10 auf 1.1.12 aktualisiert. Nun wird die Seite nach kurzer Zeit weiss. Nach einem reload erscheint der korrekte view, dann wird es wieder weiss. Im Log sehe ich nur ein disconnect und connect, keinen Fehler.
Nach einem Downgrade auf 1.1.10 geht es wieder ohne Probleme.

**Comment by sigi2345** [comment]
1.1.12 hat wahrscheinlich einen Bug.........
https://github.com/ioBroker/ioBroker.vis/issues/228

**Comment by Apollon77** [comment]
fixed in 1.2.0 (in <5 mins in repo available)
