### ISSUE TITLE
Bug: Beim maximieren des Browserfensters wird eine andere View aufgerufen

### ISSUE THREAD

**Issue by eXTreMe-1337** [ioBroker/ioBroker.vis#231]
Ich habe den Bug wenn ich vis im browser (egal ob chrome oder firefox) geöffnet habe (egal welche view) und dann das browserfenster maximiere, dass dabei immer automatisch zu einer anderen view gewechselt wird, die view auf der ich dann lande ist immer die gleiche.
Ich nutze das "View in Widget" Widget um durch meine vis zu navigieren und andere views anzeigen zu lassen, evtl hat das widget einen fehler denn die view die automatisch aufgerufen wird ist eine view die eigentlich im widget frame dargestellt werden sollte.

**Comment by Homoran** [comment]
Dann hast du den "immer gleichen" View als default view angegeben.

**Comment by eXTreMe-1337** [comment]
das habe ich inzwischen auch rausgefunden aber seltsamerweise ist der haken fest gesetzt im default view kästchen, also er ist ausgegraut :/
