### ISSUE TITLE
Random page reload

### ISSUE THREAD

**Issue by xolom** [ioBroker/ioBroker.vis#232]
Hi.

I've got the problem that the page is reloading sometimes and this is annoying... Happens like every hour or so. I tried to track the error messages in the console, but as it reloads the console is also "refreshed"..
I am using chromium in a raspberry. I also checked the memory and cpu load. Everything looks fine.
How can i debug this? Is it only me with this issue?

**Comment by Apollon77** [comment]
Please provide versions of, js-controller, admin, web, vis adapters

**Comment by xolom** [comment]
js-controller: 1.4.2
Web: 2.4.1
Vis: 1.1.11
Admin: 3.6.0

**Comment by Apollon77** [comment]
I also had such effects some time ago ... they went away as I updated all othe them to "latest" ... maybe there are some "incompatibilities in socket.io versions"

**Comment by xolom** [comment]
I used the integrated socketio of web adapter. Installed it seperately now, let's see if that helps...

**Comment by xolom** [comment]
Ok didn't solve anything...
Any ideas how to debug this further?

**Comment by xolom** [comment]
Today i noticed that the reload happens on every instance. So this is comes from iobroker and is not client related...
