### ISSUE TITLE
Bilder werden in der ioBroker.vis app nicht angezeigt 

### ISSUE THREAD

**Issue by AJJK8** [ioBroker/ioBroker.vis#243]
Hallo
Die Bilder werden in der ioBroker.vis app nicht angezeigt jedoch werden sie im Web Browser angezeigt. Ich habe keine Ahnung wieso ich habe bereits versucht andere Bildformate zu verwenden, hat jedoch nicht geholfen ich es auch mit schlechter Qualität versucht ebenfalls ohne Erfolg.
Kann mir bitte jemand Helfen
Das Bild in der Vis app:
![Screenshot_20191018-202458_ioBrokervis 1116](https://user-images.githubusercontent.com/56755387/67140690-57c63a80-f25d-11e9-9b6f-ad6fa36bb6e5.jpg)

**Comment by Apollon77** [comment]
Vis App = android app? hast du die Daten mal neu gesynct?

**Comment by AJJK8** [comment]
Ja ich habe neu geladen und gesynct und es funktioniert ebenfalls auf meinem Tablet nicht

**Comment by Apollon77** [comment]
Kannst Du mal direkt so ein bild öffnen auf dem Tablet? geht es dann?
Welcher js.controller ist im Einsatz?

**Comment by AJJK8** [comment]
Ich kann die Bilder auf meinem Tablet darstellen wenn ich über den Browser gehe. Ich verwende ioBroker über ein addons von raspbarrymatic könnte das ein Problem sein?

**Comment by AJJK8** [comment]
Ich habe die js.controller  version 1.5.14
