### ISSUE TITLE
Staus wird nicht aktualisiert

### ISSUE THREAD

**Issue by cactus-online** [ioBroker/ioBroker.vis#248]
Hallo,

seit meinem Update auf vis 1.2.2. und controller 2.x.x (aktuell 2.1.0) "friert" vis nach kurzer Zeit (2-stelliger Sekundenbereich) ein. D.h. es werden keine Stati mehr aktualisiert, obwohl der Status korrekt bei den Objekten aktualisiert wird, wird das im vis nicht angezeigt. Ich kann jedoch weiterhin mittels Widget im vis den Status des Objekts verändern.

**Comment by GermanBluefox** [comment]
Gibt es da Fehlermeldungen in der Browser Konsole?
