### ISSUE TITLE
Mehr als eine Vis-Instanz ermöglichen

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.vis#250]
Hallo, 

ich wollte mal die Anfrage stellen ob es in Zukunft möglich wäre mehr als eine Vis-Instanz zu nutzen.

Hintergund:
Ich habe meherere Tablets, über die ich mir bzw. den Kindern die Haussteuerung / Zimmersteuerung anzeige. Dazu verwende ich ein Script was nach einiger Zeit dafür sorgt das immer wieder der "Homescreen" angezeigt wird. Das löse ich über den entsprechenden Datenpunkt aus, was jedoch nicht bei Allen möglich ist, da ja eben genau dieser Datenpunkt nicht für jedes Tablet vorhanden ist.

Dank Euch!

**Comment by Apollon77** [comment]
Mehrere Projekte reichen nicht?

**Comment by peoples0815** [comment]
Leider nicht da ich ja hier:
![visinstance](https://user-images.githubusercontent.com/39387321/70938557-b4b85400-2046-11ea-9f23-febc30966878.JPG)

über das Script die gewünschte Seite "steuern" kannst. Und eben diese Datenpunkte gibt es nur einmal.

**Comment by Apollon77** [comment]
Ja, aber dazu gibt es das feld „Instanz“. Jedes device/tablet hat eine eigene id. Also: instance schreiben, dann command und so füllen. Dann hat dieses Kommando nur auf dieses Gerät Auswirkung.

**Comment by peoples0815** [comment]
Das hatte ich schon verstanden, doch funktioniert hat das bei mir nicht.
Da dachte ich dass das eben nur mit der App funktioniert. Weil wenn ich von Fully aus die View via Link-Button wechsle steht da immer notdefined

**Comment by Apollon77** [comment]
Es gibt ein Widget was du einbinden kannst um die "eigene Instanz ID" eines tablets anzuzeigen. Finde mal so die IDs raus und dann teste damit. Wenn das nicht tut ist das der Bug, tut bei mir aber an sich

**Comment by peoples0815** [comment]
Alles klar werde ich tun!

**Comment by Apollon77** [comment]
Bin gespannt ob es so tut.

**Comment by peoples0815** [comment]
Anscheinend ja, Fully hat zwar die ersten paarmal die Id nicht behalten. Dann habe ich nochmals über das Widget die Id gesetzt und seit dem ist es scheinbar die gleiche.

Ich werde jetzt mal die Tage das Script umbauen und versuchen ob es tut.
Tausend Dank Apollon

**Comment by Apollon77** [comment]
Gern
