### ISSUE TITLE
Material Design Widgets funktionieren nicht.

### ISSUE THREAD

**Issue by Elektroniker0486** [ioBroker/ioBroker.vis#253]
Hallo,

ich finde die Vis App richtig gut. Wäre super wenn man die Material Design Widgets noch mit einbinden könnte. Ich denke ich bin nicht der einzige der diese App regelmäßig nutzt.

Wenn im View ein Material Design Widget eingefügt wird und in der App geöffnet wird dann bleibt der Bildschirm weiss und es wird nichts mehr geladen.

Vielen Dank vorab!

**Comment by Apollon77** [comment]
Vis app android?

**Comment by Elektroniker0486** [comment]
Ja genau, ich nutze die Android Version.
Bei Apple weiß ich nicht ob der Fehler auch auftritt da ich keine Apple Geräte besitze.

**Comment by mottimuc** [comment]
Ich würde mich dem Punkt anschliessen. Bei Verwendung der MDW kommt es zu sporadischen Fehlern (wie oben beschrieben), in meinem Fall auf einem IPhone. Auf anderen Geräten (auch IPAD) funktionieren diese problemlos.
PS: im Browser wie in der App
