### ISSUE TITLE
Changes to index.html are not applied

### ISSUE THREAD

**Issue by Acuario4** [ioBroker/ioBroker.vis#265]
Today I tried changing the Icon (Favicon.png) in the index.html file and index.src.html file because I think that the Standard favicon is not the prettiest to use as a link on my mobile. I successfully uploaded my new Favicon to the /vis/img Folder and renamed the old Favicon. And here is my Problem: When I use nano to edit the .html files I can Change
`<link href="img/favicon.png" rel="shortcut icon" type="image/x-icon" />
    <link href="img/favicon.png" rel="apple-touch-icon" />`
to
`<link href="img/faviconNew.png" rel="shortcut icon" type="image/x-icon" />
    <link href="img/faviconNew.png" rel="apple-touch-icon" />`
without any issues but no matter what I do, the favicon won't change in my browser.
Did I edit the wrong file or something else?
I am looking forward to getting an answer soon!

Greetings

**Comment by Apollon77** [comment]
What you changed where exactly? How you uploaded the stuff into the correct folder? Which commands did you used?

**Comment by Acuario4** [comment]
Hey @Apollon77 
Thank you for the quick reply

1. I uploaded my favicon.png file in the file Manager of the vis Editor (Screenshot_1).
2. I opened another path with the file manager and renamed "favicon.png" to "faviconOld.png" (Screenshot_2). 
3. I opened the console of my Raspberry pi (via PuTTY) and got to the path "/opt/iobroker/iobroker-data/files".
4. I used `cp vis.0/viewMobile/favicon.png vis/img/` to copy the file into the correct folder.
5. Then I used `chmod` to give the file full permissions
And all of that didn't work, so I started to change some things:
6. I got to the path "/opt/iobroker/iobroker-data/files/vis/img"
7. I used `mv favicon.png faviconNew.png` to rename the file
8. I got to the path "/opt/iobroker/iobroker-data/files/vis"
9. I edited the index.html file usin the nano editor and changed:
`<link href="img/favicon.png" rel="shortcut icon" type="image/x-icon" /> <link href="img/favicon.png" rel="apple-touch-icon" />`
to
`<link href="img/faviconNew.png" rel="shortcut icon" type="image/x-icon" /> <link href="img/faviconNew.png" rel="apple-touch-icon" />`
10. Same change in the index.src.html file
11. Using the developer tools of my browser I noticed that those changes were not applied to the vis (Screenshot_3)
12. That's why I redid my recent changes, so I changed the html code back and renamed "faviconNew.png" back to "favicon.png"
That's the current state.
I hope that will help you and thank you again for the quick reply!

Greetings
![Screenshot_1](https://user-images.githubusercontent.com/47208805/74148536-f22ffc80-4c05-11ea-87ec-e675d149ce53.PNG)
![Screenshot_2](https://user-images.githubusercontent.com/47208805/74148538-f2c89300-4c05-11ea-8809-c8d827cfb4a5.PNG)
![Screenshot_3](https://user-images.githubusercontent.com/47208805/74148539-f3612980-4c05-11ea-9c9e-32663e4461b6.PNG)

**Comment by Apollon77** [comment]
There are several things in here which a wrong :-)
1.) Never edit in iobroker-data/files directly because these changes will not be seen by iobroker. There are CLI commands and the Vis Datei Manager to do such changes. This is especially true since js-controller 2.x
2.) Where you changed the index.src.html file?

I think the easiest way would be to change the favicon.png file in node_modules/iobroker.vis/www/img and then call "iobroker upload vis". After this you might need to restart web if this is caching. For sure this is not persistent and a vis update will reset the favicon ...
Also in that forder you could change the index.html ... but same effect

**Comment by Acuario4** [comment]
Hey @Apollon77 
Thank you very much for your help, those are exactly the pieces of information I needed. You saved me from a lot of time and trouble and I finally got the result I wanted.

I changed the index.src.html file in the same folder where I changed the index.html file, so in "/opt/iobroker/iobroker-data/files/vis"

I wish you a very nice day!

Many greetings

**Comment by Apollon77** [comment]
In fact you still have the problem that each update of vis ewill reset the stuf, so maybe you want to create a feature request ticket to be able to customize the favicon as configuration of the adapter or such :-)
