### ISSUE TITLE
Verbindungsfehler im VIS-Editor

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.vis#266]
Hallo,
meine ioBroker Installation:
ioBroker auf Intel NUC 7CJYH / Betriebssystem: Debian
States in Redis
Admin V4.0.2
Node V10.17.0
NPM V6.11.3
JSC V2.2.9
JSE V4.4.2
Verwahrungsort: latest

Seit dem Update von socketio und web jeweils auf die V3.0.0 bekomme ich im VIS-Editor rechts oben ca. alle 10 Minuten einen Verbindungsfehler. Im Browser-Log ist dann folgendes zu finden:

![image](https://user-images.githubusercontent.com/35137293/74606425-8ef40d80-50d0-11ea-857f-8d0c9dbdfba4.png)

Das ioBroker-Log zeigt zugleich folgende Einträge:

![image](https://user-images.githubusercontent.com/35137293/74606454-bea31580-50d0-11ea-8ab3-4f2384e1ef85.png)

Es kommen mal mehr mal weniger Verbindungsfehler hintereinander.

Gruß Steffen

**Comment by sabphil22** [comment]
Kann ich so bestätigen. 
Iobroker installiert auf eine RPI4 
Admin V4.0.2
Node V10.19.0
NPM V6.13.4
JSC V2.2.9
JSE V4.4.2

![image](https://user-images.githubusercontent.com/48645037/74774353-d37bd680-5293-11ea-9741-9fdc3c952829.png)

Gruß Philippe

**Comment by Apollon77** [comment]
Do you use any Virus scanner? Maybe Kaspersky? Try disabling it

**Comment by Steff42** [comment]
Hi Ingo,
yes i use Kaspersky, and i can´t believe it! I disabled the web-anti-virus like described in the iobroker forum and now it works. But is there another way to keep both running (vis editor and kaspersky)?
Steffen

**Comment by Apollon77** [comment]
No idea ... as long as kaspersky is interfering that agressive with the webpages I do not see any way ... Sorry

**Comment by Steff42** [comment]
With Admin V4.0.5, Web 3.0.1 and Socket.io 3.0.1 the problem is completely solved for me! Even Kaspersky Web Anti-Virus can be activated again!
Very good job!!

**Comment by sabphil22** [comment]
I can confirm that!
Admin 4.0.5
Web 3.0.1
Socket 3.0.1

**Comment by Apollon77** [comment]
Thank you!

**Comment by Dreamdancer100** [comment]
Is there any way to fix this problem !? I've the same issue! All Adapter and JS-Controller npm and node are updated. Raspberry Pi is updated too. I'm use an MacBook Pro with Safari and Firefox browser. Antivirus not installed and browser cache cleaned no result.
When I go to VIS edit page I get the message no connection and when I set an button State there're no objects in popup window. The save icon doesn't popup on the right upper corner.
Pls help

**Comment by Apollon77** [comment]
We work on a fix. for now you can use a secind Web instance for the editor and chose "websockets" there instead of socket.io in the config

**Comment by Dreamdancer100** [comment]
Ok I try and hope the best

**Comment by Dreamdancer100** [comment]
When I install socket.io adapter and setup port 8085 and fill in web.0 these port 8085 and set to socket.io browser told me Not Implemented when I open 192.168.0.73:8085 what's wrong?

**Comment by Apollon77** [comment]
SOcket.io is just used under the hood in the case.
Please install "ws" adapter. Also that port is not needed

Now create a secodn web insatnce and in the config you can choose if socket.io or ws is used in web ... then use this new web port to open vis editor

**Comment by kalle-r** [comment]
> We work on a fix. 

Can you give us a rough estimation when a fix will be available?
Same issue here. I'm not in hurry but when it takes longer then I'll try above mentioned solution.
Otherwise I'll wait for the fix :-)
