### ISSUE TITLE
Darstellen von Bildern nur Möglich, wenn Dateimanager genutzt wird.

### ISSUE THREAD

**Issue by creator81** [ioBroker/ioBroker.vis#267]
Hallo, 

ich habe ien Script in ioBroker, welches mir ein Bild von einer Webseite zieht. 
Dieses Bild wird per JS in /vis.0/Tablet/test.png gespeichert. 
Das Bild wird aber nicht vom Datei Manager gefunden. 
Andere Bilder, die ich direkt per SSH dort hingekopiere werden auch nicht gefunden im Datei Manager von VIS. 
Es gehen immer nur Bilder, die direkt über den Datei Manager hochgeladen werden.

Die Rechte oder Besitzer der Dateien sind die selben, egal wie die in den Ordner kommen, 
dennoch klappt es nicht. 

Ich nutze vis 1.2.3. 

Wäre super wenn wer eine Lösung hätte.

**Comment by Apollon77** [comment]
Bitte https://forum.iobroker.net/topic/26759/js-controller-2-jetzt-f%C3%BCr-alle-im-stable lesen, vor allem auch in der FAQ im Post # 2 ... da ist ein Link zu einem Thread wo genau das Thema diskutiert wird und wie es ab js-controller 2.0 richtig geschrieben werden muss. Ein direktes Schreiben in den ioBroker-eigene Storage via iobroker-data/files ist nicht länger erlaubt
