### ISSUE TITLE
[Feature Request] make Autosave option in Project Settings

### ISSUE THREAD

**Issue by syryna** [ioBroker/ioBroker.vis#269]
Hi,

because of a mistake (pressing CTRL+Z or CRTL+U) I lost the content of a complete view. In general that is not a problem I had a backup but I recognized my mistake quickly but not as quickly as the Autosave :-)

On Facebook I had some discussion and it seems some users had similar mistakes done and also would like to see a optional setting in the project settigs where you can configure the autosave functionality.

Suggestion:
- leave autosave by default on ON as it is right now
- but give users a setting in the project where they can disable it. In this case the save button should be visibal always and the user would have to press it to execute a save.

Michael

**Comment by Tagiwara** [comment]
Its not an Issue but i agree with that. I also don't understand what this function is supposed to do. I have often shot my view because it was saved automatically.

please turn auto save function  off and install a save button
