### ISSUE TITLE
Offline Lizenz

### ISSUE THREAD

**Issue by cybermann22** [ioBroker/ioBroker.vis#271]
Hallo, leider musste ich heute feststellen,  dass meine VIS nach Intertausfall ohne Funktion war. Scheinbar wird die Lizenz geprüft. Das ist eine Katastrophe,  da ich die Alarmanlage über VIS steuere. Der Grund für Iobroker war ja gerade der, dass ich vom Internet unabhängig sein wollte.
Bitte die Lizenzenprüfung überdenken.

**Comment by GermanBluefox** [comment]
Commercial Lizenz ist auch offline gültig.
