### ISSUE TITLE
IP Cam Einbindung

### ISSUE THREAD

**Issue by Balu0127** [ioBroker/ioBroker.vis#274]
Hab leider ein Problem mit der Vis ich bekomme immer schwerer IP Kameras in die Vis mit Widgets eingebunden.

Bis jetzt ist es über Http gegangen, wenn die Adresse so aufgebaut ist.
http://192.168.***.**=admin&pwd=admin
Also 1.) IP danach Zugangsdaten.

Leider haben immer mehr der Hersteller auf ein Anders Format gewechselt.

http://admin:Passwort@ip-adresse:Port

Würde mich über eine Lösung in der Vis freuen ohne zusätzliche Umwege.
Danke

**Comment by Apollon77** [comment]
Und genau letzteres format verbieten immer mehr Browser weil es unsicher ist. Das ist das Dilemma. Ich glaube da braucht es eher einen Adapter der solche Datenströme durchleitet oder so.

**Comment by Balu0127** [comment]
Ja, leider hilft mir Linux nicht viel weiter. Hab iobroker unter Windows laufen. Leider finde ich nicht wirklich einen Adapter der Rstp unterstützt. So einen Adapter finde ich als die besser Lösung. Leider fehlt mir das wissen dazu so etwas zu verwirklichen.

**Comment by jh2k19** [comment]
Unter Linux fuktioniert Motioneye bzw. Motion super. Unzählige Streams werden unterstützt. Habe gestern auch mehrere Kameras via RTSP eingebunden. Könnte auch auf einer Synology in Docker betrieben werden.

**Comment by Balu0127** [comment]
Okay, noch mal hilft mir bei Windows nicht weiter. Trotzdem danke.
