### ISSUE TITLE
Vis Permission error for user ..

### ISSUE THREAD

**Issue by david883** [ioBroker/ioBroker.vis#283]
Hallo,
Ich habe Probleme nach dem Umzug auf einen neuen Server (proxmox VM) mit Benutzern und Gruppen im Vis/Iobroker.

Der Admin User kann alle Views ansehen und alle Zustände setzen und ändern. Iobroker und Vis funktionieren ohne Probleme.

Die Gruppe User und deren Nutzer können keine Schaltzustände ändern.

Eine neu angelegte Usergruppe mit neuem User kann auch keine Schaltzustände ändern.

Im Iobroker Admin folgender Log:
Permission error for user  ...

Ich bekomme im Vis immer folgende Meldung angezeigt:
Kann das Kommando "setState" für sonoff.17.Licht-Flur-Obergeschoss.POWER nicht ausführen, weil nicht genügend Zugriffsrechte vorhanden sind.

Ich habe den Fixer schönen ausgeführt und die Instanz und den Server mehrfach neu gestartet. Keine Änderungen.

Auch die Standart Acl Werte sind im Iobroker Admin gesetzt.

Daten:
Iobroker-vm:~# npm -v
6.14.4
iobroker-vm:~# nodejs -v
v12.16.3
iobroker-vm:~# node -v
v12.16.3
iobroker-vm:~#

Iobroker Admin 4.0.9

Ausgabe des Fixers:
`

david@iobroker-vm:~# cd /opt/iobroker
--
  | david@iobroker-vm:/opt/iobroker# iobroker fix
  | library: loaded
  | Library version=2020-04-12
  | ioBroker or some processes are still running:
  | io.admin.0
  | io.alexa2.0
  | io.backitup.0
  | io.discovery.0
  | io.email.0
  | io.history.0
  | io.info.0
  | io.moma.0
  | io.mqtt.0
  | io.ping.0
  | io.sonoff.0
  | io.sonoff.1
  | io.sonoff.10
  | io.sonoff.11
  | io.sonoff.12
  | io.sonoff.13
  | io.sonoff.14
  | io.sonoff.15
  | io.sonoff.16
  | io.sonoff.17
  | io.sonoff.18
  | io.sonoff.19
  | io.sonoff.2
  | io.sonoff.20
  | io.sonoff.21
  | io.sonoff.22
  | io.sonoff.23
  | io.sonoff.24
  | io.sonoff.25
  | io.sonoff.3
  | io.sonoff.4
  | io.sonoff.5
  | io.sonoff.6
  | io.sonoff.8
  | io.sonoff.9
  | io.sql.0
  | io.tankerkoenig.0
  | io.web.0
  | io.javascript.0
  | io.telegram.0
  | Please stop them first and try again!
  | david@iobroker-vm:/opt/iobroker# iobroker stop
  | david@iobroker-vm:/opt/iobroker# iobroker fix
  | library: loaded
  | Library version=2020-04-12
  |  
  | ==========================================================================
  |  
  | Welcome to the ioBroker installation fixer!
  | Script version: 2020-04-12
  |  
  | ==========================================================================
  |  
  |  
  | ==========================================================================
  | Installing prerequisites (1/3)
  | ==========================================================================
  |  
  | OK:1 http://security.debian.org/debian-security buster/updates InRelease
  | OK:2 http://debian.inf.tu-dresden.de/debian buster InRelease
  | OK:3 http://debian.inf.tu-dresden.de/debian buster-updates InRelease
  | OK:4 https://deb.nodesource.com/node_12.x buster InRelease
  | Paketlisten werden gelesen... Fertig
  | Installed gcc-c++
  |  
  | ==========================================================================
  | Checking ioBroker user and directory permissions (2/3)
  | ==========================================================================
  |  
  | Created /etc/sudoers.d/iobroker
  | Fixing directory permissions...
  |  
  | ==========================================================================
  | Checking autostart (3/3)
  | ==========================================================================
  |  
  | Enabling autostart...
  | Autostart enabled!
  |  
  | ==========================================================================
  |  
  | Your installation was fixed successfully
  | Run iobroker start to start ioBroker again!
  |  
  | ==========================================================================
  |  
  | david@iobroker-vm:/opt/iobroker# iobroker start
  | david@iobroker-vm:/opt/iobroker

`
![Screenshot_2020-05-05-23-45-02-762_com android chrome](https://user-images.githubusercontent.com/28392840/81303137-9b5a8780-907b-11ea-95b3-10ec51995733.jpg)

**Comment by Apollon77** [comment]
Hier sind Objekt und State - also die Rechte der User gemeint nicht im Filesystem.

Bitte die Gruppen und user rechte Konfiguration posten.

Weiterhin: welcher js.controller?

**Comment by david883** [comment]
Hallo,
js-controller 2.2.9

Rechte der Gruppe David: 
![Screenshot_2020-05-08-18-51-32-963_com android chrome](https://user-images.githubusercontent.com/28392840/81428745-fb752a80-915c-11ea-9abd-082ecf52d0b1.jpg)

Ich habe allerdings auch schon alle Rechte an den Benutzer vergeben und als das nicht klappte habe ich den Benutzer zur Admingruppe hinzugefügt. Leider der gleiche Fehler.

**Comment by david883** [comment]
![Screenshot_2020-05-08-18-54-55-303_com android chrome](https://user-images.githubusercontent.com/28392840/81429000-6f173780-915d-11ea-8bf4-f3d25952176a.jpg)

**Comment by Apollon77** [comment]
Hat der STate selbst bestimmte Rechte? Zeig mal bitte da die Ansucht vom betroffenen State

**Comment by david883** [comment]
Hallo, wo finde ich das?

**Comment by Apollon77** [comment]
Objekte -> expertenmodus -> In Zeile des Objekts rehcts der Stift. Da ist dann permissions als Tab glaube ich

**Comment by david883** [comment]
OK hier ein ausgewähltes Objekt das nicht im Vis funktioniert:
![15891904678101800281064906581522](https://user-images.githubusercontent.com/28392840/81548252-49687900-937d-11ea-85e9-59686fcd7cea.jpg)
![15891905092988986782107511949532](https://user-images.githubusercontent.com/28392840/81548285-5ab18580-937d-11ea-8e20-4d346e545494.jpg)

![15891905358035193070098531017669](https://user-images.githubusercontent.com/28392840/81548318-69983800-937d-11ea-9942-adfd34551a67.jpg)
