### ISSUE TITLE
vis-inventwo and vis-icontwo Adapter in iobroker.vis app

### ISSUE THREAD

**Issue by jkvarel** [ioBroker/ioBroker.vis#285]
Hello,

Can you add our two adapters to the app version? 
Do we have to do something for that?

https://github.com/inventwo/ioBroker.vis-inventwo
https://github.com/inventwo/ioBroker.vis-icontwo

**Comment by GermanBluefox** [comment]
vis-inventwo was added in the latest app 2.1.0

**Comment by jkvarel** [comment]
Can you update vis-inventwo to the newest stable version 2.5.11?
