### ISSUE TITLE
Missing pulldown-menu in visualisation

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.vis#290]
I wanted to change something in my VIS when I noticed that the pull-down menu on the right edge of the screen is no longer visible. Before I could use it to select objects.

I'm using Firefox and Chrome, changed the "zoom" for both and cleared the cache. Even moving the bar does not bring any improvement.
![fehler](https://user-images.githubusercontent.com/42386692/90978134-b29a8380-e54b-11ea-88db-8e5d25fcd435.jpg)

**Comment by jolichter** [comment]
Yes, I can confirm that. Maybe as workaround: downgrad back to VIS 1.2.6 (WEB 3.0.10 / Socket.io 3.0.12) and everything runs again (#292).

**Comment by foxriver76** [comment]
Still happening in current version?

**Comment by GermanBluefox** [comment]
Is it some specific widget or all widgets?
