### ISSUE TITLE
VIS hangs after update to version 1.2.9

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.vis#291]
#289 did not resolved the problem for me.
After resync the VIS (both my tablet and my phone) the app stucks again.
A popup is showing: "Alert, No views found in abfragen" 
In the settings it is not possible to select any projects.

A downgrade is not possible for me, v1.2.8 and v1.2.7 are not avaiaible anymore.

**Comment by foxriver76** [comment]
Still an issue with 1.2.11 and above? Which app? Is the app up-to-date?
