### ISSUE TITLE
Cannot find view "chart" for search "chart" : null

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/ioBroker.vis#292]
Hi, ich habe seit der Version 1.2.9 das Problem das immer wieder mal die Meldung 
`web.0 | 2020-08-24 15:46:35.131 | error | (2408) Cannot find view "chart" for search "chart“: null`
ausgegeben wird in meiner Vis habe ich keine view **chart** .
Hier noch ein [debug log](https://github.com/ioBroker/ioBroker.vis/files/5118281/Cannot.find.view.txt) in dem aber auch nicht viel zu sehen ist.

Hat wohl mit dem Float Adapter zutun da ich den nicht installiert habe sobald ich ihn installiere kommt die Meldung nicht mehr da ich ihn aber nicht brauche sollte es vielleicht  im code abgefangen werden ob der Adapter installiert ist oder nicht.

**Comment by jolichter** [comment]
Hi, same issue like xXBJXx with VIS 1.2.10 and I don't use any charts (WEB 3.0.12 / Socket.io 3.0.13).
Also the button "Select ID from object" is missing #290.
I downgraded back to VIS 1.2.6 (WEB 3.0.10 / Socket.io 3.0.12) and everything runs again.

Thx

**Comment by foxriver76** [comment]
Problem is, that BF emits a `getObjectView` to for the design `charts` (https://github.com/ioBroker/ioBroker.vis/commit/e134632f3d0b0a64fca4b7ffaccddc31c1edca10#diff-cac666adcc96f99ac47921351950e570R806) but this design is only created when flot adapter is installed
https://github.com/ioBroker/ioBroker.flot/blob/cbf292cca656c32eddd247af1f48c2d672c73b15/io-package.json#L279

now we will get an error, and immediately return instead of executing the necessary following code, I guess this is also the problem of #290

**Comment by foxriver76** [comment]
But seems like it is fixed with 1.2.11 https://github.com/ioBroker/ioBroker.vis/commit/83fa2de7ece8df6ef7cccfc517a9f0dca11832e0

**Comment by Anzic23** [comment]
Material 1.2.2
WEB 5.2.10

Similar problem. Material cannot load objects. Hangs on their loading. There is an error in the log:
`2022-10-31 12:05:13.379 | error | Cannot find search "chart" in "system"`

**Comment by Apollon77** [comment]
@Anzic23 But you see the post above yoursthat it got fixed in 1.2.11 ? When you use 1.2.2 then yes ... Please update

**Comment by Anzic23** [comment]
> @Anzic23 But you see the post above yoursthat it got fixed in 1.2.11 ? When you use 1.2.2 then yes ... Please update

I almost always use the latest version of adapters. Here I also have the latest version installed.
Latest commit [949e783](https://github.com/ioBroker/ioBroker.material/commit/949e78330c7872f77c4418777f3f594edf908dff) 13 days ago

**Comment by Apollon77** [comment]
Ahhh  you talk about material ... but here we are in vis repo? maybe the same fix needs to be done in material too ?

**Comment by Anzic23** [comment]
> Ahhh you talk about material ... but here we are in vis repo? maybe the same fix needs to be done in material too ?

Sorry, you're probably right. I just found this issue through Google, did not pay attention that it was for vis.
Create a new issu in the appropriate repository?

**Comment by Apollon77** [comment]
>  Create a new issu in the appropriate repository?

Makes the most sense, yes ... but please referene to here. Thank you
