### ISSUE TITLE
Dokumentation & Vorgehensweise bei Widget Entwicklung

### ISSUE THREAD

**Issue by xDGeForcexD** [ioBroker/ioBroker.vis#293]
Hallo,

ich bin gerade dabei an einem eigenen Widget zu erstellen. Leider komm ich aber nicht voran.

Wie sollte man den bei der Widget Erstellung vorgehen?
Mir geht hauptsächlich um das testen und einspielen von einer neuen Version.

Als Grundlage habe ich mir ein Adapter aus dem Adapter Creator erstellt (Typescript & Widget)

Ich hatte diese Vorgehensweise gefunden: https://forum.iobroker.net/topic/930/vis-erstellung-von-widgets/3
Leider funktioniert dies nicht mehr. Wie geht man jetzt vor?

Gibt es irgendwo hilfreiche Dokumentationen welche Methode oder Objekte zu verfügung stehen?
Ich finde einfach nichts zum Thema Widget Erstellung.

Hoffe das sich hier ein paar hilfreiche Tipps ergeben.

Viele Grüße
xDGeForcexD

**Comment by GermanBluefox** [comment]
Was genau funktioniert nicht?
Mittlerweile bei jedem Versuch schreibe ich 
`iob r vis`
`iob u vis`

Ja.. umständlich, aber funktioniert immer

**Comment by xDGeForcexD** [comment]
Wenn ich nach diesem Vorgehen vorgehe:

> Es ist natürlich mühsam immer 2 Minuten bei jeder Änderung zu warten. Ich mache das so:
/opt/iobroker/iobroker-data/files/vis/edit.html mit dem Inhalt von edit.html.original ersetzen (liegt auch da)
das gleiche auch mit index.html
Danach cache.manifest modifizieren (egal was. Ich ändere "build" Nummer).
Ich kann jetzt /opt/iobroker/iobroker-data/files/vis/widgets/mywidgets.html modifizieren und einfach mit F5 (Update-Seite) dann die Änderungen

dann ändert sich nichts.
Eine edit.html.original gibt es nicht mehr ich denke mal das sie jetzt .src heißt?

Ich werde mal die zwei Befehle testen ob es dann funktioniert.

Vielen Dank.

Mein Projekt ist jetzt bisschen eingeschlafen :(
Weis somit nicht wann ich es testen werden.
