### ISSUE TITLE
Entprellzeit verschwunden in v1.2.12

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.vis#300]
Die Option zum Einstellen der Entprellzeit ist mit aktueller Version 1.2.12 nicht mehr enthalten
![image](https://user-images.githubusercontent.com/41550245/93027794-b92e8f00-f60f-11ea-9db3-7871fb09dd56.png)

**Comment by Xsev1** [comment]
Bei mir ebenfalls, nach update auf 1.2.12

**Comment by GermanBluefox** [comment]
Fixed in 1.3.2
