### ISSUE TITLE
Using formula in widget ObjectID field

### ISSUE THREAD

**Issue by apla2016** [ioBroker/ioBroker.vis#301]
Here is my fully operational widget with ActualTemperatureID derived from AccuWeather adapter showing temperature in degrees C. My ObjectID of interest here is accuweather.0.Current.Temperature.

![image](https://user-images.githubusercontent.com/19657413/93148411-b5f3db80-f6c1-11ea-8ca4-2e34c5af4b1b.png)

I am trying to convert temperature to degrees F using binding of ObjectID in widget. As I understand from VIS WiKi here is what I need to enter into ActualTemperature ID, but it does not work. What am I doing wrong?
{accuweather.0.Current.Temperature; *(9);/(5);+(32)}

**Comment by GermanBluefox** [comment]
Not in Object ID, but into html widget.
![image](https://user-images.githubusercontent.com/4582016/93719623-0d8fbc80-fb84-11ea-9ec0-1fbc159dc307.png)

And it will only be rendered in runtime (not in edit mode)

**Comment by apla2016** [comment]
Thank you, the formula does work in gadget HTML field. So, does it mean 
that "Bindings of objects" paragraph in VIS WiKi is only about HTML? It 
would be great to make it clear in WiKi page

Regards,

Anatoly
