### ISSUE TITLE
Nach update auf 1.2.11 funktioniert vis nicht mehr

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.vis#302]
Ich habe ein update von 1.2.6 auf 1.2.11 gemacht. Danach funktionierte das laden von vis und auch vis Edit nicht mehr. Auch nach dem downgrade bleibt das Verhalten bestehen. Es kommt immer "Loading values" und dann geht nichts mehr weiter (siehe Screenshot incl. Console output). Was könnte da das Problem sein?
<img width="1302" alt="Screenshot 2020-09-16 at 13 15 28" src="https://user-images.githubusercontent.com/35381530/93330566-43007700-f81f-11ea-84cc-b0d5878c3542.png">

**Comment by Apollon77** [comment]
Hast DU auch socketio und web auf der aktuellsten version? Wenn nein bitte updaten

**Comment by Apollon77** [comment]
bzw .. 1.2.12 ist aktuell weil 1.2.11 nen bug hatte!!

**Comment by nkleber78** [comment]
ich hatte web auch auf der aktuellsten version (3.0.12) und socketio verwende ich das integrierte und nicht separat installiert, allerdings spinnt dann mein System sowieso denn dann ist immer irgend ein adapter nicht installiert. Z.b. web wird installiert wird, dann ist z.b. weatherunderground nicht mehr installiert. Nach einen adapter restart von weatherunderground muss dieser wieder installiert werden. Danach scheint aber wieder web nicht mehr installiert. So ist das spiel endlos, daher bin ich wieder zurück auf die 1.2.6 mit web 3.0.9 gegangen wo es stabil ist bis auf vis

btw. 1.2.12 von vis ist nur im latest und nicht auf default. Daher habe ich 1.2.11 installiert. Ich vermeide installationen vom latest generell...

**Comment by Apollon77** [comment]
Ok, 1.2.12 comes to stable now. 

Wegen Install Themen am besten im Forum support suchen. WIndows?

**Comment by nkleber78** [comment]
Alles klar, danke. Ich verwende das Docker image von buanet auf der synology -> linux system. In Kombination mit welcher web version sollte 1.2.12 funktionieren? Sollte das mit 3.0.12 funktionieren? Sagen dir die Fehlermeldungen von der console was, kann man da etwas eingrenzen. Denn vorher hat ja die derzeit installierte Kombination funktioniert...

**Comment by Apollon77** [comment]
3.0.12 sollte tun an sich.

**Comment by nkleber78** [comment]
Es scheint als ob die Installation von VIS etwas kaputt macht. Wenn ich web auf 3.0.12 update dann läuft alles richtig. Auch bei einem Neustart von IOBroker passt alles. Wenn aber danach Vis auf 1.2.12 upgedatet wird, dann zerstört das offensichtlich die web installation. Anbei der log von der Vis installation und auch die info nach dem restart von web
<img width="1254" alt="Screenshot 2020-09-17 at 11 07 12" src="https://user-images.githubusercontent.com/35381530/93450607-73571c80-f8d6-11ea-8e2c-da2875ecc94f.png">
[upgrade_vis.txt](https://github.com/ioBroker/ioBroker.vis/files/5237836/upgrade_vis.txt)
wenn aber web wieder installiert wurde, dann fehlt vis wieder (hier der screenshot wenn vis neu gestartet wird)
<img width="1254" alt="Screenshot 2020-09-17 at 11 12 17" src="https://user-images.githubusercontent.com/35381530/93450909-cdf07880-f8d6-11ea-96bd-da26ba7a71f9.png">

**Comment by Apollon77** [comment]
which js-controller you run?

**Comment by nkleber78** [comment]
3.1.4

**Comment by GermanBluefox** [comment]
It looks like the json file with views is broken. Can you fix it manually?
It should be placed on `/opt/iobroker/iobroker-data/files/vis.0/main/vis-views.json`

**Comment by nkleber78** [comment]
Scheint als wäre dies ein allgemeines Installationsproblem gewesen welches sich hier sehr speziell geäußert hat

**Comment by Cromit001** [comment]
Hallo,
ich habe nun einen ähnlichen Fehler, wie anfangs von nkleber78 beschrieben.
Nach installation des Adapters J-Query-UI-Stil Widgets im IOBroker startet mein iobroker.vis Editor im Browser nicht mehr.
Hier die Fehlermeldung beim Laden:
![grafik](https://user-images.githubusercontent.com/112241650/187020867-bcd37c67-c3f6-48d2-9925-8c8b17305ee8.png)

Bin echt verzweifelt.
Kann mir hier jemand weiterhelfen?
Vielen Dank schon mal im Voraus!
