### ISSUE TITLE
Binding in 1.2.12 not working 

### ISSUE THREAD

**Issue by MC-1984** [ioBroker/ioBroker.vis#303]
I use bindings like 
`{v:0_userdata.0.xxxx;v != false ? "blink" : ""}`
at the CSS Class field.

In 1.2.12 the bindings do not work any more.

**Comment by foxriver76** [comment]
I assume this has only worked with 1.12.10 and 1.12.11 and not previous versions of vis, because these two versions had a bug. Normally bindings are all of type string, as stated by the documentation

> Take care about types. All of them defined as strings. To be sure, that value will be treated as number use parseFloat function.

And `false` is not equal to a string `"false"` so what you need is, e.g.:

`{v:0_userdata.0.xxxx;v !== "false" ? "blink" : ""}`

**Comment by oweitman** [comment]
please see my comment in https://forum.iobroker.net/topic/36863/binding-funktioniert-nicht-mehr/5 and https://github.com/ioBroker/ioBroker.vis/pull/281

**Comment by MC-1984** [comment]
Thanks everyone for the explanation!

**Comment by cdellasanta** [comment]
Your really really really  should document that .. I've lost a big amount of time because of that, 

I suggest you add a notice of the `boolean` special treatment in  https://github.com/ioBroker/ioBroker.vis#bindings-of-objects

**Comment by foxriver76** [comment]
There is no special treatment for boolean, also the linked documentation already states that in a binding every value is a string. 

> Take care about types. All of them defined as strings. To be sure, that value will be treated as number use parseFloat function.

**Comment by cdellasanta** [comment]
😵 my bad, I've read the whole paragraph before I posted here... but I missed it.
