### ISSUE TITLE
cannot upgrade vis to 1.3.0 on a slave

### ISSUE THREAD

**Issue by rg-engineering** [ioBroker/ioBroker.vis#304]
when I try to upgrade my vis adapter on a slave I get

`Required dependency "web" not found on this host.`

but web@3.0.13 is installed

```
datalogger@orangepizero:~$ iobroker upgrade web
Adapter "web"            is up to date.
datalogger@orangepizero:~$ iobroker version web
3.0.13
datalogger@orangepizero:~$ iobroker version vis
1.2.6
datalogger@orangepizero:~$ iobroker upgrade vis
Required dependency "web" not found on this host.

```

btw. web@3.0.12 is also installed on the host...

**Comment by Apollon77** [comment]
iobroker upload web?

**Comment by rg-engineering** [comment]
does not help. still the same error message...

**Comment by Apollon77** [comment]
Please try restart controller on the host (or reboot)

**Comment by Apollon77** [comment]
Ist es wirklich diese version auf dem slave? Bitte schau mal in /opt/iobroker/node_modules/iobroker.web/package.json wa da für eine version steht

**Comment by rg-engineering** [comment]
reboot of slave and host does not help...
package.json on slave and admin/adapter show web@3.0.13

**Comment by GermanBluefox** [comment]
vis should be installed on the same host, where web is. Vis does not "run" it just let the "web" adapter to show their files.

**Comment by rg-engineering** [comment]
`vis should be installed on the same host, where web is`

in my case both adapter are installed on a slave...
