### ISSUE TITLE
VIS 1.3.x and Fully Kiosk Browser / Wall Panel

### ISSUE THREAD

**Issue by DrBakterius** [ioBroker/ioBroker.vis#305]
I have already equipped an old tablet (Android 4) with the Fully Kiosk Browser which shows me a weather page from VIS. After installing VIS 1.3.0 the browser does not load the page anymore. Only the loading circle (without countdown) is visible.

VIS 1.3.1 has the same problem and even with 'Wall Panel' only the loading circle is shown. But with Chrome everything works correctly. A downgrade to VIS 1.2.12 solved the problem, but this cannot be a final solution.

-----

Ich habe schon einige Monate ein altes Tablet (Android 4) mit dem Fully Kiosk Browser ausgestattet der mir eine Wetterseite von VIS anzeigt. Nach der Installation von VIS 1.3.0 lädt der Browser die Seite nicht mehr. Es ist nur der Ladekreis (ohne Countdown) zu sehen.

VIS 1.3.1 hat dasselbe Problem und auch mit 'Wall Panel' wird nur der Ladekreis angezeigt. Mit Chrome funktioniert aber alles korrekt. Ein Downgrade auf VIS 1.2.12 hat das Problem zwar behoben, doch das kann keine endgültige Lösung sein.

**Comment by Apollon77** [comment]
Is also web updated to latest stable version?

**Comment by DrBakterius** [comment]
'Web' is v3.0.13

**Comment by GermanBluefox** [comment]
Cache?

**Comment by DrBakterius** [comment]
I have installed v1.3.1 again. As long as the page is open in the browser, it continues to work. But when the browser is restarted, only the loading circle appears.

Cache from browser, from app and from all apps deleted. Device restarted. Still does not work. I had never installed Wall Panel before and even there only the loading circle is displayed.

-----

Ich habe v1.3.1 noch einmal installiert. Solange die Seite im Browser geöffnet ist, funktioniert sie weiter. Doch bei Neustart des Browsers erscheint nur der Ladekreis.

Cache vom Browser, von der App und von allen Apps gelöscht. Gerät neu gestartet. Funktioniert trotzdem nicht. Wall Panel hatte ich zuvor überhaupt noch nie installiert gehabt und auch dort wird nur der Ladekreis angezeigt.

**Comment by DrBakterius** [comment]
Other users might have the same problem. See here: https://forum.iobroker.net/topic/36925/vis-ab-1-3-0-auf-android-4-4-2-lenovo-7600-keine-anzeige

-----

Andere Benutzer dürften das selbe Problem haben. Siehe hier: https://forum.iobroker.net/topic/36925/vis-ab-1-3-0-auf-android-4-4-2-lenovo-7600-keine-anzeige

**Comment by DrBakterius** [comment]
Unfortunately the problem remains with v1.3.3. Also other apps like 'SureFox Kiosk Browser Lockdown' only show the loading circle with '...' in the middle.

-----

Leider bleibt das Problem auch mit v1.3.3 bestehen. Auch andere Apps wie 'SureFox Kiosk Browser Lockdown' zeigen nur den Ladekreis mit '...' in der Mitte an.

**Comment by DrBakterius** [comment]
Unfortunately the problem still exists with v1.3.4!

-----

Leider besteht das Problem auch mit v1.3.4 immer noch!
