### ISSUE TITLE
Nach Update auf 1.3.3 Zugriff von bestimmtem Endgerät nicht mehr möglich

### ISSUE THREAD

**Issue by olderbag** [ioBroker/ioBroker.vis#307]
Problem tritt reproduzierbar nach Update von 1.2.12 auf 1.3.3 auf:
An einem Gerät (Tablet mit Android 4.3) kann ich weder auf VIS noch auf den Admin-Screen zugreifen.
Beim Zugriff auf VIS zeigt der Bildschirm "Verbinde mit dem Server..." ("Loading Values" kommt nicht!!!) und die Sanduhr (Ladekreis) läuft ewig.
Beim Zugriff auf den Admin Screen werden die (leeren) Frames geladen, sonst nichts.

Neustart, anderer Browser, Browserdaten löschen - nichts hilft. Zugriff auf andere Geräte im Netz (z.B., FritzBox, CCU) funktioniert.

Auf dem PC und dem Handy geht alles einwandfrei.

Rollback auf 1.2.12: alles wieder i.o.

**Comment by Bandit2001** [comment]
Habe das gleiche Problem an meinem "Haupt-Tablet" an der Wand.
Ein Test mit dem IE11 auf einem Windows 10 PC fördert folgendes zu Tage:
![SyntaxError](https://user-images.githubusercontent.com/20992568/94711531-85aa6f00-0348-11eb-937d-ded86b280065.png)

Hier hat sich wohl etwas an der Kompatibilität mit älteren Geräten geändert.

Edit:
Auch bei mir funktioniert es mit der 1.2.12 wieder, mit der 1.3.0 ging es auch schon nicht mehr.

**Comment by dfoerster79** [comment]
Hi have the same problem with my iPad ios9. After upgrade the VIS doesn't loading the page. Update to version 1.3.4 is no solution.
