### ISSUE TITLE
SliderTabs Anzeige falsch

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.vis#309]
Die Tabs werden nicht nebeneinander, sondern untereinander angezeigt.

<img width="380" alt="Bildschirmfoto 2020-10-17 um 21 11 05" src="https://user-images.githubusercontent.com/4241968/96351748-bf57d580-10bd-11eb-902a-c55acc3b7373.png">

**Comment by bergjet** [comment]
Der Fehler besteht noch immer.
<img width="358" alt="Bildschirmfoto 2021-01-18 um 08 33 43" src="https://user-images.githubusercontent.com/4241968/104885236-00cf7980-5968-11eb-8554-05092fbd34b0.png">

**Comment by bergjet** [comment]
Keine Änderung

**Comment by stephan1827** [comment]
I have the same issue in Safari with the latest version, any chance that this gets fixed? It seems to be always the last tab thats creates a new row.
<img width="377" alt="Bildschirmfoto 2021-05-23 um 09 21 32" src="https://user-images.githubusercontent.com/2972703/119251740-5af77a00-bba8-11eb-9d2c-ce42459d4012.png">
