### ISSUE TITLE
(829) Terminated (NO_ERROR): Without reason

### ISSUE THREAD

**Issue by Kefut** [ioBroker/ioBroker.vis#310]
Ich bekomme vis nicht mehr zum Laufen:
![image](https://user-images.githubusercontent.com/70171384/96865527-5cbe5b00-146a-11eb-9d13-ec4dd6b7ca53.png)
Die notwendigen Adapter sind alle aktuell:
![image](https://user-images.githubusercontent.com/70171384/96865673-8d9e9000-146a-11eb-852f-ef5905abefc6.png)
Node und NPM auch:
![image](https://user-images.githubusercontent.com/70171384/96866178-3e0c9400-146b-11eb-8bd8-643e19664af2.png)

Wie kann ich rausfinden warum das passiert?

Danke im Voraus!

**Comment by Kefut** [comment]
Ok, went back to Node.js v12.18.3 updated/upgraded iobroker, restarted everything and now it's back. Is there an issue with Node 12.19?

**Comment by Apollon77** [comment]
What exactly is your problem? vis as "adapter process" only runs very short and generates all www files .. after this a  files are serverd by web. SO what exactly is your issue? The log should be the same also in older nodejs version
