### ISSUE TITLE
Fails to load on Fully Android browser since 1.3.0

### ISSUE THREAD

**Issue by Signum** [ioBroker/ioBroker.vis#320]
I am using the Fully Kiosk Browser (https://www.fully-kiosk.com/#get-kiosk-apps) on an Android tablet with Vis.

That worked well up to version 1.2.12. However I have tried both 1.3.0 and 1.3.4 and only see the loading spinner rotating forever.
I tried that with both Firefox and Chrome as backends/webviews and apparently the problem started with the switch from 1.2.12 to 1.3.0.

Firefox and Chrome themselves work properly on Android. Just the webview used by the kiosk browser starts to break. Unfortunately I couldn't debug that any better. So all I can tell you is the versions I tried.

I would appreciate if you found time to look into it. In my opinion a kiosk browser is the perfect tool on a cheap chinese tablet. :)

**Comment by Apollon77** [comment]
Android version?

**Comment by Signum** [comment]
Android version | 8.1 (SDK 19)
Webview version | 30.0.0.0
Webview UA | Mozilla/5.0 (Linux; Android 8.1; T906 Build/KOT49H) App...
Device model | T906 (HYD)

**Comment by twonky4** [comment]
I have an similar issue. For my old device "new" javascript feature are not supported. for example:
```
formatMomentDate: function formatMomentDate(dateObj, _format, useTodayOrYesterday = false) {
```

Error message:

```
Unexpected token =; /vis/js/vis.js@L2253
```

So default values with syntax " = false" not allowed.

**Comment by capitaenz** [comment]
I have the problem too, can I install the Github version or should I wait?

**Comment by GermanBluefox** [comment]
Please test 1.3.6

**Comment by Signum** [comment]
@GermanBluefox Updated. Works on Fully. Thanks.
