### ISSUE TITLE
"No Connection" nach Update auf 1.3.5

### ISSUE THREAD

**Issue by MarcelW85** [ioBroker/ioBroker.vis#322]
Nach dem Update auf Version 1.3.5 kriege ich keine Verbindung mehr zu VIS.

Er meldet nur oben rechts im Fenster "No Connection".

**Comment by ivo443** [comment]
Yup, gleiches Problem.
Auch via Shell und NPM install das gleiche Problem.
Downgrade auf 1.3.4 und alles läuft wieder.

**Comment by sigi2345** [comment]
Dito.

![Screenshot (2905)](https://user-images.githubusercontent.com/41079106/102020086-40a6ae00-3d77-11eb-82c0-b208f59d87de.png)


`Platform: Windows
RAM: 16 GB 
Node.js: v12.19.0
NPM: 6.14.8
JS Controler: 3.1.6
Admin: 4.1.11
Web: 3.1.0
Socket.io: 3.0.13
Script Engine: 4.10.8
IOT: 1.8.5
VIS: 1.3.5`

**Comment by MarcelW85** [comment]
Downgrade läuft gerade...
Mal sehen ob es gleich wieder läuft.

**Comment by ivo443** [comment]
> Dito.
> 
> ![Screenshot (2905)](https://user-images.githubusercontent.com/41079106/102020086-40a6ae00-3d77-11eb-82c0-b208f59d87de.png)
> 
> `Platform: Windows RAM: 16 GB Node.js: v12.19.0 NPM: 6.14.8 JS Controler: 3.1.6 Admin: 4.1.11 Web: 3.1.0 Socket.io: 3.0.13 Script Engine: 4.10.8 IOT: 1.8.5 VIS: 1.3.5`

Meine Console sagte genau das gleiche.

**Comment by Frank1604** [comment]
In Zeile 3607 der vis.js fehlt ein Hochkomma.

statt
`vis.sound.attr('muted, false);`

muss da stehen
`vis.sound.attr('muted', false);`

**Comment by luke200611** [comment]
Gleiche problem nach update 1.3.5 keine verbindung zum VIS .  Wie kann ich downgrade auf 1.3.4?

**Comment by MathiasJZ** [comment]
Hier das selbe.
Ich gehe dann mal zurück auf die 1.3.4

**Comment by GermanBluefox** [comment]
PLease test 1.3.6

**Comment by sigi2345** [comment]
> PLease test 1.3.6

Läuft wieder. Danke.

**Comment by ivo443** [comment]
> PLease test 1.3.6

works, thx
