### ISSUE TITLE
Text-To-Speech Nutzung in v1.3.6 nicht möglich-Kein Ton

### ISSUE THREAD

**Issue by testit2020** [ioBroker/ioBroker.vis#324]
Erstelle nur den issue, bitte kontrollieren, Danke:
https://forum.iobroker.net/topic/39798/text-to-speech-1-12-2-keine-tonausgabe

**Comment by wendy2702** [comment]
Kann ich bestätigen. Kein TON mit 1.3.6. Nach downgrade auf 1.3.4 alles wieder OK aber natürlich keine Anzeige mehr auf IPAD 2 was sehr schade ist.

`
node -v v12.19.0
npm -v 6.14.8
iobroker -v 3.1.6
`




https://forum.iobroker.net/topic/40049/doch-nicht-gel%C3%B6st-pl%C3%B6tzlich-keine-ansagen-mehr-%C3%BCber-sayit/8

**Comment by wendy2702** [comment]
Habe die Änderungen https://github.com/ioBroker/ioBroker.vis/pull/318/files zum testen bei mir mal Rückgängig gemacht. Dann iobroker restart und danach gehen die Ansagen wieder und auch der View auf dem IPAD 2 ist noch OK.

**Comment by cavernerg** [comment]
Kann ich bestätigen. Kein Ton mehr mit VIS 1.3.6 - playSound-Befehl ist wirkungslos

//und die Änderung von wendy funktioniert. Der "fix" ist fehlerhaft.
