### ISSUE TITLE
No tts possible on sonos, if two (or more) speakers are grouped

### ISSUE THREAD

**Issue by Huseriato** [ioBroker/ioBroker.vis#326]
I'm using version 1.12.2 of the sayit adapter.

I've created an instance for every Sonos Speaker I own and assigned one speaker to each instance.

If the speaker is not grouped I can use Google/Amazon Polly AWS or any other service to play a text using the object (in objects list - for example `sayit.0.tts.text`). All works fine.

But if I just group to SONOS speakers this does not work anymore. If the speakers are playing something, than setting the text will mute the designated speaker (the other continues to play). After TTS text finished, the used speaker for tts is still muted (but playing what he was playing before).

The tts mp3 file is generated and plays when clicking in object list.

I think sayit have to ungroup the speakers, play tts and group them back after this.

**Comment by Huseriato** [comment]
Anybody here? The issue is still valid and sayit adapter is not usable for us. Speakers are grouped every day in several ways. If I can test something (debug) please tell me.

**Comment by Huseriato** [comment]
The behaviour is unchanged since I first submitted the bug. I'm testing with every version that's released. Same issue everytime.

**Comment by Huseriato** [comment]
The behaviour is unchanged since I first submitted the bug. I'm testing with every version that's released. Same issue everytime.

**Comment by Huseriato** [comment]
The behaviour is still unchanged since I first submitted the bug. I'm testing with every version that's released. Same issue everytime.

**Comment by Apollon77** [comment]
Hm ... why this is an vis adapter issue? What do I get wrong? SHoud it not be sayit or sonos?

**Comment by Feuer-sturm** [comment]
@Huseriato Did you see the question from Apollon77?
