### ISSUE TITLE
Customize / Blank loading screen

### ISSUE THREAD

**Issue by ScumbagSteve** [ioBroker/ioBroker.vis#331]
I enjoy a very customized vis via mobile and tablet via the ioBroker app.
Unfortunately every time I open the app, I see the decentered and unadjusted loading text on mobile and tablet.
I would love to see an option to set a blank screen in an adjustable color with just a loading icon in the middle.
This way we could select the background colour from our vis and the interface just "appears" after a second of loading.

If not possible, can you hint me where I find the relevant file in the iobroker to play around myself? I looked around but couldn't find it. I attached a screenshot of my iPhone. The green loading circle appears in the very top left (almost looks like coordinates 0,0 which looks weird with mobile round screen edges)

![IMG_0445](https://user-images.githubusercontent.com/8447146/103841680-6a13da80-5094-11eb-82b9-0a3674f8823e.PNG)

Keep up the good work

**Comment by CodingTfC** [comment]
Hey liebe Entwickler ;)
Ich spiele jetzt auch schon seit geraumer Zeit mit der VIS rum und es macht mir auch echt Spaß. Ich schreib mich hier mal drunter, weil mich der Einsprungpunkt zum Laden auch interessiert. Wurde an der Stelle nämlich gerne ein eigenes GIF einbauen oder ähnliches um beim Start und Laden der VIS eine nette Animation zu haben ;)
Wäre cool hier etwas machen zu können.
Danke schon mal

**Comment by ice987987** [comment]
Push
