### ISSUE TITLE
VPN Agrressive Mode

### ISSUE THREAD

**Issue by PhilippLeitner** [ioBroker/ioBroker.vis#335]
Hallo,

ich habe ein Problem mit der ioBroker iOS App.
Mein VPN Server (Sophos UTM 9 Home) unterstützt leider keinen Agrressive mode bei VPN Verbindungen. Kann man dies in den Einstellungen der App irgendwie deaktivieren und auf den Normalen Mode zurückschalten?

Danke

LG Philipp

**Comment by foxriver76** [comment]
iPhone App wird in dem Repo nicht gewartet, am Besten in diesem Thread nachfragen: https://forum.iobroker.net/topic/26175/test-iphone-ios-app-1-0-x/253
