### ISSUE TITLE
1.3.7 Fehler bei Binding

### ISSUE THREAD

**Issue by drohne200** [ioBroker/ioBroker.vis#338]
Hallo zusammen,

nach dem Update von heute funktionieren mehrer Bindungs nicht mehr wie z.B. der hier:

```
<i class="mdui-mdi-90 {val:javascript.0.TasmotaZigbee.Temp_Schlafzimmer.BatteryPercentage;val >= 70 ? "mdui-green\">&#xF12A3" :: val >= 40 ? "mdui-orange\">&#xF12A2" :: val < 40 ? "mdui-red\">&#xF12A1" :: "error"};</i>

<i class="mdui-mdi {val:javascript.0.TasmotaZigbee.Temp_Schlafzimmer.LinkQuality;val >= 120 ? "mdui-green\">&#xF08BE" :: val >= 65 ? "mdui-orange\">&#xF08BD" :: val < 65 ? "mdui-red\">&#xF08BC" :: "error"};</i>

<i class="mdui-mdi mdui-lightblue">&#xF0151</i>
```

BatteryPercentage, LinkQuality sind beides Integer. 
Irgendeine Idee? 

Danke und Grüße

**Comment by drohne200** [comment]
Hab mir das selbst nochmal angeschaut. Als "Escape Character" reiche kein einfaches \ mehr sondern es muss ein doppeltes \\ her um das nachfolgende " auszunehmen. 

So funktionierts wieder:

`<i class="mdui-mdi-90 {val:0_userdata.0.testobject;val >= 70 ? "mdui-green \\"> &#xF12A3" :: val >= 40 ? "mdui-orange \\"> &#xF12A2" :: val < 40 ? "mdui-red \\"> &#xF12A1" :: "error"};</i>`

Danke und macht weiter so! 

Kann geschlossen werden

**Comment by cdellasanta** [comment]
@drohne200 
Die verantwortliche änderung ist hier https://github.com/ioBroker/ioBroker.vis/pull/333

Ich frage mich ob es aber korrekt gelöst würde, weil ich kann keinen State der einen JSON enthaltet prozessieren.
