### ISSUE TITLE
Binding for background-color does not work

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis#339]
**Describe the bug**  
Binding for background-color does not work

**To Reproduce**  
1. Create a new view in vis
2. Go to „Eigenschaften“ -> „Aussicht“ -> section „CSS Hintergrund (background-...)
3. Enter a binding in: „-color:“

**Expected behavior**  
Binding is to be executed

**Screenshots & Logfiles**  
![AB7326BC-6216-4F6C-9805-D9153565E136](https://user-images.githubusercontent.com/69053781/105639423-90998a00-5e78-11eb-8c81-bd1fb4b0eed4.jpeg)

**Versions:**  
Adapter version: vis: 1.3.4
JS-Controller version: 3.1.6
Node version: v12.20.1
Operating system: linux

**Additional context**  
See https://forum.iobroker.net/topic/34532/hintergrundfarbe-als-binding-dp/6?_=1611510408865 for reference.

**Comment by drohne200** [comment]
Servus Ice987987,

nimm mal die '' bei deiner Abfrage nach true weg! Somit würdest Du nach einen String erwarten. 
Ich geh mal davon aus das du ein bool hast.

`{test:0_userdata.0.testobject;test == true ? 'geht' : 'geht nicht'}`

So gehts ;-)

**Comment by cdellasanta** [comment]
Hoi @drohne200 
Genau umgekehrt ist aber beschrieben in der Doku .. es muss einen String vergleich sein:

https://github.com/ioBroker/ioBroker.vis#bindings-of-objects
> Take care about types. All of them defined as strings. To be sure, that value will be treated as number use parseFloat function.

**Comment by ice987987** [comment]
@drohne200 
`{test:0_userdata.0.test.test1;test == true ? '#ffff00' : '#ff0000'}` funktioniert nicht mit den genannten Versionen.

**Comment by ice987987** [comment]
push

**Comment by tomg1970** [comment]
please

**Comment by ice987987** [comment]
push

**Comment by dsiggi** [comment]
Das gleiche Problem hier. Wenn ich direkt eine Farbe angebe wird der Hintergrund entsprechend eingefärbt.
Gebe ich ein Binding ein, bleibt der Hintergrund weiß. Der Datenpunkt ist ein String und beinhaltet #555555 .
```
{0_userdata.0.vis.Farben.Hintergrund}
```

Das Problem habe ich nur bei der Hintergrundfarbe von Views. Bei Widgets klappt alles wie es soll.

**Comment by selles8** [comment]
Ich hab ebenfalls das Problem. Bei mir funktioniert es bei der Hintergrundfabre von Views, aber nicht bei Widgets (z.B: HTML oder SVG Shape)

**Comment by vonCartman** [comment]
ist bei mir genau so.

**Comment by ice987987** [comment]
push

**Comment by selles8** [comment]
Push

**Comment by ice987987** [comment]
continue here: https://github.com/ioBroker/ioBroker.vis-2/issues/19

**Comment by oweitman** [comment]
workaround for vis1
https://forum.iobroker.net/topic/76281/views-hintergrundfarbe-zentral-steuern
