### ISSUE TITLE
Vis Hängt: Loading Values .... und nichts passiert

### ISSUE THREAD

**Issue by lammy000** [ioBroker/ioBroker.vis#349]
Hi, ich habe die Adapter, web 3.3.0, vis 1.3.7, socket 3.3.14 auf die aktuellensten Versionen geupdatet und bekomme wie vor 2 Monaten das Problem das ich auf die VIS nicht mehr drauf komme da die Meldung "Loading Values" nicht weg geht.

Aktuell läuft sie wieder mit den Versionen
web 3.0.1
vis 1.3.7
socket 3.0.12

was muss ich machen damit es rennt :-)

**Comment by Apollon77** [comment]
Bitte schau mal in der Browser Konsole nach Fehlern
