### ISSUE TITLE
view in jqui Dialog – scrolling problem on touch devices

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis#354]
I use various jqui dialog buttons in my vis. What is very annoying is, that the dialog always opens when one of the buttons is only briefly touched while scrolling on touch devices such as a smartphone.

The problem occurs with all jqui dialog widgets, regardless of whether container-HTML, container-icon-view, etc.
All other widgets I use, such as Button Link or similar, do not show this behaviour when scrolling, here it is only triggered when it is actually pressed.

Would be great if this problem with the dialog widgets could be fixed by the developers.
Many thanks

Edit in German 06.04.2021:
Ich habe jetzt mal den Event Listener "touchend" bei´den dialog widgets bzw. beim vis-widget-body durch folgendes Skript in VIS temporär abgeschaltet, wodurch sich das Problem des vorzeitigen Öffnens der Dialoge beim Scrollen auf Touch Geräten beheben lässt.

`$( "#vis_container" ).on( "touchstart", function(event) { 
setTimeout(function () {
$(".vis-widget-body").unbind("touchend");
}, 50);
});`

Wenn man bei verschiedenen Widgets sich per F12 im Browser den Event Listener "touchend" anschaut, sieht man dass bei den jqui Dialog Widgets dieser u.a. auf vis.widget-body angewendet wird, bei anderen Widgets hingegen ist dieser stattdessen bei vis-widget. Ich weiß nicht ob hier das Problem liegt, aber vielleicht hilft diese Erkenntnis den Entwicklern den Bug schneller zu finden und zu fixen?
MK-66

**Comment by fritzke316** [comment]
I just wanted to say that im dealing with the same problem, i also opend a issue some weeks ago and would be happy if it can be fixed.
THX
