### ISSUE TITLE
Version 1.3.8 in title (instead 1.3.9)

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.vis#361]
Last version 1.3.9
![Скриншот 29-04-2021 183532](https://user-images.githubusercontent.com/6728198/116578219-dfdcd400-a919-11eb-9e8a-4e5692f13c86.jpg)
![Скриншот 29-04-2021 183521](https://user-images.githubusercontent.com/6728198/116578222-e0756a80-a919-11eb-8b50-6114cf8e2ac2.jpg)

**Comment by skvarel** [comment]
Same here (Admin 5.0.11 old UI)

![grafik](https://user-images.githubusercontent.com/1114419/116591538-38fb3680-a91f-11eb-83eb-701e35f2d606.png)

![grafik](https://user-images.githubusercontent.com/1114419/116591554-3dbfea80-a91f-11eb-9426-346f2e578348.png)

**Comment by skvarel** [comment]
with the React UI, the version is correct
![grafik](https://user-images.githubusercontent.com/1114419/116595328-8083c180-a923-11eb-9fb4-c7ac3b5d4217.png)

**Comment by skvarel** [comment]
After the update from js-controller to 3.3 it fits

![grafik](https://user-images.githubusercontent.com/1114419/116648166-a8534380-a97c-11eb-82ae-97bac323ef1c.png)

**Comment by itProfi** [comment]
ou..thanks!
