### ISSUE TITLE
Widget "jqui-input" saves numbers as strings

### ISSUE THREAD

**Issue by mrfenyx** [ioBroker/ioBroker.vis#372]
Issue: the "jqui-input" widget will save an entered value as string even though the checkbox "As string" is not selected.

![image](https://user-images.githubusercontent.com/2023454/119719744-7218bf00-be69-11eb-9cb0-522803117a56.png)

Steps to reproduce:

1. create a new state of type "number" -> input.
2. create a second new state of type "number" -> output.
3. create a new vis view containing 1 jqui-input widget that is linked to the "input" state. save the view.
4. open the view and enter a number in that input field (ex: 100).
5. create a new javascript that reads the value of "input" and writes it to "output"
6. run the script
-> Error is displayed: 
`You are assigning a string to the state "0_userdata.0.piHole.output" which expects a number. Please fix your code to use a number or change the state type to string. This warning might become an error in future versions.`

Example Script:
```
var inputDP = "0_userdata.0.piHole.timer";  //type "number"
var outputDP = "0_userdata.0.piHole.output";  //type "number"
var num = getState(inputDP).val;
setState(outputDP, num);
```

See also https://forum.iobroker.net/topic/45307/setstate-string-vs-number

**Comment by tseroo** [comment]
Same issue here. Lots of automations are not working anymore because of this. Any ideas when someone can look into this?

Thanks
