### ISSUE TITLE
Übersicht Adminadapter Fehler

### ISSUE THREAD

**Issue by lindi200000** [ioBroker/ioBroker.vis#373]
Hallo,
ich habe die VIS 1.3.9 installiert.
Diese bringt die Übersicht vom Adminadapter zum Absturz (leere Seite).
Reproduzieren lässt sich das ganze mit aktivieren und deaktivieren des VIS Adapters.

Fehlercode in der Browser Console:
`Uncaught TypeError: o.replace is not a function
    at r (adminIntro.js:229)
    at adminIntro.js:344
    at l (adminIntro.js:515)
    at i (adminIntro.js:553)
    at r.<anonymous> (adminIntro.js:27)
    at r.onack (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)`

Nodejs 14.17.0
npm 6.14.13
JS Controller 3.2.16
Adminadapter 4.2.1
Visadapter 1.3.9

VG
Lindi

**Comment by Jey-Cee** [comment]
Es scheint mit diesem Eintrag zusammen zu hängen:
```
"localLinks": {
            "_default": "%web_protocol%://%ip%:%web_port%/vis/edit.html"
        }
```

**Comment by lindi200000** [comment]
Hallo,
ist hier ein fix in Aussicht? Ist bescheiden, wenn man die Adminseite nicht mehr sieht.

**Comment by lindi200000** [comment]
@GermanBluefox die neue Vis Version hat den Fehler immer noch drin.

**Comment by GermanBluefox** [comment]
> @GermanBluefox die neue Vis Version hat den Fehler immer noch drin.

Aktuell man kann das mit Admin 5 beseitigen

**Comment by lindi200000** [comment]
> > @GermanBluefox die neue Vis Version hat den Fehler immer noch drin.
> 
> Aktuell man kann das mit Admin 5 beseitigen

Der ist aber nicht stable. Ich vermute mal, dass es noch paar Monate dauert bis er stable ist?

**Comment by Apollon77** [comment]
Nein, Admin 5 kommt sobald js-controller 3.3 draussen ist. passiert in den "Nächsten Wochen"

**Comment by GermanBluefox** [comment]
> > > @GermanBluefox die neue Vis Version hat den Fehler immer noch drin.
> > 
> > 
> > Aktuell man kann das mit Admin 5 beseitigen
> 
> Der ist aber nicht stable. Ich vermute mal, dass es noch paar Monate dauert bis er stable ist?

Admin 4.2.2 ist in stable und da ist der Fehler gefixt
