### ISSUE TITLE
Password protection for vis edit

### ISSUE THREAD

**Issue by bluefish007** [ioBroker/ioBroker.vis#374]
Hello! Is there any way to password protect the vis edit page?

**Comment by foxriver76** [comment]
You mean only the edit page? With simple methods it’s only possible to secure the whole web instance.

**Comment by bluefish007** [comment]
Yes, only for the edit page....
I know that I can turn on the authentication for the whole web instance, but I need the vis views without password...

**Comment by Apollon77** [comment]
in fact vis would need a "edit page only after authentication" setting to check that a user is logged in when this is set ... but on fact it would only be a client side check ... adding that in a secure way would mean a bigger change

**Comment by foxriver76** [comment]
Yes, maybe more https://github.com/ioBroker/ioBroker.vis/issues/362 but is also a bigger thing

**Comment by Apollon77** [comment]
Yes something like tis would be needed, or vis would need to add some kind of web extension that can be used as server side for such things
