### ISSUE TITLE
Plötzlich keine Lizenz - Service ist momentan nicht erreichbar - SyntaxError: Unexpected token F in JSON at position 0

### ISSUE THREAD

**Issue by SmartyML** [ioBroker/ioBroker.vis#377]
(953) Cannot check license! Nothing updated. Error: SyntaxError: Unexpected token F in JSON at position 0

**Comment by MrThreesome** [comment]
Same problem here after updateing from 1.3.9 to 1.3.10

**Comment by SmartyML** [comment]
I have got this also in 1.3.8.
Same problem if I load my backup from yesterday

**Comment by bertl83** [comment]
Same problem

**Comment by andiyk** [comment]
same Problem

**Comment by xlklwr** [comment]
same problem

**Comment by EddyDsSmartHome** [comment]
same :)
on version 1.3.9 and on Version 1.3.10

**Comment by SmokyJoe0** [comment]
Same Problem. Cannot check license! Nothing updated. Error: SyntaxError: Unexpected token F in JSON at position 0

**Comment by GermanBluefox** [comment]
Fixed

**Comment by andiyk** [comment]
License Check now ok, but same Message: "Keine gültige vis Lizenz gefunden! Bitte vis Instanz prüfen."

Same on 1.3.10 and 1.3.9.

![image](https://user-images.githubusercontent.com/23166953/124076395-7b87df00-da46-11eb-8ae5-365b539be3f7.png)

**Comment by skvarel** [comment]
Hier läuft es rund

![grafik](https://user-images.githubusercontent.com/1114419/124078779-95c2bc80-da48-11eb-9ec4-e9079623a4d3.png)

**Comment by Apollon77** [comment]
@andiyk Releoad in broewser incl. cache clerar please, pot restart web adapter

**Comment by andiyk** [comment]
Shame on me.  You are right, it was a dirty Cache in Browser. Now it works.
