### ISSUE TITLE
Licensing issues - License is invalid! Nothing updated. Error: invalid

### ISSUE THREAD

**Issue by mueckeflo** [ioBroker/ioBroker.vis#380]
When trying to use the new offline license, VIS is showing the version 1.4.2 blinking and in a red color.

While adding the new license to the instnace, the action can be performed successfully and the check is completed with "OK".
Still, the license does not work when opening VIS.

**Comment by sigi2345** [comment]
Dito

**Comment by jupzup** [comment]
Same Problem here.

**Comment by Boronsbruder** [comment]
Same Problem here.
Old "FREE" license is running fine.
Paid one  shows up "OK" in instance but is showing up as "Invalid" in log.

**Comment by GermanBluefox** [comment]
Fixed in 1.4.3.

**Comment by sigi2345** [comment]
> Fixed in 1.4.3.

Run, THX

**Comment by mueckeflo** [comment]
Issue fixed in 1.4.3
