### ISSUE TITLE
Basic ifram nicht mit der Maus markier-/verschiebbar

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.vis#393]
VIS Version 1.4.3. - Admin 5.1.19 - js-controller 3.3.15

Wenn man im VIS Editor versucht ein "Basic iframe" mit der Maus zu markieren und zu verschieben, gelingt das nicht. Man muss das Basic-iframe über das "Akive Widgets" Menü auswählen und anhaken. Erst dann ist das iframe markiert (gestrichelter Rahmen). Versucht man es mit der Maus zu verschieben, passiert nichts.

Das markierte Iframe Widget läßt sich nur über die Pfeil Tasten der Tastatur verschieben, nicht aber mit der Maus. Auch ein vergrößern oder verkleinern mit der Maus funktioniert nicht.  Über das seitliche "Eigenschaften" Menü kann man aber nach wie vor die Höhe und die Breite anpassen.

**Comment by slonovouho** [comment]
Hallo,
man muss im Vis Editor das Vorhängeschloss anklicken dann geht es wieder.

**Comment by JBSullivan** [comment]
Vielen Dank - ein sehr wertvoller Hinweis - es funktioniert. Kann geschlossen werden.
