### ISSUE TITLE
ladezeit auf raspi (chrome) und tablet (fully) lang

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.vis#394]
siehe forum:
https://forum.iobroker.net/topic/47102/ladezeit-der-vis-bei-raspi-und-tablet

auf tablets mit fully-browser und raspi 4 mit chromium (kiosk) eine seltsame "weiße" seite kommt. zuerserst kommt das übliche "...daten werden geladen..." , dann wird die seite weiß, dann dauert es gefühlt ewig, bis die vis-seite geladen ist

ist auch in der vis app 

auf dem pc mit z.b chrome ist kein problemerkennbar

leider weiß ich nicht mehr, welchen adapter ich upgedatet habe, als das zum vorschein kam - evtl der web adapter ?

 ich habe keine ahnung, wie ich den fehler finden könnte bzw wie ich einen fehler dokumentieren könnte
lt apollon77 oll ich ein video machen:

hier ein video - die letzten 5 sekunden mit dem weißen bildschirm dauert bei mir immer länger - der teil mit dem "lade werte" ist meist schnell weg - das video wurde mit der vis app aufgenommen

https://user-images.githubusercontent.com/18462890/129707830-20d7215a-919a-4eee-8f8c-7ced01694ad2.mp4

**Comment by chrisdu** [comment]
Ich hab leider das selbe Problem. Hatte mir den Alexa FireHD10 besorgt und wollte mit vis mein SmartHome bedienen. Dabei tauchte bei jedem Zugriff auf die Seite das weiß transparente Bild auf. Ich dachte mir der Fire HD ist einfach zu langsam und kaufte mir den Chuwi Tablet. Darauf lief vis bedeutend besser und die weiße Überlagerung auf dem Bildschirm tauchte seltener auf. Mittlerweile ist das weiße Bild bei jedem neu laden wieder da!? Es ist auch egal was auf dem View dargestellt wird. Die Wlan Verbindung ist sehr gut. Ich weiß nicht was ich dagegen machen soll und bitte um eure hilfe.

glg Christian
