### ISSUE TITLE
VIS Lizenz läuft nicht 

### ISSUE THREAD

**Issue by h2okopfmt** [ioBroker/ioBroker.vis#395]
Hallo,

seid heute 7:36 heute morgen geht meine VIS nicht mehr.
Die Lizenz soll abgelaufen sein.
Ist mein Account gelöscht worden?
Er sagt das der Service nicht erreichbar ist oder keine Internetverbindung vorhanden sei.
Internetverbindung ist vorhanden und wird auch nicht geblockt.
Auf die HP komme ich im Browser aber nicht auf die PRO Seite.
Was kann ich machen damit die VIS wieder läuft.
Der IOBroker ist aktuell , Node 17.17.5 , NPM 6.14.14, Admin 5.1.23
VG MarkusT

**Comment by Apollon77** [comment]
Bitte mal vis adapter neu starten. Ist es dann gefixt? Kann es sein das heute früh mal kurz Internet weg war?

**Comment by h2okopfmt** [comment]
Hallo,

Leider nein, klappt immer noch nicht.

Das Internet war meinst wissen nicht weg.

Es geht um den Account : ***@***.***

Ich kann mich auch nicht auf der HP anmelden, so als ob der Account gelöscht sei.


Mit freundlichem Gruss

Markus Teeuwen

**Comment by h2okopfmt** [comment]
Moin,

ich konnte mich eben ca 18.40 mal kurz auf iobreoker .pro anmelden !! war aber nur für ein paar Sekunden drin und jetzt komm ich nicht mehr rein.

**Comment by h2okopfmt** [comment]
moin,

auf der Konsole im Iobroker :
ping auf iobroker.net bekomme ich :


<img width="892" alt="Bildschirmfoto 2021-08-19 um 19 12 29" src="https://user-images.githubusercontent.com/45139677/130113450-3120243f-b6a3-4b34-8f68-b6626cb164b0.png">

über die Entwickler Konsole des Browsers bekomme ich : 

{
    "result": "invalid",
    "error": "not found"
}
<img width="1351" alt="Bildschirmfoto 2021-08-19 um 19 10 57" src="https://user-images.githubusercontent.com/45139677/130113214-c5dd9fc7-12aa-4f7e-86f6-408b9302a485.png">

**Comment by h2okopfmt** [comment]
So ich hab mich neu registriert und jetzt läuft die VIS wieder
