### ISSUE TITLE
VIS Loading Values for ever

### ISSUE THREAD

**Issue by mcsweeper** [ioBroker/ioBroker.vis#399]
Hello!

Iam not sure if it is better to write in englisch or in german. So I decided to write in englisch (its not my native language).
I posted the problem already in IOBROKER Forum but without any result
https://forum.iobroker.net/topic/47588/vis-loading-values-vis-startet-nicht-mehr/6

Problem:
I have a Problem in respect to the Visualisation. As soon I update "Socket.io" or "WEB-SERVER" Adapter my Visualisation wont work anymore. I just get a screen with LOADING VALUES and thats it. 

**Versions:**  
 - Adapter version: <adapter-version>
Adapter    "admin"         : 5.1.23   , installed 5.1.23
Adapter    "alexa2"        : 3.9.3    , installed 3.9.3
Adapter    "daswetter"     : 3.0.7    , installed 3.0.7
Adapter    "discovery"     : 2.7.0    , installed 2.7.0
Adapter    "flot"          : 1.10.6   , installed 1.10.6
Adapter    "history"       : 1.9.13   , installed 1.9.13
Adapter    "ical"          : 1.11.2   , installed 1.11.2
Adapter    "icons-mfd-png" : 1.0.2    , installed 1.0.2
Adapter    "info"          : 1.9.8    , installed 1.9.8
Adapter    "javascript"    : 5.2.8    , installed 5.2.8
Controller "js-controller" : 3.3.15   , installed 3.3.15
Adapter    "knx"           : 1.0.45   , installed 1.0.45
Adapter    "openhab"       : 1.1.0    , installed 1.1.0
Adapter    "pushover"      : 2.0.5    , installed 2.0.5
Adapter    "rickshaw"      : 1.0.0    , installed 1.0.0
Adapter    "simple-api"    : 2.6.1    , installed 2.5.3 [Updateable]
Adapter    "snmp"          : 0.5.0    , installed 0.5.0
Adapter    "socketio"      : 3.1.4    , installed 3.0.12 [Updateable]
Adapter    "vis"           : 1.4.3    , installed 1.2.9 [Updateable]
Adapter    "vis-fancyswitch": 1.1.0   , installed 1.1.0
Adapter    "vis-history"   : 1.0.0    , installed 1.0.0
Adapter    "vis-hqwidgets" : 1.1.7    , installed 1.1.7
Adapter    "vis-jqui-mfd"  : 1.0.12   , installed 1.0.12
Adapter    "vis-map"       : 1.0.4    , installed 1.0.4
Adapter    "vis-metro"     : 1.1.2    , installed 1.1.2
Adapter    "web"           : 3.4.7    , installed 3.0.10 [Updateable]

 - JS-Controller version:  3.3.15
 - Node version: v12.22.6
 - Operating system: Debian

Anybody who can assist me ?`

Many thanks
BG

**Comment by Apollon77** [comment]
Please update web, socketio and vis to the latest available version - else check changelogs because it coud just be version interoperability ... and your vis is way outdated

**Comment by mcsweeper** [comment]
i tried to do this, but as soon i leave the old versions, the problems occurs

**Comment by mcsweeper** [comment]
the above listed adapter version are working right now but as soon i update to the latest versions the problem appears

**Comment by Apollon77** [comment]
In fact you need to update ALL together and then do a hard reload pot incl clearing caches ... most users use uptodate versions and no report of such an error appears so far. Also the one warning in forum id no reason for it not loading.

**Comment by mcsweeper** [comment]
<html>
<body>


host.IOBrokerVers4 | 2021-09-07 11:47:36.890 | error | startInstance system.adapter.vis.0: required adapter "web" has wrong version. Installed "3.0.10", required ">=3.0.12"!
-- | -- | -- | --
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.666 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/cordova.js: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/cordova.js'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.604 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/css/add_kian.css: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/css/add_kian.css'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.546 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/css/app.css: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/css/app.css'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.487 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/css/backgrounds.css: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/css/backgrounds.css'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.429 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/css/doc.css: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/css/doc.css'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.372 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/css/montserrat-regular-webfont.woff: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/css/montserrat-regular-webfont.woff'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.313 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/css/styles.css: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/css/styles.css'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.256 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/css/vis-editor.css: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/css/vis-editor.css'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.199 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/css/vis.css: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/css/vis.css'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.141 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/edit.html: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/edit.html'
host.IOBrokerVers4-Server | 2021-09-07 11:47:36.071 | error | Cannot write files: /opt/iobroker/iobroker-data/files/vis/edit.src.html: EACCES: permission denied, open '/opt/iobroker/iobroker-data/files/vis/edit.src.html'


</body>
</html>

That i found in the logs after updating to the last versions. 

currently this adapter version are installed:

Used repository: stable
hash unchanged, use cached sources
update done
Adapter    "admin"         : 5.1.23   , installed 5.1.23
Adapter    "alexa2"        : 3.9.3    , installed 3.9.3
Adapter    "daswetter"     : 3.0.7    , installed 3.0.7
Adapter    "discovery"     : 2.7.0    , installed 2.7.0
Adapter    "flot"          : 1.10.6   , installed 1.10.6
Adapter    "history"       : 1.9.13   , installed 1.9.13
Adapter    "ical"          : 1.11.2   , installed 1.11.2
Adapter    "icons-mfd-png" : 1.0.2    , installed 1.0.2
Adapter    "info"          : 1.9.8    , installed 1.9.8
Adapter    "javascript"    : 5.2.8    , installed 5.2.8
Controller "js-controller" : 3.3.15   , installed 3.3.15
Adapter    "knx"           : 1.0.45   , installed 1.0.45
Adapter    "openhab"       : 1.1.0    , installed 1.1.0
Adapter    "pushover"      : 2.0.5    , installed 2.0.5
Adapter    "rickshaw"      : 1.0.0    , installed 1.0.0
Adapter    "simple-api"    : 2.6.1    , installed 2.6.1
Adapter    "snmp"          : 0.5.0    , installed 0.5.0
Adapter    "socketio"      : 3.1.4    , installed 3.1.4
Adapter    "vis"           : 1.4.3    , installed 1.4.3
Adapter    "vis-fancyswitch": 1.1.0   , installed 1.1.0
Adapter    "vis-history"   : 1.0.0    , installed 1.0.0
Adapter    "vis-hqwidgets" : 1.1.7    , installed 1.1.7
Adapter    "vis-jqui-mfd"  : 1.0.12   , installed 1.0.12
Adapter    "vis-map"       : 1.0.4    , installed 1.0.4
Adapter    "vis-metro"     : 1.1.2    , installed 1.1.2
Adapter    "web"           : 3.4.7    , installed 3.4.7

**Comment by mcsweeper** [comment]
it is working again. i just changed the config of the web adapter.

binded ip: allow all ips -> 127.0.0.1 then i tried it again and no connection was possible.
after that i switched back to allow all ips and then it worked.

can be closed

**Comment by Apollon77** [comment]
In fact for the "permission denied" try to run "iobroker fix". should fix that too
