### ISSUE TITLE
Vis meldet "Keine gültige Lizenz ..." nach update von JS-Controller auf 3.3.16

### ISSUE THREAD

**Issue by Harry-58** [ioBroker/ioBroker.vis#400]
Nach Update des JS-Contollers auf die aktuelle Version 3.3.16 meldet VIS, dass keine gültige Lizenz vorhanden ist.

![grafik](https://user-images.githubusercontent.com/56926733/132670630-906887e3-405e-4916-b7c3-562be32e0079.png)

![grafik](https://user-images.githubusercontent.com/56926733/132670736-22987130-44da-43e8-85b9-0ab5befb3754.png)

Der Fehler kommt nur bei der Offline-Lizenz. Wenn ich die "normale" Lizenz benutze funktioniert  VIS.

Im Changelog vom JS-Controller steht: (bluefox) Adjust generation of installation UUID
Vermute, es hängt damit zusammen.

**Comment by Apollon77** [comment]
Bitte melde dich bei info@iobrtoker.net

**Comment by Apollon77** [comment]
Hast DU ggf noch die Konsolenmeldungen vom controller Update?

**Comment by Harry-58** [comment]
Habe mit einem Backupimage den Update nochmal durchgeführt. Es kommen keine Fehlermeldungen.
Verhalten hat sich aber nicht geändert:  Offline-Lizenz ungültig,  Normale-Lizenz OK

Habe vor dem Update die Seriennummer in VIS gesichert.
Nach dem Update war eine andere Seriennummer eingetragen!

> pi@iobroker:~ $ iob stop
pi@iobroker:~ $ iob update
Used repository: beta
hash unchanged, use cached sources
update done
Adapter    "admin"         : 5.1.25   , installed 5.1.25
Adapter    "cloud"         : 4.1.0    , installed 4.1.0
Adapter    "devices"       : 1.0.9    , installed 1.0.9
Adapter    "discovery"     : 2.7.2    , installed 2.7.2
Adapter    "flot"          : 1.10.7   , installed 1.10.7
Adapter    "fritzbox"      : 0.2.1    , installed 0.2.1
Adapter    "frontier_silicon": 0.0.10  , installed 0.0.10
Adapter    "history"       : 1.9.13   , installed 1.9.13
Adapter    "hm-rega"       : 3.0.31   , installed 3.0.31
Adapter    "hm-rpc"        : 1.14.45  , installed 1.14.45
Adapter    "icons-mfd-png" : 1.0.2    , installed 1.0.2
Adapter    "icons-mfd-svg" : 1.0.2    , installed 1.0.2
Adapter    "info"          : 1.9.10   , installed 1.9.10
Adapter    "javascript"    : 5.2.9    , installed 5.2.9
Controller "js-controller" : 3.3.16   , installed 3.3.15 [Updateable]
Adapter    "mobile"        : 1.0.1    , installed 1.0.1
Adapter    "mqtt"          : 2.4.0    , installed 2.4.0
Adapter    "octoprint"     : 1.1.1    , installed 1.1.1
Adapter    "ping"          : 1.5.0    , installed 1.5.0
Adapter    "rpi2"          : 1.3.1    , installed 1.3.1
Adapter    "sayit"         : 1.12.3   , installed 1.12.3
Adapter    "simple-api"    : 2.6.1    , installed 2.6.1
Adapter    "socketio"      : 3.1.4    , installed 3.1.4
Adapter    "telegram"      : 1.10.0   , installed 1.10.0
Adapter    "text2command"  : 2.1.1    , installed 2.1.1
Adapter    "tr-064"        : 4.2.14   , installed 4.2.14
Adapter    "vis"           : 1.4.4    , installed 1.4.4
Adapter    "vis-jqui-mfd"  : 1.0.12   , installed 1.0.12
Adapter    "web"           : 3.4.9    , installed 3.4.9
^[[A^[[Api@iobroker:~ $ iob stop
pi@iobroker:~ $ iob upgrade self
Update js-controller from @3.3.15 to @3.3.16
NPM version: 6.14.15
npm install iobroker.js-controller@3.3.16 --loglevel error --unsafe-perm --prefix "/opt/iobroker" (System call)
pi@iobroker:~ $ iob start

**Comment by Apollon77** [comment]
Die Seriennummer von Vis hat sich geändert?? Ehrlich? Oder hat sich deine Installation-UUID geändert?

**Comment by Harry-58** [comment]
In den Instanzeinstellungen von VIS steht nach dem Update eine neue Seriennummer.
Wo finde ich die Installations-UUID?
Kann den Update mit meinem letzten Backup-Image auch nochmal durchführen falls notwendig.
Bei dem Image handelt es sich um eine Kopie der SD-Karte mit "dd" erstellt.

**Comment by Apollon77** [comment]
Alles gut ... @GermanBluefox  your turn ... (@Harry-58 as said best send email to Bluefox)
