### ISSUE TITLE
Warn seit JS-Controller 3.3.14

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.vis#403]
Sobald auf einem Echo etwas abgespielt wird, wird dies auch in VIS angezeigt.

Folgende Meldungen treten dann auf

`web.0 | 2021-07-07 23:42:22.948 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "88" web.0 | 2021-07-07 23:42:22.277 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "87" web.0 | 2021-07-07 23:42:20.950 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "86" web.0 | 2021-07-07 23:42:20.284 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "85" web.0 | 2021-07-07 23:42:18.946 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "84" web.0 | 2021-07-07 23:42:18.274 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "83" web.0 | 2021-07-07 23:42:16.946 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "82" web.0 | 2021-07-07 23:42:15.953 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "81" web.0 | 2021-07-07 23:42:14.947 | warn | (26845) Read-only state "alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgress" has been written without ack-flag with value "80"`

**Comment by Apollon77** [comment]
Dann bitet das Vis Widget suchen welches versucht diesen State zu schreiben ... da kann vis selbst nichts tun. Da ist scheinbar ein Widget falsch konfiguriert oder falsch

**Comment by Negalein** [comment]
> Dann bitet das Vis Widget suchen welches versucht diesen State zu schreiben ... da kann vis selbst nichts tun. Da ist scheinbar ein Widget falsch konfiguriert oder falsch

dies ist das Widget. Ich wüsste nicht, wo man dort was falsch einstellen könnte, das diese Meldung hervorbringt!
hat vor 3.3.14 funktioniert

`[{"tpl":"tplValueString","data":{"oid":"alexa2.0.Echo-Devices.G090U5099045059V.Player.mediaProgressStr","g_fixed":true,"g_visibility":false,"g_css_font_text":true,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis.0/Buchenweg/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis.0/Buchenweg/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis.0/Buchenweg/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"html_prepend":"","class":"mdui-blue-glow","visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide"},"style":{"left":"354px","top":"503px","color":"#ffffff","width":"78px","height":"37px","text-align":"left","font-style":"normal","font-size":"x-large","z-index":"58","font-weight":"bold","font-family":"RobotoCondensed-Light","text-shadow":"rgba(0, 0, 0, 0.9) 3px 3px 4px"},"widgetSet":"basic"}]`

![Edit vis (1)](https://user-images.githubusercontent.com/45309436/134074709-85a2d628-e0fd-4b68-a691-ec1c388d6530.png)

**Comment by Apollon77** [comment]
Die Frage ist warum das Widget den State überhaupt schreibt! Das iost das Problem. Es schreibt einen "read only" state und der js.controller weisst darauf jetzt hin weil das "darf nicht sein"

**Comment by Negalein** [comment]
> Die Frage ist warum das Widget den State überhaupt schreibt! Das iost das Problem. Es schreibt einen "read only" state und der js.controller weisst darauf jetzt hin weil das "darf nicht sein"

Fertig! :)

Der Übeltäter ist das Widget `Basic-String`!
Mit `Materialdesign-Value` und String ausgewählt funktionierts!

**Comment by Apollon77** [comment]
Reopen to fix the widget, or?!

**Comment by Negalein** [comment]
> Reopen to fix the widget, or?!

stimmt, sorry :)

**Comment by Negalein** [comment]
@Apollon77 
leider zu früh gefreut.
Ohne irgendwelche Updates gemacht zu haben, kommt heute der Fehler auch mit `Materialdesign-Value`

**Comment by Apollon77** [comment]
Dann dafür bitte Issue bei materialdesign widget auf machen!

**Comment by Scrounger** [comment]
> Dann bitet das Vis Widget suchen welches versucht diesen State zu schreiben ... da kann vis selbst nichts tun. Da ist scheinbar ein Widget falsch konfiguriert oder falsch

Da bin ich anderer Meinung, jeder korrekt konfigurierte Widget Adapter nutzt die Funktion `setValue` aus dem VIS Adapter.
Und hier wird der Wert ohne ack flag geschrieben, siehe
https://github.com/ioBroker/ioBroker.vis/blob/2c42bb638c3b4a794bca5224990af8cf0f1e8f3e/www/js/vis.js#L343
https://github.com/ioBroker/ioBroker.vis/blob/2c42bb638c3b4a794bca5224990af8cf0f1e8f3e/www/js/conn.js#L754

Wie man das lösen könnte hab ich keine Idee, da man im VIS nicht mitbekommt ob das readonly ist.
Und stur das ack = true mitschicken, würde natürlich bei Steuerung von Hardware zu Problemen führen.

Wenn ich den Code richtig verstehe, müsste man neben dem State auch das Objekt mit einlesen und dann schauen bin ich readonly -> ja -> ack flag mitschicken, sonst nicht. Würde dann aber bedeuten das man wieder mehr Daten laden muss.

Evtl. wäre ja eine alternative diese Warnmeldung nicht anzuzeigen, wenn from = vis instanze ist?

**Comment by Apollon77** [comment]
Nein darum geht es nicht!
"ohne ack flag" ist identisch zu "ack=false" was eine Steuer-Aktion ist ... AUf einen State der nur "Read-Only" ist darf (und kann per definition) keine Steueraktion ausgeführt werden!

Bedeutet: Entweder das Widget ist das falsche für die relevante Logik oder das Widget setzt werte obwohl es das nicht sollte.

**Comment by Apollon77** [comment]
PS: In meiner welt müsste es "Werte anzeigen" Widgets geben die niemals Werte setzen und "Steuer-Widgets geben" (oder das beim Widget durch den User konfigurierbar gemacht werden oder das Widget das Objekt lesen um selbst zu wissen was erlaubt ist und was nicht. Ob das Widget überhaupt Werte mit "ack=true" setzen sollte ist die nächste Frage - ich denke eher nicht. Also so oder so in meinen Augen eine Widget Thematik

**Comment by Scrounger** [comment]
> Nein darum geht es nicht! "ohne ack flag" ist identisch zu "ack=false" was eine Steuer-Aktion ist ... AUf einen State der nur "Read-Only" ist darf (und kann per definition) keine Steueraktion ausgeführt werden!

Das ist klar, readonly sollte man eigentlich nicht setzen, bin ich ganz deiner Meinung. Wird aber trotzdem gemacht, weil z.b. user datenpunkte falsch angelegt haben. Meine Anmerkung oben waren nur Überlegungen wie es gehen könnte, die Sinhaftigkeit ist natürlich fraglich ;-)

> PS: In meiner welt müsste es "Werte anzeigen" Widgets geben die niemals Werte setzen und "Steuer-Widgets geben" (oder das beim Widget durch den User konfigurierbar gemacht werden oder das Widget das Objekt lesen um selbst zu wissen was erlaubt ist und was nicht. 

Und genau das ist doch heute so. Es gibt Widgets die Werte anzeigen oder eben Steuern können.
Die zwei oben erwähnten Widgets eghören in die Kategorie "Werte anzeigen". Beide führen auch keinen setValue Befehl aus, trotzdem kommt die Warn Meldung?

**Comment by Apollon77** [comment]
Wenn User Datenounkte falsch angelegt haben ist die Warnung genau richtig - dann müsen die Objekte korrigiert werden.

Wenn die Meldung kommt dann gibt es ein setState ... sonst käme die Meldung nicht

**Comment by Negalein** [comment]
muss wieder verbessern.

Schaut so aus, dass es das Widget `hqwidgets-CircleKnob` ist.

`Materialdesign-Value` scheidet somit aus! :)

**Comment by GermanBluefox** [comment]
Meine Frage ist: warum steuert man read-only States?

**Comment by Apollon77** [comment]
Vermutung ist eher das Widgets dinge tun ohne da der use "aware ist"

**Comment by Apollon77** [comment]
Aber ja wenn es ein CircleKnob ist dann bleibt die Frage warum man das steuert :-)

**Comment by Negalein** [comment]
> Aber ja wenn es ein CircleKnob ist dann bleibt die Frage warum man das steuert :-)

steuere damit nichts. Zeige damit nur die Restlaufzeit des aktuellen Songs an.
