### ISSUE TITLE
Text in widgets (basic - String) all of a sudden ends with "true" through the whole project

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.vis#410]
**Describe the bug**  
May be it's a user error: Anyone have an idea what went wrong?
All of a sudden in every text widget (basic - String) a status is added to the text: "true".
This is not visible in edit, but if I invoke a view in the vis.edit?html this "true" is visible at the end of the text.

**Expected behavior**  
No "true" added please when the view is shown.

**Screenshots & Logfiles**  
n.a.

**Versions:**  
 - Adapter version: <1.4.4>
 - JS-Controller version: <3.3.15> 
 - Node version: <v12.22.1> 
 - Operating system: <Debian / Proxmox>

**Additional context**  
Probably a user fault, but I cannot see anything that might have been done wrong

**Comment by GermanBluefox** [comment]
Do you have a screenshot for me?

**Comment by MichaelSchaaf999** [comment]
Dear GermanBluefox,

this is a screenshot, via the index.html:

<img width="111" alt="grafik" src="https://user-images.githubusercontent.com/53481090/136537550-0d1c3dda-4c42-47b0-b859-3012bdb9a86c.png">

This is the edit of the same widget:

<img width="112" alt="grafik" src="https://user-images.githubusercontent.com/53481090/136537607-a52fb7c1-c69b-42ae-950f-e8c9d0dd4b01.png">

BUT I already found the explanation / solution, by accident: I used the widget  "basic - String" for plain text, without an object-ID. You might say I mis-used it.
So in the past the definition of the widget read like this:

<img width="286" alt="grafik" src="https://user-images.githubusercontent.com/53481090/136537918-3d85595b-991c-4722-942f-bcf63776fd12.png">

And something must have changed during the last updates of adapters and perhaps of JS too.
Means: If I delete this "nothing_selected" entry which came and still comes automatically as soon as you select a new widget of this kind, i.e. "basic - String", then this "true" is gone.

<img width="281" alt="grafik" src="https://user-images.githubusercontent.com/53481090/136538444-1754f153-b3cf-44f4-8164-7ffe0d747b03.png">

<img width="116" alt="grafik" src="https://user-images.githubusercontent.com/53481090/136538507-7909e12d-d418-47bc-95dc-05d87c241371.png">

So I can declare this issue as closed now.

Thank you,
best regards
Michael
