### ISSUE TITLE
question : jquery

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.vis#415]
ich hätte eine frage:

ich würde gerne das ausführen im script-tab des vis-ediitors
`
    $('.seiteNachObenScrollen').click(function () {  
    console.log( "ready!"+typeof $ );
    myupFunction() });
 `

das funktioniert so nicht

nutze ich das:

`let timeout11 = 3500;
setTimeout( () => {  
$('.seiteNachObenScrollen').click(function () {  
    console.log( "ready!"+typeof $ );
    myupFunction() });
 }, timeout11);
 `

anscheinend ist etwas auf der vis-seite nicht 100%ig geladen. was kann ich nutzen, widget-unabhängig" , damit ich keinen timeout nutzen muss - bei meiner vis würde 3500ms nicht reichen.
ich habe schon alles mögliche versucht (warten auf jquery, window.load, ...) und finde keine lösung dafür

damit ich bei all den scripten nicht immer einen setTimeot brauche, wollte ich nach einer lösung fragen. falls es keine löung gibt, könnte man etwas in die vis einbauen, das man abfragen könnte?

**Comment by Scrounger** [comment]
Dazu hab ich mir die folgende Funktion geschrieben - wartet bis das Widget vollständig geladen ist:

```
    function waitForElement(parent, elementPath, wid, widgetName, callBack, counter = 0, debug = false) {
        if (counter < 10000) {

            setTimeout(function () {
                if (parent.find(elementPath).length > 0) {
                    if (debug) console.log(`[${widgetName} ${wid}] it took ${counter}ms to wait for the element '${elementPath}'`);
                    callBack();
                } else {
                    if (debug) console.log(`[${widgetName} ${wid}] wait for element '${elementPath}'`);
                    counter++
                    waitForElement(parent, elementPath, wid, widgetName, callBack, counter, debug);
                }
            }, 1);
        } else {
            console.warn(`[${widgetName} ${wid}] stop waiting after ${counter} retries`);
            callBack();
        }
    }
```

und dann z.B. so verwenden:
```
    waitForElement($('body'),'.seiteNachObenScrollen', 'dummy', 'dummy', function () {
        // Widget ist vollständig geladen, wir können irgendwas damit machen

    }, 0, true);

```

**Comment by liv-in-sky** [comment]
@Scrounger  
erstmal vielen dank für deine antwort - klasse script !!!
auf das widget warten funktioniert sehr gut. 

kann ich meine eigentliche frage, ob das widget unabhängig geht, damit lösen. 

- ich würde gerne deine function nutzen und alle meine commands darunterlegen - wenn ich dein script richtig verstehe, muss waitForElement  immer für jede class aufrufen
- was bedeutet wid im aufruf ? 
- ich weiß garnicht, ob ich in der vis zwei classes unter gerneral css class eingeben darf
- was passiert, wenn 2 widgets die gleiche class bekommen - das script reagiert doch auf das erste, was geladen ist
- könntest du mal ein beispiel zeigen, wie du das mit einer widget id machst ohne eine class bestimmt zu haben -kann es sein, dass da eigentlich noch mehr in der function stehen sollte

finde dein script cool -  werde ich wohl noch oft brauchen können

**Comment by Scrounger** [comment]
@liv-in-sky 
Ich nutze verschiedene solcher Funktionen im MDW Adapter, schau dir die einfach mal an, die kannst auch als skript ausführen:
https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/7ceb1c029de93f66cf13f53cd014554f543be7ed/widgets/materialdesign/js/widgets/materialdesign.00.helper.js#L23

>     * ich würde gerne deine function nutzen und alle meine commands darunterlegen - wenn ich dein script richtig verstehe, muss waitForElement  immer für jede class aufrufen

ja mit der Funktion schon, da muss man explizit ein Element (class, id, attribute, etc. alles was [ jquery find](https://api.jquery.com/find/) halt aktzeptiert, google mal da gibts sehr viele Beispiele).

Wenn du warten willst bis die Widgets der View alle da sind, dann geht das so z.B.:
https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/7ceb1c029de93f66cf13f53cd014554f543be7ed/widgets/materialdesign/js/widgets/materialdesign.00.helper.js#L80

Achtung musst du dann noch umbauen - falls du es nicht hinbekommst einfach melden.
 
>     * was bedeutet wid im aufruf ?

Das ist ein überbleibsel aus der MDW Funktion und wird nur im logging verwendet, sofern debug = true ist. Im MDW wird hier die Widget Id mit übergeben.

>     * ich weiß garnicht, ob ich in der vis zwei classes unter gerneral css class eingeben darf

Ist möglich mit leerzeichen trennen, z.B.:
![grafik](https://user-images.githubusercontent.com/6370451/137626005-ba448e3c-caa0-468c-9780-7d756aa48125.png)

>     * was passiert, wenn 2 widgets die gleiche class bekommen - das script reagiert doch auf das erste, was geladen ist

Ja es reagiert auf das erste gefundene. Du kannst aber die Prüfung `if (parent.find(elementPath).length > 0) {` auch auf z.B. 2,3,4 setzen. Allerdings musst du halt wissen wieviele Widget es sind - find ich umständlich, nimm dann lieber die `waitForWidgets` Funktion die ich oben beschrieben habe.

>     * könntest du mal ein beispiel zeigen, wie du das mit einer widget id machst ohne eine class bestimmt zu haben -kann es sein, dass da eigentlich noch mehr in der function stehen sollte

```
    waitForElement($('body'),'#w00015', 'dummy', 'dummy', function () {
        // Widget ist vollständig geladen, wir können irgendwas damit machen

    }, 0, true);
```

> finde dein script cool - werde ich wohl noch oft brauchen können

Sollten wir das nicht lieber in einem Thread im Forum weiter diskutieren, ist sicher für andere auch interessant bzw. zwecks Dokumentation?
Wenn ja könntest du bitte einen Thread aufmachen und alles aus dem Issue hier schonmal rein kopieren?

**Comment by liv-in-sky** [comment]
perfekt - ich danke dir vielmals !! ich werde einen thread für das forum öffnen .. dauert eine weile- muss mir überlegen, wie ich das am besten mache
