### ISSUE TITLE
view doesn't load on Android Kitkat after update to v1.4.5

### ISSUE THREAD

**Issue by 150d** [ioBroker/ioBroker.vis#424]
After the update vis v1.4.4 -> v1.4.5, one of my display devices was unable to load the view anymore. It remained on the white screen with the spinning wheel indefinitly.

Reverting to vis v1.4.4 on the server and reloading the view on the device cleared up the issue immediatly.

The affected device is an older Android phone running Android v4.4.4/Kitkat.

Did v1.4.5 introduce new compatibility requirements that weren't necessary for v1.4.4?

**Comment by ds-1982** [comment]
The same problem with an old iPad and the ioBroker App.

**Comment by irudi** [comment]
Same for me: an old iPad and the ioBroker App does not work with 1.4.5 anymore.

**Comment by 150d** [comment]
Can someone please look into this?

This issue is keeping me from updating the adapter, which in turn keeps me from updating any other component on my ioBroker installation. Not a good situation. :-(

**Comment by Apollon77** [comment]
1.4.5 is also not working?

**Comment by 150d** [comment]
Correct, as described in my initial post: The problem occured after updating vis v1.4.4 -> v1.4.5. Going back to v1.4.4 resolved the issue. I have not tried the v1.4.6 I've heard about, which apparently is not yet available from the "stable" update repository.

**Comment by Apollon77** [comment]
OI think the reason for this is ... https://github.com/ioBroker/ioBroker.vis/commit/ab82b1d2efc5c2c21954cd525e6634dbe5467575#diff-dc1ba6228bdc7ca8f354b8baf72deb978cb8a3d60942af60123ac35aa991b800R3042 ... template strings are not supported by androdi 4.4.4 https://caniuse.com/template-literals (and some other places, e.g. https://github.com/ioBroker/ioBroker.vis/commit/3f287815b04f7fb9d1dc8fcdba99cbde2b47bdb4#diff-dc1ba6228bdc7ca8f354b8baf72deb978cb8a3d60942af60123ac35aa991b800R3128)

@GermanBluefox ?? Change that back? Or should we start using some kind of bundler that transforms the code regardless what we do?

**Comment by 150d** [comment]
Can someone please do something about this? I've not been able to upgrade my system for three months now, even though there are some desirable fixes in other adapters. But I can't update them because they require a new admin adapter, which in turn vis v1.4.4 doesn't work with any more. Even js-controller itself can't be upgraded, since one of the steps of the process is to upgrade all of the other adapters - which, again, I cannot do because of the problem with vis v1.4.5.

**Comment by Apollon77** [comment]
Vis has no dependency to Admin ... So what do you mean?

**Comment by 150d** [comment]
Good question. I believe I inferred this dependency from reading through some version history file, but going back to them now I can't find anything in either the admin history, nor the vis history, nor the web (adapter) history. Not quite sure how I arrived at that conclusion now... ;-)

**Comment by GermanBluefox** [comment]
I removed some ES6 code in 1.4.9. Please try

**Comment by 150d** [comment]
I installed "from GitHub", got version v1.4.12.

With this version, my old device shows the view again.

Thank you!

**Comment by irudi** [comment]
Thanks! 1.4.12 works with my old iPad as well! 👍
