### ISSUE TITLE
Too slow reaction on user input via buttons

### ISSUE THREAD

**Issue by RkcCorian** [ioBroker/ioBroker.vis#426]
**Describe the bug**  
I try to create a VIS for remote control of my FireTvCube. Unfortunately the buttons (tested with ```ctrl-Icon State``` / ```Buld on/off```) in VIS reacts too slow in terms of multiple clicks. Use Case: I would like to navigate multiple steps to the right. But the VIS will react only on a few when I click them in "normal" speed as I'm used to by using a "normal" remote control.
Problem: Several clicks will be missed

**To Reproduce**  
1. Create VIS with ```ctrl-Icon State``` or ```Bulb on/off``` + assign a DP
2. By a script show a ```debug``` by each click recognized
2. Click multiple times fast on the button
3. Compare the number of clicks with the number of recognized events via ```debug``` output

**Expected behavior**  
Same number of clicks and ```debug``` outputs

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
Don't know what might be helpful here but I'm open to measure something in case this is requested :-)

**Versions:**  
 - Adapter version: 1.4.5
 - JS-Controller version: 3.3.18
 - Node version: 4.18.1
 - Operating system: Docker Container  (buanet v5.2.0) on Synology

**Additional context**

**Comment by RkcCorian** [comment]
Hab's gerade mal mit einem Button in JARVIS probiert, damit geht es recht schnell, zumindest ausreichend. Daher muss es an VIS liegen. Hat jemand eine Idee, was ich machen kann, falls es irgendwo eine Konfiguration oder sowas gäbe?! Vielen Dank im Voraus!!!

Sieht aktuell so aus...
![image](https://user-images.githubusercontent.com/79741077/143785789-9a0ecbbc-d39e-4003-a359-5f6419e7ed30.png)



@Zefau: FYI

**Comment by RkcCorian** [comment]
I checked again also with the VIS-Inventwo buttons. Same problem...
Is VIS not usable for "normal" repetitive user inputs? In case ioBroker/VIS is not able to do such stuff is it better to check for alternatives to ioBroker or is there any chance?

**Comment by kahlering** [comment]
I think this could be a problem with the debounce time in VIS. After you press a button there is a 1 second debounce time until the button deactivates. This debounce time can be lowered in the settings of VIS under Setup->Settings->States Debounce Time. You might have to restart iobroker after changing this settings.

**Comment by RkcCorian** [comment]
@kahlering : That is the solution! Many many thanks!!!
