### ISSUE TITLE
view doesn't load on Tizen browsers on v1.4.7

### ISSUE THREAD

**Issue by kopierschnitte** [ioBroker/ioBroker.vis#437]
**Describe the bug**  
After updating to v1.4.7 (latest branch), vis doesn't load on my fridge's integrated tablet (Samsung Tizen) anymore. It stays at the spinning wheel forever. Switching back to v1.4.6 solves this immediately.
Access using other systems (Edge / Firefox) always works.

**To Reproduce**  
Update to vis 1.4.7
Open vis on a Tizen based browser

**Expected behavior**  
vis should work as in previous versions.

**Screenshots & Logfiles**  
No entry in iobroker's log.

**Versions:**  
 - Adapter version: 1.4.7
 - JS-Controller version: 3.3.22
 - Node version: 14.18.2
 - Operating system: Ubuntu 20.04

**Additional context**  
Might be related to #424

**Comment by Apollon77** [comment]
How old is that system? it is k on that sometimes libraryies like socketio or such do not work anymore on too old systems

**Comment by kopierschnitte** [comment]
Difficult to tell because it's a closed system. OS is Tizen 4 and the firmware is dated 05/2021. In my case it's a "Family Hub" refrigerator but the same OS is used on Samsung TVs.

**Comment by Apollon77** [comment]
Does 1.4.6 of vis work for you?

@GermanBluefox could it be that this "unicode regex" breaks it for some browsers? We also had issues with "self compiled" noejs, so the unicode regex support in browsers might be an issue?

https://caniuse.com/mdn-javascript_builtins_regexp_unicode if "samsung internet 4" means "Tizen 4" then yes ... not supported

**Comment by kopierschnitte** [comment]
Yes, 1.4.6 works without problems. I'll update the topic.

**Comment by bkomac** [comment]
Same for Lenovo Essential Tab7 with Fully Browswer or Chrome. Installing back v1.4.6 did the trick, but in adapter view still shows as version 1.4.7.
This tab can't be updated anymore.

**Comment by Apollon77** [comment]
@GermanBluefox https://github.com/mathiasbynens/regexpu ?! ;-)) (at least for reference maybe)

**Comment by Knallix** [comment]
Das gleiche bei Fully Browser Fire HD 10 1.4.7 i. O. // 1.4.7 lädt nicht

**Comment by GermanBluefox** [comment]
I removed some ES6 code in 1.4.9. Please try

**Comment by kopierschnitte** [comment]
@GermanBluefox Just tested 1.4.12 on my Tizen-fridge and everything seems to **work as expected**. Thanks!
I'm closing this because this issue was only related to this specific browser.
