### ISSUE TITLE
Upload per VIS-Dateimanager unter gleichem Namen funktioniert nicht

### ISSUE THREAD

**Issue by SBorg2014** [ioBroker/ioBroker.vis#441]
siehe auch: https://forum.iobroker.net/topic/51084/vis-dateimanager-bild-updaten-funktioniert-nicht

Man kann aktuell keine Bilder unter dem gleichen Namen hochladen. Es wird nach wie vor immer das alte Bild angezeigt. Upload unter neuem Namen funktioniert.

VIS: 1.4.7
JSC:  3.3.22
Node.js:v14.18.2
NPM:6.14.15

**Comment by Apollon77** [comment]
langsam ... wird das alte bild noch angezeigt oder gibts einen fehler? Kann es browser cache sein? Auch der web adapter hat einen cache ... 

Also bitte mal nach upload rausgehen aus dem Editor, browser restarten oder cache löschen, ggf mal web restarten. dann editor wieder öffnen. Ist es dann immer noch das alte Image? Wenn das neue dann ists ein Caching issue ... AM besten beide obigen varianten mal einzeln testen. ist es ggf nur einsa davon? (ich tippe ggf auf web adapter caching)

**Comment by SBorg2014** [comment]
Hallo Ingo,
am Browser (getestet mit FF und Edge) bzw. Cache (per Menü und Hand gelöscht) liegt es nicht. Fehlermeldung kommt keine, er zeigt einfach weiter das alte Pic an.
In meinem Fall war es so, dass einfach von jetzt auf gleich (also keinerlei Änderungen an der VIS oder ich im Editor gewesen) einfach ein Icon (als Bild hochgeladen) von insgesamt 19 weg war. Anzeige Mini-Icon für "kein Bild vorhanden". Erneutes hochladen brachte keinen Erfolg.
Eben versucht mal ein anderes Bild dafür hoch zu laden, selbes Problem. Cache leeren, anderer Browser etc. hilft alles nix.
Was aber tatsächlich hilft ist den Web-Adapter neu zu starten, danach ist es dann wieder im VIS-Editor, VIS-Dateimanager und der VIS-runtime korrekt sichtbar. Also IMO hier bei VIS falsch und ein Caching-Problem vom Web-Adapter?

**Comment by Apollon77** [comment]
> Caching-Problem vom Web-Adapter?

Naja der Cache von web ist aktuell 100% "dumm". der cacht ein asset einmal und das wars bis zum Restart. Er kann aber auch bei "File changes" gar keine Info bekommen weil es sowas nicht gibt. Also alles in allem wird das eher tricky zu löschen, aber ja das Issue gehört dann eher zum Web das "Vis uploads das relevante alte cache entry löschen sollten" ...

**Comment by SBorg2014** [comment]
Komisch das ich das Problem noch nie hatte, aber wenn es ein feature ist ^^

**Comment by Apollon77** [comment]
Neee stop ... der cache ist ein feature con web ... das er beim upload eines neuen bildes nicht gelöscht oder aktualisiert wird ist durchaus ein bug ... hat nur noch keiner gemeldet :-) Also gern web issue anlegen!!
