### ISSUE TITLE
View Export funktioniert nicht mit best. Widgets

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.vis#442]
ich kann keinen export einer view machen, wenn bestimmte widget vorhanden sind - ich kann nur 2 beispiele zeigen, bei denen das so ist - warum diese widgets ein problem erzeugen, weiß ich nicht - evtl gibt es auch andere widgets, die ein problem machen. 

es liegt wohl nicht direkt an den widgets, sondern was darin definiert wurde

im forum:  https://forum.iobroker.net/topic/51087/views-exportieren-aus-vis

version 1.4.7

fehlermeldungen:

![Image 4](https://user-images.githubusercontent.com/18462890/148535227-34cfe902-2260-451b-ba15-10e8b5011172.png)

![1641540252897-9aacbbd1-0501-4afe-9079-0856806aed24-image](https://user-images.githubusercontent.com/18462890/148535280-3e8e4484-b2a5-467e-bf6d-673478101fc4.png)

**widget beispiele:**

`[{"tpl":"tplMetroTileDialogStatic","data":{"hover":false,"transform":false,"bg_class":"bg-grayDarker","icon_class":"","icon_badge":"","badge_bg_class":"","brand_bg_class":"","dialog_draggable":"true","dialog_icon_class":"icon-film","gestures-offsetX":0,"gestures-offsetY":0,"name":"Tagesschau","label":"","html":"<div>\n <video id=\"Movie\" src='{javascript.0.System.Sonstige.Tagesschau_100}' width='950' height='543' poster='video-standbild.jpg' autobuffer autoplay controls><div>Schade – abspielen nicht moeglich !</div></video>\n <script>\n\tvar vid = document.getElementById(\"Movie\");\n\tvid.volume = 0.3;\n </script>\n </div>","dialog_width":"960","dialog_height":"633","dialog_title":"Tagesschau in 100s","dialog_flat":true,"dialog_shadow":true,"dialog_modal":true,"icon_src":"/vis.0/main/img/tagesschau.png","icon_height":"86","icon_width":"92","icon_top":"93","icon_left":"26","dialog_icon_src":"","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"views":["Yamaha2"],"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"g_visibility":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide"},"style":{"left":"1010px","top":"193px","z-index":"20","width":"120px","height":"35px","line-height":"255px","font-family":"Arial, Helvetica, sans-serif","position":"","overflow-x":"","overflow-y":"","cursor":""},"widgetSet":"metro"}] `

`[{"tpl":"tplHtml","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":true,"g_css_shadow_padding":false,"g_css_border":true,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","refreshInterval":"0","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"html":"<script>$('#w00006').click(function () { \n \n myupFunction()\n});\nfunction myupFunction() {\n $('html,body').scrollTop(0);\n}\n</script>"},"style":{"left":"1161px","top":"846px","border-width":"1px","border-style":"solid","border-color":"#6eea1f","border-radius":"15px","background":"#6eea1f","width":"137px","height":"62px"},"widgetSet":"basic"}] `

**Comment by GermanBluefox** [comment]
Fixed in 1.4.12
