### ISSUE TITLE
html wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.vis#443]
Ich habe ein script welches html code erstellt und in einen dp sichert - darin sind klassen und scripte - es wird eine tabelle angezeigt. wenn ich in einer view nur ein widget mit solch einer tabelle habe, wird bei einem browser refresh die tabelle, die in einem dp liegt über binding im html widget angezeigt.

habe ich mehr wie ein solches widget mit tabelle, wird nach einem refresh der vis nur ein oder meist keines der widgets mit inhalt angezeigt

ich sehe in den entwicklertools einen style eintag, der nicht von meinem script erzeugt wird - er existiert nicht im htm-teil des widgets. 

hier sieht man das - wenn ich das script neu starte wird alles richtig angezeigt - es passiert also nur, wenn die vis frisch ladet

![AApossis (168)](https://user-images.githubusercontent.com/18462890/148584157-3f042777-d15b-4dbf-afe1-caf1ed0f80cf.gif)

es scheint von der vis zu kommen - siehe entwicklertools 

**ich habe das "display: none" nicht erzeugt !**

![Image 4](https://user-images.githubusercontent.com/18462890/148584298-85d1802a-89f9-4928-9d2e-61a7387b45d8.png)

hier ein wenig nach oben - dort sieht man woher es wahrscheinlich kommt

![Image 5](https://user-images.githubusercontent.com/18462890/148584401-bfa2eb96-5a99-4839-8172-b4354f696085.png)

**kann ich da was dagegen machen**

ist das ein bug oder soll das so sein ?

**Comment by GermanBluefox** [comment]
Dann brauche ich einen Beispiel von so eine Tabelle, die ich dann in DP speichern werde und in HTML widget platzieren werde

**Comment by liv-in-sky** [comment]
sorry - habe es irgendwie anders gelöst
