### ISSUE TITLE
Keine Verbindung zu Vis nach Update (V 1.4.8 )

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis#444]
Hallo, nach einen Update auf VIS 1.4.8 bekomme ich keine Verbindung mehr.

![Screenshot (4670)](https://user-images.githubusercontent.com/41079106/151692407-804042c9-fecc-4222-ac0d-3893531b728c.png)

Plattform: Windows
RAM: 16 GB
NODE.JS: V14.18.3
NPM: 6.14.15
JS Controller: 3.3.22
Admin: 5.2.3
Web: 4.0.0
Socket.io: 4.0.1
Script Engine: 5.2.19
IOT: 1.9.1
VIS: 1.4.8

**Comment by fuchs-1978** [comment]
Die Android App verbindet auch nicht lokal. Cloud funktioniert

**Comment by Apollon77** [comment]
@Wegen der App darfst DU web nicht auf 4.0 updaten aktuell!!

**Comment by fuchs-1978** [comment]
@Apollon77 nur Web? Denn mit 3.4.16 verbindet sie sich auch nicht lokal.

Allerdings bekomme ich Werte wenn ich erst in der Cloud bin und dann wechsle zu lokal. Die App starten lokal geht nicht mit der 3.4.16

**Comment by Apollon77** [comment]
socketio libBitte mal browser cache leeren, hart reloaden ... irgendwie nutzt der browser noch die "echte" lib von früher

**Comment by fuchs-1978** [comment]
Wie leere ich denn den Cache in der iobroker App? Lokal verbindet er sich nicht zum reload

**Comment by mag333** [comment]
> socketio libBitte mal browser cache leeren, hart reloaden ... irgendwie nutzt der browser noch die "echte" lib von früher

Bringt nichts... no connection -> Browser+App

Wie kann eine lokale Anwendung plötzlich bei mehreren Usern nicht mehr funktionieren?

**Comment by fuchs-1978** [comment]
Also nach dem Cache leeren hatte ich auch im Browser keine Verbindung. Mit der 4 geht's wieder im Browser. App habe ich jetzt Mal ausschließlich über die Cloud verbunden. Dann geht's erstmal

**Comment by mbrock70** [comment]
Ich hatte grad das gleiche Problem nach dem Update von Adapter web von 3.4.11 auf 3.4.16. 
In der Browser Console war danach immer zu sehen, das er eine word.js nicht laden konnte (404) und er dann keine Socket Verbindung aufbauen kann.
Als ich mir dann meine installierten Adapter Versionen angeschaut habe, fiel mir auf, dass der Adapter socketio nun die Version 4.0.3 hatte.
Ich habe diesen Version wieder zurückgesetzt auf eine 3.x Version (3.1.5). 

Danach ging VIS wieder im Browser und der Mobile-App

**Comment by mag333** [comment]
Nach rollback auf die folgenden Versionen klappt es bei mir auch wieder. Ich wundere mich aber immernoch, warum neue Versionen bei mir installiert wurden ohne mein Einverständnis.

vis 1.4.5
socket.io 3.1.5
webserver 3.4.9

btw: Für meine vis-Display-Devices verwende ich jetzt lieber Fully Kiosk Browser (mehr Settings verfügbar)

**Comment by Apollon77** [comment]
@fuchs-1978 Die App geht lokal generell nocht nicht. Da hilft auch kein Browser cache leeren

@mag333 Der web Adapter hat den socketip Adapter als interne Abhängigkeit ... Scheinbar hat npm bei Dir gedacht das es eine gute Idee wäre das dann direkt zu aktualisieren ...

**Comment by fuchs-1978** [comment]
@Apollon77 danke für die Info. Ich habe die ssid in der App geändert. So greift er immer auf die Cloud. So geht's erstmal bis es wieder korrekt läuft.
