### ISSUE TITLE
vis 1.4.8 editor blocked by proxy 1.2.2

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.vis#450]
Bei laufendem proxy Adapter lässt sich der vis Editor nicht mehr öffnen. Das sieht dann so aus, dass auf der vis Edit Browser-Seite immer ganz kurz der rote Kasten "no connection" aufblinkt und der Editor nie aufgeht. Sobald ich den Proxy Adapter deaktiviere, kann ich den Editor öffnen.

**Comment by Apollon77** [comment]
Denke das liegt daran das proxy keine websockets supported und das damit nicht geht

**Comment by Apollon77** [comment]
@fu-zhou Please create a feature request for proxy to support WS
