### ISSUE TITLE
Vis zeigt nicht alle installierten Widgeds an

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.vis#467]
Ich habe die Vis mit der Version 1.4.5 installiert.
Istalliert man nun einzelnen widged adapter (Bspw. justGage Widgets V1.0.2), dann werden diese Widgeds leider nicht im
Vis Editor angezeigt.

**Comment by Apollon77** [comment]
Bitte mal "iob upload vis" bzw "iob upload all" machen und dann vis neu starten. Kommt es dann?
