### ISSUE TITLE
Ausrufezeichen im Viewnamen verursacht massive Probleme

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.vis#471]
Um die Sortierung der Views in der Tab-Leiste zu "vereinfachen", habe ich eine View <!pop_Decke> genannt, ohne die spitzen Klammern natürlich. Dies sollte ein Popfenster werden.

Seit dem die View angelegt wurde, kann ich weder diese View editieren, noch irgendeine andere! Alle anderen Seiten sind ausgegraut, nix geht mehr richtig.

Bei dem Versuch, die <!pop...> zu löschen, erscheint in der Sicherheitsabfrage (Willst Du wirklich ...) ein anderes View als das, dass ich ausgesucht und selektiert habe.

LG Uwe

**Comment by seers84** [comment]
Habe genau das gleiche Problem. Gibt hierzu eine Lösung?

**Comment by Haifeif** [comment]
No response so far ...

**Comment by Haifeif** [comment]
Still no response ...

**Comment by Apollon77** [comment]
What response do you expect? In fact you know a workaround (not use this character) and then wait until a developer finds time to look into it. Thank you

**Comment by Haifeif** [comment]
To be honest: I deleted the whole project, because I couldn’t fix it! 

 

Just knowing a workaround sometimes isn’t enough.

 

You are welcome

 

Von: Ingo Fischer ***@***.***> 
Gesendet: Freitag, 6. Mai 2022 13:23
An: ioBroker/ioBroker.vis ***@***.***>
Cc: Haifeif ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.vis] Ausrufezeichen im Viewnamen verursacht massive Probleme (Issue #471)

 

What response do you expect? In fact you know a workaround (not use this character) and then wait until a developer finds time to look into it. Thank you

**Comment by Feuer-sturm** [comment]
Issue is duplicate to #527

With vis2-beta (Alpha Version) v2.0.6 I have no problems with special characters at beginning of the view name.  It is possible to edit, rename, delete this view.
