### ISSUE TITLE
Project delete/rename function in UI

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.vis#474]
Would be great to have a project delete/rename function in the VIS editor UI.
It's more user friendly, would avoid looking for "how can I delete a project" in the web, reduces errors when deleting something via file browser.
(and I think most people would expect such a function in the editor)

**Comment by Feuer-sturm** [comment]
With vis2-beta v2.0.6 (Alpha Version of vis2) it is possible to delete and rename projects.

![grafik](https://user-images.githubusercontent.com/25422320/202866172-f3c30875-0a22-4123-9343-f880a758eb47.png)

**Comment by Feuer-sturm** [comment]
issue wird geschlossen, da das Problem mit vis2 gefixt ist.
Für vis1 wird es keine Bugfixes mehr geben, da die Energie in vis2 investiert wird (siehe auch https://forum.iobroker.net/topic/60398/test-adapter-vis-2-0-alpha)
