### ISSUE TITLE
Auswahlknopf Datenpunkt ist manchmal weg!!

### ISSUE THREAD

**Issue by rmp63526** [ioBroker/ioBroker.vis#487]
Hallo,

bin jetzt mit meinem Latein/Geduld am Ende.
Ich kann an meine Vis nicht weiter arbeiten, weil mir der Auswahlknopf um in die Datenpunkte zu gelangen fehlt!
Benutze den Google Browser und habe auch bereits den Edge Browser versucht. Cache und Cookies habe ich alles gelöscht (Browserdaten).
Vis adapter neu gestartet und den Web adapter.

- Node.js v12.22.11 (Es gibt eine neuere Version: v12.22.12 - Empfohlene Version v14.19.2) 
- Raspberry pi 4 8gb über SSD laufen
- NPM 6.14.16

**Comment by Apollon77** [comment]
Google Browser === Chrome?

Ansonsten ... Hast Du mal einen Screenshot der das Zeigt?

Und: Irgendwelche Fehler in der Browser Konsole?

**Comment by rmp63526** [comment]
Habe in der Zwischenzeit natürlich nicht nochmal diesen Fehler gehabt.
Wenn der Fehler wieder kommt, wo schaue ich in der Konsole vom Browser?

**Comment by rmp63526** [comment]
Schließe den Beitrag, da in der Zwischenzeit der Fehler nicht mehr auftrat.
