### ISSUE TITLE
Aufruf VIS über VPN dauert bis zu 20 Sekunden

### ISSUE THREAD

**Issue by slimline33** [ioBroker/ioBroker.vis#511]
Hi, 

Ich habe das Problem, dass der Aufruf bis zur Meldung "Connecting to Server...." der VIS über eine VPN Verbindung sehr lange dauert. Teilweise bis zu 20 Sekunden. Ich leite den Gesamten Traffic über die VPN Verbindung. Der Aufruf des Admins geht blitzschnell. Da hakt nichts.

- Das ganze läuft über einen Glasfaseranschluss mit 400/200 (ipv6 und ipv4 über Vserver mit 500/100)
- VPN Server ist eine DS918+ mit integriertem openVPN
- Speed über VPN 66.9/96 Mbps

Da ich das Problem schon recht lange habe, kann ich leider nicht sagen seit welcher Version der VIS das ist. Ich hab schon einige Versionen durch. Auch Beta Versionen, ändert aber nichts.

Der Aktuelle Stand ist: 
WEB Server: 5.2.4
VIS: 1.4.1.5

Es ist aber egal auf welche Version ich springe, das Problem besteht weiterhin.

![image](https://user-images.githubusercontent.com/3323812/180261893-cfe55d87-e6a0-41cc-8807-b7013b76e332.png)

Hat jemand eine Idee?

Gruß

**Comment by Feuer-sturm** [comment]
@slimline33 Besteht das Problem weiterhin bei dir oder hat sich das Thema erledigt?

**Comment by slimline33** [comment]
Das Problem besteht leider immer noch! 😑 Vorallem mit openvpn. Mit wireguard ist es etwas besser. Könnte allerdings auch an der Geschwindigkeit liegen. 

Nur im Moment keine Zeit dem nochmal nachzugehen. 
Ich hätte das issue sonst geschlossen 👍

**Comment by Apollon77** [comment]
fragen:
* werden viele Aliasse genutzt in der Vis?
* Wieviele Datenwerte werden denn so angezeigt (weil wird ja alles zu beginn geladen)

**Comment by slimline33** [comment]
Aliase werden gar keine genutzt.

Meine VIS ist schon aufwändig, das gebe ich zu jedoch geht es mir gar nicht um das Laden der VIS selber, sondern um das "Verbinde zum Server". Bis diese Meldung kommt, vergehen schon mal 10-15 Sekunden jetzt. 

Ich versuche ein Video zu machen.

**Comment by slimline33** [comment]
Mit vpn:

https://user-images.githubusercontent.com/3323812/202913324-fc5a40d1-c607-426e-995b-72a1cc99b233.mp4

Ohne vpn:

https://user-images.githubusercontent.com/3323812/202913339-232fc0f2-36b5-4d80-b4e2-cf841db9e694.mp4

**Comment by slimline33** [comment]
Wohngegend ich den admin innerhalb Sekunden aufrufen kann.

https://user-images.githubusercontent.com/3323812/202913531-0c21d00e-59eb-4cfe-9845-9a1ab225f640.mp4

**Comment by slimline33** [comment]
Folgende Adapter sind installiert:

Used repositories: Stable (default), Live
Adapter    "admin"        : 6.2.23   , installed 6.2.23
Adapter    "alexa2"       : 3.21.0   , installed 3.21.0
Adapter    "backitup"     : 2.5.4    , installed 2.5.4
Adapter    "broadlink2"   : 2.1.5    , installed 2.1.5
Adapter    "daswetter"    : 3.1.4    , installed 3.1.4
Adapter    "device-reminder": 1.2.9  , installed 1.2.9
Adapter    "device-watcher": 2.0.2   , installed 2.0.2
Adapter    "feiertage"    : 1.1.0    , installed 1.1.0
Adapter    "flot"         : 1.11.0   , installed 1.11.0
Adapter    "fullybrowser" : 2.1.2    , installed 2.1.2
Adapter    "heatingcontrol": 2.9.3   , installed 2.9.3
Adapter    "heizoel"      : 1.0.3    , installed 1.0.3
Adapter    "ical"         : 1.13.1   , installed 1.13.2
Adapter    "icons-material-png": 0.1.0, installed 0.1.0
Adapter    "icons-mfd-png": 1.1.0    , installed 1.1.0
Adapter    "icons-mfd-svg": 1.1.0    , installed 1.1.0
Adapter    "influxdb"     : 3.1.8    , installed 3.1.8
Adapter    "iot"          : 1.11.9   , installed 1.11.9
Adapter    "javascript"   : 6.0.3    , installed 6.0.3
Controller "js-controller": 4.0.23   , installed 4.0.23
Adapter    "logparser"    : 1.1.0    , installed 1.1.0
Adapter    "mihome-vacuum": 3.8.6    , installed 3.8.6
Adapter    "mqtt"         : 4.0.7    , installed 4.0.7
Adapter    "netatmo-crawler": 0.8.1  , installed 0.8.1
Adapter    "nut"          : 1.5.1    , installed 1.5.1
Adapter    "octoprint"    : 4.0.0    , installed 4.0.0
Adapter    "parser"       : 1.1.8    , installed 1.1.8
Adapter    "phantomjs"    : 1.1.3    , installed 1.1.3
Adapter    "ping"         : 1.5.3    , installed 1.5.3
Adapter    "proxmox"      : 1.3.4    , installed 1.3.5
Adapter    "pvforecast"   : 2.3.0    , installed 2.3.0
Adapter    "scenes"       : 2.3.9    , installed 2.3.9
Adapter    "schoolfree"   : 1.0.1    , installed 1.0.1
Adapter    "simple-api"   : 2.7.0    , installed 2.7.2
Adapter    "smartcontrol" : 1.2.1    , installed 1.3.0
Adapter    "socketio"     : 4.2.0    , installed 6.1.10
Adapter    "sonoff"       : 2.5.1    , installed 2.5.1
Adapter    "sprinklecontrol": 0.2.13 , installed 0.2.13
Adapter    "synology"     : 2.1.13   , installed 2.1.13
Adapter    "telegram"     : 1.14.1   , installed 1.14.1
Adapter    "terminal"     : 0.2.6    , installed 0.2.6
Adapter    "text2command" : 2.2.2    , installed 2.2.2
Adapter    "tr-064"       : 4.2.16   , installed 4.2.16
Adapter    "unifi"        : 0.5.10   , installed 0.6.1
Adapter    "vis"          : 1.4.15   , installed 1.4.15
Adapter    "vis-bars"     : 0.1.4    , installed 0.1.4
Adapter    "vis-canvas-gauges": 0.1.5, installed 1.0.1
Adapter    "vis-colorpicker": 1.2.0  , installed 1.2.0
Adapter    "vis-fancyswitch": 1.1.0  , installed 1.1.0
Adapter    "vis-google-fonts": 1.0.3 , installed 1.0.3
Adapter    "vis-history"  : 1.0.0    , installed 1.0.0
Adapter    "vis-hqwidgets": 1.3.0    , installed 1.3.0
Adapter    "vis-jqui-mfd" : 1.0.12   , installed 1.0.12
Adapter    "vis-justgage" : 1.0.2    , installed 1.0.2
Adapter    "vis-material-advanced": 1.7.2, installed 1.7.2
Adapter    "vis-metro"    : 1.2.0    , installed 1.2.0
Adapter    "vis-rgraph"   : 0.0.2    , installed 0.0.2
Adapter    "vis-weather"  : 2.5.6    , installed 2.5.6
Adapter    "web"          : 4.3.0    , installed 5.2.10
Adapter    "wlanthermo-nano": 0.2.1  , installed 0.2.1
Adapter    "ws"           : 1.3.0    , installed 2.1.5
Adapter    "zigbee"       : 1.7.5    , installed 1.7.6

Ich habe es stellenweise dann mit Beta Versionen versucht und bin dann auch hin und her geswitcht zwischen den Versionen um etwas zu finden woran das liegen kann. Vorallem bei WS, WEB und socket.io. 

Aktuell bin ich beim WEB Adapter bei 5.2.1.0, jedoch ist es da identisch. Das ganze hat ca. angefangen, als man das IPAD nicht mehr unterstützt hatte ab einer gewissen Version. Genau weiß ich leider nicht mehr.
