### ISSUE TITLE
Viele Probleme 

### ISSUE THREAD

**Issue by Starter4711** [ioBroker/ioBroker.vis#515]
Hallo,
aktuellst VIS Version, aktuelle Beta ioBroker
Die Anzeigen zeigen oft nur "undefined" oder "NaN" an (Werte im Widget).
Aktualisierung fkt. teils gar nicht, man muss manuell aktualisieren und per Glück passt die Anzeige mal.
Es hat sich mit jedem Update verschlechtert, früher (ca. 1-2 Jahre) waren es deutlich weniger fehlerhafte Anzeigen und Aktualisierungprobleme.
Vorallem die App am iPhone ist schon ein wenig ein Problem.
Startet man die App, wird nichts aktualisiert, nach einigen Sekunden kommt der Ladering, der manchmal gar nicht mehr weg geht, sonst dauert es auch viel zu lange bis aktualisiert wird.
(Trotzdem vielen Dank für die Nutzung!!)
![IMG_1985](https://user-images.githubusercontent.com/15359915/185334504-1f2a35d1-13bf-43c1-9d4c-d2029050cca1.PNG)

**Comment by Apollon77** [comment]
Hi,

Danke für Deinen bericht, aber jetzt verrate mir mal was ein Developer damit anfangen soll?

Bitte:
* pro Thema ein Issue
* ggf rausfindenw arum es "dundefined "ist bedarf checken der Konfig. Sowas vllt besser im Forum
* Es fehlen Versionsangaben zu den genutzten Dingen, welche Widgets sind da im Einsatz und und und

Sorry, aber so ist dieses issue nicht hilfreich.

Am besten mal im Forum ein Thread (vllt auch da "gleiche Probleme zusammenfassen" und mehrere Threads?) auf machen um erstmal rauszufinden ob es Nutzer, Konfigurations oder Widgetfehler sind
