### ISSUE TITLE
Projekt-Backup lässt sich nicht mehr importieren - Verbindungsfehler

### ISSUE THREAD

**Issue by Bodengriller** [ioBroker/ioBroker.vis#517]
Ich musste meinen iobroker-Container neu aufsetzen (Update auf den V7.0.1 Docker-Container).

Nach Einspielen des Backups funktionierte soweit auch alles, bis ich heute feststellen musste, dass der VIS-Editor meine Projekte nicht mehr korrekt lädt.
(z.B. Wenn man im Main-Projekt über "Setup -> Projekte" geht, wird dort NUR "Main" angezeigt, die anderen 2 Projekte fehlen. Ändert man allerdings in der Browser-Adresszeile den Projektnamen, landet man auch im entsprechenden Projekt)

Ich habe daraufhin dann kurzerhand also alle Projekte gelöscht und wollte einfach die letzten Projekt-Backups im Editor laden....dumm gelaufen - geht nicht.
2/3 Projekten werden importiert.
Das Main-Projekt (ca. 2,2MB)  wird leider nicht importiert -> "Verbindungsfehler"

Irgendwo las ich mal was, dass es Probleme mit der Dateigröße beim Upload gab?!

In diesem Projekt gibt es ein PNG-Bild, welches 1,01MB hat -> dieses kann ich über den vis-Dateimanager auch nicht einzeln hochladen (der Uploader zeigt einfach ewig den Sanduhr-Kringel).
Ebenso klappt der Einzelupload der "vis-views.json" nicht (963kb)
Kleinere Bilder und Dateien werden jedoch geuploaded.

Per SSH darf ich die Dateien auch nicht mehr uploaden, das ist m.W. auch nicht mehr "erlaubt" - die Dateien tauchen dann nicht im Editor auf.

Nun stehe ich dumm da - hat jemand eine Idee, wie ich meine Backups wieder in den Adapter bekomme?
Bzw. Wie bekommt man etwas größere Dateien wieder importiert? (2MB finde ich tatsächlich gar nicht SO groß)

Probiert mit Chrome, Edge, Firefox, Brave von verschiedenen Geräten.
Neustart des iobroker-Containers erfolglos.

Node.js v16.17.0
js-controller 4.0.23
vis-Adapter 1.4.15

**Comment by Apollon77** [comment]
Bitte im Web-Adapter von socket.io auf "use ws" ändern ... dann geht es wieder

duplicate #510

**Comment by Bodengriller** [comment]
Da muss man erstmal drauf kommen...
danke, funktioniert!
