### ISSUE TITLE
VIS nicht bearbeitbar, "Verbindungsfehler"

### ISSUE THREAD

**Issue by srwilli1** [ioBroker/ioBroker.vis#519]
Die vis ist nicht bearbeitbar, bearbeitet man irgendwas erscheint die Meldung Verbindungsfehler.

**Versions:**  
 - Adapter version: 1.4.15
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Raspberry OS

**Comment by Apollon77** [comment]
duplicate #510 , siehe auch dort für workaround
