### ISSUE TITLE
VIS lässt sich nicht bearbeiten

### ISSUE THREAD

**Issue by fuchs-1978** [ioBroker/ioBroker.vis#520]
Neuerding habe ich bei der Bearbeitung der VIS Probleme. Über den Cloud Adapter bekommen ich nach kurzer Zeit folgende Meldung:

Cloud says: Too many updates or requests

Lokal bekomme ich eine Dreieck mit dem Hinweis Verbindungsfehler. (Dies kann man beheben durch die Umstellung des WS )

Wie kann ich herausfinden, was die vielen requests macht?

**Comment by Apollon77** [comment]
Verbindungsfehler lokal -> #510 ggf kommendaher auch viele retry versuche?
