### ISSUE TITLE
Verbindungsfehler

### ISSUE THREAD

**Issue by DerDoubleD** [ioBroker/ioBroker.vis#521]
**Describe the bug**  
Nach einem Restore. Sind meine Projekte nicht mehr da. Wenn ich ein neues Projet erstelle sind auf einmal alle alten wieder da.
Diese kann ich auch öffnen aber nicht speichern. Es erscheint dann ein Verbindungsfehler.

![grafik](https://user-images.githubusercontent.com/47006370/187503949-8f9d0fd0-c3e7-4337-a08b-86a80c72969b.png)

**Versions:**  
 - Adapter version: 1.4.15
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: debian 11 on proxmox

**Comment by Ricox1975** [comment]
dasselbe hier

**Comment by Apollon77** [comment]
duplicate #510 (incl. workaround
