### ISSUE TITLE
View-Name mit Slash-Zeichen "/" verursacht Fehler

### ISSUE THREAD

**Issue by prorun26** [ioBroker/ioBroker.vis#527]
Wenn ein neues view angelegt wird und der Name ein Slash-Zeichen enthält "/" wird dieses zwar dem Projekt hinzugefügt doch leider Fehlerhaft bzw kann der View-Name dann nicht ordnungsgemäß ausgewertet werden.

Löschen oder bearbeiten des fehlerhaften Views ist leider nicht möglich. 
Nur ein manuelles entfernen aus der vis-views.json konnte das Problem beheben. 
Dies funktioniert jedoch nur wenn das System heruntergefahren ist.

Verwendete Version: 1.4.15

**Comment by sigi2345** [comment]
Sonderzeichen sind nicht erlaubt

**Comment by Feuer-sturm** [comment]
Mit vis2-beta (Alpha Version) v2.0.6 hab ich keine Probleme, wenn die View mit einem Sonderzeichen anfängt. Man kann die View bearbeiten, umbenennen, löschen.

**Comment by Haifeif** [comment]
Werden noch Betatester für 2.x gebraucht? Ich habe Zeit ...

**Comment by Feuer-sturm** [comment]
@Haifeif Hi, jeder ist eingeladen zu testen, :-)
Hier findet du im Forum den entsprechenden Thread https://forum.iobroker.net/topic/60398/test-adapter-vis-2-0-alpha
Wenn du Fehler findest bitte hier auf github ein entsprechendes issue erstellen.

**Comment by Feuer-sturm** [comment]
issue wird geschlossen, da das Problem mit vis2 gefixt ist.
Für vis1 wird es keine Bugfixes mehr geben, da die Energie in vis2 investiert wird (siehe auch https://forum.iobroker.net/topic/60398/test-adapter-vis-2-0-alpha)
