### ISSUE TITLE
Import von bestehenden Projekten nicht möglich

### ISSUE THREAD

**Issue by ApolloSK** [ioBroker/ioBroker.vis#528]
Hallo zusammen,

ich habe heute iobroker komplett neu aufgesetzt. Beim Versuch ein bestehendes Projekt, welches ich vorher aus der alten Installation exportiert hatte, in die neue Instanz zu importieren passiert nichts. Das Projekt wird nicht importiert.

Dafür erhalte ich folgende Fehlermeldungen. In der Kopfzeile des Browsers wird ein "Verbindungsfehler" angezeigt: 

![image](https://user-images.githubusercontent.com/43525358/190849677-3ac8db05-1f72-4489-ae57-cc3af19714f5.png)

In der Konsole des Browsers erfolgt ein paar Sekunden nach der Anzeige dieses Popups ein "Try Connect"

![image](https://user-images.githubusercontent.com/43525358/190849702-74dcc62c-bc26-4ec7-8b99-a9643f47a67b.png)

Im Protokoll wird für die Instanz web.0 im Sekundenintervall "connects" und "disconnects" angezeigt für den user admin angezeigt.

Weshalb können keine Projekte importiert werden? Was verursacht den Verbindungsfehler?

**Comment by Apollon77** [comment]
duplicate #510?
