### ISSUE TITLE
Anzahl Bindings ist begrenzt

### ISSUE THREAD

**Issue by DerDoubleD** [ioBroker/ioBroker.vis#529]
**Describe the bug**  
ab ca. 60 bindings werden diese in einem HTML-Widget nicht mehr angezeigt.

_
\<td align=right>{shelly.0.SHPLG-S#C5075B#1.Relay0.Power}</td>
\<td align=right>{shelly.0.SHPLG-S#C5075B#1.firmware}</td>
\td align=right>{shelly.0.SHPLG-S#C5075B#1.hostname}</td>
_

**To Reproduce**  
1. Ziehe eine HTML-WIdget in ein VIS
2. Erstelle darin mehr als ca. 60 bindings
3. Ab einer gewissen zahl werden die bindings nicht mehr ausgewertet.

**Expected behavior**  

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/47006370/191048003-4df04704-0510-4d6e-9e56-80cf462b0e03.png)

**Versions:**  
 - Adapter version: aktuell
 - JS-Controller version: aktuell
 - Node version: aktuell
 - Operating system: debian

**Additional context**

**Comment by ice987987** [comment]
same as https://github.com/ioBroker/ioBroker.vis/issues/381?

**Comment by Apollon77** [comment]
yes duplicate #381
