### ISSUE TITLE
main/vis-views.json [object Object]

### ISSUE THREAD

**Issue by Nogger82** [ioBroker/ioBroker.vis#536]
Hallo,
Ich habe das Problem, dass sich meine VIS irgendwann nicht mehr laden wollte. Da ich eh nicht zufrieden war, habe ich den VIS Adapter komplett gelöscht und neu aufgesetzt. Nun bekomme ich folgende Meldung:
main/vis-views.json [object Object]

Was kann ich dagegen tun?

![vis](https://user-images.githubusercontent.com/102550384/196006881-4a87af3d-fe41-43a9-b00b-16f0be067c83.png)

**Comment by philippeaellig** [comment]
i have the same problem. is there a solution for this problem anywhere?
i am running a brand new instance in a debian linux container. all adapters are working fine. only the vis is making troubles...

EDIT:
for me, the problem is solved. after i clicked "OK", a second alert apears and by clicking on "OK" on the second alert box, a new project was created and i was able to start. Before i clicked "OK" i was pressing escape on the keyboard and then in the second alert box, the project will not be created.

**Comment by Nogger82** [comment]
> i have the same problem. is there a solution for this problem anywhere? i am running a brand new instance in a debian linux container. all adapters are working fine. only the vis is making troubles...
> 
> EDIT: for me, the problem is solved. after i clicked "OK", a second alert apears and by clicking on "OK" on the second alert box, a new project was created and i was able to start. Before i clicked "OK" i was pressing escape on the keyboard and then in the second alert box, the project will not be created.

That doesn't work on my Case. I don't what happens, if setup a complete New System and load an Backup from my actual System. Would this problem be transferred?

**Comment by Nogger82** [comment]
Is there no way for getting a solution?

**Comment by steinfahrer** [comment]
Ich habe das gleiche Problem... vis-views.json nicht gefunden. Die Android App funktioniert nicht mehr. Die vis selber und auch die runtime lokal funktionieren aber.

**Comment by steinfahrer** [comment]
Für mich sieht es so aus, als ob immer versucht wird, im "main"-Projekt etwas zu finden. Wenn ich links oben klicke, um auf die Einstellungen zu kommen, erscheint nach ein paar sekunden mein Projekt und dann geht es auch. Muss wohl mein ganzes Projekt nach main verschieben...

**Comment by Nogger82** [comment]
> Für mich sieht es so aus, als ob immer versucht wird, im "main"-Projekt etwas zu finden. Wenn ich links oben klicke, um auf die Einstellungen zu kommen, erscheint nach ein paar sekunden mein Projekt und dann geht es auch. Muss wohl mein ganzes Projekt nach main verschieben...

Kannst du mir evtl sagen, wo sich dieser Main Ordner befindet? Notfalls leg ich ihn halt an. gibt es diese Datei "vis-views.json" überhaupt? Vielleicht könnte ich die aus einem anderen System übernehmen, damit es wieder läuft. Wie gesagt, ich komme nicht mal auf den Editor drauf.

**Comment by Nogger82** [comment]
Jetzt gab es grad ein neues Verhalten. Es kam eine Meldung, dass keine Views gefunden wurden und ob neu erstellt werden soll. Nun ist der Editor wieder da. Ich habe keine Ahnung, warum es auf einmal wieder funktioniert.
