### ISSUE TITLE
Keine Vorschau im Datei Manager

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.vis#54]
Wie schon im Forum vorbesprochen (http://forum.iobroker.org/viewtopic.php?f=22&t=742) gibt es ein Problem mit der Vorschau. Bei mir mit Chrome und IE. Festgestellt bei vis 0.5.0

**Comment by ykuendig** [comment]
Auch bei 0.5.1 besteht das Problem noch.

**Comment by ykuendig** [comment]
Im Forum hat jens-slf geschrieben: 'ich habe das gleiche Problem und habe zufällig raus gefunden das die vorschau nicht fehlt sondern die Grafiken fast weiß auf weiß sind ,in ein bestimmten winkel kann ich sie auf mein Display sehen des wegen in allen Browsern das gleiche . Warum das so ist habe ich keinen schimmer .In DashUI war der Hintergrund Schwarz . Hoffe das die kleine Info hilft .
Mfg Jens-slf'
Scheint mir ein guter Hinweis

**Comment by ykuendig** [comment]
Habe das geprüft, und stimmt, wenn man das div der files:
<div class="fm_files ui-state-default no_background" ...>
ohne 'no_background' rendert, kommen die mfd-Bildchen brav raus...

**Comment by GermanBluefox** [comment]
Ich habe in 0.5.2 einen Knof im Image Select Dialog eingebaut. Kannst du checken und damit leben?
![image](https://cloud.githubusercontent.com/assets/4582016/7747282/7c8fc6e2-ffb9-11e4-9784-c3bbfb6a6855.png)

**Comment by ykuendig** [comment]
Habe ich gesehen. Finde ich durchaus hilfreich. Zumindest für den Moment. 
Ist das eine definitive Lösung oder nur bis Dir etwas besseres einfällt?

**Comment by GermanBluefox** [comment]
Dein Vorschlag? Was konnte da besseres sein? Die Icons können doch immer
andere Farbe haben.

2015-05-21 19:53 GMT+02:00 ykuendig notifications@github.com:

**Comment by ykuendig** [comment]
Es ist gut so. Es war nur eine Frage.
;-) _Und wenn wir über Automation sprechen, gibt es etwas besseres als einen Knopf?_ ;-)

**Comment by GermanBluefox** [comment]
"Und wenn wir über Automation sprechen" .... Das geht nicht. :)
Wenn du was anbietest, merge ich das gerne :) Bitte issue zumachen.
