### ISSUE TITLE
VIS Update von Elementen nicht mehr möglich

### ISSUE THREAD

**Issue by The2Earthlings** [ioBroker/ioBroker.vis#541]
**Describe the bug**  
In der Visualisierung können Inhalte von Elemente (z.B. Basic HTML) nicht mehr verändert werden. Dies tritt erst seit Update von VIS, WEB und socketio etc. auf. Vor dem Update hat sich alles reibungslos updaten lassen.

Versionen der Adapter:
Adapter    "admin"        : 6.2.23   , installed 6.2.23
Adapter    "socketio"     : 4.2.0    , installed 4.2.0
Adapter    "vis"          : 1.4.15   , installed 1.4.15
Adapter    "web"          : 4.3.0    , installed 4.3.0

System Versionen:
node: v12.20.0
js-controller: 4.0.23

Im VIS wird oben rechts auch abgeschnitten nach einer Änderung von Werten im z.B. HTML Widget -> HTML eine rote Fehlerbox angezeigt - leider ist der Inhalt nicht lesbar da abgeschnitten (vermutlich no connection?)

Der Entwickler Mode im Browser zeigt auch ständig wiederkehrend diese Fehler an:

Trying connect... [conn.js:157:25](http://192.168.1.99:8082/vis/js/conn.js)
was offline for 10.024s [conn.js:281:29](http://192.168.1.99:8082/vis/js/conn.js)
2022-11-04T12:09:21.670Z Connected => authenticate [conn.js:305:25](http://192.168.1.99:8082/vis/js/conn.js)
2022-11-04T12:09:21.793Z Authenticated: true [conn.js:326:33](http://192.168.1.99:8082/vis/js/conn.js)
Request all states. [vis.js:3700:33](http://192.168.1.99:8082/vis/js/vis.js)
"Use background": {"en": "Use background", "de": "Use background", "ru": "Use background"}, [translate.js:20:17](http://192.168.1.99:8082/vis/lib/js/translate.js)
"Änderungen": {"en": "Änderungen", "de": "Änderungen", "ru": "Änderungen"}, [translate.js:20:17](http://192.168.1.99:8082/vis/lib/js/translate.js)
**Die Verbindung zu ws://192.168.1.99:8082/socket.io/?key=nokey&EIO=3&transport=websocket&sid=G2Zi_Pu6CCrl5knKAAAI wurde unterbrochen, während die Seite geladen wurde. [socket.io.js:8:5939](http://192.168.1.99:8082/lib/js/socket.io.js)
Socket error: Error: websocket error [conn.js:495:29](http://192.168.1.99:8082/vis/js/conn.js)**
Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 3
GEThttp://192.168.1.99:8082/vis/icon/dimmer.png
[HTTP/1.1 404 Not Found 12ms]

**Trying connect... [conn.js:157:25](http://192.168.1.99:8082/vis/js/conn.js)
was offline for 10.148s [conn.js:281:29](http://192.168.1.99:8082/vis/js/conn.js)**
2022-11-04T12:13:23.731Z Connected => authenticate [conn.js:305:25](http://192.168.1.99:8082/vis/js/conn.js)
2022-11-04T12:13:25.618Z Authenticated: true [conn.js:326:33](http://192.168.1.99:8082/vis/js/conn.js)
Request all states. [vis.js:3700:33](http://192.168.1.99:8082/vis/js/vis.js)
"Use background": {"en": "Use background", "de": "Use background", "ru": "Use background"}, [translate.js:20:17](http://192.168.1.99:8082/vis/lib/js/translate.js)
"Änderungen": {"en": "Änderungen", "de": "Änderungen", "ru": "Änderungen"}, [translate.js:20:17](http://192.168.1.99:8082/vis/lib/js/translate.js)

[console-export-2022-11-4_13-17-28.txt](https://github.com/ioBroker/ioBroker.vis/files/9938155/console-export-2022-11-4_13-17-28.txt)

**Comment by Apollon77** [comment]
Bitte im web adapter auf "native websockets nutzen" setzen. Geht es dann wieder?

**Comment by The2Earthlings** [comment]
Hi @Apollon77 
in der tat die Option "Reine Web-Sockets (iobroker.ws) verwenden" ist nun aktiviert und damit funktioniert alles bestens.

Danke für die schnelle Hilfe.
