### ISSUE TITLE
vis2.x: Filemanager missing

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis#547]
**Describe the bug**  
Filemanager (Dateimanager) is missing
![image](https://user-images.githubusercontent.com/69053781/202532612-33fc7ab0-d3f1-4bee-834d-12e64f2aaa2d.png)

I can find it only in `basic image`-widget -> Quelle (but is hard to see)
![image](https://user-images.githubusercontent.com/69053781/202532970-fc255e23-78aa-45b7-8f1a-844454c7f672.png)

- Adapter version: ioBroker.vis v2.0.6
- JS-Controller version: v4.0.23
- Node version: v16.18.1
- Operating system: ioBroker.docker v7.2.1

**Comment by Apollon77** [comment]
Hm ... is it missing or shpould we not say "Admin has it now"? But yes thenAdmin would also need to show images and such ... ?!

**Comment by GermanBluefox** [comment]
Added in 2.0.9, that already released

**Comment by ice987987** [comment]
filemanager "files" is availabe in v2.0.9. upload and download works as expected.
thank you very much!
