### ISSUE TITLE
vis2.x: CSS Font & Text is not rendered in editor

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis#548]
**Describe the bug**  
widget section `CSS Font & Text` is not rendered in editor. It is only applied, if runtime in a new window is opened.

**To Reproduce**  
import widget

```
[
  {
    "tpl": "tplHtml",
    "data": {
      "refreshInterval": "0",
      "g_common": true,
      "html": "{0_userdata.0.test1}",
      "g_css_font_text": true
    },
    "style": {
      "left": 172,
      "top": 105,
      "color": "rgba(58,27,203,1)",
      "text-align": "right",
      "font-family": "Courier",
      "font-style": "italic",
      "font-weight": "bold",
      "font-size": "25px"
    },
    "_id": "i000001"
  }
]
```

**Screenshots & Logfiles**  
![Animation](https://user-images.githubusercontent.com/69053781/202535353-85a414b7-56aa-4c9a-8809-411cb7816b86.gif)

**Versions:**  
- Adapter version: ioBroker.vis v2.0.6
- JS-Controller version: v4.0.23
- Node version: v16.18.1
- Operating system: ioBroker.docker v7.2.1

**Comment by Feuer-sturm** [comment]
@ice987987 I imported your widget and with vis 2.0.23 it is ok
![Animation5](https://user-images.githubusercontent.com/25422320/227720117-2622909d-bf39-40b3-874f-b1ee1a8fa34d.gif)
