### ISSUE TITLE
Zählung beim Selektieren

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.vis#55]
Wenn mehr als ein Widget selektiert und dann gelöscht werden, wird immer 1 zuviel berechnet. ('Alle' wird mit gezählt?!)

**Comment by GermanBluefox** [comment]
Um welches Element es geht? Kann nicht reproduzieren.

**Comment by ykuendig** [comment]
Ist nur eine Kleinigkeit. Vielleicht hilft ein Bild. Wenn Du 2 Widgets selektierst und 'DEL' drückst, kommt ein Dialog, der fragt ob Du 3 Widgets löschen möchtest.
![ioborkerfehler02](https://cloud.githubusercontent.com/assets/12490872/7738035/94ca4052-ff50-11e4-9b4e-e8c0c57d8c9e.PNG)

**Comment by GermanBluefox** [comment]
Ok. Jetzt habe ich gefunden. Danke.

2015-05-21 0:32 GMT+02:00 ykuendig notifications@github.com:

**Comment by GermanBluefox** [comment]
Muss in 0.5.3 gefixt sein.

**Comment by ykuendig** [comment]
Stimmt.
