### ISSUE TITLE
vis2.x: menuband disappears on iPad

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis#551]
**Describe the bug**  
the menuband disappears on iPad while a widget is edited. Vis is without a reload unusable.

**To Reproduce**  
1. open vis2.x on iPad
2. drag/edit a widget

**Expected behavior**  
menuband must not disappear

**Screenshots & Logfiles**  
https://user-images.githubusercontent.com/69053781/205114932-f315b65b-3162-43ad-b523-ee323b2ba29f.MOV

**Versions:**  
Adapter version: ioBroker.vis v2.0.6
JS-Controller version: v4.0.23
Node version: v16.18.1
Operating system: ioBroker.docker v7.2.1 / iPadOS 16.1.1 (20B101)

**Comment by Feuer-sturm** [comment]
@ice987987 Can you please double check with current vis2 version 2.0.23 if this issue is still active?

**Comment by ice987987** [comment]
works as expected in v2.0.23
thank you very much!
