### ISSUE TITLE
vis2.x: size of widget no longer automatically adjusted

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis#553]
**Describe the bug**  
if a table with a defined height is inside of the `html-widget` the height of the widget is no loger adjusted to its (variable) size of its content (height of widget is always 130px).

**To Reproduce**  
import widget: 

`[
  {
    "tpl": "tplHtml",
    "data": {
      "refreshInterval": "0",
      "g_common": true,
      "html": "<table border=\"1\" width=100% height=300px>\n    <tr>\n        <td>\n            content1\n        </td>\n    </tr>\n</table>"
    },
    "style": {
      "left": "0px",
      "top": "50px",
      "width": "100%",
      "height": ""
    },
    "_id": "i000001"
  }
]`

**Expected behavior**  
size of widget is automatically adjusted to its content, same as in vis1.x

**Versions:** 
- Adapter version: ioBroker.vis v2.0.6
- JS-Controller version: v4.0.23
- Node version: v16.18.1
- Operating system: ioBroker.docker v7.2.1

-

**Comment by GermanBluefox** [comment]
Some behaviors cannot be same as in vis-1. Your config is invalid, it must be so:
`[ { "tpl": "tplHtml", "data": { "refreshInterval": "0", "g_common": true, "html": "<table border=\"1\" width=\"100%\" height=\"100%\">\n <tr>\n <td>\n content1\n </td>\n </tr>\n</table>" }, "style": { "left": "0px", "top": "50px", "width": "100%", "height": "300px" }, "_id": "i000001" } ]`

**Comment by ice987987** [comment]
I know that the value for `height` in the html-widget-definition is missing. Reason for that is: the content of the table is dynamic (with a binding), therefore `height` is dynamic as well.
In vis1.x it was possible to enter `100%` and then delete this value (leave `height` empty). It worked pretty well.

How can we handle a dynamic widget-height in dependency of its content?

**Comment by GermanBluefox** [comment]
>  It worked pretty well.
And now it does not work as intended to. Sorry I don't know how to make it work.
The widget MUST have some height.
