### ISSUE TITLE
vis2.x: import does not work from old project

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.vis#558]
export a actual vis and try to import to vis 2.x
![grafik](https://user-images.githubusercontent.com/6681528/203827426-44d81042-484a-4b33-b3a3-5b0d7bc5db79.png)

**Comment by Feuer-sturm** [comment]
@arteck What happens after you press the button "Overwrite"?
Is it possible to import you project if this project does not exist in vi2?
