### ISSUE TITLE
vis2.x: text is not readable

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.vis#559]
generate a new instance
![grafik](https://user-images.githubusercontent.com/6681528/203828449-5b3c1310-c19b-4992-93de-b4c1715f2289.png)

**Comment by Feuer-sturm** [comment]
With v2.0.8
![grafik](https://user-images.githubusercontent.com/25422320/204367877-e240a2ca-6ce2-4bf6-a127-7ebdc8191337.png)

![grafik](https://user-images.githubusercontent.com/25422320/204367799-4fea1b78-e56f-49ad-9cb6-9925897e3e90.png)
