### ISSUE TITLE
Closed pages can not be opened once again

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis#562]
**Describe the bug**  
If there are serveral pages and they are closed it is not possible to show them once again.
There is no reaction if you click on the marked buttons.

With vis-2 version 2.0.6 a window opens and I was able to select which page shall be visible in the project

![grafik](https://user-images.githubusercontent.com/25422320/204107882-3fa9dde5-4675-4319-85f2-eec70b24212a.png)

**To Reproduce**  
1. Create some new pages
2. close the pages
3. Press marked buttons to show closed pages once again -> not working

**Expected behavior**  
If button is pressed a window will pop up and I can select which pages shall be shown (like in verion 2.0.6)

**Versions:**  
 - Adapter version: vis-2 version 2.0.7

**Comment by GermanBluefox** [comment]
Fixed in 2.0.8

**Comment by Feuer-sturm** [comment]
is fixed with v.2.0.8
