### ISSUE TITLE
z-index is not working

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis#563]
**Describe the bug**  
If the z-index of one element is higher than the other one this has no impcat in the vis runtime and the text (in this case) is not shown

**To Reproduce**  
1. Use image widget with green background
2. use item basic-string with higher z-index than image widget
3. Activate runtime view

**Expected behavior**  
basic-string widget is visible in front of the image widget

**Screenshots & Logfiles**  

Editor View:
![grafik](https://user-images.githubusercontent.com/25422320/204108358-aa6491c7-1c64-419c-9fcb-d04764185c0b.png)

Runtime view:
![grafik](https://user-images.githubusercontent.com/25422320/204108353-17c6a04b-4859-41b3-a729-d3551beb3909.png)

Widget export:
```
[
  {
    "tpl": "tplValueStringRaw",
    "data": {
      "oid": "nothing_selected",
      "test_html": "fddadf"
    },
    "style": {
      "left": 221,
      "top": 209,
      "width": "85px",
      "height": 39,
      "z-index": 2
    },
    "_id": "i000001"
  },
  {
    "tpl": "tplImage",
    "data": {
      "refreshInterval": "0",
      "g_common": true,
      "src": "",
      "g_css_background": true
    },
    "style": {
      "left": 149,
      "top": 162,
      "z-index": 0,
      "background": null,
      "background-color": "green",
      "background-image": null,
      "background-repeat": null,
      "background-attachment": null,
      "background-position": null,
      "background-size": null,
      "background-clip": null,
      "background-origin": null
    },
    "_id": "i000002"
  }
]
```

**Versions:**  
 - Adapter version: vis2 v2.0.7

**Comment by GermanBluefox** [comment]
test_html is not visible in runtime mode, so the text is empty in runtime and so not visible

**Comment by Feuer-sturm** [comment]
Thanks for the hint.
Using corect fields and with vis2 v2.0.8 I have no further problems with z-index.
