### ISSUE TITLE
VIS2 Beta Instanzen Icon bei neuen Widget falsch

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis#566]
Hallo,

die Icons bei den neuen Widgets in Instanzen zeigen ein Zeit Icon an.

![Screenshot (5135)](https://user-images.githubusercontent.com/41079106/204125013-32318f5d-7d4b-4b46-b42c-9f735d8bdf1f.png)

Plattform: Windows
RAM: 16 GB 
NODE.JS: V16.18.1
NPM: 8.19.2
JS Controller: 4.0.23
Admin: 6.2.23
WS: 2.2.1
WEB: 5.2.12
Socket.io: 6.2.0
Script Engine: 6.1.4
IOT: 1.12.5
VIS: 1.4.15
VIS2. 2.0.6

**Comment by Apollon77** [comment]
@GermanBluefox They are all type scheduled. This needs to be changed

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
Issue is not fixed yet:
![grafik](https://user-images.githubusercontent.com/25422320/222810429-6a882bc0-b393-48b1-bea2-db968eed3ef1.png)

Admin 6.3.6
Vis2: v2.0.18
Vis 2 Widgets Energy: 0.1.8 
Vis 2 Widgets Gauge: 0.1.8
Vis 2 Widgets Material: 0.2.9

**Comment by Feuer-sturm** [comment]
Issue is fixed.
There was a need to uninstall the adapters and install them once again. After this the "scheduled icon" is not visible any more

Admin 6.3.7
Vis2: v2.0.21
Vis 2 Widgets Energy: v0.1.10
Vis 2 Widgets Gauge: v0.1.11
Vis 2 Widgets Material: v0.2.11
