### ISSUE TITLE
Fehlermeldung beim Nutzung vis-inventwo Widgets

### ISSUE THREAD

**Issue by Chaot1** [ioBroker/ioBroker.vis#568]
Beim Aufruf der Demoview in VIS2.0 kommt diese Fehlermeldung:
`<html>
<body>

ws.0 | 2022-11-27 14:41:13.369 | error | 10 - at Function.renderTo (http://192.168.8.50:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
-- | -- | -- | --
ws.0 | 2022-11-27 14:41:13.366 | error | 9 - at r (http://192.168.8.50:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
ws.0 | 2022-11-27 14:41:13.362 | error | 8 - at Function.frag (http://192.168.8.50:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
ws.0 | 2022-11-27 14:41:13.358 | error | 7 - at Function.hookup (http://192.168.8.50:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
ws.0 | 2022-11-27 14:41:13.354 | error | 6 - at a.each (http://192.168.8.50:8082/vis-2-beta/lib/js/can.custom.js:343:211)
ws.0 | 2022-11-27 14:41:13.351 | error | 5 - at HTMLSpanElement.<anonymous> (http://192.168.8.50:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
ws.0 | 2022-11-27 14:41:13.346 | error | 4 - at Object.eval (i-vis-multi.js:22:87)
ws.0 | 2022-11-27 14:41:13.343 | error | 3 - at Object.universalButton2 (http://192.168.8.50:8082/vis-2-beta/widgets/vis-inventwo/js/vis-inventwo.js:4258:3)
ws.0 | 2022-11-27 14:41:13.339 | error | 2 - at createWidget (http://192.168.8.50:8082/vis-2-beta/widgets/vis-inventwo/js/vis-inventwo.js:4739:30)
ws.0 | 2022-11-27 14:41:13.336 | error | 1 - at Object.getImgColorFilter (http://192.168.8.50:8082/vis-2-beta/widgets/vis-inventwo/js/vis-inventwo.js:5757:17)
ws.0 | 2022-11-27 14:41:13.333 | error | 0 - TypeError: Cannot read properties of undefined (reading 'toLowerCase')TypeError: Cannot read properties of undefined (reading 'toLowerCase')
ws.0 | 2022-11-27 14:41:13.329 | error | can't render i-vis-multi w000036 on "DemoView":

</body>
</html>`

**Comment by Feuer-sturm** [comment]
Hello @Chaot1  , please check with 2.0.10
