### ISSUE TITLE
 jqui  Probleme

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.vis#57]
Issue aus: http://forum.iobroker.org/viewtopic.php?p=5624#p5624
A
val-Türe & val-Drehgriff
Hier verändert sich der Status nicht. Status wird aber nach ioBroker korrekt übertragen.

B
value-Shutter & ctrl-Shutter + jqui Dialog & ctrl-Dimmer + jqui Dialog
Hier wird auch nicht der korrekte Status angezeigt. Unter CCU.IO hat sich aus das Bild verändert.

**Comment by GermanBluefox** [comment]
Muss in 0.5.3 gefixt sein.

**Comment by mctom** [comment]
val-Türe
- Status wird nicht korrekt angezeigt
- es fehlt der übliche jqui widget hintergrund  

val-Drehgriff
- status funktioniert
- es fehlt der übliche jqui widget hintergrund  

ctrl-Shutter + jqui Dialog funktioniert nicht korrekt.
wenn das widget auf die arbeitsfäche gezogen wird sieht es wie folgt aus:

![2015-05-28 21_07_07-iobroker vis](https://cloud.githubusercontent.com/assets/12543796/7868597/95b83860-057d-11e5-9c80-cbcc3e7c6286.png)

value-Shutter
hier wird der status nicht korrekt angezeigt.
das bild verändert sich richtig, aber wenn das rollo offen ist wird der button als aktiv angezeigt

ctrl-Dimmer + jqui Dialog
- hier scheint eine url zu einem Bild (Licht aus) nicht korrekt zu sein
- im jqui Dialog ist der 0% Button zu klein 
- die button 25% / 50% / 75% und der schieber sind ohne funktion
  ![2015-05-28 21_16_53-iobroker vis](https://cloud.githubusercontent.com/assets/12543796/7868849/ef788a34-057e-11e5-9b70-161127fab22d.png)

**Comment by GermanBluefox** [comment]
Bitte mit 0.5.7 testen

**Comment by mctom** [comment]
val-Türe & val-Drehgriff
- Hintergrund wird korrekt angezeigt
- wenn  die Tür/Fenster offen ist wird es allerdings nicht als aktiv angezeigt
- ist es möglich noch ein zusätzliches Widget zu erzeugen. Türe mit Drehgriff?

ctrl-Shutter + jqui Dialog & value-Shutter
- Funktionen sind okay
- wenn das Rolle auf ist wird das Icon als aktiv angezeigt dies sollte nicht so sein

ctrl-Dimmer + jqui Dialog
- die button 25% / 50% / 75% und der schieber sind ohne funktion 
- hier fehlt auch die Auto-zu Funktion noch

**Comment by mctom** [comment]
val-Türe & val-Drehgriff => alles okay
ctrl-Shutter + jqui Dialog & value-Shutter => siehe Issue #75  

ctrl-Dimmer + jqui Dialog => alles okay
aus meiner sicht kann das issue geschlossen werden
