### ISSUE TITLE
VIS2 Neue Widgets werden nicht angezeigt

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis#576]
Hallo,

nach dem Installieren werden die neuen Widgets nicht in der Palette angezeigt.

![Screenshot (5135)](https://user-images.githubusercontent.com/41079106/204157006-3bd5b54e-7f15-4f48-947f-2a2e546c68f2.png)
![Screenshot (5134)](https://user-images.githubusercontent.com/41079106/204157009-8ec6d809-b210-40eb-aeba-e4a433cf0d35.png)

![Screenshot (5137)](https://user-images.githubusercontent.com/41079106/204157103-04c9f803-d139-482c-aba8-d1aba37986af.png)

Plattform: Windows
RAM: 16 GB 
NODE.JS: V16.18.1
NPM: 8.19.2
JS Controller: 4.0.23
Admin: 6.2.23
WS: 2.2.1
WEB: 5.2.12
Socket.io: 6.2.0
Script Engine: 6.1.4
IOT: 1.12.5
VIS: 1.4.15
VIS2. 2.0.8

**Comment by GermanBluefox** [comment]
And after `iob r vis-2-beta` are they visible?

**Comment by sigi2345** [comment]
> And after `iob r vis-2-beta` are they visible?

No

**Comment by thps1990** [comment]
same here...
i noticed deleted the instance and added it again. Here is the log:

> `$ iobroker add vis-2-widgets-energy auto --host smarthome --debug

>INFO: Directory "/opt/iobroker/node_modules/iobroker.vis-2-widgets-energy/www" was not found! Nothing was uploaded or >deleted.

>Adapter "system.adapter.vis.0" restarted.

>host.smarthome create instance vis-2-widgets-energy

>host.smarthome object system.adapter.vis-2-widgets-energy.0 created

>Process exited with code 0`

I´m running the VIS on Docker (official image).

**Comment by juggi1962** [comment]
Ich habe leider das selbe Problem.
Nach der Installation der neuen VIS 2 Widgets erscheinen diese nicht in der VIS 2
Unter Adapter und Instanzen sind sie zu finden aber aber unter VIS 2 nicht.
Unter Instanzen haben alle drei vorne ein oranges Uhren Symbol

Adapter version: ioBroker.vis v2.0.10
JS-Controller version: v 4.0.23
Node version: v 16.17.1

**Comment by hombach** [comment]
same here
Adapter version: ioBroker.vis v2.0.9 on Raspi4
JS-Controller version: v 4.0.23
Node version: v 14.19.2

Edit: After update to adapter 2.0.10 nothing is working anymore. Including Vis1

**Comment by thps1990** [comment]
Mmh i checked it with a plain iobroker docker container... also here the same behavior...

**Comment by sigi2345** [comment]
Anbei Log und Screenshots:

![Screenshot (5195)](https://user-images.githubusercontent.com/41079106/210980078-3caaa2e6-c149-4ee7-8d6d-ce48f241e595.png)
![Screenshot (5194)](https://user-images.githubusercontent.com/41079106/210980091-4c496029-3885-4cb7-a80a-639fbc2fbd54.png)
![Screenshot (5193)](https://user-images.githubusercontent.com/41079106/210980103-21875e43-bb5a-4daf-9435-ed225d9b586d.png)


`iobroker.vis-2-beta@2.0.16 using theme "dark"
main.c31a7d5a.js:657 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.c31a7d5a.js:657 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.c31a7d5a.js:657 Help us to create open source project with reactJS!
main.c31a7d5a.js:657 See you :)
socket.io.js:66 [2023-01-06T10:10:04.536Z] Try to connect
VM300:140 Version vis-canvas-gauges: 0.1.5
VM301:4 Uncaught TypeError: Cannot read properties of undefined (reading 'localization')
    at <anonymous>:4:39
    at Qe.<anonymous> (visEngine.jsx:1154:38)
    at Generator.next (<anonymous>)
    at 188.b5f35900.chunk.js:29:17517
    at new Promise (<anonymous>)
    at bi (188.b5f35900.chunk.js:29:17337)
    at Qe.setInnerHTML (visEngine.jsx:1117:42)
    at Qe.<anonymous> (visEngine.jsx:1183:29)
    at Generator.next (<anonymous>)
    at o (188.b5f35900.chunk.js:29:17375)
(anonym) @ VM301:4
(anonym) @ visEngine.jsx:1154
(anonym) @ 188.b5f35900.chunk.js:29
bi @ 188.b5f35900.chunk.js:29
setInnerHTML @ visEngine.jsx:1117
(anonym) @ visEngine.jsx:1183
o @ 188.b5f35900.chunk.js:29
VM302:184 Version coronavirus-statistics: 0.1.0
VM305:402 Version eventlist: 1.2.2
VM308:75 Version vis-history: 1.0.0
VM310:110 Version vis-jqui-mfd: 1.0.12
VM312:645 Metro version: "1.2.0"
VM313:97 Version vis-plumb: 1.0.0
kodi.js:48 Version kodi: 2.0.0
musiccast.js:38 Version musiccast: 0.0.2
players.js:55 Version players: 0.1.0
rssfeed.js:26 Version rssfeed: 0.0.1
trashschedule.js:152 Version trashschedule: 2.1.0
:8082/vis-2-beta/adapter/rssfeed/words.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
info.js:84 Uncaught SyntaxError: Unexpected end of input
lib.min.js:44 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
lib.min.js:44 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
materialdesign.js:33 Version vis-materialdesign: 0.5.94
widgets.min.js:1 vis-materialdesign: vibration supported by device: 'true'
customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
visUtils.jsx:848 Cannot load i18n "openweathermap": Error: Cannot load openweathermap from ./widgets/openweathermap/customWidgets.js
visUtils.jsx:868 Error: Cannot load openweathermap from ./widgets/openweathermap/customWidgets.js
    at d.onerror (visUtils.jsx:738:43)
(anonym) @ visUtils.jsx:868
customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
visUtils.jsx:848 Cannot load i18n "vis2gaugeWidgets": Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
3visUtils.jsx:868 Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
    at d.onerror (visUtils.jsx:738:43)
(anonym) @ visUtils.jsx:868
widgets.min.js:1 vis-materialdesign: click audio file '/vis.0/materialdesign-widgets-click-sound.mp3' not exists!
(anonym) @ widgets.min.js:1
visUtils.jsx:848 Cannot load i18n "vis2materialWidgets": Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
13visUtils.jsx:868 Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    at d.onerror (visUtils.jsx:738:43)
(anonym) @ visUtils.jsx:868
visUtils.jsx:848 Cannot load i18n "vis2energyWidgets": Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js
4visUtils.jsx:868 Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js
    at d.onerror (visUtils.jsx:738:43)
(anonym) @ visUtils.jsx:868
instrument.ts:129 sentry initialized for vis-materialdesign
instrument.ts:129 [2023-01-06T10:10:07.145Z] +SUBSCRIBE: vis-inventwo.0.CSS.Text
instrument.ts:129 [2023-01-06T10:10:07.164Z] +SUBSCRIBE: backitup.0.history.json
instrument.ts:129 [2023-01-06T10:10:07.170Z] +SUBSCRIBE: backitup.0.oneClick.ccu
instrument.ts:129 [2023-01-06T10:10:07.176Z] +SUBSCRIBE: backitup.0.oneClick.iobroker
instrument.ts:129 [2023-01-06T10:10:07.179Z] +SUBSCRIBE: backitup.0.history.ccuLastTime
instrument.ts:129 [2023-01-06T10:10:07.185Z] +SUBSCRIBE: backitup.0.info.ccuNextTime
instrument.ts:129 [2023-01-06T10:10:07.190Z] +SUBSCRIBE: backitup.0.history.iobrokerLastTime
instrument.ts:129 [2023-01-06T10:10:07.196Z] +SUBSCRIBE: backitup.0.info.iobrokerNextTime
instrument.ts:129 [2023-01-06T10:10:07.222Z] +SUBSCRIBE: backitup.0.history.ccuSuccess
instrument.ts:129 [2023-01-06T10:10:07.226Z] +SUBSCRIBE: backitup.0.history.iobrokerSuccess
instrument.ts:129 [2023-01-06T10:10:07.303Z] +SUBSCRIBE: backitup.0.output.line
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE konnte nicht geladen werden
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://localhost:8082/vis-2-beta/static/js/313.3238287f.chunk.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE konnte nicht geladen werden
instrument.ts:129 [waitForWidgets] stop waiting for vis widgets after 500 retries
(anonym) @ instrument.ts:129
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87
setTimeout (async)
(anonym) @ trycatch.ts:119
waitForWidgets @ widgets.min.js:1
(anonym) @ widgets.min.js:1
sentryWrapped @ helpers.ts:87`

Edit:

`
web.0 | 2023-01-22 09:20:31.578 | error | 21 - at http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1896:35619
-- | -- | -- | --
web.0 | 2023-01-22 09:20:31.578 | error | 20 - at p3 (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1894:3299)
web.0 | 2023-01-22 09:20:31.577 | error | 19 - at Ca (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1896:38308)
web.0 | 2023-01-22 09:20:31.577 | error | 18 - at G0 (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1896:41846)
web.0 | 2023-01-22 09:20:31.576 | error | 17 - at on (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1896:42513)
web.0 | 2023-01-22 09:20:31.576 | error | 16 - at Vc (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1896:32242)
web.0 | 2023-01-22 09:20:31.575 | error | 15 - at _8 (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1896:32751)
web.0 | 2023-01-22 09:20:31.574 | error | 14 - at h8 (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1896:32982)
web.0 | 2023-01-22 09:20:31.574 | error | 13 - at Ue.componentDidMount (http://localhost:8082/vis-2-beta/static/js/188.b5f35900.chunk.js:16:53862)
web.0 | 2023-01-22 09:20:31.573 | error | 12 - at Ue.renderWidget (http://localhost:8082/vis-2-beta/static/js/188.b5f35900.chunk.js:16:70324)
web.0 | 2023-01-22 09:20:31.573 | error | 11 - at e.view.e.template (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1401:47)
web.0 | 2023-01-22 09:20:31.572 | error | 10 - at Function.renderAs (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1465:39)
web.0 | 2023-01-22 09:20:31.572 | error | 9 - at Function.renderTo (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
web.0 | 2023-01-22 09:20:31.571 | error | 8 - at r (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
web.0 | 2023-01-22 09:20:31.570 | error | 7 - at Function.frag (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
web.0 | 2023-01-22 09:20:31.570 | error | 6 - at Function.hookup (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
web.0 | 2023-01-22 09:20:31.569 | error | 5 - at a.each (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-01-22 09:20:31.569 | error | 4 - at HTMLSpanElement.<anonymous> (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
web.0 | 2023-01-22 09:20:31.567 | error | 3 - at Object.eval (i-vis-valuelist.js:47:87)
web.0 | 2023-01-22 09:20:31.566 | error | 2 - at Object.valueList (http://localhost:8082/vis-2-beta/widgets/vis-inventwo/js/vis-inventwo.js:5368:3)
web.0 | 2023-01-22 09:20:31.566 | error | 1 - at createList (http://localhost:8082/vis-2-beta/widgets/vis-inventwo/js/vis-inventwo.js:5390:19)
web.0 | 2023-01-22 09:20:31.565 | error | 0 - TypeError: listTxt.split is not a functionTypeError: listTxt.split is not a function
web.0 | 2023-01-22 09:20:31.564 | error | can't render i-vis-valuelist w01079 on "ECharts_Strom":
web.0 | 2023-01-22 09:20:25.830 | error | Error: can't create states object for 0_userdata.0.echarts.range(TypeError: listTxt.split is not a function): "TypeError: listTxt.split is not a function\n at createList (http://localhost:8082/vis-2-beta/widgets/vis-inventwo/js/vis-inventwo.js:5390:19)\n at a.<anonymous> (http://localhost:8082/vis-2-beta/widgets/vis-inventwo/js/vis-inventwo.js:5365:4)\n at t.dispatch (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:272:72)\n at Object.stop (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:720:96)\n at a._setAttrs (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:972:28)\n at a.attr (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:894:29)\n at http://localhost:8082/vis-2-beta/static/js/188.b5f35900.chunk.js:29:21017\n at T.<anonymous> (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1932:31019)\n at Generator.next (<anonymous>)\n at g (http://localhost:8082/vis-2-beta/static/js/main.c31a7d5a.js:1:564)"
`

**Comment by jh2k19** [comment]
Ich würde gerne für ein Re-Design die Vis2 und die neuen Widgets einsetzen. Vis2 könnte nach ersten Versuchen in der aktuellen Version grundlegend dafür verwendet werden. Klar, dass da noch einiges zu machen ist und mit der Zeit bestimmt auch kommt. Aber leider bekomme ich gerade die neuen Widgets nicht zum laufen. Diese hätte ich schon gerne gleich verwendet. Die Adapter sind im Admin eingebunden erscheinen aber nicht im Vis-Editor. Habe erfolglos schon so einiges probiert. Wäre toll, wenn sich bezüglich der neuen Widgets bald was tut.

**Comment by sigi2345** [comment]
> Ich würde gerne für ein Re-Design die Vis2 und die neuen Widgets einsetzen. Vis2 könnte nach ersten Versuchen in der aktuellen Version grundlegend dafür verwendet werden. Klar, dass da noch einiges zu machen ist und mit der Zeit bestimmt auch kommt. Aber leider bekomme ich gerade die neuen Widgets nicht zum laufen. Diese hätte ich schon gerne gleich verwendet. Die Adapter sind im Admin eingebunden erscheinen aber nicht im Vis-Editor. Habe erfolglos schon so einiges probiert. Wäre toll, wenn sich bezüglich der neuen Widgets bald was tut.

Ja, wäre schön, aber @GermanBluefox ist derzeit im Urlaub.

**Comment by jh2k19** [comment]
Wohlverdient. Urlaub darf und muss auch mal sein. 
Danke für die Info.

**Comment by csicom** [comment]
vis-2-widgets-material@0.2.0 funktioniert bei mir
Die anderen werden bei mir auch nicht angezeigt

**Comment by jh2k19** [comment]
Was wird wo angezeigt?
Die Vis-2-Widgets im Vis-2-Beta Editor oder der Adapter in den Instanzen?

**Comment by csicom** [comment]
Auch im Editor. Die Version 0.2.1 bei den Adaptern entfernen und die Version 0.2.0 installieren.

**Comment by jh2k19** [comment]
Danke für die Info. Kann das mit der 0.2.0 so bei mir allerdings nicht bestätigen. In der Regel versuche ich immer ältere Versionen eines Adapters, wenn der aktuelle nicht geht. So habe ich auch vor einigen Tagen die Version 0.1.2 und 0.1.5 erfolglos versucht. Selbstverständlich habe ich mich versichert , dass die Installation sauber weg ist. Anschließend auch ein kompletter neustart der ioB Installation. Evtl. liegt es auch an meiner Umgebung (Proxmox), wobei die Fehlermeldung aber auf fehlende Dateien im Bereich des Adapterpfades (www) hinweist. Irgend eine Konstelation wird allerding ja mal funktioniert haben. Die Bilder im Forum (https://forum.iobroker.net/topic/60398/test-adapter-vis-2-0-alpha) von Apollon77 und Bluefox sind ja nicht von alleine entstanden.

**Comment by PEPITO82** [comment]
Gleicher Fehler bei mir.
Wie kann Version 0.2.0 installiert werden?

**Comment by jh2k19** [comment]
Einfach in einer Konsole eingeben:

cd /opt/iobroker
npm i iobroker.vis-2-widgets-material@0.2.0
iob upload vis-2-widgets-material

1. der Pfad wo die Installationsdatei hin muss
2. @0.2.0 ist die Version es geht auch @latest für die aktuellste
3. der Upload installiert den Adapter dann in ioB

Ich hoffe, dass ist soweit alles klar.  Sonst bitte nochmals melden.

**Comment by sigi2345** [comment]
Funktioniert jetzt nach Update der Widgets.

![Screenshot (5414)](https://user-images.githubusercontent.com/41079106/221587844-528d0719-542b-40a6-abe6-e5a937928992.png)

**Comment by Feuer-sturm** [comment]
New vis2 widgets are available. Issue closed
