### ISSUE TITLE
v2.x Add function shift+mark for items / elements

### ISSUE THREAD

**Issue by dos1973** [ioBroker/ioBroker.vis#583]
**Describe the bug**  
Previously, multiple objects could be selected using Shift+left mouse button.
Hold Shift and then select all widgets to apply specific actions to the selection.

also in v1 it was also possible to draw a frame with the mouse and hold down the left mouse button, everything contained in it was marked for further processing

**Expected behavior**  
please enable this feature agian for easy selection of items /widgets

**Screenshots & Logfiles**  
[iobroker forum](https://forum.iobroker.net/topic/60398/test-adapter-vis-2-0-alpha/77?_=1669663252664)

**Versions:**  
v2.08

**Comment by Feuer-sturm** [comment]
@dos1973 I try to reproduce your issue.
I created an empty page and added some widgets "Zeichenfolge"
Selecting with Shift + left mouse button or Strg + left mouse button is possible on my system.
Marking an area and selecting elements as well
![Animation1](https://user-images.githubusercontent.com/25422320/204371884-c29b9dd2-9bdd-4e57-99aa-79896a64ab30.gif)

Did you use a new project or an imported vis1 project for testing?

**Comment by dos1973** [comment]
new project.
could this be all about mac.
i tested in safari aswell on chrome ?!

**Comment by Feuer-sturm** [comment]
@dos1973 Can you please check this issue with current vis version?
