### ISSUE TITLE
v2.x enable copy/ paste of widgets

### ISSUE THREAD

**Issue by dos1973** [ioBroker/ioBroker.vis#585]
**Describe the bug**  
copy / paste (strg-c/ v) of one or more widgets are not possible

**Expected behavior**  
copy / paste :-)

**Versions:**  
v2.08

**Comment by Feuer-sturm** [comment]
@dos1973 Is it possible to copy paste one element with strg+c  strg+v?
On my system I can copy / pase one element.

If I select two elemts and copy them the same way only one new element will be created
![Animation3](https://user-images.githubusercontent.com/25422320/204374774-1509888a-d92a-40db-b733-65d8d1966c36.gif)

**Comment by dos1973** [comment]
no, I can't copy and paste one alone or multiple with ctrl-c /v. 
Just copy with the right mouse button and paste it again with the right mouse button. 
Keyboard shortcuts don't work.

Im MAC OSX User maybe thats the issue ;-)

**Comment by Feuer-sturm** [comment]
> Im MAC OSX User maybe thats the issue ;-)

Good hint. I am using Firefox and Chrome with Windows

**Comment by Feuer-sturm** [comment]
@dos1973 Please check with vis2-beta v2.0.10

**Comment by dos1973** [comment]
unfortunately v2.10 didn't start... only white spinning iobroker

**Comment by Feuer-sturm** [comment]
@dos1973 Please check with vis 2.0.16

**Comment by Feuer-sturm** [comment]
@dos1973 Can you please check if this issue is fixed?
