### ISSUE TITLE
VIS-2 Pfeil zum Aufklappen der Navigation verschwindet bei dunklem Widget

### ISSUE THREAD

**Issue by Chaot1** [ioBroker/ioBroker.vis#586]
Wenn ich ein Widget in der linken obersten Ecke platziere das einen schwarzen Hintergrund hat verschindet der kleine Pfeil zum Aufklappen der Navigation.
Navigation offen
![vis2-4](https://user-images.githubusercontent.com/37418118/204394938-ddbe77a9-535d-4e02-b636-ed817df14549.jpg)
Navigation zugeklappt
![vis2-5](https://user-images.githubusercontent.com/37418118/204395033-fc0a30e7-88c3-45c6-96ce-a75101f84fef.jpg)
Widget responsive positioniert links oben
![vis2-6](https://user-images.githubusercontent.com/37418118/204395097-3e656de8-352c-4687-a734-d1ec7d062277.jpg)
Der Pfeil ist nur deshalb noch zu sehen, weil das Widget im Markiermodus eine andere Farbe hat.

**Comment by Feuer-sturm** [comment]
Hello @Chaot1  , please check with 2.0.10

**Comment by Feuer-sturm** [comment]
This is how it looks like with vis 2.0.23
![grafik](https://user-images.githubusercontent.com/25422320/227717614-327681ab-2dd0-4f18-bfcf-6a6c226803ca.png)

From my point of view it is ok.
