### ISSUE TITLE
VIS2: Start nach Installation nicht

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.vis#587]
Ich habe die VIS2 heute morgen mit den Befehlen aus dem Forumspost installiert. Wenn ich die Admin Oberfläche aufrufe sieht das so aus. Es fehlen viele Seiten meiner UI und ich kann nix machen.
Was könnte da schiefgegangen sein?
![2022-11-29_09-41-42](https://user-images.githubusercontent.com/45976162/204482361-0bdfbb48-1ff3-468f-b83f-0b4ae5ca36b1.png)

**Comment by Apollon77** [comment]
Was bedeutet "seiten fehlen" ? Mal oben auf "Seiten verwalten" bzw das "+" geklickt?

**Comment by Feuer-sturm** [comment]
@Horgul123 ich hatte es bei mir auch, dass mein Projekt beim ersten installieren nicht übernommen wurde.

Erste Workaround für dich: vis1 Projekt exportieren und in vis 2 importieren. 

Dennoch sollten wir hier einmal schauen,  warum die Übernahme von vis 1 nach 2 nicht funktioniert

**Comment by Horgul123** [comment]
So.... 

@Apollon77 : Danke für den Hinweis. Die Seiten waren ausgeblendet (ist natürlich etwas verwirrend ;) ). Allerdings sind sie "leer" Er zeigt nicht mehr an als im Screenshot oben.

@Feuer-sturm : Ok. Werde ich mal probieren. Ich lösche mal alles in der VIS2..... Danke für den Tipp

**Comment by Horgul123** [comment]
So... Import aus VIS1 hat geklappt, Allerdings ist ein bearbeiten nicht wirklich möglich, die Inhalte werden teilweise gar nicht angezeigt und wie ich in der horizontalen Liste der Seiten nach links und rechts scrollen kann, hab ich auch noch nicht rausgefunden.

Aber vor allem, dass der Inhalt der Seiten nicht angezeigt wird, ist ein Problem. Keine Ahnung wieso das so ist

**Comment by Feuer-sturm** [comment]
@Horgul123 Kannst du bitte einmal dein issue mit vis2 v2.0.18 nachtesten ob das Problem noch besteht?

**Comment by Horgul123** [comment]
Leider immer noch das Gleiche :(

**Comment by Feuer-sturm** [comment]
@Horgul123 Bitte einmal auf den Adapter vis-2 umsteigen (vis-2-beta wird nicht als Adapter fortgeführt, siehe https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta)
Wenn das issue weiterhin besteht können, können wir das issue hier gerne wieder öffnen.
