### ISSUE TITLE
Tippfehler widget static image

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.vis#59]
Ein Text im Widget 'static image', Sektion 'Allgemein' ist falsch:
'Streken' => 'Strecken'

Der Titel im Widget 'static image', Sektion 'CSS Shatten und Abstand' ist falsch:
'CSS Shatten und Abstand' => 'CSS Schatten und Abstand'

Der Titel im Widget 'static image', Sektion 'CSS Border (border-...)' ist nicht übersetzt.
'CSS Border (border-...)' -Vorschlag-> 'CSS Ränder (border-...)'
[Die betrifft mehrere Widgets...]

**Comment by GermanBluefox** [comment]
Muss in 0.5.3 gefixt sein.

**Comment by ykuendig** [comment]
Ist so. Danke
