### ISSUE TITLE
Vis2 keine Übernahme des Hindergrund bei einem View in widget

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.vis#590]
Vis selbst läuft mit dem eingestellten Theme dark-hive, sowie auch in der View, diesbezüglich wird ein **View in widget** ebenfalls mit schwarzem Hintergrund angezeigt, auch wenn man in diesem View die Hintergrundklasse auf `keiner` stellt. Dies wird erst übernommen und korrekt angezeigt, sobald man irgend etwas bei `backround` reinschreibt
![image](https://user-images.githubusercontent.com/41550245/204541196-ee9d090d-4ae3-4788-aa7a-00365a25f170.png)
ursprünglich eingestellt in Vis1.x
![image](https://user-images.githubusercontent.com/41550245/204545428-ce7f21c4-75cd-46c6-8313-1bda28c03968.png)

Edit:
dazu kommt die Frage, was ist da der Unterschied?
![image](https://user-images.githubusercontent.com/41550245/204543015-0b6f1c48-c165-4b44-9784-ba27231bbf65.png)

**Comment by GermanBluefox** [comment]
Ich habe "keine" auf "nicht definiert" geändert. D.h. es wird gar kein background gesetzt und
Kein Hintergrund auf `{background: none !important}` geändert. D.h. es wird extra kein Background (auch wenn irgendwo über Klassen definiert wird) angezeigt. 

nicht definiert. Es wird background von Thema genommen:
![image](https://user-images.githubusercontent.com/4582016/204797926-a4e8041b-6b64-404a-879d-d7e6321eee6f.png)

Kein background: 
![image](https://user-images.githubusercontent.com/4582016/204798166-5eafd5fb-cd9f-4ea2-9d5a-9a4760b7bcc9.png)

**Comment by Feuer-sturm** [comment]
@crunchip77 Please check with vis 2.0.16

**Comment by crunchip77** [comment]
> @crunchip77 Please check with vis 2.0.16

Mit meinem main Projekt alles i.o, wollte es aber erst noch bei meinem anderen Projekt prüfen

**Comment by crunchip77** [comment]
alles in Ordnung und funktioniert wie gewünscht
