### ISSUE TITLE
vis2x.: Filemanager does not accept button "OK" (basic-image widget)

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis#591]
**Describe the bug**  
Filemanager does not accept button "OK" in "basic-image widget" and "jqui ctrl - Icon state widget". Picture can't be choosen.

**Screenshots & Logfiles**  
![Animation](https://user-images.githubusercontent.com/69053781/204582593-74104334-af54-4673-bc76-6721c99c7a4e.gif)

**Versions:**  
- Adapter version: ioBroker.vis v2.0.9
- JS-Controller version: v4.0.23
- Node version: v16.18.1
- Operating system: ioBroker.docker v7.2.1
- Browser: Google Chrome v107.0.5304.122 (64-Bit)

**Comment by Feuer-sturm** [comment]
Hello @ice987987 , please check with 2.0.10

**Comment by Feuer-sturm** [comment]
is fixed with 2.0.10
