### ISSUE TITLE
vis2x.: Input field CSS too small

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis#592]
**Describe the bug**  
Input field CSS too small

**Expected behavior**  
CSS input field has same height as screen.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/69053781/204587637-752dc019-5538-4e22-b721-f2af7a0037b2.png)

**Versions:**  

- Adapter version: ioBroker.vis v2.0.9
- JS-Controller version: v4.0.23
- Node version: v16.18.1
- Operating system: ioBroker.docker v7.2.1
- Browser: Google Chrome v107.0.5304.122 (64-Bit)

**Comment by Feuer-sturm** [comment]
Hello @ice987987 , please check with 2.0.10

**Comment by ice987987** [comment]
works as expected in v2.0.10
thank you very much!
