### ISSUE TITLE
VIS2.x: Editor GUI zeigt <Seite ...> statt <Projekt ...> 

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.vis#595]
Ein Bild sagt mehr als 1000 Worte:

![image](https://user-images.githubusercontent.com/59795191/204811277-7e90dbc3-42cd-4686-8dbf-a8f7b5c5dad1.png)

LG Uwe

**Comment by Feuer-sturm** [comment]
@Haifeif bitte vis Version ergänzen

**Comment by Feuer-sturm** [comment]
Is fixed with vis 2.0.16
Now the name of the project is shown and you can click on the name to manage the projects.
![grafik](https://user-images.githubusercontent.com/25422320/208527035-8fdea894-628d-4f69-8a89-ddfb8944239f.png)
