### ISSUE TITLE
Themenwahl nicht/schlecht möglich

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.vis#60]
Im Menü 'Setup'-'Thema' können nicht alle Themen ausgewählt werden.
Einige gehen schlecht, andere gar nicht.

**Comment by GermanBluefox** [comment]
Muss in 0.5.3 gefixt sein.

**Comment by ykuendig** [comment]
0.5.3 geht bei mir leider gar nicht mehr...

**Comment by ykuendig** [comment]
Habe in 0.5.5 probiert. Da ist es gut. Danke.
