### ISSUE TITLE
License is for other adapter "iobroker.vis". Expected "iobroker.vis-2-beta"

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis#606]
**Describe the bug**  
In Log file the error 
`"License is for other adapter "iobroker.vis". Expected "iobroker.vis-2-beta"" `
is shown
I copied my vis1 licence from vis1 instance into vis-2-beta as well

Currently it is not possible to order here https://iobroker.net/www/account/licenses a vis2 licence

Is this just a "warning" or are there any restriction without a valid vis2 licence?

If there is no licence in vis-2-beta in log file the following error is shown:
```
vis-2-beta.0
	2022-12-01 22:03:17.124	error	No license found for vis. Please get one on https://iobroker.net !
vis-2-beta.0
	2022-12-01 22:03:17.019	info	starting. Version 2.0.10 in /opt/iobroker/node_modules/iobroker.vis-2-beta, node: v16.18.1, js-controller: 4.0.23
```

**Expected behavior**  
vis1 licence is compatible with vis2 or vis2 licence can be generated under iobroker.net

**Versions:**  
 - Adapter version: vis-2-beta v2.0.10

**Comment by github-ps1304** [comment]
same here and Vis 2 showing a white screen- 

Debug info:

`

-beta.0 | 2022-12-02 13:34:14.911 | error | License is for other adapter "iobroker.vis". Expected "iobroker.vis-2-beta"
-- | -- | -- | --
vis-2-beta.0 | 2022-12-02 13:34:14.529 | info | starting. Version 2.0.10 in /opt/iobroker/node_modules/iobroker.vis-2-beta, node: v16.18.1, js-controller: 4.0.23
vis-2-beta.0 | 2022-12-02 13:34:06.666 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
vis-2-beta.0 | 2022-12-02 13:34:06.665 | info | terminating
vis-2-beta.0 | 2022-12-02 13:34:06.162 | info | Got terminate signal TERMINATE_YOURSELF

`

Log entry:

> 

vis-2-beta.0 | 2022-12-02 09:48:16.217 | error | License is for other adapter "iobroker.vis". Expected "iobroker.vis-2-beta"
-- | -- | -- | --
vis-2-beta.0 | 2022-12-02 09:43:55.045 | error | No license found for vis. Please get one on https://iobroker.net !
vis-2-beta.0 | 2022-12-02 09:43:09.662 | error | No license found for vis. Please get one on https://iobroker.net !
vis-2-beta.0 | 2022-12-02 09:43:04.448 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/jquery-ui.min.css: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.446 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_cd0a0a_256x240.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.444 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_888888_256x240.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.442 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_454545_256x240.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.439 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_2e83ff_256x240.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.434 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_222222_256x240.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.433 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_highlight-soft_75_cccccc_1x100.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.431 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_95_fef1ec_1x400.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.427 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_75_e6e6e6_1x400.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.426 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_75_dadada_1x400.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.424 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_65_ffffff_1x400.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.421 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_55_fbf9ee_1x400.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.420 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/jquery-ui.theme.min.css: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.418 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/jquery-ui.structure.min.css: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.416 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/jquery-ui.min.css: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.415 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/images/ui-icons_ffffff_256x240.png: DB closed
vis-2-beta.0 | 2022-12-02 09:43:04.413 | error | Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/images/ui-icons_cccccc_256x240.png: DB closed

**Comment by anno171986** [comment]
> same here and Vis 2 showing a white screen-
> 
> Debug info:
> 
> `
> -beta.0 	2022-12-02 13:34:14.911 	error 	License is for other adapter "iobroker.vis". Expected "iobroker.vis-2-beta"
> vis-2-beta.0 	2022-12-02 13:34:14.529 	info 	starting. Version 2.0.10 in /opt/iobroker/node_modules/iobroker.vis-2-beta, node: v16.18.1, js-controller: 4.0.23
> vis-2-beta.0 	2022-12-02 13:34:06.666 	info 	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
> vis-2-beta.0 	2022-12-02 13:34:06.665 	info 	terminating
> vis-2-beta.0 	2022-12-02 13:34:06.162 	info 	Got terminate signal TERMINATE_YOURSELF
> 
> `
> 
> Log entry:
> 
> > 
> 
> vis-2-beta.0 	2022-12-02 09:48:16.217 	error 	License is for other adapter "iobroker.vis". Expected "iobroker.vis-2-beta"
> vis-2-beta.0 	2022-12-02 09:43:55.045 	error 	No license found for vis. Please get one on https://iobroker.net !
> vis-2-beta.0 	2022-12-02 09:43:09.662 	error 	No license found for vis. Please get one on https://iobroker.net !
> vis-2-beta.0 	2022-12-02 09:43:04.448 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/jquery-ui.min.css: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.446 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_cd0a0a_256x240.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.444 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_888888_256x240.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.442 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_454545_256x240.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.439 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_2e83ff_256x240.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.434 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-icons_222222_256x240.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.433 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_highlight-soft_75_cccccc_1x100.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.431 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_95_fef1ec_1x400.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.427 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_75_e6e6e6_1x400.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.426 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_75_dadada_1x400.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.424 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_65_ffffff_1x400.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.421 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-light/images/ui-bg_glass_55_fbf9ee_1x400.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.420 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/jquery-ui.theme.min.css: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.418 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/jquery-ui.structure.min.css: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.416 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/jquery-ui.min.css: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.415 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/images/ui-icons_ffffff_256x240.png: DB closed
> vis-2-beta.0 	2022-12-02 09:43:04.413 	error 	Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/lib/css/themes/jquery-ui/custom-dark/images/ui-icons_cccccc_256x240.png: DB closed

For me the same!

**Comment by Feuer-sturm** [comment]
For information
In this post https://forum.iobroker.net/topic/60822/cloud-vis-offline-weihnachtsangebot-2022 Bluefox mentioned that current vis1 offline licence will be valid for vis2 as well

**Comment by AnTri** [comment]
For me the same. License can be checked with positive result, but in the log comes the error message:

License is for other adapter "iobroker.vis". Expected "iobroker.vis-2-beta".

**Comment by Apollon77** [comment]
All good, simpy ignore that error for now

**Comment by Feuer-sturm** [comment]
not relevant any more.
vis-2-beta will stop, current development will continue in vis-2 adapter
Licencs for vis-2 see: https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta
