### ISSUE TITLE
Button for factory reset of vis2 during testing phase

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis#607]
**Is your feature request related to a problem? Please describe.**

Users are importing there VIS1 project into current vis2 versions.
If a vis project is imported and vis2 is updated to newest testing version it might happen that vis2 can not be access becaus of different issue.
If vis2 editor can not be accesses any more (black/white screen) it is not possible to remove earlier imported projects which vis trys to load.
In this case testing with current vis version is not possible any more

**Describe the solution you'd like**

Integrate a (temporary) button in vis-2-beta instance settings to do a factory reset of vis.
Factory reset = delete all vis projects and create a default vis2 project

**Comment by ice987987** [comment]
is deleting the corresponding folder in ioBroker Admin -> Files -> vis-2-beta.0 -> [Project] possibly a solution to clean up the (old) projects?

**Comment by Feuer-sturm** [comment]
@ice987987 It seems to be a workaround. I simply deleted all projects in the Admin File Explorer under the path you mentioned. After refreshing the Vis Editor and creating a new page plus a new refresh of the Vis Editor, the Project Explorer opens again and has created an "undefined" project.
