### ISSUE TITLE
vis2.x: toolbar gets too big/high if many widgets are selected

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis#609]
**Describe the bug**  
Toolbar gets too big if many widgets are selected

**To Reproduce**  
select some widgets:

**Expected behavior**  
Toolbar high does not change

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/69053781/205311575-0d1a1dc1-c61f-4274-aafe-1fe011981c9d.png)

**Versions:**  
- Adapter version: ioBroker.vis v2.0.10
- JS-Controller version: v4.0.23
- Node version: v16.18.1
- Operating system: ioBroker.docker v7.2.1
- Browser: Google Chrome v108.0.5359.72 (Offizieller Build) (64-Bit)

**Comment by Feuer-sturm** [comment]
@ice987987 With vis 2.0.23 this is ok from my point of view
![grafik](https://user-images.githubusercontent.com/25422320/227719456-715ff026-a96a-40dc-a120-9ec5089d5984.png)

**Comment by ice987987** [comment]
works as expected in v2.0.23
thank you very much!
