### ISSUE TITLE
Widget navigation Views bar

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.vis#61]
Das Widget kann sich die Anzahl Knöpfe nicht merken.
Wird zum Beispiel die Knopfzahl auf 4 reduziert, so werden in der Ansicht (oder auch nach neu laden des Editors wieder 8 Knöpfe angezeigt. (Ich habe zZ 8 Views im Test)

**Comment by GermanBluefox** [comment]
Kann dein Problem nicht reproduzieren. Kannst du deine Views mir schicken? dogafox at gmail.com

**Comment by ykuendig** [comment]
Ein andere Nutzer hat auch Probleme damit:
http://forum.iobroker.net/viewtopic.php?f=30&t=802&sid=0f6a6ad4b6ecd76778fc28491895dd23
Zudem habe ich herausgefunden, dass die Probleme erst auftauchen, wenn das Widget in mehreren Views angezeigt wird. Das ist zwar quasi normal, hast Du aber ev. beim testen nicht gemacht...

**Comment by GermanBluefox** [comment]
Bitte mit 0.5.7 testen

**Comment by ykuendig** [comment]
0.5.7 startet nicht. -> 0.5.8 startet, teste nun.

**Comment by ykuendig** [comment]
Grundsätzlich ist das Verhalten gut. Die Werte werden gespeichert und auch behalten; sowohl in einer View, wie auch in mehreren. Leider werden aber beim ersten Einfügen nicht mehr die vorhandenen Views ausgefüllt. Ist das Absicht?

**Comment by GermanBluefox** [comment]
Ne. So ist das nicht gewollt. Muss fixen
1 Июн 2015 г. 8:24 пользователь "ykuendig" notifications@github.com
написал:

**Comment by GermanBluefox** [comment]
Bitte testen

**Comment by ykuendig** [comment]
Jetzt ist es noch einmal anders:
Vorhanden Views werden ausgefüllt und gespeichert. Man kann auch die Anzahl der Tabs einstellen. Aber wenn 'Zeige in Views' geändert wird, werden die default Werte erneut geladen und auch die Anzahl Tabs überschrieben.

**Comment by GermanBluefox** [comment]
Wie ist das in 0.6.2 ?

**Comment by ykuendig** [comment]
Hatte noch keine Zeit die Updates zu machen. Muss das am Wochenende noch testen...
