### ISSUE TITLE
vis2.x Import von Projekt nicht möglich

### ISSUE THREAD

**Issue by Knallix** [ioBroker/ioBroker.vis#617]
**Describe the bug**  
Projekt ZIP wird nicht importiert.
Ich drücke auf den "Importieren" Button und es passiert nichts !

**To Reproduce**  
Import Projekt 
![Import 2022-12-09 234034](https://user-images.githubusercontent.com/42406048/206808975-4609ece6-f2c8-4176-bbf9-53c071ca65ee.JPG)

**Screenshots & Logfiles**  
![Console 2022-12-09 233942](https://user-images.githubusercontent.com/42406048/206808933-4f7c662f-d6f1-41b3-b2bb-b4edf98ccdbc.JPG)

**Versions:**  
 - Adapter version: V2.0.10
![image](https://user-images.githubusercontent.com/42406048/206809091-6a9f918b-bb30-4ae5-83dd-cc72907806d1.png)

 - Operating system: Debian <os-name>

**Comment by Feuer-sturm** [comment]
Perhaps there is a relation to #604 

@Knallix were you able to import your project in VIS 2 2.0.9?

**Comment by Knallix** [comment]
> Perhaps there is a relation to #604
> 
> @Knallix were you able to import your project in VIS 2 2.0.9?

I only got in here at VIS 2.0.10.
Unfortunately didn't have the opportunity.
Should I test it again with VIS 2.0.9?

**Comment by Feuer-sturm** [comment]
@Knallix if you like you can try.

**Comment by Knallix** [comment]
@Feuer-sturm bin auf 2.0.9 zurück und nochmal neu Installiert auf 2.0.10. Keine Besserung
@Feuer-Sturm am back to 2.0.9 and re-installed on 2.0.10. No improvement

**Comment by Feuer-sturm** [comment]
@Knallix my suggestion was to downgrade to 2.0.9 and then try if you can Import you project and check if this works.

**Comment by Knallix** [comment]
Didn't make any change. At least the import is running now
