### ISSUE TITLE
VIS2-beta is not starting

### ISSUE THREAD

**Issue by shelly20222** [ioBroker/ioBroker.vis#624]
The instance is red after installing:

![grafik](https://user-images.githubusercontent.com/119663882/210060694-36ad5924-4f2a-4b2d-89db-f8e4102ab232.png)

<html><body>

vis-2-beta.0 | 247675 | 2022-12-30 11:27:17.184 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | -- | --
vis-2-beta.0 | 247675 | 2022-12-30 11:27:17.182 | info | terminating
vis-2-beta.0 | 247675 | 2022-12-30 11:27:16.674 | error | Exception-Code:  ENOENT: ENOENT: no such file or directory, scandir  '/opt/iobroker/node_modules/iobroker.vis-2-beta/node_modules/'
vis-2-beta.0 | 247675 | 2022-12-30 11:27:16.673 | error | Error: ENOENT: no such file or directory, scandir '/opt/iobroker/node_modules/iobroker.vis-2-beta/node_modules/'     at Object.readdirSync (node:fs:1438:3)     at collectWidgetSets (/opt/iobroker/node_modules/iobroker.vis-2-beta/main.js:396:19)     at /opt/iobroker/node_modules/iobroker.vis-2-beta/main.js:441:51     at Array.forEach (<anonymous>)     at readAdaptersList (/opt/iobroker/node_modules/iobroker.vis-2-beta/main.js:441:36)     at async buildHtmlPages (/opt/iobroker/node_modules/iobroker.vis-2-beta/main.js:666:25)     at async Object.main [as ready] (/opt/iobroker/node_modules/iobroker.vis-2-beta/main.js:804:5)
vis-2-beta.0 | 247675 | 2022-12-30 11:27:16.671 | error | unhandled  promise rejection: ENOENT: no such file or directory, scandir  '/opt/iobroker/node_modules/iobroker.vis-2-beta/node_modules/'
vis-2-beta.0 | 247675 | 2022-12-30 11:27:16.669 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
vis-2-beta.0 | 247675 | 2022-12-30 11:27:16.484 | info | vis license is OK.
vis-2-beta.0 | 247675 | 2022-12-30 11:27:16.231 | info | starting. Version 2.0.16 in /opt/iobroker/node_modules/iobroker.vis-2-beta, node: v16.19.0, js-controller: 4.0.24

Directory seems not to be there:
![grafik](https://user-images.githubusercontent.com/119663882/210061780-68d62fe7-5638-4e81-aa5a-abf0be5ab011.png)

**Comment by Feuer-sturm** [comment]
Start support in forum https://forum.iobroker.net/topic/60398/test-adapter-vis-2-0-alpha/269 to find out if it is an issue

**Comment by Feuer-sturm** [comment]
@shelly20222 What was the workaround to fix your problem temporary?

**Comment by shelly20222** [comment]
> @shelly20222 What was the workaround to fix your problem temporary?

I have created the directory: /opt/iobroker/node_modules/iobroker.vis-2-beta/**node_modules**/

**Comment by Feuer-sturm** [comment]
@shelly20222 Can you please recheck this issue with vis2 v2.0.18?
