### ISSUE TITLE
VIS-2-beta Link to View changes on loading

### ISSUE THREAD

**Issue by Telefisch** [ioBroker/ioBroker.vis#632]
**Describe the bug**  
I had two projects in my VIS (main and MagicMirror), before installing the beta.
Now these projects were converted to beta as expected.

In the Editor (Chrome Browser) I caould edit and run a page from the second project (MagicMirror).
The page, I worked on was named index, so I called it with the following link:
http://192.168.178.4:8082/vis-2-beta/?MagicMirror#index 

So far, so fine.
I also added that link to my multihost-slave, with chromium browser but it opened a view from the main project.
I tried to open the view from my pc on edge-browser and could see that short befor the view was loaded, the link has been transformed to http://192.168.178.4:8082/vis-2-beta/?MagicMirror#iPhone_Temperaturen, which is a view in the main project.
I normally called thview with http://192.168.178.4:8082/vis-2-beta/?main#iPhone_Temperaturen.

So I decided to change the name of the view to make it more unique.
I called it mirror_index, so I expected to open it with http://192.168.178.4:8082/vis-2-beta/?MagicMirror#mirror_index
The result, as I open the view directly out of the editor the adress is changed to http://192.168.178.4:8082/vis-2-beta/?MagicMirror#cameras, which is alphabetically the first view in that project.

I hope I could explain my problems.

**Expected behavior**  
Open the named view

**Versions:**  
 - Adapter version: 2.0.16
 - JS-Controller version: 4.0.24
 - Node version: 16.19.0
 - Operating system: Host: latest buanet, Multihost Slave: latest Bullseye, Editor: Windows 11 (Chrome and Edge)

**Comment by Feuer-sturm** [comment]
I think I have the same problem.
Vis 2.0.16

In vis2 I have to projects
- Main (which is an import from Vis 1.x)
- RESP_Haus (which is a new project created in Vis 2)

# Szenario 1
- Firefox Browser 108.0.1 (64-Bit)
- Open project RESP_Haus in Vis 2 Editor
- :heavy_check_mark: Start Runtime of Vis 2 and a new window opens with the correct project with the URL: http://192.168.178.77:8082/vis-2-beta/?Resp_Haus#Garage
- :heavy_check_mark: If I call the adress http://192.168.178.77:8082/vis-2-beta/?Resp_Haus# in Firefox browser it changes to http://192.168.178.77:8082/vis-2-beta/?Resp_Haus#Garage and the vis is loaded correctly

# Szenario 2
- Edge Browser Version 108.0.1462.54 (Offizielles Build) (64-Bit)
- Call Link http://192.168.178.77:8082/vis-2-beta/?Resp_Haus#Garage from project "RESP_Haus" in Edge Browser
- :x: The link changes to the following link http://192.168.178.77:8082/vis-2-beta/?Resp_Haus#00_Main and the content of the Main project is shown

# Szenario 3
- Chrome Browser Version 108.0.5359.125 (Offizieller Build) (64-Bit)
- Call Link http://192.168.178.77:8082/vis-2-beta/?Resp_Haus#Garage from project "RESP_Haus" in Chrome Browser
- Link changes to http://192.168.178.77:8082/vis-2-beta/?Resp_Haus#
- :x: Page will stay white and the following output is in the browser console


## Browser Konsole for Szenario 2
```
iobroker.vis-2-beta@2.0.16 using theme "colored"
main.c31a7d5a.js:657 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.c31a7d5a.js:657 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.c31a7d5a.js:657 Help us to create open source project with reactJS!
main.c31a7d5a.js:657 See you :)
socket.io.js:66 [2023-01-03T19:56:04.175Z] Try to connect
App.jsx:385 Cannot read project file vis-views.json: Not exists
(anonymous) @ App.jsx:385
VM22:75 Version vis-history: 1.0.0
VM24:110 Version vis-jqui-mfd: 1.0.12
VM26:45 Version vis-map: 1.0.3
VM27:645 Metro version: "1.2.0"
justgage.js:115 Version justgage: 1.0.2
trashschedule.js:152 Version trashschedule: 2.1.0
:8082/vis-2-beta/wid…/info/js/info.js:84 Uncaught SyntaxError: Unexpected end of input
lib.min.js:43 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
lib.min.js:43 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
materialdesign.js:33 Version vis-materialdesign: 0.5.9
customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
baseclient.ts:160 Uncaught (in promise) TypeError: t.update is not a function
    at t.captureSession (baseclient.ts:160:15)
    at K._sendSessionUpdate (313.3238287f.chunk.js:158:13029)
    at K.captureSession (313.3238287f.chunk.js:158:12277)
    at sdk.ts:200:9
    at t.init (sdk.ts:94:5)
    at Object._initializeSentry (widgets.min.js:1:20151)
    at Object.initializeSentry (widgets.min.js:1:19863)
instrument.ts:129 Cannot load i18n "vis2materialWidgets": Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
13instrument.ts:129 Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    at d.onerror (visUtils.jsx:738:43)
(anonymous) @ instrument.ts:129
customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
instrument.ts:129 Cannot load i18n "vis2gaugeWidgets": Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
3instrument.ts:129 Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
    at d.onerror (visUtils.jsx:738:43)
(anonymous) @ instrument.ts:129
customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
instrument.ts:129 Cannot load i18n "vis2energyWidgets": Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js
4instrument.ts:129 Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js
    at d.onerror (visUtils.jsx:738:43)
(anonymous) @ instrument.ts:129
:8082/vis-2-beta/?Resp_Haus#:1 Uncaught (in promise) Not exists
DevTools failed to load source map: Could not load content for http://192.168.178.77:8082/vis-2-beta/static/js/main.c31a7d5a.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.77:8082/vis-2-beta/static/js/313.3238287f.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by Feuer-sturm** [comment]
On my system everything is fine now with vis v2.0.20
Szenario 2 ✔️
Szenario 3 ✔️

@Telefisch : Can you please check your issue with the current version of vis2 (currently v2.0.20) ?
