### ISSUE TITLE
Fehlerhafte widgets

### ISSUE THREAD

**Issue by marcSu77** [ioBroker/ioBroker.vis#636]
Hallo
Bei den Widgets Paletten Metro und jqui-mfd werden verschiedene Widgets wie das OnOff + jqui dialog oder das Metro shutter dialog nicht richtig dargestellt:
![image](https://user-images.githubusercontent.com/122046488/210854792-70430079-0444-43a8-b9f7-bd4543556bd4.png)
Die Widgets habe ich ebenfalls auf einer frischen iobroker Installation getestet

**Comment by Feuer-sturm** [comment]
@marcSu77 Bitte die verwendete Vis Version ergänzen. Kommen in der Konsole (F12) Fehlermeldungen?

**Comment by Feuer-sturm** [comment]
Widget für "shutter + jqui Dialog" wird auch nicht angezeigt
![grafik](https://user-images.githubusercontent.com/25422320/222927947-149a632d-f787-457e-8519-3846861c2bc6.png)

vis2 v2.0.18

**Comment by Feuer-sturm** [comment]
mentioned widgets in this issue are fixed with vis-2 v2.0.27
