### ISSUE TITLE
VIS-2 / Widget <View im Widget> Attribute lassen sich nicht ändern

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.vis#637]
Attribute "Breite" + "Höhe" einer "View im Widget" lassen sich nicht im Fenster "Attribute" ändern, Maus und Cursortasten funktionieren.

Ändern eines Digits im Wert von "Breite" oder "Höhe" (802 ändern zu 812) reagiert nicht, egal ob <TAB> oder <ENTER> nach der Änderung betätigt wird.

Lösche ich die "Breite" oder "Höhe" mit "BACKSPACE", um eine neue Zahl einzugeben, verschwindet das Widget vollständig vom Editorfenster, das Fenster "Attribute" wechselt von "WIDGET" zu "SEITE".

Node.js 	        # v16.18.0
NPM                # 8.19.2
ioBroker 	        # v6.3.5
vis-2-beta	# v2.0.16
vis-inventwo    # v3.3.1

**Comment by Feuer-sturm** [comment]
@Haifeif Bitte einmal mit der aktuellen vis Version testen ob das issue gefixt ist.

**Comment by Haifeif** [comment]
Alles gut! Funktioniert vollständig.

 

LG Uwe

 

Von: Feuer-sturm ***@***.***> 
Gesendet: Samstag, 17. Juni 2023 00:54
An: ioBroker/ioBroker.vis ***@***.***>
Cc: Uwe ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.vis] VIS-2 / Widget <View im Widget> Attribute lassen sich nicht ändern (Issue #637)

 

@Haifeif <https://github.com/Haifeif>  Bitte einmal mit der aktuellen vis Version testen ob das issue gefixt ist.
