### ISSUE TITLE
Update von 1.4.15

### ISSUE THREAD

**Issue by dbeckers99** [ioBroker/ioBroker.vis#638]
Hz!

Ich versuche von VIS 1.4.15 auf eine neuere Version zu kommen. Das Update wird zwar ausgeführt, aber es bleibt dennoch immer die v1.4.15 installiert im ioBroker.

Zweites Problem: der Aufruf von Vis-Edit auf Port 8082 bleibt hängen nach "Loading Values..."

Wer hat eine Idee für mich?

**Comment by Apollon77** [comment]
1.4.15 ist die aktuellste Version. vis 2.x ist nur als separate Beta Version erhältlich.
