### ISSUE TITLE
Jarvis 3.1.2 - Thermostate werden nicht erkannt.

### ISSUE THREAD

**Issue by StephanRibbrock** [ioBroker/ioBroker.vis#639]
Ich habe versucht, 3 neue Heizköperthermostate in Jarvis zu importieren. Leider stehen diese immer unter den Geräten mit undefinierten Datenpunkten.
Bei genauerer Betrachtung wurden bisher alle anderen Thermostate erkannt und stehen mit der Typenbezeichnung HmIP-eTRV-2 in der CCU3. Die neuen Thermostate haben nun folgende Typenbezeichnung: HmIP-eTRV-2 I9F. Der Wandthermostat hat die Typenbezeichnung HmIP-WTH-1.
Die Geräte sind im ioBroker sichtbar
![2022-12-25_13-34-35](https://user-images.githubusercontent.com/123153176/213652590-5b3a4784-2950-4925-951f-8efc4d2bd8c6.jpg)

**Comment by Apollon77** [comment]
Please open issue in Jarvis repository
