### ISSUE TITLE
VIS-2-beta: input val - CSS text size and others gets ignored and line break before HTML append

### ISSUE THREAD

**Issue by MichaelUray** [ioBroker/ioBroker.vis#640]
**Describe the bug**  
It does not apply CSS text size and other CSS settings to the "input val" widget.

**To Reproduce**  
Change the text look via font-size or font-weight, it will not change.

**Screenshots & Logfiles**  
The upper indicator has the same text size and it shows the correct size, but the input fileld ignores these settings.
![2023-01-21_13-52-52_Vis_–_Mozilla_Firefox](https://user-images.githubusercontent.com/25169478/213867814-064c58da-6d6d-4d87-9ff3-559df12a1f88.png)

If I use "HTML anhängen" / "HTML append" then it applies the CSS settings to the appended text, but not to the input text.
Another issue is, that the appanded text gets added after a line break instead into the same line.
![2023-01-21_13-58-50_Vis_–_Mozilla_Firefox](https://user-images.githubusercontent.com/25169478/213867916-a222b1c6-124b-4b36-ad77-2b011ef3fb3f.png)

**Versions:**  
 - Adapter version: v2.0.16

**Comment by GermanBluefox** [comment]
It shouldn't.
To apply font size to input element you must define the class
```
.big-font input[type="text"]{
    font-size: 24px;
}
```
![image](https://user-images.githubusercontent.com/4582016/229605006-4121a1ab-b8af-4300-8389-79d3035f00fe.png)

and then apply it to widget
![image](https://user-images.githubusercontent.com/4582016/229605221-c13d7c5e-32f7-4a28-9f80-2308edffbac5.png)

Result:
![image](https://user-images.githubusercontent.com/4582016/229606769-bb231808-82f6-44f5-95cd-bb625cec8603.png)
