### ISSUE TITLE
VIS-2-beta - Widget Installationsmeldung unter Win falsch

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.vis#641]
Bei der Widget Installation unter Windows wird gemeldet, das der Installationspfad nicht gefunden werden kann und somit auch nichts installiert/deinstalliert wird. In Wahrheit war die Installation aber erfolgreich. Bei erneuter Ausführung wird eine weitere Instanz angelegt.

Die Frage ist, gehört das WWW an das Ende des Install Pfades?

`INFO: Directory "C:/ioBroker/node_modules/iobroker.vis-2-widgets-material/www" was not found! Nothing was uploaded or deleted.
Adapter "system.adapter.vis-2-beta.0" restarted.
host.HobbyPC create instance vis-2-widgets-material
host.HobbyPC object system.adapter.vis-2-widgets-material.0 created

C:\ioBroker>iob add vis-2-widgets-material
INFO: Directory "C:/ioBroker/node_modules/iobroker.vis-2-widgets-material/www" was not found! Nothing was uploaded or deleted.
Adapter "system.adapter.vis-2-beta.0" restarted.
host.HobbyPC create instance vis-2-widgets-material
host.HobbyPC object system.adapter.vis-2-widgets-material.1 created`

**Comment by GermanBluefox** [comment]
This will be fixed in js-controller. See above PR.
