### ISSUE TITLE
VIS-2-beta - Datei löschen in Symbol Vorschau nicht möglich

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.vis#650]
Das löschen von Dateien ist aktuell nur in der Listenansicht möglich (Mülleimer Symbol am Ende Zeile).

In der Thumbnail Vorschau fehlt das Mülleimer Symbol (in der Kopfzeile)

![image](https://user-images.githubusercontent.com/44617472/216771548-1d8a03b5-573a-441c-99b3-f6d375348088.png)

**Comment by Feuer-sturm** [comment]
@JBSullivan welche vis2 Version verwendest du?

**Comment by JBSullivan** [comment]
>welche vis2 Version verwendest du?

2.0.17

**Comment by Feuer-sturm** [comment]
issue is fixed with vis2 2.0.24
![grafik](https://user-images.githubusercontent.com/25422320/229625999-0c80a440-0f94-4160-b496-8b3751dd6dca.png)
