### ISSUE TITLE
Auf Smartphone wird Hintergrund nur teilweise dargestellt

### ISSUE THREAD

**Issue by Ersthelfer** [ioBroker/ioBroker.vis#653]
Hallo,

ich habe ein Problem mit der Hintergrundfarbe. Wenn ich meine VIS auf dem PC anschaue ist alles okay:

![1676797402121-vis-2_pc](https://user-images.githubusercontent.com/81872304/219944160-f5854fd3-cf7b-4dd4-b599-8c8eae919ce4.jpg)

Die Hintergrundfarbe füllt die Fläche vollständig aus.

Schaue ich mir das auf meinem Smartphone an, scheint auch erstmal alles okay zu sein:
![1676797496245-screenshot_20230219-100027](https://user-images.githubusercontent.com/81872304/219944227-ced78991-1740-4729-81ad-3b0e8de815c4.png)

Verkleinere ich jedoch die Anzeige ist die Hintergrundfarbe nur noch ein einem Teilbereich vorhanden:
![1676797567812-screenshot_20230219-100102](https://user-images.githubusercontent.com/81872304/219944239-f313b801-93ab-45bc-9f0f-21c80c95be6f.png)

![1676802353329-vis-2_aufloesung](https://user-images.githubusercontent.com/81872304/219944251-9277f131-e093-42d9-8157-c6486efff918.jpg)
Eigentlich sollte ich doch jetzt einen sehr großen Bereich haben. Ist auf dem Smartphone aber nicht

**Comment by GermanBluefox** [comment]
Es gibt momentan keine Lösung dafür. Als mögliche Lösung wäre einen HTML mit z-index=0 zu platzieren was so gros ist. Alle andere Elemente auf z-index=1.

**Comment by Feuer-sturm** [comment]
@Ersthelfer zur Info. Issue wird geschlossen.
