### ISSUE TITLE
Keine Bild-Laufleisten bei großen Seiten

### ISSUE THREAD

**Issue by Ersthelfer** [ioBroker/ioBroker.vis#654]
Hallo,

ich habe eine Seite mit 1800 x 2800 Pixel erstellt.

Wenn ich jetzt in meinem Webbrowser raus zoome kann ich auch alles sehen.
Zoome ich jedoch etwas hinein, habe ich keine Bildlaufleisten um mich auf der Seite zu bewegen.

Wenn ich den Browser auf 100% stelle sieht das so aus:
![VIS-2_PC](https://user-images.githubusercontent.com/81872304/220868171-877cd510-8b48-4434-8901-403e1d0ec5d2.JPG)

Auf der Linken Seite sind eigentlich 3 Diagramme untereinander.
Aber wie man sieht, keine Laufleisten

**Comment by Feuer-sturm** [comment]
Issue ist doppelt mit ioBroker/ioBroker.vis-2#22
