### ISSUE TITLE
VIS-2-beta - eingebundene Skripte im html-widget werden bei Start nicht ausgeführt

### ISSUE THREAD

**Issue by ghost** [ioBroker/ioBroker.vis#655]
Im html-widget werden eingebundene Skripte bei Start nicht ausgeführt. Mit einer eingestellten Updatezeit wird es nach dem ersten Updateintervall erstmals ausgeführt. Beispiel: 10000 ms -> erste Ausführung nach 10s. Bei einer Updatezeit von 0 ms wird es demnach nie ausgeführt.

Habe es in v2.0.17 und v2.0.16 getestet.

**Comment by Feuer-sturm** [comment]
@goesebrecht1 bitte stelle hier einmal deinen test Code mit ein,  den du im Forum gepostet hattest. Das erleichtert für andere das spätere Nachtesten

**Comment by ghost** [comment]
Hier mal ein einfacher test-code:

```
<script>
    console.log('hello');
</script>

<p>some text</p>
```

"some text" im widget wird angezeigt, "hello" in der Konsole nicht bzw. erst beim Update nach der eingestellten Updatezeit.

**Comment by Feuer-sturm** [comment]
@goesebrecht1 Please check with vis 2.0.24

**Comment by ghost** [comment]
It runs with v 2.0.24. Thanks.
