### ISSUE TITLE
No valid VIS license found

### ISSUE THREAD

**Issue by hgschwibbe** [ioBroker/ioBroker.vis#657]
When I open the VIS runtime, I got the message that no valid VIS License has been found:
![grafik](https://user-images.githubusercontent.com/1725648/221514711-745f52d4-8193-46f5-afe5-01f72276b68d.png)

But when I push the Check License button in the settings, it shows OK:
![grafik](https://user-images.githubusercontent.com/1725648/221515286-99518f67-d4f6-485e-ae71-4a7f4d37555d.png)

**Comment by hgschwibbe** [comment]
I checked the protocol and I recognized that VIS failed to call home over the internet:
![grafik](https://user-images.githubusercontent.com/1725648/221516933-82318549-8ee1-4d99-a52f-71e2552dcd73.png)

This makes me a little bit nervous if my smart home visualization depends on internet connection and/or the reachability of some internet domain (iobroker.net in this case).

**Comment by Apollon77** [comment]
For this case there is a vis offline license which is not requiring this check. This one is payed and not free like your current one -> https://iobroker.net/www/pricing#community

**Comment by hgschwibbe** [comment]
Thanks a lot, got it:
![grafik](https://user-images.githubusercontent.com/1725648/221535183-b615f061-882a-4b99-82a8-8b8d16194ce4.png)
