### ISSUE TITLE
Wrong version WEB Adapter

### ISSUE THREAD

**Issue by WeltenbummlerKA** [ioBroker/ioBroker.vis#658]
The VIS-2 isn't starting because of following error from the LOG:

startInstance system.adapter.vis-2-beta.0 Adapter dependency not fulfilled on "ioBroker": required adapter "web" has wrong version. Installed "4.3.0", required ">=5.4.0"!

But there isn't such a version available

**Comment by Apollon77** [comment]
This web version is in Lateast/Beta. Because of the fact that vis 2 is alpha tooit should work together. so please update web from Beta
