### ISSUE TITLE
Existing or new added widgets can not be selected

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis#667]
**Describe the bug**  
 Existing or new added widgets can not be selected 

**To Reproduce**  
- Update to vis2 v2.0.18
- Existing widgets or new widgets can not be selected to change the settings and widget can not be moved

**Expected behavior**  
Widget can be selected by mouse click

**Screenshots & Logfiles**  
There is no output during this error in the browser console.
![Animation3](https://user-images.githubusercontent.com/25422320/222831907-3eef9dc5-cddb-4ffe-853f-8d56409e9ecd.gif)

**Versions:**  
 - Adapter version: vis2 v2.0.18

**Comment by GermanBluefox** [comment]
Exactly this error I tried to fix in 2.0.18

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
The new widgets vis 2 -material widgets + Messgeräte + Energie Widgets are not affected of this issue.
But if I drag e.g. the widget "jqui botton link" or one of the map widgets in my view the bug is there.

**Comment by GermanBluefox** [comment]
Fixed in 2.0.19

**Comment by Feuer-sturm** [comment]
Issue is fixed with 2.0.19
Thanks :-)
