### ISSUE TITLE
SliderTabs doesn´t work in Runtime

### ISSUE THREAD

**Issue by Hilti23** [ioBroker/ioBroker.vis#669]
vis-2-beta.0
v2.0.17
Raspi Pi 4, 4 GB RAM

It works in the Designer when he doesn´t run:
![image](https://user-images.githubusercontent.com/31133588/222966090-900cd8a5-2a13-4dcc-8375-6c8928d2bb81.png)

It not works when it run:
![image](https://user-images.githubusercontent.com/31133588/222966213-dc8ad557-0f26-45a6-9266-b1c587ce41dd.png)

It not works in the Browser:
![image](https://user-images.githubusercontent.com/31133588/222966246-832cf1ed-5f83-4dd6-8b4b-76c777852e14.png)

Testet with Chrome und Edge

**Comment by GermanBluefox** [comment]
Slider tabs were re-written. Please retest with latest vis-2 version

**Comment by Feuer-sturm** [comment]
Issue is fixed with vis2 2.0.23
Is working in editor and in runtim view

![grafik](https://user-images.githubusercontent.com/25422320/229615743-5413df93-4290-44a7-8fb9-13eb0f090973.png)
![grafik](https://user-images.githubusercontent.com/25422320/229615818-3de7f93a-f121-4001-976c-e8f56e083012.png)
