### ISSUE TITLE
vis 0.5.5 runtime - no connection to server

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.vis#67]
Wenn man bei vis 0.5.5 aus dem Editor in die Runtime gehen will, kommt "no connection to server" und die Runtime startet nicht.

**Comment by fu-zhou** [comment]
Das passiert nur, wenn man den Editor über das X schließt. Da wird dann auf http://192.168.178.50:8082/vis/index.html#DemoView verlinkt.
Mit http://192.168.178.50:8082/vis/#DemoView funktioniert es.

**Comment by GermanBluefox** [comment]
Ist das jetzt besser geworden?

**Comment by fu-zhou** [comment]
```
Ja. Was ist jetzt der Unterschied
    zwischen vis und vis mit metro widgets?

Am 02.07.2015 um 19:33 schrieb
  GermanBluefox:


  Ist das jetzt besser geworden?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by GermanBluefox** [comment]
Es werden nur Basic Widgets in vis sein. Alle andere Widgets muss man nach
installieren.  Damit konnte die Geschwindigkeit erhöht werden. Auch Pflege
sollte einfache sein.
2 Июл 2015 г. 19:56 пользователь "fu-zhou" notifications@github.com
написал:
