### ISSUE TITLE
Palette wird nicht angezeigt Vis-2

### ISSUE THREAD

**Issue by Chris2106** [ioBroker/ioBroker.vis#672]
nach kompletter neu Installation von Vis-2, wird die Palette auf der linken Seite immer noch nicht angezeigt. Es wird nur ein Ladebalken angezeigt. 

![image](https://user-images.githubusercontent.com/61455542/224344359-54d1833b-4db7-4e18-9cf1-229107a17c59.png)

getestet mit Chrome Edge OperaGX

**Versions:**  
 - Adapter version: 2.0.20
 - JS-Controller version: 4.0.24
 - Operating system: Raspi Linux

folgende Fehler werden angezeigt 

getestet mit Chrome Edge OperaGX
![image](https://user-images.githubusercontent.com/61455542/224471047-3467784e-6b13-4ff3-a909-73c078458c46.png)

**Comment by Feuer-sturm** [comment]
@Chris2106 Welchen Browser verwendest du? Ich hatte mit Firefox auch schon einmal das Problem und mit Chrome ging es dann.
Schau bitte mal in der Browser Konsole (F12) welche Fehler dort auftauchen und ergänze sie bitte in einem issue als Log.

**Comment by Huskerdu24** [comment]
Bei mir das gleiche Problem:
Habe es neben meinem Standardbrowser Firefox auch mit Chrome und Vivaldi probiert:

```
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
main.16c4564f.js:657:11
Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters main.16c4564f.js:657:26
Help us to create open source project with reactJS! main.16c4564f.js:657:186
See you :) main.16c4564f.js:657:253
[2023-03-11T17:19:38.908Z] Try to connect socket.io.js:66:41
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.9.101:8082/vis-2-beta/static/js/main.16c4564f.js
Source-Map-Adresse: main.16c4564f.js.map
GEThttp://192.168.9.101:8082/vis-2-beta/widgets/metro/css/iconFont.min.css
[HTTP/1.1 404 Not Found 55ms]

GEThttp://192.168.9.101:8082/vis-2-beta/widgets/metro/css/metro-bootstrap.css
[HTTP/1.1 404 Not Found 53ms]

Version fritzdect: 0.0.2 fritzdect.js:46:12
Version players: 0.1.0 players.js:55:21
GEThttp://192.168.9.101:8082/vis-2-beta/widgets/metro/js/metro.js
[HTTP/1.1 404 Not Found 59ms]

Version chromecast: 1.3.5 chromecast.js:149:21
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.9.101:8082/vis-2-beta/widgets/metro/js/metro.js". edit.html:1:1
Version Info-Adapter-Widget: 0.0.9 info.js:29:12

```
Hie noch meine Systeminfo:
    Plattform: linux
    Betriebssystem: linux
    Architektur: x64
    CPUs: 2
    Geschwindigkeit: 2500 MHz
    Modell: Intel(R) Celeron(R) J4105 CPU @ 1.50GHz
    RAM: 2.9 GB
    System-Betriebszeit: 16 T. 15:47:37
    Node.js: v16.19.1
    time: 1678524619352
    timeOffset: -60
    Adapter-Anzahl: 562
    NPM: 8.19.3
    Datenträgergröße: 7.8 GB
    Freier Festplattenspeicher: 1.3 GB
    Betriebszeit: 16 T. 15:47:33
    Aktive Instanzen: 20
    Pfad: /opt/iobroker/

**Comment by Feuer-sturm** [comment]
@Huskerdu24 hast du den metro Adapter installiert?

**Comment by Huskerdu24** [comment]
Stimmt. Der war nicht vorhanden. Habe ihn nachinstalliert. Jetzt laden die Widgets. Danke.

**Comment by Feuer-sturm** [comment]
ioBroker/ioBroker.vis-2#37 
@Huskerdu24 die Abhängigkeit zum metro Adapter wird  ebenfalls im issue ioBroker/ioBroker.vis-2#37 verfolgt. 

@Chris2106 ist bei der metro Adapter installiert ?

**Comment by Chris2106** [comment]
ja den hatte ich nicht installiert gehabt, jetzt gehts danke :)

**Comment by Feuer-sturm** [comment]
Top. Dann mache ich hier zu.
