### ISSUE TITLE
Version number of vis has wrong description in vis editor

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis#673]
**Describe the bug**  
In the vis2 editor the version of vis2 is here shown:
![grafik](https://user-images.githubusercontent.com/25422320/224506676-196ae8fc-e066-4976-88a5-13e90967d581.png)

Please change the description from "Projekte" for example to "VIS version:"

**Versions:**  
 - Adapter version: vis2 v2.0.20

**Comment by GermanBluefox** [comment]
The word belongs to the tab and not to the version. If you know where better to place version, you are welcome

**Comment by Feuer-sturm** [comment]
@GermanBluefox Ahh ok :-)
My proposal would be to put it in the right corner
![grafik](https://user-images.githubusercontent.com/25422320/225431333-01ed773d-5515-417f-9f69-9b49c0cf45b5.png)

**Comment by GermanBluefox** [comment]
Fixed

**Comment by Feuer-sturm** [comment]
Is fixed with vis2 2.0.24
![grafik](https://user-images.githubusercontent.com/25422320/229618884-d155770f-22c3-447a-91f4-dd021d15e839.png)
