### ISSUE TITLE
Make Vis Responsive

### ISSUE THREAD

**Issue by hgschwibbe** [ioBroker/ioBroker.vis#674]
If you wanna make VIS responsive for desktop and mobile devices, I already did it.

Here is my sample project:
[2023-03-19-rolladen.zip](https://github.com/ioBroker/ioBroker.vis/files/11010718/2023-03-19-rolladen.zip)

The basic concept:
1. create custom widget groups directly as children of the the VIS view
2. reset all relative positioning rules on the VIS view and first level children (e.g. top, left  to zero)
3. make the VIS view flex layout together with first level children
4. Have fun on different devices

Things you can do. 
What I am currently missing is a separate flex view mode where I can assign and order my widget groups.
The only thing how I can affect the order of the children in a flex view is to edit widget groups in the proper order.
Then they will appear in the order they were edited. But if you have to edit the first one later, it will become last element in the view. So I have to modify each widget group after to restore the proper order again.

**Comment by Apollon77** [comment]
Did yiou tried Vis2? THere anything should be there already to allow responive UIs, see the relevant foruzm thread for Vis2

**Comment by hgschwibbe** [comment]
No, but Im not sure that I will use it.
As you can see in the screenshots below I already invested too much time into widget design etc. pp.:

Thermostat (Desktop View):
![Thermostate (Desktop)](https://user-images.githubusercontent.com/1725648/226191290-4808455a-2a6e-4b9a-8d3c-0089b21f8923.png)

Thermostat (Mobile View):
![Thermostate (Mobile)](https://user-images.githubusercontent.com/1725648/226191294-f57a9568-5300-4eb9-b441-d35d4a7ba58d.png)

Sockets (Desktop View):
![Steckdosen (Desktop)](https://user-images.githubusercontent.com/1725648/226191520-bd7f6052-87c1-4e53-a446-de7fab696c9e.png)

Sockets (Mobile View):
![Steckdosen (Mobile)](https://user-images.githubusercontent.com/1725648/226191523-20b56fa0-be68-48c2-8d53-2b1b7526fbe4.png)

**Comment by Apollon77** [comment]
Ahh ok so it was more an inforational post? Then I think the Forum is much better suited for this then a GitHub where we track issues, bugs and feature requests!

**Comment by Apollon77** [comment]
But that you for that intereting outline!
