### ISSUE TITLE
VIS-2-beta: License Code Error

### ISSUE THREAD

**Issue by Gurke258** [ioBroker/ioBroker.vis#675]
Hello,

i've install the VIS-2-beta and enter my License.

I get the message:

Error in GUI!
Please open the browser console (F12), copy error text from there and create the issue on [github](https://github.com/ioBroker/ioBroker.admin/issues)
Without this information it is not possible to analyse the error.
It should looks like
error
If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BCountry%2C%20Name%2C%20AddressLine1%2C%20ZIP%2C%20City%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
`
Zr@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:14:12781(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))h@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:14:14568(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))S@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:14:15719(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))Q@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:14:17812(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))ae@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:1494(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))oa@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:45838(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))ra@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:39834(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))Jc@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:39765(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))ml@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:39622(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))iu@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:36004(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))ea@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:36817(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))hn@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:14:3267(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))bc@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:41345(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))$n@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:40316(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))bs@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:16:35807(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))Ln@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:24:1615(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))Gn@http://192.168.178.79:8081/static/js/3961.a98ff7ab.chunk.js:24:2007(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))`

But in my Console there is no Error with this message:

```
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BCountry%2C%20Name%2C%20AddressLine1%2C%20ZIP%2C%20City%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 15
        Zr
        h
        S
        Q
        ae
        oa
        ra
        Jc
        ml
        iu
        ea
        hn
        bc
        $n
        bs
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
[instrument.ts:124:32](http://192.168.178.79:8081/static/node_modules/@sentry/src/instrument.ts)
    Oe instrument.ts:124
    React 13
        Hi
        callback
        Yo
        Zs
        Gs
        Xc
        bc
        $n
        ea
        hn
        bc
        $n
        bs
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14

​
```

**Comment by Feuer-sturm** [comment]
@Gurke258 which vis2 Version and admin version do you use?

**Comment by Gurke258** [comment]
Admin: 6.3.5
Vis2: 2.0.21

**Comment by Feuer-sturm** [comment]
Probably this is more an admin issue than a vis2 issue. See also https://github.com/ioBroker/ioBroker.admin/issues/1900 in admin repo

**Comment by eyichbins** [comment]
Habe das Problem gelöst, war ein Web Adapter Problem. 
Mit Web 5.5.3 geht es jetzt und man muss:
Reine Web-Sockets (iobroker.ws) verwenden einschalten.

Danke euch

**Comment by Gurke258** [comment]
Hat bei mir leider nicht geholfen... trotz Neustart der Adapter bzw. des ganzen Iobrokers.

**Comment by GermanBluefox** [comment]
This is admin problem
