### ISSUE TITLE
VIS2 mit Android VIS App

### ISSUE THREAD

**Issue by Huskerdu24** [ioBroker/ioBroker.vis#678]
Hallo.
Kann es sein, dass Projekte welche mit VIS2 erstellt wurden, nicht mehr in der VIS App angezeigt/aufgerufen werden können?
Bei mir werden auch nach einem Re-Sync in der App nur die VIS1 Projekte aufgelistet.

VIS2 Adapter Version v2.0.22
VIS App Version v2.2.0

**Comment by GermanBluefox** [comment]
vis-2 ist noch nicht mit Android App lauffähig. Nur mit https://play.google.com/store/apps/details?id=com.iobroker.visu

**Comment by Huskerdu24** [comment]
Die visu App kannte ich noch nicht. Funktioniert damit prima. Danke.
