### ISSUE TITLE
VIS-2-beta: Material Design Line History Chart Widgeds (vis.GetHistory is not a function

### ISSUE THREAD

**Issue by JamesBHof** [ioBroker/ioBroker.vis#679]
With vis-materialdesign Version 0.5.94 Vis runtime shows this error:

![grafik](https://user-images.githubusercontent.com/118039671/227795670-8088016b-f795-4c3a-8a47-00cf3b0442f7.png)

![grafik](https://user-images.githubusercontent.com/118039671/227795774-2e0f7c92-ca0d-44f2-bdb5-4949bd78f2f3.png)

"Aapter instance" and "Objekt ID" seems to be buggy.

In "Aapter instance" it is not possible to select sql.0 or history.0 instance.
The filter dialog in "Objekt ID" shows only some datapoints.

**Comment by Feuer-sturm** [comment]
@JamesBHof please add the vis2 Version which is installed

**Comment by Feuer-sturm** [comment]
@JamesBHof Please check with vis2 2.0.24

**Comment by Feuer-sturm** [comment]
vis2 2.0.24
@GermanBluefox 
If I click on the three dots the dialog box for the object-ids opens and I can not select an adapter instance
![grafik](https://user-images.githubusercontent.com/25422320/230794882-1853db14-6a0d-43e1-ac01-4efcd5edecb5.png)
![grafik](https://user-images.githubusercontent.com/25422320/230794914-b68bfe11-f0d2-4fd4-8067-c0acab57ff20.png)

If I add the instancename on my own this does not work as well:
![grafik](https://user-images.githubusercontent.com/25422320/230795012-db4bc06e-75c6-4b6c-a0d8-92630c5448d1.png)

**Comment by Feuer-sturm** [comment]
is fixed with 2.0.33
