### ISSUE TITLE
Widget jqui-mfd - value - Light/Dimmer

### ISSUE THREAD

**Issue by mctom** [ioBroker/ioBroker.vis#68]
Hier fehlt der korrekte Hintergrund. Es wird nur das Bild angezeigt.
![2015-05-28 21_10_44-iobroker vis](https://cloud.githubusercontent.com/assets/12543796/7868677/0acdb116-057e-11e5-9596-ce1f159c17f0.png)

**Comment by GermanBluefox** [comment]
Bitte mit 0.5.7 testen

**Comment by mctom** [comment]
Hintergrund ist vorhanden.
Allerdings ist dieser nicht aktiv wenn die Lampe an ist.

**Comment by mctom** [comment]
in Version 0.5.9 getestet 
alles OK
Danke
