### ISSUE TITLE
Widget 'Metro - Tile Toggle' Ikone

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.vis#69]
Die Ikonen für Wahr und Falsch arbeiten nicht. Es wird immer die Ikone für 'Falsch' angezeigt.

**Comment by GermanBluefox** [comment]
Bitte mit 0.5.7 testen

**Comment by ykuendig** [comment]
0.5.7 startet nicht. -> 0.5.8 startet, teste nun.

**Comment by ykuendig** [comment]
fixed in 0.5.8. Danke
