### ISSUE TITLE
vis-2-beta versteckte Felder

### ISSUE THREAD

**Issue by formifan2002** [ioBroker/ioBroker.vis#690]
Wenn man versteckte Felder im Widget verwendet und dann mehrere Widgets selektiert hat, bekommt man beim Start die Fehlermeldung (im Chrome Developertool): "Cannot execute hidden on "true"..." (siehe Screenshot):

![image](https://user-images.githubusercontent.com/95829446/229550800-31283694-a1e3-4f9a-8f08-635695f93bc6.png)

Ich denke, es liegt an der Codestelle:

        const isHidden = [];
        for (let i = 0; i < selectedWidgets.length; i++) {
            const data = project[selectedView].widgets[selectedWidgets].data;
            const style = project[selectedView].widgets[selectedWidgets].style;

Diese müsste m.E. geändert werden in:

        const isHidden = [];
        for (let i = 0; i < selectedWidgets.length; i++) {
            const data = project[selectedView].widgets[selectedWidgets[i].data;
            const style = project[selectedView].widgets[selectedWidgets[i].style;

**Comment by Feuer-sturm** [comment]
@formifan2002 Please check with 2.0.24

**Comment by formifan2002** [comment]
OK, many thanks for the feedback. On npm I only find the version 2.0.23. By when will you distribute the new version?

**Comment by formifan2002** [comment]
Works perfect with 2.0.24 !
