### ISSUE TITLE
vis-2-beta add possibility to add classname in visAttrs[x].fields 

### ISSUE THREAD

**Issue by formifan2002** [ioBroker/ioBroker.vis#691]
Beside the exisiting attributes like 'hidden', 'tooltip',... it would be great to have an option to add a 'classname' to the field in order to be able to change / manipulate the field in the DOM later on.

**Comment by GermanBluefox** [comment]
Actually it works. What exactly is required?
![image](https://user-images.githubusercontent.com/4582016/236810308-a5764d86-db31-42de-89ac-56a7a8f8f774.png)

**Comment by formifan2002** [comment]
Hi,
as far as I understand, the CSS class is for the complete widget. My idea / suggestion was to have one individual class or ID per field (!). For my personal requirement I have solved this in the meantime via a "custom field".
