### ISSUE TITLE
vis-2-beta (2.0.24) versteckte Felder werden bei Auswahl mehrerer Widgets desselben Typs angezeigt 

### ISSUE THREAD

**Issue by formifan2002** [ioBroker/ioBroker.vis#694]
In der Version 2.0.24 werden versteckte Felder im Menü angezeigt, sobald man mehrere Widgets desselben Typs selektiert hat.

![image](https://user-images.githubusercontent.com/95829446/230379424-aa3d1c0e-b82e-40bc-871b-f0a99f49f4b7.png)

Das Feld 'instancenamehidden' ist ist wie folgt deklariert:
```
                        {
                            name: 'instancenamehidden', 
                            type: 'text',
                            hidden: true,
                            default: 'false',
                        },
```
Es steuert die Sichtbarkeit eines anderen Feldes mit Namen 'instancename':
```
                        {
                            name: 'instancename',
                            label: 'vis_2_widgets_instance',
                            type: 'custom',
                            hidden: 'data.instancenamehidden === "true"',
                            component: (
                                field,
                                data,
                                onDataChange,
                            ) => this.showInstances(field,data,onDataChange),
                        },
```
Alles funktioniert perfekt, solange man nicht zwei oder mehr Widgets gleichzeitig auswählt.

**Comment by Feuer-sturm** [comment]
@formifan2002 Can you please check with vis2 version >=2.0.28 if this issue is fixed?

**Comment by formifan2002** [comment]
Works perfectly with 2.0.29. Many thanks.
