### ISSUE TITLE
vis, css and the specifity of css classes

### ISSUE THREAD

**Issue by oweitman** [ioBroker/ioBroker.vis#696]
each view in vis currently has its own container. this view gets an id in html according to the schema #visview_test if the view was named test.

many widgets and their html elements are formatted using css rules. if you now want to change the design, you could enter this via your own rules in the css tab.

using the following example, this is currently causing difficulties.
when using the jqui button state widget, you can only change the design if you explicitly specify the id of the widget.

now if you want to apply the same design to several widgets you have to copy and duplicate accordingly instead of using a uniform class name and applying it to all widgets.

the reason for this is the priority of the specificity of the css classes. since the id of the view container is already contained in the standard classes, an id must also be contained in the css rule in order to achieve greater specificity. otherwise your own rules will be overwritten by the existing ones.

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

to fix this, you would have to define the view id as a separate css class and have all css rules refer to the css class instead of the id of the container.

the following function generates the css rules directly related to the view container id

https://github.com/ioBroker/ioBroker.vis/blob/442157dde1080199f9079c7d7314d8480535fcc0/www/js/vis.js#L1038

if it is no longer corrected in vis1, this should possibly be taken into account in vis2, since changes that may not be backwards compatible can be implemented and extensively tested here.

**Comment by GermanBluefox** [comment]
@oweitman 
May be you can help me somehow, because I don't understand what is required. Views have now `className='.visview_test'` too.
But I am not sure if it helps
