### ISSUE TITLE
VIS2.024 Installation in Ordnung, Import hat funktioniert, Widget Top App Bar und view in widget 8, keine Funktion

### ISSUE THREAD

**Issue by uweschalke04** [ioBroker/ioBroker.vis#701]
zieht man das widget topp app bar und view in widget 8 auf die Arbeitsfläche, zur Konfiguration eines seitlichen Menüs,
und fängt an die einzelnen vorher erstellten views mit einzubinden, hat man auf einmal nur noch einen weißen Bildschirm.
Da kommt man auch nicht mehr raus. Startet man ioBroker und den Editor neu hat man sofort wieder einen weißen Bildschirm. 
Da ich mit Container arbeite kann ich nur immer neu anfangen. So kann ich den VIS 2 Adapter nicht testen! Ich fang ja mit dem Menü und den neuen Seiten an. Kann da jemand helfen, oder braucht ihr mehr infos?

vis-2-beta  v2.0.24
widget   topp app bar
widget   view in widget 8

**Comment by Feuer-sturm** [comment]
@uweschalke04 Wenn die weiße Seite erscheint, drücke bitte einmal F12 und im Reiter "Konsole" siehst du ein Log mit vermutlich Fehlermeldungen.
Bitte poste dein Log einmal hier.

**Comment by uweschalke04** [comment]
Ok, werde ich machen. Danke.

**Comment by uweschalke04** [comment]
iobroker.vis-2-beta@2.0.24 using theme "colored"
main.7b76ba87.js:658 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.7b76ba87.js:658 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.7b76ba87.js:658 Help us to create open source project with reactJS!
main.7b76ba87.js:658 See you :)
lib.min.js:43 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
lib.min.js:43 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
materialdesign.js:33 Version vis-materialdesign: 0.5.9
baseclient.ts:160 Uncaught (in promise) TypeError: t.update is not a function
    at t.captureSession (baseclient.ts:160:15)
    at Q._sendSessionUpdate (236.3eae57b4.chunk.js:159:12920)
    at Q.captureSession (236.3eae57b4.chunk.js:159:12216)
    at sdk.ts:200:9
    at t.init (sdk.ts:94:5)
    at Object._initializeSentry (widgets.min.js:1:20151)
    at Object.initializeSentry (widgets.min.js:1:19863)
instrument.ts:129 Translate: show code
instrument.ts:129 Translate: ==
instrument.ts:129 Translate: !=
instrument.ts:129 Translate: <=
instrument.ts:129 Translate: >=
instrument.ts:129 Translate: <
instrument.ts:129 Translate: >
instrument.ts:129 Translate: consist
instrument.ts:129 Translate: not consist
instrument.ts:129 Translate: exist
instrument.ts:129 Translate: not exist
instrument.ts:129 Translate: disabled
instrument.ts:129 TypeError: t.getUserGroups is not a function
    at HTMLDivElement.init (widgets.min.js:14:19916)
    at WidgetField.jsx:400:40
    at P2 (main.7b76ba87.js:1914:25081)
    at Ca (main.7b76ba87.js:1914:43813)
    at Ma (main.7b76ba87.js:1914:37807)
    at B3 (main.7b76ba87.js:1912:3299)
    at yc (main.7b76ba87.js:1914:42607)
    at Fr (main.7b76ba87.js:1914:41573)
    at vo (main.7b76ba87.js:1914:36906)
    at x (main.7b76ba87.js:1948:1548)
    at MessagePort.w (main.7b76ba87.js:1948:1907)
(anonymous) @ instrument.ts:129
main.7b76ba87.js:1912 Uncaught TypeError: t.getUserGroups is not a function
    at HTMLDivElement.init (widgets.min.js:14:19916)
    at WidgetField.jsx:400:40
    at P2 (main.7b76ba87.js:1914:25081)
    at Ca (main.7b76ba87.js:1914:43813)
    at Ma (main.7b76ba87.js:1914:37807)
    at B3 (main.7b76ba87.js:1912:3299)
    at yc (main.7b76ba87.js:1914:42607)
    at Fr (main.7b76ba87.js:1914:41573)
    at vo (main.7b76ba87.js:1914:36906)
    at x (main.7b76ba87.js:1948:1548)
    at MessagePort.w (main.7b76ba87.js:1948:1907)
instrument.ts:129 Common user CSS not found: Not exists
(anonymous) @ instrument.ts:129
edit.html#index:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
DevTools failed to load source map: Could not load content for chrome-extension://klekeajafkkpokaofllcadenjdckhinm/sourceMap/chrome/content.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/static/js/main.7b76ba87.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/static/js/236.3eae57b4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_i18n_de_json-src_i18n_en_json-src_i18n_es_json-src_i18n_fr_json-src_i18n_it_json-src_i18n-67bb96.1677e5d1.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_translations_js.4825f038.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Generic_jsx-src_ObjectChart_jsx.bdb36970.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Thermostat_jsx.00661837.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Static_jsx.de18c1d2.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Actual_jsx.29743391.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Switches_jsx.9f8f5c4d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Blinds_jsx.66f75413.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Clock_jsx.93e562af.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_SimpleState_jsx.034a9b74.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_ViewInWidget_jsx.ed9f4f18.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Camera_jsx.9abd0ce3.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Security_jsx.8203d3a4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Player_jsx.53f18e7b.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Html_jsx.151c713c.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.44.106:8082/vis-2-beta/widgets/vis-2-widgets-material/static/css/src_Map_jsx-node_modules_leaflet_dist_leaflet_css.11ebe247.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by uweschalke04** [comment]
Hier nur die Errors:

Uncaught (in promise) TypeError: t.update is not a function
    at t.captureSession (baseclient.ts:160:15)
    at Q._sendSessionUpdate (236.3eae57b4.chunk.js:159:12920)
    at Q.captureSession (236.3eae57b4.chunk.js:159:12216)
    at sdk.ts:200:9
    at t.init (sdk.ts:94:5)
    at Object._initializeSentry (widgets.min.js:1:20151)
    at Object.initializeSentry (widgets.min.js:1:19863)
instrument.ts:129 TypeError: t.getUserGroups is not a function
    at HTMLDivElement.init (widgets.min.js:14:19916)
    at WidgetField.jsx:400:40
    at P2 (main.7b76ba87.js:1914:25081)
    at Ca (main.7b76ba87.js:1914:43813)
    at Ma (main.7b76ba87.js:1914:37807)
    at B3 (main.7b76ba87.js:1912:3299)
    at yc (main.7b76ba87.js:1914:42607)
    at Fr (main.7b76ba87.js:1914:41573)
    at vo (main.7b76ba87.js:1914:36906)
    at x (main.7b76ba87.js:1948:1548)
    at MessagePort.w (main.7b76ba87.js:1948:1907)
(anonymous) @ instrument.ts:129
main.7b76ba87.js:1912 Uncaught TypeError: t.getUserGroups is not a function
    at HTMLDivElement.init (widgets.min.js:14:19916)
    at WidgetField.jsx:400:40
    at P2 (main.7b76ba87.js:1914:25081)
    at Ca (main.7b76ba87.js:1914:43813)
    at Ma (main.7b76ba87.js:1914:37807)
    at B3 (main.7b76ba87.js:1912:3299)
    at yc (main.7b76ba87.js:1914:42607)
    at Fr (main.7b76ba87.js:1914:41573)
    at vo (main.7b76ba87.js:1914:36906)
    at x (main.7b76ba87.js:1948:1548)
    at MessagePort.w (main.7b76ba87.js:1948:1907)
edit.html#index:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by uweschalke04** [comment]
Ich habe gerade selber noch einen Test gemacht, das Problem scheint mit Chrome zusammen zuhängen. Wenn ich das Projekt im Firefox öffne, funktioniert das Menü so weit, vielleicht hilft das weiter.

**Comment by uweschalke04** [comment]
Mit Firefox war auch nur eine Momentaufnahme, der Fehler kommt eindeutig über den neuen Adapter VIS-2-Beta 2.0.24

**Comment by Feuer-sturm** [comment]
@uweschalke04 Bitte einmal mit der aktuellen Version von vis2 nachtesten ob das issue gefixt ist.

**Comment by uweschalke04** [comment]
Hallo,

 

bin zur Zeit nicht zuhause, werde es auf jedem Fall ausprobieren und mich dann melden.

 

 

Von: Feuer-sturm ***@***.***> 
Gesendet: Freitag, 16. Juni 2023 22:16
An: ioBroker/ioBroker.vis ***@***.***>
Cc: uweschalke04 ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.vis] VIS2.024 Installation in Ordnung, Import hat funktioniert, Widget Top App Bar und view in widget 8, keine Funktion (Issue #701)

 

@uweschalke04 <https://github.com/uweschalke04>  Bitte einmal mit der aktuellen Version von vis2 nachtesten ob das issue gefixt ist.

**Comment by uweschalke04** [comment]
Hallo,Leider ist das Problem noch immer,Zuerst das Widget Top App bar auf die Seite,Dann das view in widget 8 auf die Seite ziehen, dann ist Ende. Nur noch eine weiße Seite.Bei F12 kommen auch Meldungen,Sagen mir aber leider nichts.Uwe SchmidtAm 19.08.2023 um 22:12 schrieb Feuer-sturm ***@***.***>:﻿
Closed #701 as completed.

**Comment by uweschalke04** [comment]
iobroker.vis-2-beta@2.1.4 using theme "colored"
main.6c4ff8e5.js:2 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.6c4ff8e5.js:2 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.6c4ff8e5.js:2 Help us to create open source project with reactJS!
main.6c4ff8e5.js:2 See you :)
sentry.iobroker.net/api/232/envelope/?sentry_key=76ba808e24ed438ab3bf32ce00836dbb&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.59.2:1     Failed to load resource: the server responded with a status of 403 ()
554.68737bc5.chunk.js:2 Version trashschedule: 2.2.0
554.68737bc5.chunk.js:2 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
554.68737bc5.chunk.js:2 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
554.68737bc5.chunk.js:2 Version vis-materialdesign: 0.5.9
baseclient.ts:160 Uncaught (in promise) TypeError: t.update is not a function
    at t.captureSession (baseclient.ts:160:15)
    at e.value (554.68737bc5.chunk.js:2:59502)
    at e.value (554.68737bc5.chunk.js:2:58816)
    at e.value (554.68737bc5.chunk.js:2:59211)
    at sdk.ts:199:9
    at t.init (sdk.ts:94:5)
    at Object._initializeSentry (widgets.min.js:1:20151)
    at Object.initializeSentry (widgets.min.js:1:19863)
554.68737bc5.chunk.js:2 Translate: jqui_html_dialog
554.68737bc5.chunk.js:2 Translate: jqui_icon_dialog
554.68737bc5.chunk.js:2 Translate: jqui_container_dialog
554.68737bc5.chunk.js:2 Translate: jqplot
554.68737bc5.chunk.js:2 Translate: materialdesign
554.68737bc5.chunk.js:2 Translate: swipe
554.68737bc5.chunk.js:2 Translate: trashschedule
554.68737bc5.chunk.js:2 Translate: tabs
554.68737bc5.chunk.js:2 Object
554.68737bc5.chunk.js:2 DOMRect
554.68737bc5.chunk.js:2 Object
554.68737bc5.chunk.js:2 TypeError: Cannot read properties of undefined (reading 'length')
    at Function.value (visRxWidget.jsx:118:46)
    at new i (visRxWidget.jsx:95:48)
    at i.<anonymous> (createSuper.js:11:24)
    at new i (BasicViewInWidget8.jsx:23:25)
    at Wo (main.6c4ff8e5.js:2:6779192)
    at Li (main.6c4ff8e5.js:2:6799633)
    at Cs (main.6c4ff8e5.js:2:6845778)
    at Hl (main.6c4ff8e5.js:2:6833919)
    at gl (main.6c4ff8e5.js:2:6833847)
    at zl (main.6c4ff8e5.js:2:6833710)
    at al (main.6c4ff8e5.js:2:6830490)
    at ll (main.6c4ff8e5.js:2:6830881)
    at Nc (main.6c4ff8e5.js:2:6771421)
    at main.6c4ff8e5.js:2:6828423
(anonymous) @ 554.68737bc5.chunk.js:2
main.6c4ff8e5.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Function.value (visRxWidget.jsx:118:46)
    at new i (visRxWidget.jsx:95:48)
    at i.<anonymous> (createSuper.js:11:24)
    at new i (BasicViewInWidget8.jsx:23:25)
    at Wo (main.6c4ff8e5.js:2:6779192)
    at Li (main.6c4ff8e5.js:2:6799633)
    at Cs (main.6c4ff8e5.js:2:6845778)
    at Hl (main.6c4ff8e5.js:2:6833919)
    at gl (main.6c4ff8e5.js:2:6833847)
    at zl (main.6c4ff8e5.js:2:6833710)
    at al (main.6c4ff8e5.js:2:6830490)
    at ll (main.6c4ff8e5.js:2:6830881)
    at Nc (main.6c4ff8e5.js:2:6771421)
    at main.6c4ff8e5.js:2:6828423

**Comment by Feuer-sturm** [comment]
Hallo @uweschalke04 
der Adapter "vis-2-beta" den du aktuell installiert hast wird nicht weiter gepflegt. Die weitere Entwicklung von vis-2 erfolgt über den Adapater "vis-2". Siehe hierzu auch diesen Thread: https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta

Die aktuelle vis-2 Version ist die v2.2.7
