### ISSUE TITLE
VIS2 -  Widgetliste Anzeige

### ISSUE THREAD

**Issue by wszene** [ioBroker/ioBroker.vis#704]
kann man die Anzeige der Widgets evtl. auch wie in der VIS1 anzeigenlassen kann
In VIS1 werden ja die selbst definierten Namen angezeigt in VIS2 die Widgets-IDs

**VIS 1:**
[![vis1.png](https://i.postimg.cc/TYr97BVY/vis1.png)](https://postimg.cc/PP5YN3VB)
**VIS 2:**
[![vis2.png](https://i.postimg.cc/ncY4YBxX/vis2.png)](https://postimg.cc/jL2nRWLT)

**Comment by GermanBluefox** [comment]
![image](https://github.com/ioBroker/ioBroker.vis/assets/4582016/51de4aba-8604-48e6-a87b-3f48e5c23de3)

Implemented in 2.0.28

**Comment by Feuer-sturm** [comment]
Tested with 2.0.28 and issue is fixed :-)
