### ISSUE TITLE
Editor öffnet sich nicht nach Installation der Beta

### ISSUE THREAD

**Issue by Maschler** [ioBroker/ioBroker.vis#712]
**Beschreibung**  
Die Installation wurde nach Vorgabe aus https://forum.iobroker.net/topic/60398/test-adapter-vis-2-0-alpha/660 durchgeführt.

Leider wurder der Editor der Vis 2 bei mir nicht richtig aufgerufen. Wenn ich den Editor aufrufe, erscheint kurz oben eine Leiste (wahrscheinlich die vom Editor) und danach ist die Seite weiß.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/38862834/236453463-ab3b96f4-e10b-4b9e-9a7d-7315af758f54.png)
![grafik](https://user-images.githubusercontent.com/38862834/236453538-a0327f38-d736-4829-bad6-31f062111c72.png)

**Fehlermeldung**  
> Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. jquery-1.11.2.min.js:4:29775
> Mutations-Ereignisse sollten nicht mehr verwendet werden. Verwenden Sie MutationObserver stattdessen. analyser.js:485:17
> iobroker.vis-2-beta@2.0.24 using theme "colored" bootstrap.jsx:20:8
> 
> ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
> ██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
> ██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
> ██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
> ██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
> ╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
> main.7b76ba87.js:658:11
> Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters main.7b76ba87.js:658:26
> Help us to create open source project with reactJS! main.7b76ba87.js:658:186
> See you :) main.7b76ba87.js:658:253
> [2023-05-04T19:26:32.634Z] Try to connect socket.io.js:66:41
> TypeError: e.field is undefined
>     Ns ToolbarItems.jsx:61
>     As ToolbarItems.jsx:255
>     As ToolbarItems.jsx:247
>     An main.7b76ba87.js:1912
>     ma main.7b76ba87.js:1914
>     _c main.7b76ba87.js:1914
>     Uo main.7b76ba87.js:1914
>     Fc main.7b76ba87.js:1914
>     Ha main.7b76ba87.js:1914
>     _o main.7b76ba87.js:1914
>     Ma main.7b76ba87.js:1914
>     B3 main.7b76ba87.js:1912
>     I0 main.7b76ba87.js:1914
> main.7b76ba87.js:1914:177
> TypeError: e.field is undefined
>     Ns ToolbarItems.jsx:61
>     As ToolbarItems.jsx:255
>     As ToolbarItems.jsx:247
>     An main.7b76ba87.js:1912
>     ma main.7b76ba87.js:1914
>     _c main.7b76ba87.js:1914
>     Uo main.7b76ba87.js:1914
>     Fc main.7b76ba87.js:1914
>     Ha main.7b76ba87.js:1914
>     _o main.7b76ba87.js:1914
>     Ma main.7b76ba87.js:1914
>     B3 main.7b76ba87.js:1912
>     I0 main.7b76ba87.js:1914
> main.7b76ba87.js:1914:177
> TypeError: l.settings is undefined
>     Mi View.jsx:206
>     An main.7b76ba87.js:1912
>     _c main.7b76ba87.js:1914
>     Uo main.7b76ba87.js:1914
>     Fc main.7b76ba87.js:1914
>     Ha main.7b76ba87.js:1914
>     _o main.7b76ba87.js:1914
>     Ma main.7b76ba87.js:1914
>     B3 main.7b76ba87.js:1912
>     I0 main.7b76ba87.js:1914
> main.7b76ba87.js:1914:177
> Uncaught TypeError: e.field is undefined
>     Ns ToolbarItems.jsx:61
>     As ToolbarItems.jsx:255
>     As ToolbarItems.jsx:247
>     An main.7b76ba87.js:1912
>     ma main.7b76ba87.js:1914
>     _c main.7b76ba87.js:1914
>     Uo main.7b76ba87.js:1914
>     Fc main.7b76ba87.js:1914
>     Ha main.7b76ba87.js:1914
>     _o main.7b76ba87.js:1914
>     Ma main.7b76ba87.js:1914
>     B3 main.7b76ba87.js:1912
>     I0 main.7b76ba87.js:1914
> ToolbarItems.jsx:61:16
> Metro version: "1.2.0" edit.html:645:10
> Version Info-Adapter-Widget: 0.0.9 info.js:29:12
> Source-Map-Fehler: Error: request failed with status 404
> Ressourcen-Adresse: http://192.168.100.40:8082/vis-2-beta/static/js/main.7b76ba87.js
> Source-Map-Adresse: main.7b76ba87.js.map
> 
> ​
> 
> 
> ```

**Versions auf Raspberry pi:**  
    Plattform: linux
    Betriebssystem: linux
    Architektur: arm
    CPUs: 4
    Geschwindigkeit: 1500 MHz
    Modell: unknown
    RAM: 3.7 GB
    Node.js: v18.16.0
    NPM: 9.5.1

**Comment by Maschler** [comment]
Das Löschen der importierten Vis aus der 1er Version im Admin im Datei Menü hat den Erfolg gebracht. Jetzt wird der Editor geöffnet.

**Comment by Feuer-sturm** [comment]
It seens that there is a problem with a widget which is used in vis1 project and which causes the error during the Import in vis2

**Comment by Feuer-sturm** [comment]
@Maschler Can you please retest your issue?
