### ISSUE TITLE
File index.html not found 

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.vis#732]
**Describe the bug**  
Dass sich VIS überhaupt nicht starten lässt, weder index. noch edit. - das hatte ich ja noch nie.
Ich hab aber auch immer ein Glück.  ;-O

**To Reproduce**  
?

**Expected behavior**  
VIS Aufruf startet VIS.

**Screenshots & Logfiles**  
File index.html not found: {}

**Versions:**  
 - Adapter version: <1.4.16>
 - JS-Controller version: <5.0.3> 
 - Node version: <v18.16.0> 
 - Operating system: <Debian 4.19.269-1 (2022-12-20) ×86_64>

**Additional context**  

Der iOBroker scheint ja zu laufen: Ich komme auf die Konsole (was ich gar nicht brauche: Aber für die o.a. Anweisungen "determine this with ... on the console" hab ich natürlich die Konsole aufgerufen).
Ich komme auch bspw mit http://192.168.178.201:8081/#tab-logs auf die Tabs...  Nichts Auffälliges.
Der Aufruf von "http://192.168.178.201:8082/vis/index.html?ALF1#ALF1_Home" führt allerdings zum Fehler "File index.html not found: {}".

Hatte ich noch nie.
Bin damit auch völlig hilflos: Was muss ich tun?
Welche Angaben kann ich noch machen?

LG 
M

**Comment by nobodyMO** [comment]
Hi, hatte dieselben Probleme.
Die controller-Versionen 5.x löschen bei der Installation fleißig Dateien der Adapter. bzw. installiert einfach alle Adapter mit npm neu Dies betrifft auch meine node-red nodes, die leider nicht alle automatisch wieder korrekt installiert werden (weil aus github und nicht npm).

Das Problem mit VIS lässt sich relativ einfach beheben. Im admin auf den Reiter Adapter gehen, Den Experten-Modus anschalten, falls noch nicht geschehen und für den Eintrag Visualisierung hinten auf Dateiupload klicken. Danach sollte es wieder gehen.

**Comment by MichaelSchaaf999** [comment]
Danke für die Info, nobodyMO,
wo und was ist denn "im Admin" und "auf den Reiter Adapter"?
Hier?
<img width="113" alt="grafik" src="https://github.com/ioBroker/ioBroker.vis/assets/53481090/b9c9ca87-a2e1-4d35-a795-8e4bafea2a8b">
Systemeinstellungen?

Oder gibt es einen Link "Admin", bspw "http://192.168.178.201:8081/#tab-admin"?
Da kommt aber nix.

Da ich da, glaube ich, noch nie war, bin ich da etwas ratlos, sorry.

**Comment by MichaelSchaaf999** [comment]
oder nur "admin"?
Da kommt aber eine Fehlermeldung:
<img width="534" alt="grafik" src="https://github.com/ioBroker/ioBroker.vis/assets/53481090/0c75f0c5-b3a7-4e40-bf77-0b6ea15e1a9c">

**Comment by MichaelSchaaf999** [comment]
Also: Anscheinend meinst Du dies, @nobodyMO 

<img width="1362" alt="grafik" src="https://github.com/ioBroker/ioBroker.vis/assets/53481090/95ebe615-b893-4dfe-9bc1-9b57bf7d1ae1">
- Das ist wohl die "Admin"-Oberfläche.
- Der Reiter "Adapter" ist ausgewählt. 
-  Dort finde ich den Eintrag "Visualisierung" und 'hinten' den Dateiupload.
-  Dann läuft irgendetwas ab, kenn ich nicht, sieht aber spannend aus.
-  Danach wieder auf "http://192.168.178.201:8082/vis/index.html?ALF1#ALF1_Home":
    Fehler.

<img width="668" alt="grafik" src="https://github.com/ioBroker/ioBroker.vis/assets/53481090/f67912b9-72d5-4bad-9fa5-a739ae88519a">

Und was mach ich nun?

**Comment by MichaelSchaaf999** [comment]
Hi  @nobodyMO,
vorweg: Es läuft jetzt. 
Obwohl der erste Upload ja durchaus fehlerfrei durchgelaufen ist, hab ich den nochmal laufen lassen: Meine Annahme war, dass man damit nicht viel kaputtmachen kann.

Danach liess sich bspw "http://192.168.178.201:8082/vis/index.html?ALF1#ALF1_Solaranzeige_3" problemlos und ohne die o.a. Fehlermeldung "File index.html not found" aufrufen.

Also vielen Dank für Deine Hilfe! Ohne Dich wäre ich bei diesem Problem echt voll aufgeschmissen gewesen, zumal sich auch BlueFox noch nicht dazu gemeldet hatte. 
1000Dank!

LG
M

Unabhängig von dem von Dir geschilderten Issue ("controller-Versionen 5.x löschen bei der Installation fleißig Dateien der Adapter") close ich dieses Ticket dann aber mal, jedenfalls für mich okay soweit.
greeez
