### ISSUE TITLE
Since last Update (1.4.16) HTML Widget not working

### ISSUE THREAD

**Issue by heckmic** [ioBroker/ioBroker.vis#733]
Since last Update (1.4.16) no HTML is working anymore.

**Comment by heckmic** [comment]
The HTML Element:

  <section>
    <div style="padding: 25px 50px 75px 100px";>
    <div class="loader" style="padding-left:260px;">
      <div class="dotbig" style="--i:0; --colour:#ffff00;"></div>
      <div class="dotbig" style="--i:1; --colour:#ffff00;"></div>
      <div class="dotbig" style="--i:2; --colour:#ffff00;"></div>
      <div class="dotbig" style="--i:3; --colour:#ffff00;"></div>
    </div>
     </div>
  </section>

**Comment by heckmic** [comment]
HTML wich is not working anymore:

```
  <section>
    <div style="padding: 25px 50px 75px 100px";>
    <div class="loader" style="padding-left:260px;">
      <div class="dotbig" style="--i:0; --colour:#ffff00;"></div>
      <div class="dotbig" style="--i:1; --colour:#ffff00;"></div>
      <div class="dotbig" style="--i:2; --colour:#ffff00;"></div>
      <div class="dotbig" style="--i:3; --colour:#ffff00;"></div>
    </div>
     </div>
  </section>  
```

**Comment by heckmic** [comment]
CSS was lost after update. Got i from Backup.

**Comment by Feuer-sturm** [comment]
@heckmic So the issue can be closed?

**Comment by bruno4712** [comment]
calling UI from iobroker this dump occurs:

URIError: Failed to decode param '%web_protocol%://192.168.2.119:%web_port%/vis/edit.html'
    at decodeURIComponent (<anonymous>)
    at decode_param (/opt/iobroker/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/opt/iobroker/node_modules/express/lib/router/layer.js:148:15)
    at matchLayer (/opt/iobroker/node_modules/express/lib/router/index.js:585:18)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:226:15)
    at compression (/opt/iobroker/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:328:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:346:12)

**Comment by Feuer-sturm** [comment]
@bruno4712 Is your web instance running? How does the configuration of your web instance look like?

**Comment by bruno4712** [comment]
vis instance is running for sure.  I can not start my view for edit. The dump will thrown here too.

this is my config:

Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 2
Geschwindigkeit: 1397 MHz
Modell: AMD G-T48E Processor
RAM: 3.4 GB
System-Betriebszeit: 02:50:50
Node.js: v16.20.0
time: 1687967570573
timeOffset: -120
Adapter-Anzahl: 475
NPM: v8.19.4
Datenträgergröße: 13.1 GB
Freier Festplattenspeicher: 8.2 GB
Betriebszeit: 02:50:29
Aktive Instanzen: 9
Pfad: /opt/iobroker/
aktiv:

**Comment by bruno4712** [comment]
downgrade to all versions down to 14.6.8 will not help any further. Same dump occurs.

**Comment by Feuer-sturm** [comment]
@bruno4712 Do you mean with "14.6.8" a downgrade to nodejs 14.6.8?

This is how the config of my web.0 instance look like.
![grafik](https://github.com/ioBroker/ioBroker.vis/assets/25422320/477c5355-55dc-4c26-9420-260625fe9a76)


What are the settings of your web.0 instance?

**Comment by bruno4712** [comment]
No, I have downgraded VIS only to 14.6.8. But WEB instance was not running ;-) Thanks, I have started the WEB adapter now. VIS 1.4.16 works fine now. Is there a description that both adapter have to run?

**Comment by bruno4712** [comment]
Sollte ich hier Web Sockets ankreuzen?

**Comment by Feuer-sturm** [comment]
@bruno4712 Ja die web Instanz muss auch laufen. Übernehme ruhig die Einstellungen wie ich sie oben gepostet habe, damit sollte es dann auch bei dir funktionieren.

**Comment by bruno4712** [comment]
Danke. Ich habe Web Socket aktiviert. Wenn es Probleme damit gibt, melde ich mich wieder. Nun kann ich mich wieder mit meinem Zigbee Adapter rumärgern. Der läuft einfach nicht stabil. Da kann mir auch keiner helfen. Mal ein guter Grund JS richtig zu lernen, habe sonst immer was anderes programmiert. Meine Quick Hacks haben da noch nicht viel geholfen. Gibt es irgendwo eine Beschreibung wie die Adapter funktionieren? Dann könnte ich auch vielleicht verstehen, wie die beiden Adapter zusammen arbeiten ...

https://github.com/ioBroker/ioBroker.zigbee/issues/1735
https://github.com/Koenkk/zigbee-herdsman-converters/issues/5826

**Comment by Feuer-sturm** [comment]
@bruno4712 Ich mach dann das issue hier erstmal zu. Bzgl. zigbee hast du ja schon ein issue angelegt. Ich kann dir da leider nicht weiterhelfen.
