### ISSUE TITLE
Ein VIS Projekt öffnet sich nicht mehr

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.vis#734]
**Describe the bug**  
Connecting to Server...   Loading Values...
Dann passiert nichts mehr.

iOBroker läuft, aber die Visualisierung nicht. Weder Edit noch Index.

Andere Projekte lassen sich öffnen: Dies eine nicht mehr.

**To Reproduce**  
...

**Expected behavior**  
VIS edit und VIS index sollten das Projekt wieder zeigen

**Screenshots & Logfiles**  
n.a.

**Versions:**  
 - Adapter version: <1.4.16>
 - JS-Controller version: <5.0.5> 
 - Node version: <18.16.0> 
 - Operating system: <Debian 4.19.269-1> in einer Proxmox-VM

**Additional context**  
...

Was kann oder muss ich tun?

**Comment by MichaelSchaaf999** [comment]
@GermanBluefox 
Hast Du eine Idee? Was kann ich tun?
btw: tab-echarts meldet wieder "File tab.html not found".
Hab ich durch Zufall entdeckt.
Aber ein Dateiupload auf dem Adapter Visualisierung bringt keine Besserung. Dieser Hinweis kam mal von @nobodymo  beim Ticket #732 File index.html not found.

**Comment by Apollon77** [comment]
* "iob upload vis"
* vis restarten
* Bei dem einen Projekt bitte inner Browser Javascript konsole nach fehlern schauen

**Comment by MichaelSchaaf999** [comment]
Danke sehr! Nach Beseitigen der Speicher"probleme" läuft auch der VIS-Aufruf erstmal wieder.
Thx.
