### ISSUE TITLE
error "no valid VIS license found" if internet connection is broken

### ISSUE THREAD

**Issue by pustelbaer** [ioBroker/ioBroker.vis#742]
Last week my internet router died, so that my local network is no longer connected to the internet. At this point my VIS runtime stopped working. It showed me the Web content for only 2 or 3 seconds, then a message appears "no valid VIS license found...".
This is very annoying.

I'm using a private/free license with the latest adapter versions from the release branch.

In the log I've found the following message; 

<html><body>

  | error | Cannot check license: Error: getaddrinfo EAI_AGAIN iobroker.net
-- | -- | --

</body>
</html>

I tried to fix it by using a teethering hotspot and a network bridge on my Windows notebook. With this configuration I was able to check the license in the configuration of the VIS instance: It replied with an 'OK', but the VIS frontend is still showing the license error. 
Please fix! The visualization should be usable even with a broken internet connection. Thanks!

**Comment by Feuer-sturm** [comment]
Hi @pustelbaer , for this use case you will need the "vis offline" licence.
Details you can find for example here: https://forum.iobroker.net/topic/46334/neue-vis-offline-lizenz-f%C3%BCr-die-private-nutzung

**Comment by pustelbaer** [comment]
Hi @Feuer-sturm, many thanks for the hint. I would like to buy an offline license, but I am concerned about the serial number. My iobroker runs in a Docker container. I already had to reinstall it 3 times due to problems. If I understand it correctly, I would get a new serial number with each reinstallation!? Then my license would be lost, or am I missing something?

**Comment by Apollon77** [comment]
Ideally restore a backup, then the ID will not change . I worst case you can request an uodated serial via email
