### ISSUE TITLE
Widget jqui-mfd - ctrl,shutter,dialog Shutter + jqui Dialog

### ISSUE THREAD

**Issue by mctom** [ioBroker/ioBroker.vis#75]
In dem Moment wo die Object ID ausgewählt wird verschwindet das Widget. Es ist nur noch über das Pulldown Aktiv Widget zu finden und zu löschen.

**Comment by GermanBluefox** [comment]
Ist das jetzt besser?

**Comment by mctom** [comment]
Ja die Funktion ist jetzt OK. Eine kleine Funktion wäre noch klasse. Wenn das Rollo zu oder auf ist (je nach Userwunsch) soll das Icon aktiv angezeigt werden. Zur Zeit ist es nur möglich immer aktiv oder inaktiv.

**Comment by GermanBluefox** [comment]
Kannst du bitte das klären am besten mit ein paar Screenshots
