### ISSUE TITLE
Vis-2 V2.1.5: Vis editor lädt nicht. Seite bleibt komplett schwarz

### ISSUE THREAD

**Issue by IoBMarcios** [ioBroker/ioBroker.vis#753]
Hi, 

nach Installation von Vis-2 öffnet der Editor zwar, allerdings bleibt der Bildschirm komplett schwarz. Im Log wird kein fehler angezeigt.

Hier der bericht meines Browsers:

iobroker.vis-2-beta@2.1.4 using theme "dark"
main.6c4ff8e5.js:2 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.6c4ff8e5.js:2 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.6c4ff8e5.js:2 Help us to create open source project with reactJS!
main.6c4ff8e5.js:2 See you :)
socket.io.js:66 [2023-07-30T08:22:07.976Z] Try to connect
554.68737bc5.chunk.js:2 Translate: Grid color
554.68737bc5.chunk.js:2 Translate: Grid size
554.68737bc5.chunk.js:2 TypeError: Cannot read properties of undefined (reading 'name')
    at renderValue (View.jsx:322:77)
    at main.6c4ff8e5.js:2:5328644
    at Ca (main.6c4ff8e5.js:2:6787700)
    at Vi (main.6c4ff8e5.js:2:6797810)
    at Cs (main.6c4ff8e5.js:2:6846876)
    at Hl (main.6c4ff8e5.js:2:6833919)
    at gl (main.6c4ff8e5.js:2:6833847)
    at zl (main.6c4ff8e5.js:2:6833710)
    at al (main.6c4ff8e5.js:2:6830490)
    at ol (main.6c4ff8e5.js:2:6829041)
    at V (main.6c4ff8e5.js:2:8260120)
    at MessagePort.T (main.6c4ff8e5.js:2:8260654)
(anonymous) @ 554.68737bc5.chunk.js:2
main.6c4ff8e5.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at renderValue (View.jsx:322:77)
    at main.6c4ff8e5.js:2:5328644
    at Ca (main.6c4ff8e5.js:2:6787700)
    at Vi (main.6c4ff8e5.js:2:6797810)
    at Cs (main.6c4ff8e5.js:2:6846876)
    at Hl (main.6c4ff8e5.js:2:6833919)
    at gl (main.6c4ff8e5.js:2:6833847)
    at zl (main.6c4ff8e5.js:2:6833710)
    at al (main.6c4ff8e5.js:2:6830490)
    at ol (main.6c4ff8e5.js:2:6829041)
    at V (main.6c4ff8e5.js:2:8260120)
    at MessagePort.T (main.6c4ff8e5.js:2:8260654)
554.68737bc5.chunk.js:2 Version vis-colorpicker: 2.0.3
554.68737bc5.chunk.js:2 Version vis-history: 1.0.0
554.68737bc5.chunk.js:2 Version vis-jqui-mfd: 1.0.12
554.68737bc5.chunk.js:2 Metro version: "1.2.0"
554.68737bc5.chunk.js:2 Version vis-weather: 2.5.6
554.68737bc5.chunk.js:2 Version vis-colorpicker: 2.0.3
554.68737bc5.chunk.js:2 Version vis-history: 1.0.0
554.68737bc5.chunk.js:2 Version vis-jqui-mfd: 1.0.12
554.68737bc5.chunk.js:2 Metro version: "1.2.0"
554.68737bc5.chunk.js:2 Version vis-weather: 2.5.6
554.68737bc5.chunk.js:2 Version justgage: 1.0.2
554.68737bc5.chunk.js:2 Version trashschedule: 2.2.0
554.68737bc5.chunk.js:2 Version tvprogram: 0.0.1
554.68737bc5.chunk.js:2 Version iobroker.vis-keyboard: 0.0.2
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/static/js/main.6c4ff8e5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/static/js/554.68737bc5.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_translations_js.395fc3f6.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_translations_js.10c291be.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_translations_js.cace16e5.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Wizard_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.30d0a143.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_ConsumptionComparison_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.9872d5b0.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Generic_jsx-src_ObjectChart_jsx.a869e768.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Actual_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.f3367609.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Components_BlindsBase_js.a97ca885.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Thermostat_jsx.45f6cba5.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Blinds_jsx-src_Generic_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.646317ad.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_SimpleState_jsx.a0141dc2.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_ViewInWidget_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.2af4d761.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Switches_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.92ab537c.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Security_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.11a2b3dc.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Player_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js-node_modules_babel_-7005d6.3ba6f752.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Camera_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.8a40c365.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_ThemeSwitcher_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.32bdf261.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Html_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.e5b84709.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_WasherDryer_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.1d6f4dd1.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Clock_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.2625ef46.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_Consumption_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.cca5fa90.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_IntervalSelector_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.451e9be7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_Distribution_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js.32473956.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_ColorGauge_jsx-node_modules_babel_runtime_helpers_esm_defineProperty_js-node_modules_babe-17d7ec.7cfe7aba.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_WaterGauge_jsx.55c65fc6.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_BatteryGauge_jsx.9a9b6397.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.123.34:8082/vis-2-beta/widgets/vis-2-widgets-material/static/css/src_Map_jsx-node_modules_react_cjs_react-jsx-runtime_production_min_js-node_modules_leaflet_d-16aa83.be92513e.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Feuer-sturm** [comment]
@IoBMarcios poste bitte einmal die Einstellungen von deiner web Instanz.

**Comment by IoBMarcios** [comment]
![web](https://github.com/ioBroker/ioBroker.vis/assets/140943500/1ec9a6b2-0c0c-42e9-b619-67d5f533a3e4)

**Comment by Feuer-sturm** [comment]
@IoBMarcios vis-2-beta adapter is stopped. The current development will continue with vis-2 adapter (please see https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta)

please install vis-2 adapter and try once again (current version 2.2.2)
If the issue is still present, please open a new issue here: https://github.com/ioBroker/ioBroker.vis-2/issues
