### ISSUE TITLE
iobroker vis 0 auf synology läuft nicht

### ISSUE THREAD

**Issue by Goldenfinn** [ioBroker/ioBroker.vis#762]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Goldenfinn** [comment]
Hallo,
will mit iobroker von raspbery pi auf synology umziehen. Habe bisher auch alles intalliert bekommen. Bis auf influx db und shelly laufen auch schon alle Adapter. Beim aufruf von vis kommt Meldung Seite nicht erreichbar. Lizens ist geprüft und ok
Danke für eure Hilfe

**Comment by Feuer-sturm** [comment]
@Goldenfinn hast du ein Backup eingespielt? Wenn ja, bitte erst vis installieren (ich nehme an du sprichst von vis1) und dann das Backup einspielen

**Comment by Goldenfinn** [comment]
Hi,
habe auf Synology zuerst vis adapter installiert. Steht dort unter vis0. Vis lässt sich nicht öffnen. " Seite nicht erreichbar".IP Adresse der Synology ist richtig. Port ist 8082. komischer Weise läßt sich Habpanel auch nicht öffnen. Hatte ich auf raspberry nicht installiert. An der Öffnung Ports kann es auch nicht liegen, da ich mit influxdb Port 8086 kein Problem habe. Woran kann es noch liegen?

**Comment by Feuer-sturm** [comment]
@Goldenfinn Erstelle am besten ein Thread im iobroker Forum. Dort wirst du schnell Hilfe bekommen. Das ganze klingt nicht nach einem vis ssue. Mein Vorschlag: das issue hier schließen und Problem im Forum diskutieren.
