### ISSUE TITLE
VIS 1.4.16 Keine gültige Lizenz gefunden

### ISSUE THREAD

**Issue by ReneIoFan** [ioBroker/ioBroker.vis#767]
Hallo zusammen,

Seit einigen Tagen habe ich Probleme mit der VIS. Es wird angezeigt das keine gültige Lizenz gefunden werden kann.

Ich habe in den Foren gelesen, dass auch die Vorgängerversionen das Problem hatten, kann jedoch leider die Lösungen dieses Problems nicht finden.

Kann mir hier jemand weiterhelfen?

Danke Euch!

**Comment by Feuer-sturm** [comment]
@ReneIoFan Bitte ergänze deinen Beitrag um ein paar Informationen.  Wo wird angezeigt das keine gültige Lizenz gefunden werden kann? (Screenshots). Welche Admin Version verwendest du? Welche VIS Lizenz hast du dir geholt (iobroker.vis oder iobroker.vis.offline)?

**Comment by ReneIoFan** [comment]
Vielen Dank @Feuer-sturm für Deine Antwort!!

Das ist die ADMIN Version 6.3.5. Angezeigt wird es in der VIS Runtime. Auch im VIS Editor blinkt die 1.4.16 durchgehend oben links in der Ecke des Bildschirms. Als VIZ Lizenz habe ich die iobroker.vis.offline
![Screenshot 2023-08-15 155931](https://github.com/ioBroker/ioBroker.vis/assets/142170510/4d96d270-029f-4abe-8d57-9cace66568d9)
![Screenshot 2023-08-15 155826](https://github.com/ioBroker/ioBroker.vis/assets/142170510/71c25803-8270-4aa2-9ab4-fb36fda31444)
![Screenshot 2023-08-15 160909](https://github.com/ioBroker/ioBroker.vis/assets/142170510/f1d97b62-fd0a-4755-a5de-239139b4105f)
![Screenshot 2023-08-15 155958](https://github.com/ioBroker/ioBroker.vis/assets/142170510/96f173d8-b3be-4d43-a5fd-fefc72fc47bc)
![Screenshot 2023-08-15 160622](https://github.com/ioBroker/ioBroker.vis/assets/142170510/3af45847-1b5b-462d-b97c-9f250079d603)

**Comment by Feuer-sturm** [comment]
@ReneIoFan Hast du schon überprüft, das der vis.offline Key auch der korrekte Key ist, welchen du in der VIS Instanz eingetragen hast (und nicht der normale VIS Lizenz key?)
Hast du deinen ioBroker ggf. komplett neu aufgesetzt und es hat sich die Seriennummer (steht in der Konfiguration der VIS Instanz) geändert? Die VIS offline Lizenz ist abhängig von der Seriennummer.
Siehe auch die Erklärung bei der vis.offline Lizenz unter iobroker.net
![grafik](https://github.com/ioBroker/ioBroker.vis/assets/25422320/adb0f3db-d5f0-4f86-b386-695bc6176763)
In diesem Fall schreib mal eine Mail an info@iobroker.net, dort wirst du sicherlich weitere Hilfe bekommen.

**Comment by ReneIoFan** [comment]
@Feuer-sturm Danke für die Hinweise. Neu aufgesetzt habe ich in der Zeit nichts. Ich habe auch mal die IDs verglichen, das passt scheinbar alles. Auch kann ich im IObroker die Lizenz nicht verwalten. Das geht automatisch über den Lizence Manager, den ich leider auch nicht abwählen kann.

Ich befolge Deinen Rat und gehe direkt auf den Support zu. Danke Dir!

![Screenshot 2023-08-17 120239](https://github.com/ioBroker/ioBroker.vis/assets/142170510/3657bb9d-a80f-499b-9c0c-4a368da3650a)
