### ISSUE TITLE
Verhalten von Widget Dropdown 'Zeige in Views'

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.vis#77]
Das Dropdown verhält sich unschön, insofern, dass beim ersten Öffnen und Auswählen einer zusätzlichen View, sich das Feld sofort wieder schliesst. Werden weitere Views in einem zweiten Anlauf  angeklickt, bleibt das Dropdown offen bis man fertig ist.
Besser wäre, es würde von Anfang an offen bleiben bis alle nötigen Views angeklickt sind.

**Comment by GermanBluefox** [comment]
Sollte in der neuen Version gefixt werden.
