### ISSUE TITLE
BarChart widget: Color for labels is not set.

### ISSUE THREAD

**Issue by nanosonde** [ioBroker/ioBroker.vis#78]
The color for the labels is not set and uses the default color "black" for bar charts.
All other colos canbe changed successfully.
https://github.com/ioBroker/ioBroker.vis/blob/master/www/widgets/RGraph.html

Something like this should exist for `tplRBarChart`:

```
t.Set('text.color', data.attr("labels_color"));
```

and to make it available for editing:

```
data-vis-attrs4="group.labels;labels_color[#000000]/color;labels_font/fontname;labels_size/slider,1,100;labels_centered/checkbox;labels_offset/slider,-500,500,1;"
```

**Comment by GermanBluefox** [comment]
Must be fixed
