### ISSUE TITLE
update von 1.4.16 auf 1.5.1 - edit geht nicht mehr

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.vis#800]
https://forum.iobroker.net/topic/69951/vis-1-x-revived-als-mit-community-projekt-ohne-lizenz/49
https://forum.iobroker.net/topic/69988/keine-g%C3%BCltige-vis-einstellung-gefunden/14?page=1

Bei 1.4.16 kam ich normal in den edit Modus von VIS.
Dann update auf 1.5.1; bei Aufruf von edit kommt dann "no connection".

Dann wieder downgrade auf 1.4.16; und alles läuft wieder.

Fazit:
Mit 1.5.1 komme ich nicht mehr in den edit Modus.

**Comment by GermanBluefox** [comment]
Gibt es irgendwelche Fehlermeldungen im Browser Konsole?

**Comment by bahnuhr** [comment]
Ja, siehe
https://forum.iobroker.net/topic/70129/vis-update-auf-1-5-1-no-connection-bei-edit/26?_=1699785740369

**Comment by champ0209** [comment]
Hallo, ich kann mich nur anschließen!
Habe nun ebenfalls das Problem, dass sich der Vis-Editor nicht mehr öffnen lässt (No connection)

**Comment by GermanBluefox** [comment]
> Hallo, ich kann mich nur anschließen! Habe nun ebenfalls das Problem, dass sich der Vis-Editor nicht mehr öffnen lässt (No connection)

> Gibt es irgendwelche Fehlermeldungen im Browser Konsole?

Ich kann nur die Frage die ich an @bahnuhr gestellt habe wiederholen.

Die Einstellungen in web sind (integriert, Reine Websockets)?
Die vis version ist 1.5.1?

**Comment by champ0209** [comment]
Jep! Vis Version 1.5.1 Web steht auf integriert.
Reine Websockets funktioniert, sowohl mit gesetztem Haken als auch ohne den Haken nicht.
Nachtrag! Vis2 Beta läuft!

**Comment by GermanBluefox** [comment]
> Jep! Vis Version 1.5.1 Web steht auf integriert. Reine Websockets funktioniert, sowohl mit gesetztem Haken als auch ohne den Haken nicht.

Wurde dann auch Ctrl+F5 gemacht? Nach der Umschaltung von Reine-WS/Scoket.io? Ist nötig dabei den Browser-Cache zu löschen

**Comment by champ0209** [comment]
Browser-Cache gelöscht, anderen Browser incl. anderes Endgerät verwendet. Leider ohne Erfolg.

**Comment by bahnuhr** [comment]
Ich auch; Browser Cache wurde gelöscht.
Einstellungen: integriert + Reine-WS -> no connection
oder nur unten WS -> no connection

**Comment by bahnuhr** [comment]
So, jetzt habe ich alles deinstalliert was mit vis zusammen hängt. Alle Adapter mit vis.
Dann browser cache gelöscht.
und versucht vis über git zu installieren; dann kam Fehler 25.
Fazit:
Frische Installation über git mit V 1.5.1. ist nicht möglich.

Jetzt muss ich ein 2 Tage altes backup per proxmox einspielen. 2 Tage Daten sind halt nun weg.
Schade.

Eine Lösung des Problems wäre gut. Bin ja anscheinend doch nicht der Einzige.

**Comment by Apollon77** [comment]
ÄÄhhmm??? 
1.) Fehler 25 ?? "iob fix" ...
2.) Warum vopn git?

**Comment by bahnuhr** [comment]
auch ÄÄhhmm ???
iob fix mach ich einmal die Woche.
1.5.1 wie sonst installieren ?

Nachtrag:
@Apollon77 
was ich alles schon probiert habe, hast du ja in den threads schon gelesen. Hast mich ja dazu angeregt extra einen separaten aufzumachen. Obwohl mein Beitrag ja bei deinem vis 1. sehr gut dazu gepasst hat.
Und ÄÄhhmm war sehr unangemessen.
(aber vielleicht liegt es heute auch an mir)
Und sollte ich der Einzige (fast) sein, dann können wir das issue auch gerne schließen.

**Comment by Apollon77** [comment]
Naja vis 1.5.1 ist im latest repo. GitHub install ist da nicht nötig. Deswegen war ich überrascht. Sorry für das äähm in dem Zusammenhang. Und ja Error 25 ohne weitere Details sind wieder komische npm Struktur Dinge die iob fix halt behebt. 

Ich würde es ja auch gern verstehen warum es bei dir nicht geht aber kann gerade nur dafür sorgen das die Infos das sind.

**Comment by bahnuhr** [comment]
Nein !
1.5.1 ist nicht im latest. 
Aber vielleicht bin ich ja auch da wieder der Einzige.

Wenn du Infos haben willst, dann sag mir welche. Ich bin für alles offen (gerne auch anydesk).
Von alleine mache ich nun nichts mehr.
1.5.1. läuft bei mir nicht.
Warum weiß ich nicht.

Noch ein Thema:
du schreibst im thread: integriert weglassen und ws an
bluefox schreibt oben: integriert an und ws an

Vielleicht könnte man sich da einigen.

P.S.
Und wenn keiner antwortet oder ich anscheinend wirklich der fast Einzige bin, dann kann ich das issue auch gerne schließen.

**Comment by arto5754** [comment]
Habe genau das selbe Problem.

**Comment by Anbima** [comment]
Bei mir auch das selbe Problem.

**Comment by champ0209** [comment]
Kleine Ergänzung! Bei mir funktioniert der Editor von Vis1 nun wieder und auch meine alten Visualisierungen funktionieren wieder. Ich hatte aber vermutlich ein ganz anderes Problem. Seitdem ich Redis auf dem System installiert hatte, hat sich der iobroker regelmäßig aufgehängt. Ich habe Redis gerade deaktiviert uns siehe da, das System läuft wieder stabil und ich komme auch wieder an den Vis1 Editor. Jetzt habe ich nur noch das Problem, dass Vis2 die von Vis1 portierte Lizenz nicht akzeptiert. Dafür habe ich ein Ticket bein ioBroker-Team geöffnet.

**Comment by bahnuhr** [comment]
Redis kann bei mir nicht das Problem sein.
Benutze ich nicht.

**Comment by TomBom41** [comment]
Ich habe das gleiche Problem. Wenn ich den vis1 Adapter im ioBroker aktualisieren will erhalte ich die folgende Fehlermeldung:

Aktualisieren "vis" auf v1.5.1
Dependencies
web (>=3.0.12): 5.2.10

js-controller (>=2.0.0): 4.0.9

**node (>=16): 14.19.0**

Änderungen
1.5.1(vor 9 Tagen)

• Changed License: it is now MIT, and the license check was removed
1.4.16

• Corrected connection with "only port" URLs

**Comment by TomBom41** [comment]
Es hat sich geklärt. Alles funktioniert
Der Update ging nach dem Löschen der Cookies und der Zugriff auf den Fronis ging nach dem Einschalten des API (Im Fronius Menü Kommunikation-Solar API-Kommunikation über Solar API aktivieren

**Comment by bahnuhr** [comment]
Bei mir läuft es auch.
Installiert über npm (nicht git); cache gelöscht; und dann kam ich wieder auf edit.
Fazit:
habe 1.5.1 drauf und es läuft.
