### ISSUE TITLE
vis adapter instantiation is hanging

### ISSUE THREAD

**Issue by HarryHpd** [ioBroker/ioBroker.vis#801]
I am not able to install iobroker.vis 

it appears to me, the problem is not in vis but in iobroker.web instantiation.

The process is hanging at 

![grafik](https://github.com/ioBroker/ioBroker/assets/23189400/ad9778f3-b741-457a-869b-853aa91eada4)

the same problem appears if I try to create a iobroker.web instance.

![grafik](https://github.com/ioBroker/ioBroker/assets/23189400/537fba0a-75bb-489a-b79d-cf712f49ff7e)

**Systeminfos**

    Plattform: linux
    Betriebssystem: linux
    Architektur: x64
    CPUs: 2
    Geschwindigkeit: 2901 MHz
    Modell: Intel(R) Core(TM) i5 CPU M 520 @ 2.40GHz
    RAM: 0 MB
    System-Betriebszeit: 01:56:48
    Node.js: v18.18.2
    time: 1700073089052
    timeOffset: --
    NPM: 9.8.1
    Adapter-Anzahl: 510
    Datenträgergröße: 7.8 GB
    Freier Festplattenspeicher: 3.0 GB
    Aktive Instanzen: 10
    Pfad: /opt/iobroker/
    Betriebszeit: 01:26:24
    aktiv:

**Comment by Apollon77** [comment]
Did you checked your computer? Is anything on 100% CPU? Mem issue? any indication of othert issues?

**Comment by HarryHpd** [comment]
... Oh dear, you are on the right track.

my sandbox iobroker sits on a proxmox server and I had indeed very limited
memory (1Gb). After increasing it to 4Gb instantiation is done within
seconds.

You can close this issue.

Many thanks

Am Do., 16. Nov. 2023 um 09:48 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by HarryHpd** [comment]
Add on....

4Gb of memory was still not enough to instantiate echart es well.

After increasing it to 8Gb I got it to finalize this instantiation.

Am Do., 16. Nov. 2023 um 09:48 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by MichaelSchaaf999** [comment]
echarts seems to be a memory-eater - here as well.
And the usage slows down the system performance: Can be demonstrated if this adapter is de-activated (Proxmox performance graphics)

**Comment by HarryHpd** [comment]
... good to know.
I am currently in a evaluation phase and a iobroker newbie. I am not sure
which graphics engine I will use for my time series. I know grafana for a
long time. I just tried e-charts now, because I thought it might be the
only choice I have to integrate time series charts in vis.



Am Do., 16. Nov. 2023 um 11:50 Uhr schrieb MichaelSchaaf999 <
***@***.***>:

**Comment by Apollon77** [comment]
Ok thats all interesting ... and yes intertingly enought echarts (and also web?) seems siometimes have issues when beuing uploaded.
(@foxriver76 another case). Please share yiur nodejs versions and such.

When echarts needs too much CPU when running please open an echarts issue with details

**Comment by Feuer-sturm** [comment]
@Apollon77 I see the issue of massive RAM consumption on different adater updates (uploads) like vis2, fullcalender as well. Currentl my production system has 8 GByte RAM which are sporadically necessary to update some adapters. 
This problem should be tracked somewhere else (js-controller??) but I think it is not a vis specific issue.

**Comment by foxriver76** [comment]
Is it during the npm install or during upload?

**Comment by Feuer-sturm** [comment]
@foxriver76 on my system during upload

**Comment by foxriver76** [comment]
Then controller issue

**Comment by Feuer-sturm** [comment]
@foxriver76 Issue created https://github.com/ioBroker/ioBroker.js-controller/issues/2538
