### ISSUE TITLE
vis 1,5.2 "no connection" when trying to edit my visualisation

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.vis#808]
Entering ip address of iob vis editor in my browser (http://192.168.1.23:8082/vis/edit.html?vis2023#Wetter) leads to an empty screen and error message "no connection"
Firefox browser, iobroker on a proxmox container
proxmox 8.1.3, container debian 12
iob node.js 18.18.2, npm 9.8.1, js-controller 5.0.16

Switching back to vis 1.5.1 --> Everything works fine

**Comment by guergen1** [comment]
s.o.
selbes Problem, selbe Konfig ausser Proxmox VM
![grafik](https://github.com/ioBroker/ioBroker.vis/assets/34395245/419e7288-a4c2-46fd-895c-12cdf32d9b87)

**Comment by MK-66** [comment]
Same problem with 1.5.2 for me too; vis editor "No connection", vis runtime ok.

JS-controller version: 5.0.16
WEB-Server: 6.1.10 
Node version: 18.18.2

Operating system: Debian 12 VM (Proxmox)

**Comment by Apollon77** [comment]
Which settings you have i web adapter fort websockets? ws? Socketio? Builtin?

**Comment by amg666** [comment]
![grafik](https://github.com/ioBroker/ioBroker.vis/assets/45561610/067dcb8f-a506-4f17-956c-c5b80e4f3105)

**Comment by m-s-b** [comment]
@Apollon77 
Tried every combination of ws, socketio, built in.... Always the same result. "No connection" in editor, runtime works fine.

**Comment by m-s-b** [comment]
Browserkonsole gibt 2 Fehler aus.
`Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at main (vis.js:3471:47)
    at HTMLDocument.<anonymous> (vis.js:3982:9)
    at j (jquery-1.11.2.min.js:2:27295)
    at Object.fireWith [as resolveWith] (jquery-1.11.2.min.js:2:28108)
    at Function.ready (jquery-1.11.2.min.js:2:29942)
    at HTMLDocument.J (jquery-1.11.2.min.js:2:30308)`

markiert hier die Zeile:  document.querySelector('#webmanifest').setAttribute('href', manifestURL);

`Uncaught TypeError: Cannot read properties of undefined (reading '_socket')
    at Object.getObject (widgets.min.js:1:17444)
    at Object.getVersion (widgets.min.js:1:17552)
    at materialdesign.js:32:25
    at Object.waitForVisConnected (widgets.min.js:1:1025)
    at widgets.min.js:1:903`

hier die Zeile:    vis.conn._socket.emit("getObject", e, function(e, o) {

**Comment by m-s-b** [comment]
Mit der 1.5.4 läuft es bei mir wieder

**Comment by amg666** [comment]
Same here, I installed 1.5.4 via console and now it works
