### ISSUE TITLE
vis 1.5.4 on Google Chrome - the editor does not appear

### ISSUE THREAD

**Issue by MaaG-dA** [ioBroker/ioBroker.vis#827]
Windows 11, Google Chrome browser.. and blank edit screen vis 1.5.4.
In the case of the Edge browser, the appearance is ok.

Problem with screens are here (and solution):
https://forum.iobroker.net/topic/72212/vis-1-5-4-on-google-chrome-not-work?_=1706369353439

**Comment by Apollon77** [comment]
@GermanBluefox maybe in general all adapters that use localstprage (so also admin and such) SHould get an error handling in the case the local storage is invalid on restore and reset with a info message

**Comment by GermanBluefox** [comment]
It could help to clear cache and all local storage variables
![image](https://github.com/ioBroker/ioBroker.vis/assets/4582016/760c40b7-8560-4772-8ab3-a2777753c341)
or
![image](https://github.com/ioBroker/ioBroker.vis/assets/4582016/eea389f0-69fd-4a77-814a-ef67cbc89077)

**Comment by GermanBluefox** [comment]
Fixed in 1.5.6

**Comment by Feuer-sturm** [comment]
@MaaG-dA please check with current beta version 1.5.6 .

**Comment by MaaG-dA** [comment]
1.5.6 installed .. and work ;)

My problem was fixed as @Apollon77  wrote in his post.
"delete local storage in your browser and try again please."

@GermanBluefox thx for info and fix.
