### ISSUE TITLE
Dateimanager öffnet sich nicht mehr mit 1.5.6

### ISSUE THREAD

**Issue by saeft2003** [ioBroker/ioBroker.vis#844]
Ich kann mit der Version 1.5.6 in einem Widget unter Allgemein den Dateimanager nicht mehr öffen. Es passiert nichts. Der Dateimanager kann nur unter Setup geöffnet werden. 

Wenn ich ein downgrade auf 1.5.5 mache, kann der Dateimanager wieder wie gewohnt aus einem widget geöffnet werden.

**Comment by mcm1957** [comment]
Bitte bei allen Issues um vollständige Versionsangeben:

adapter: 1.5.6
js-controller:
admin:
node:
O/S:

**Comment by saeft2003** [comment]
adapter: 1.5.6
js-controller: 5.0.19
admin: 6.13.16
node: 18.20.3
O/S: bookworm (aktuell)

**Comment by saeft2003** [comment]
@mcm1957 

Konnte der Fehler nachgestellt werden?

**Comment by mcm1957** [comment]
Mir sind keine Informationen zur Bearbeitung bekannt.

**Comment by ohle64** [comment]
ubuntu 22.04.4 LTS, node v20.16.0, npm 10.8.1, js-controller 6.0.9, admin 7.0.22, web 6.3.0, ws 2.6.2, vis 1.5.6
Hi, ich konnte den Fehler weiter eingrenzen. Wenn bei einem Widget das Bild-Feld leer ist, öffnet der Dateimanager. Steht dort ein Wert drin - öffnet er nicht mehr. Keine Reaktion auf Mausklick. Getestet mit Firefox und Google Chrome.

**Comment by ThomasZappe** [comment]
> ubuntu 22.04.4 LTS, node v20.16.0, npm 10.8.1, js-controller 6.0.9, admin 7.0.22, web 6.3.0, ws 2.6.2, vis 1.5.6 Hi, ich konnte den Fehler weiter eingrenzen. Wenn bei einem Widget das Bild-Feld leer ist, öffnet der Dateimanager. Steht dort ein Wert drin - öffnet er nicht mehr. Keine Reaktion auf Mausklick. Getestet mit Firefox und Google Chrome.

Bei mir genau das gleiche Problem. Bin auf der Suche nach einer Lösung hier gelandet.

**Comment by Aniliner** [comment]
Auch ich habe das gleiche Problem. Dateimanager öffnet sich nicht, wenn ich im VIS Widget ein Bild ändern will. Bei neu erstellten Widgets (Image) öffnet sich zwar der Dateimanager, übernimmt aber das ausgewählte Bild nicht.
Gibt es inzwischen eine Idee woran das liegen kann?

**Comment by Heinz2100** [comment]
Hab auch dasselbe Problem.

**Comment by steefan85** [comment]
Habe dasselbe Problem. Wenn ich ein Bild eines Widgets ändern möchte und auf das Ordner-Symbol klicke, öffnet sich der Dateimanager nicht. Unter Setup kann er allerdings geöffnet werden.

adapter: 1.5.6
js-controller: 6.0.11
admin: 7.1.5
node: 20.17.0
O/S: Debian GNU/Linux 12 (bookworm)

**Comment by saeft2003** [comment]
@mcm1957 

anscheinend betrifft das Problem doch mehrere. Wird in Zukunft geschaut wo das Problem her kommt? Weil ich update deswegen im Moment VIS nicht und irgendwann wird das zum Problem…

**Comment by mcm1957** [comment]
Ich kann zur Entwicklung von vis (1) leider keinerlei Aussagen treffen.

@Apollon77, @foxriver76 
könnt ihr da was dazu sagen oder habt eine Idee an was das Problem liegen könnte?

**Comment by Apollon77** [comment]
Gibts Fehler irgendwo?JS Konsole? Screenshots? Welcher File Editor wo genau ist gemeint?  Visa Admin seite?

**Comment by saeft2003** [comment]
@Apollon77 

Mit VIS 1.5.6 öffnet sich hier der Dateimanager nicht mehr. Unter Setup --> Dateimanager kann er noch geöffnet werden.

![Unbenannt](https://github.com/user-attachments/assets/1f256d3f-749c-4ebc-a463-66dbb715a137)

Mit VIS 1.5.5 tritt das Problem nicht auf.

Mein System ist soweit aktuell:

js-controller: 6.0.11
admin: 7.1.5
node: 20.x
O/S: bookworm (aktuell)

**Comment by Apollon77** [comment]
Irgendwelche Fehler in der Browser JS Konsole wenn man es klickt oder davor?

**Comment by steefan85** [comment]
> Irgendwelche Fehler in der Browser JS Konsole wenn man es klickt oder davor?

Moin,

ich bekomme folgendes beim Klicken:

`Uncaught TypeError: Cannot create property 'path' on string '{"path":"/vis-icontwo/Weather/","view":"prev","all":false,"background":""}'
    at $.fm (fileManager.js:90:25)
    at HTMLButtonElement.click (visEditInspect.js:674:23)
    at HTMLButtonElement.dispatch (jquery-1.11.2.min.js:3:8549)
    at m.event.add.r.handle (jquery-1.11.2.min.js:3:5252)`

Das momentan verwendete Icon liegt allerdings in einem anderen Verzeichnis unter `/vis-icontwo/Arrows`.

**Comment by saeft2003** [comment]
> Irgendwelche Fehler in der Browser JS Konsole wenn man es klickt oder davor?

Und so bei mir...

`Uncaught TypeError: can't assign to property "path" on "{\"path\":\"http://192.168.178.106:5000/webapi/\",\"view\":\"prev\",\"all\":false,\"background\":\"\",\"filter\":\"\"}": not an object
    fm http://192.168.178.90:8082/vis/js/fm/fileManager.js:90
    click http://192.168.178.90:8082/vis/js/visEditInspect.js:674`

**Comment by saeft2003** [comment]
@Apollon77 

kannst du mit dem Error vom Browser etwas anfangen? Gibt es Hinweise was das Problem ist?

**Comment by ThomasZappe** [comment]
Wenn ich eine Seite zur Bearbeitung im Inkognitofenster öffne, funktionier alles fehlerfrei. So behelfe ich mir gerade aktuell.

**Comment by DEV2DEV-DE** [comment]
Browsercache löschen behebt das Problem!

**Comment by ohle64** [comment]
Browsercache löschen ohne Wirkung bei Bild auswählen, vis öffnen bei Browser in privaten Modus funktioniert. Bin wieder auf 1.5.5 zurück.

**Comment by saeft2003** [comment]
> Browsercache löschen behebt das Problem!

kann ich bestätigen funktioniert bei firefox. Vielen Dank für den Tipp!

Ich musste die web site daten und cookies löschen...

![Unbenannt](https://github.com/user-attachments/assets/131089ad-d6cd-43f4-b737-0df9dedde6ee)

**Comment by Aniliner** [comment]
Bei mir auch, wenn der Cache gelöscht wird (Firefox), funktioniert es wieder! Danke.

**Comment by steefan85** [comment]
Funktioniert ebenfalls unter Safari und Chrome. Vielen Dank!
