### ISSUE TITLE
V1.56 ohne Internet keine Funktion

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.vis#850]
bei mir ist Internet ausfgefallen. ioBroker läuft ganz normal aber ich kann sowohl vis den Editor als auch die View nicht aufrufen. Im Log sind keine Fehler. Adapter habe ich neu gestartet ohne Funktion. Habe schon länger keine Änderungen in vis vorgenommen. Gestern Abend mit Internet lief der Aufruf auch noch.

Wenn ich die Seite in Safari öffne bleibt die Seite einfach schwarz. Ich sehe in Safari oben unter der URL einen Ladebalken der ca. bis 1/3 der Adresszeile läuft und dann passiert nicht mehr. Trenne ich nun die Verbindung zum WLAN sehe ich auf der Seite den typischen Ladekreis von vis. Trenne ich die Seite nicht passiert das auch nach längerer Wartezeit nicht. 

Früher gab es eine Offline Lizenz, die ich auch gekauft habe. Gilt die noch? Oder gilt die nach Installation von vis2 nur noch dafür? vis2 läuft nämlich.

**Comment by mcm1957** [comment]
Die aktuelle vis Release benötigt KEINE Lizenz mehr

**Comment by Baenker** [comment]
Ok keine Lizenz dann läd Vis etwas aus dem Internet was nicht sein sollte? Internet ist wieder da und Vis funktioniert sofort wieder.

Am Projekt kann es auch nicht liegen, da ich keine Internetinhalte anzeigen lasse…

**Comment by mcm1957** [comment]
Wenn möglich check auf wohin vis zugreift. Entweder via pihole (o.ä.) sollte das gehen. Oder alternativ wär es auch einen Versuch wert vis zum Hängen zu bringen und auf Systemebene zu schaunw elche Verbindungen offen sind (bz.w pending sind.

Gibt wahrscheinljuch im Forum mehr Hilfe zur Diagnose. Ich kann nur raten, dass z.B. ein Widget irgendwelche Fonts laden will

P.S: Bitte korrigier gelegentlich Subject (1.56 sollte wohl 1.5.6 sein)

**Comment by Baenker** [comment]
Ich mach hier mal zu. Da ich spontan keine Idee habe wie ich es heraus finden kann. Und da andere das Problem nicht haben muss es ein individuelles Problem sein.

Ja war Version 1.5.6
