### ISSUE TITLE
Widget ctrl-Icon State

### ISSUE THREAD

**Issue by mctom** [ioBroker/ioBroker.vis#93]
Wenn das Icon aktiv ist kann es ausgewählt werden und es verändert den Status nach inaktiv.
Dies sollte unterbunden werden, da das Icon nur als Status Anzeige dienen soll.

Eine Änderung von inaktiv nach aktiv ist nicht möglich. Dies ist korrekt so.

**Comment by GermanBluefox** [comment]
Ist bug noch da?
