### ISSUE TITLE
Editor, Kopieren von Merkmalen (Sternchen): rechte Leiste springt zur nächsten Kategorie

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.vis#99]
Beim Übernehmen von Merkmalen aus anderem Widget mit dem "Copytool" (Sternchen) springt im rechten Bereich die ANzeige zur nächsten Markierung (Überschrift). Was ein wildes hin- und herspringen bedeutet, wenn man mehrere Eigenschaften kopieren möchte.

Mac OS X
diverse Browser

**Comment by GermanBluefox** [comment]
![selektieren](https://cloud.githubusercontent.com/assets/4582016/10218970/701e7378-683b-11e5-8f7f-243796c50a9c.gif)
Wie kann ich das reproduzieren?
